// Auto-generated by backend/curriculum/build_parcours_manuels.py — do not edit by hand.
import type { ManuelData } from '../ManuelInteractif'

const DATA: ManuelData = {
"book": "Le pion à la bande et le pion au centre",
"level": "Intermédiaire",
"chapters": [
{
"n": 0,
"title": "Présentation"
},
{
"n": 1,
"title": "La structure bande / centre"
}
],
"blocks": [
{
"type": "h1",
"ch": 0,
"runs": [
{
"t": "Le pion à la bande et le pion au centre"
}
]
},
{
"type": "p",
"ch": 0,
"runs": [
{
"t": "Lire les structures de pions."
}
]
},
{
"type": "p",
"ch": 0,
"runs": [
{
"b": 1,
"t": "Objectif. "
},
{
"t": "Comprendre l'opposition entre un pion à la bande et un pion au centre, et transformer cette structure en avantage."
}
]
},
{
"type": "h2",
"ch": 1,
"runs": [
{
"t": "La structure bande / centre"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "Une structure clé du jeu positionnel : un pion fixé à la bande face à un pion au centre. Apprenez à voir qui domine et comment exploiter la position."
}
]
},
{
"type": "board",
"id": "int_structure_bande_centre_l1_ex0",
"ch": 1
},
{
"type": "board",
"id": "int_structure_bande_centre_l1_ex1",
"ch": 1
},
{
"type": "board",
"id": "int_structure_bande_centre_l1_ex2",
"ch": 1
},
{
"type": "board",
"id": "int_structure_bande_centre_l1_ex3",
"ch": 1
},
{
"type": "board",
"id": "int_structure_bande_centre_l1_ex4",
"ch": 1
},
{
"type": "board",
"id": "int_structure_bande_centre_l1_ex5",
"ch": 1
},
{
"type": "board",
"id": "int_structure_bande_centre_l1_ex6",
"ch": 1
},
{
"type": "board",
"id": "int_structure_bande_centre_l1_ex7",
"ch": 1
},
{
"type": "board",
"id": "int_structure_bande_centre_l1_ex8",
"ch": 1
},
{
"type": "board",
"id": "int_structure_bande_centre_l1_ex9",
"ch": 1
},
{
"type": "board",
"id": "int_structure_bande_centre_l1_ex10",
"ch": 1
},
{
"type": "board",
"id": "int_structure_bande_centre_l1_ex11",
"ch": 1
},
{
"type": "board",
"id": "int_structure_bande_centre_l1_ex12",
"ch": 1
},
{
"type": "board",
"id": "int_structure_bande_centre_l1_ex13",
"ch": 1
},
{
"type": "board",
"id": "int_structure_bande_centre_l1_ex14",
"ch": 1
},
{
"type": "board",
"id": "int_structure_bande_centre_l1_ex15",
"ch": 1
},
{
"type": "board",
"id": "int_structure_bande_centre_l1_ex16",
"ch": 1
}
],
"positions": {
"int_structure_bande_centre_l1_ex0": {
"id": "int_structure_bande_centre_l1_ex0",
"ch": 1,
"title": "SIJBRANDS — combinaison (p.90 #10)",
"start": {
"wm": [
48
],
"wk": [],
"bm": [
3
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "48-42",
"f": 48,
"t": 42,
"c": [],
"path": [
48,
42
],
"p": false
},
{
"n": "3-9",
"f": 3,
"t": 9,
"c": [],
"path": [
3,
9
],
"p": false
},
{
"n": "42-38",
"f": 42,
"t": 38,
"c": [],
"path": [
42,
38
],
"p": false
},
{
"n": "9-14",
"f": 9,
"t": 14,
"c": [],
"path": [
9,
14
],
"p": false
},
{
"n": "38-33",
"f": 38,
"t": 33,
"c": [],
"path": [
38,
33
],
"p": false
},
{
"n": "14-20",
"f": 14,
"t": 20,
"c": [],
"path": [
14,
20
],
"p": false
},
{
"n": "33-29",
"f": 33,
"t": 29,
"c": [],
"path": [
33,
29
],
"p": false
},
{
"n": "20-25",
"f": 20,
"t": 25,
"c": [],
"path": [
20,
25
],
"p": false
},
{
"n": "29-24",
"f": 29,
"t": 24,
"c": [],
"path": [
29,
24
],
"p": false
},
{
"n": "25-30",
"f": 25,
"t": 30,
"c": [],
"path": [
25,
30
],
"p": false
},
{
"n": "24x35",
"f": 24,
"t": 35,
"c": [
30
],
"path": [
24,
35
],
"p": false
}
],
"theme": "Un pion à la bande et un pion dans le centre",
"pub": "48-42 3-9 42-38 9-14 38-33 14-20 33-29 20-25 29-24 25-30 24x35",
"win": "white",
"exp": "Un pion à la bande et un pion dans le centre"
},
"int_structure_bande_centre_l1_ex1": {
"id": "int_structure_bande_centre_l1_ex1",
"ch": 1,
"title": "SIJBRANDS — combinaison (p.90 #11)",
"start": {
"wm": [
48
],
"wk": [],
"bm": [
12
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "48-42",
"f": 48,
"t": 42,
"c": [],
"path": [
48,
42
],
"p": false
},
{
"n": "12-17",
"f": 12,
"t": 17,
"c": [],
"path": [
12,
17
],
"p": false
},
{
"n": "42-37",
"f": 42,
"t": 37,
"c": [],
"path": [
42,
37
],
"p": false
},
{
"n": "17-21",
"f": 17,
"t": 21,
"c": [],
"path": [
17,
21
],
"p": false
},
{
"n": "37-32",
"f": 37,
"t": 32,
"c": [],
"path": [
37,
32
],
"p": false
},
{
"n": "21-26",
"f": 21,
"t": 26,
"c": [],
"path": [
21,
26
],
"p": false
},
{
"n": "32-27",
"f": 32,
"t": 27,
"c": [],
"path": [
32,
27
],
"p": false
},
{
"n": "26-31",
"f": 26,
"t": 31,
"c": [],
"path": [
26,
31
],
"p": false
},
{
"n": "27x36",
"f": 27,
"t": 36,
"c": [
31
],
"path": [
27,
36
],
"p": false
}
],
"theme": "Un pion à la bande et un pion dans le centre",
"pub": "48-42 12-17 42-37 17-21 37-32 21-26 32-27 26-31 27x36",
"win": "white",
"exp": "Un pion à la bande et un pion dans le centre"
},
"int_structure_bande_centre_l1_ex2": {
"id": "int_structure_bande_centre_l1_ex2",
"ch": 1,
"title": "SIJBRANDS — combinaison (p.90 #13)",
"start": {
"wm": [
38,
48
],
"wk": [],
"bm": [
16,
25
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "48-43",
"f": 48,
"t": 43,
"c": [],
"path": [
48,
43
],
"p": false
},
{
"n": "25-30",
"f": 25,
"t": 30,
"c": [],
"path": [
25,
30
],
"p": false
},
{
"n": "43-39",
"f": 43,
"t": 39,
"c": [],
"path": [
43,
39
],
"p": false
},
{
"n": "30-35",
"f": 30,
"t": 35,
"c": [],
"path": [
30,
35
],
"p": false
},
{
"n": "39-34",
"f": 39,
"t": 34,
"c": [],
"path": [
39,
34
],
"p": false
},
{
"n": "16-21",
"f": 16,
"t": 21,
"c": [],
"path": [
16,
21
],
"p": false
},
{
"n": "38-32",
"f": 38,
"t": 32,
"c": [],
"path": [
38,
32
],
"p": false
},
{
"n": "21-26",
"f": 21,
"t": 26,
"c": [],
"path": [
21,
26
],
"p": false
},
{
"n": "32-27",
"f": 32,
"t": 27,
"c": [],
"path": [
32,
27
],
"p": false
},
{
"n": "26-31",
"f": 26,
"t": 31,
"c": [],
"path": [
26,
31
],
"p": false
},
{
"n": "27x36",
"f": 27,
"t": 36,
"c": [
31
],
"path": [
27,
36
],
"p": false
},
{
"n": "35-40",
"f": 35,
"t": 40,
"c": [],
"path": [
35,
40
],
"p": false
},
{
"n": "34x45",
"f": 34,
"t": 45,
"c": [
40
],
"path": [
34,
45
],
"p": false
}
],
"theme": "Un pion à la bande et un pion dans le centre",
"pub": "48-43 25-30 43-39 30-35 39-34 16-21 38-32 21-26 32-27 26-31 27x36 35-40 34x45",
"win": "white",
"exp": "Un pion à la bande et un pion dans le centre"
},
"int_structure_bande_centre_l1_ex3": {
"id": "int_structure_bande_centre_l1_ex3",
"ch": 1,
"title": "SIJBRANDS — combinaison (p.91 #15)",
"start": {
"wm": [
29,
33,
37
],
"wk": [],
"bm": [
19,
21,
27
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "37-32",
"f": 37,
"t": 32,
"c": [],
"path": [
37,
32
],
"p": false
},
{
"n": "27x38",
"f": 27,
"t": 38,
"c": [
32
],
"path": [
27,
38
],
"p": false
},
{
"n": "33x42",
"f": 33,
"t": 42,
"c": [
38
],
"path": [
33,
42
],
"p": false
},
{
"n": "21-27",
"f": 21,
"t": 27,
"c": [],
"path": [
21,
27
],
"p": false
},
{
"n": "42-37",
"f": 42,
"t": 37,
"c": [],
"path": [
42,
37
],
"p": false
},
{
"n": "19-24",
"f": 19,
"t": 24,
"c": [],
"path": [
19,
24
],
"p": false
},
{
"n": "29x20",
"f": 29,
"t": 20,
"c": [
24
],
"path": [
29,
20
],
"p": false
},
{
"n": "27-31",
"f": 27,
"t": 31,
"c": [],
"path": [
27,
31
],
"p": false
},
{
"n": "37x26",
"f": 37,
"t": 26,
"c": [
31
],
"path": [
37,
26
],
"p": false
}
],
"theme": "Un pion à la bande et un pion dans le centre",
"pub": "37-32 27x38 33x42 21-27 42-37 19-24 29x20 27-31 37x26",
"win": "white",
"exp": "Un pion à la bande et un pion dans le centre"
},
"int_structure_bande_centre_l1_ex4": {
"id": "int_structure_bande_centre_l1_ex4",
"ch": 1,
"title": "SIJBRANDS — combinaison (p.91 #17)",
"start": {
"wm": [
35,
39
],
"wk": [],
"bm": [
3,
25
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "39-33",
"f": 39,
"t": 33,
"c": [],
"path": [
39,
33
],
"p": false
},
{
"n": "3-9",
"f": 3,
"t": 9,
"c": [],
"path": [
3,
9
],
"p": false
},
{
"n": "33-29",
"f": 33,
"t": 29,
"c": [],
"path": [
33,
29
],
"p": false
},
{
"n": "9-14",
"f": 9,
"t": 14,
"c": [],
"path": [
9,
14
],
"p": false
},
{
"n": "29-24",
"f": 29,
"t": 24,
"c": [],
"path": [
29,
24
],
"p": false
},
{
"n": "25-30",
"f": 25,
"t": 30,
"c": [],
"path": [
25,
30
],
"p": false
},
{
"n": "24-20",
"f": 24,
"t": 20,
"c": [],
"path": [
24,
20
],
"p": false
},
{
"n": "14x25",
"f": 14,
"t": 25,
"c": [
20
],
"path": [
14,
25
],
"p": false
},
{
"n": "35x24",
"f": 35,
"t": 24,
"c": [
30
],
"path": [
35,
24
],
"p": false
},
{
"n": "25-30",
"f": 25,
"t": 30,
"c": [],
"path": [
25,
30
],
"p": false
},
{
"n": "24x35",
"f": 24,
"t": 35,
"c": [
30
],
"path": [
24,
35
],
"p": false
}
],
"theme": "Un pion à la bande et un pion dans le centre",
"pub": "39-33 3-9 33-29 9-14 29-24 25-30 24-20 14x25 35x24 25-30 24x35",
"win": "white",
"exp": "Un pion à la bande et un pion dans le centre"
},
"int_structure_bande_centre_l1_ex5": {
"id": "int_structure_bande_centre_l1_ex5",
"ch": 1,
"title": "SIJBRANDS — combinaison (p.91 #18)",
"start": {
"wm": [
26,
47
],
"wk": [],
"bm": [
16,
22
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "47-42",
"f": 47,
"t": 42,
"c": [],
"path": [
47,
42
],
"p": false
},
{
"n": "22-27",
"f": 22,
"t": 27,
"c": [],
"path": [
22,
27
],
"p": false
},
{
"n": "26-21",
"f": 26,
"t": 21,
"c": [],
"path": [
26,
21
],
"p": false
},
{
"n": "27-31",
"f": 27,
"t": 31,
"c": [],
"path": [
27,
31
],
"p": false
},
{
"n": "21-17",
"f": 21,
"t": 17,
"c": [],
"path": [
21,
17
],
"p": false
},
{
"n": "31-36",
"f": 31,
"t": 36,
"c": [],
"path": [
31,
36
],
"p": false
},
{
"n": "42-37",
"f": 42,
"t": 37,
"c": [],
"path": [
42,
37
],
"p": false
},
{
"n": "16-21",
"f": 16,
"t": 21,
"c": [],
"path": [
16,
21
],
"p": false
},
{
"n": "17x26",
"f": 17,
"t": 26,
"c": [
21
],
"path": [
17,
26
],
"p": false
},
{
"n": "36-41",
"f": 36,
"t": 41,
"c": [],
"path": [
36,
41
],
"p": false
},
{
"n": "37x46",
"f": 37,
"t": 46,
"c": [
41
],
"path": [
37,
46
],
"p": false
}
],
"theme": "Un pion à la bande et un pion dans le centre",
"pub": "47-42 22-27 26-21 27-31 21-17 31-36 42-37 16-21 17x26 36-41 37x46",
"win": "white",
"exp": "Un pion à la bande et un pion dans le centre"
},
"int_structure_bande_centre_l1_ex6": {
"id": "int_structure_bande_centre_l1_ex6",
"ch": 1,
"title": "SIJBRANDS — combinaison (p.91 #19)",
"start": {
"wm": [
29,
31,
39
],
"wk": [],
"bm": [
26,
28
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "29-23",
"f": 29,
"t": 23,
"c": [],
"path": [
29,
23
],
"p": false
},
{
"n": "28x19",
"f": 28,
"t": 19,
"c": [
23
],
"path": [
28,
19
],
"p": false
},
{
"n": "31-27",
"f": 31,
"t": 27,
"c": [],
"path": [
31,
27
],
"p": false
},
{
"n": "19-24",
"f": 19,
"t": 24,
"c": [],
"path": [
19,
24
],
"p": false
},
{
"n": "39-34",
"f": 39,
"t": 34,
"c": [],
"path": [
39,
34
],
"p": false
},
{
"n": "26-31",
"f": 26,
"t": 31,
"c": [],
"path": [
26,
31
],
"p": false
},
{
"n": "27x36",
"f": 27,
"t": 36,
"c": [
31
],
"path": [
27,
36
],
"p": false
},
{
"n": "24-29",
"f": 24,
"t": 29,
"c": [],
"path": [
24,
29
],
"p": false
},
{
"n": "34x23",
"f": 34,
"t": 23,
"c": [
29
],
"path": [
34,
23
],
"p": false
}
],
"theme": "Un pion à la bande et un pion dans le centre",
"pub": "29-23 28x19 31-27 19-24 39-34 26-31 27x36 24-29 34x23",
"win": "white",
"exp": "Un pion à la bande et un pion dans le centre"
},
"int_structure_bande_centre_l1_ex7": {
"id": "int_structure_bande_centre_l1_ex7",
"ch": 1,
"title": "SIJBRANDS — combinaison (p.91 #20)",
"start": {
"wm": [
33,
37,
39
],
"wk": [],
"bm": [
22,
23
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "39-34",
"f": 39,
"t": 34,
"c": [],
"path": [
39,
34
],
"p": false
},
{
"n": "23-28",
"f": 23,
"t": 28,
"c": [],
"path": [
23,
28
],
"p": false
},
{
"n": "33-29",
"f": 33,
"t": 29,
"c": [],
"path": [
33,
29
],
"p": false
},
{
"n": "22-27",
"f": 22,
"t": 27,
"c": [],
"path": [
22,
27
],
"p": false
},
{
"n": "29-23",
"f": 29,
"t": 23,
"c": [],
"path": [
29,
23
],
"p": false
},
{
"n": "28x19",
"f": 28,
"t": 19,
"c": [
23
],
"path": [
28,
19
],
"p": false
},
{
"n": "34-29",
"f": 34,
"t": 29,
"c": [],
"path": [
34,
29
],
"p": false
},
{
"n": "19-24",
"f": 19,
"t": 24,
"c": [],
"path": [
19,
24
],
"p": false
},
{
"n": "29x20",
"f": 29,
"t": 20,
"c": [
24
],
"path": [
29,
20
],
"p": false
},
{
"n": "27-31",
"f": 27,
"t": 31,
"c": [],
"path": [
27,
31
],
"p": false
},
{
"n": "37x26",
"f": 37,
"t": 26,
"c": [
31
],
"path": [
37,
26
],
"p": false
}
],
"theme": "Un pion à la bande et un pion dans le centre",
"pub": "39-34 23-28 33-29 22-27 29-23 28x19 34-29 19-24 29x20 27-31 37x26",
"win": "white",
"exp": "Un pion à la bande et un pion dans le centre"
},
"int_structure_bande_centre_l1_ex8": {
"id": "int_structure_bande_centre_l1_ex8",
"ch": 1,
"title": "SIJBRANDS — combinaison (p.96 #6)",
"start": {
"wm": [],
"wk": [
38
],
"bm": [
16,
28
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "38-27",
"f": 38,
"t": 27,
"c": [],
"path": [
38,
27
],
"p": false
},
{
"n": "28-33",
"f": 28,
"t": 33,
"c": [],
"path": [
28,
33
],
"p": false
},
{
"n": "27-43",
"f": 27,
"t": 43,
"c": [],
"path": [
27,
43
],
"p": false
},
{
"n": "33-39",
"f": 33,
"t": 39,
"c": [],
"path": [
33,
39
],
"p": false
},
{
"n": "43x34",
"f": 43,
"t": 34,
"c": [
39
],
"path": [
43,
34
],
"p": false
},
{
"n": "16-21",
"f": 16,
"t": 21,
"c": [],
"path": [
16,
21
],
"p": false
},
{
"n": "34-18",
"f": 34,
"t": 18,
"c": [],
"path": [
34,
18
],
"p": false
},
{
"n": "21-26",
"f": 21,
"t": 26,
"c": [],
"path": [
21,
26
],
"p": false
},
{
"n": "18-27",
"f": 18,
"t": 27,
"c": [],
"path": [
18,
27
],
"p": false
},
{
"n": "26-31",
"f": 26,
"t": 31,
"c": [],
"path": [
26,
31
],
"p": false
},
{
"n": "27x36",
"f": 27,
"t": 36,
"c": [
31
],
"path": [
27,
36
],
"p": false
}
],
"theme": "Un pion à la bande et un pion dans le centre",
"pub": "38-27 28-33 27-43 33-39 43x34 16-21 34-18 21-26 18-27 26-31 27x36",
"win": "white",
"exp": "Un pion à la bande et un pion dans le centre"
},
"int_structure_bande_centre_l1_ex9": {
"id": "int_structure_bande_centre_l1_ex9",
"ch": 1,
"title": "SIJBRANDS — combinaison (p.96 #9)",
"start": {
"wm": [
10
],
"wk": [],
"bm": [
13,
17
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "10-5",
"f": 10,
"t": 5,
"c": [],
"path": [
10,
5
],
"p": true
}
],
"theme": "Un pion à la bande et un pion dans le centre",
"pub": "10-5",
"win": "white",
"exp": "Un pion à la bande et un pion dans le centre"
},
"int_structure_bande_centre_l1_ex10": {
"id": "int_structure_bande_centre_l1_ex10",
"ch": 1,
"title": "SIJBRANDS — combinaison (p.97 #11)",
"start": {
"wm": [],
"wk": [
2
],
"bm": [
23,
27
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "2-7",
"f": 2,
"t": 7,
"c": [],
"path": [
2,
7
],
"p": false
},
{
"n": "23-28",
"f": 23,
"t": 28,
"c": [],
"path": [
23,
28
],
"p": false
},
{
"n": "7-11",
"f": 7,
"t": 11,
"c": [],
"path": [
7,
11
],
"p": false
},
{
"n": "28-32",
"f": 28,
"t": 32,
"c": [],
"path": [
28,
32
],
"p": false
},
{
"n": "11-16",
"f": 11,
"t": 16,
"c": [],
"path": [
11,
16
],
"p": false
},
{
"n": "27-31",
"f": 27,
"t": 31,
"c": [],
"path": [
27,
31
],
"p": false
},
{
"n": "16x38",
"f": 16,
"t": 38,
"c": [
32
],
"path": [
16,
38
],
"p": false
},
{
"n": "31-37",
"f": 31,
"t": 37,
"c": [],
"path": [
31,
37
],
"p": false
},
{
"n": "38-47",
"f": 38,
"t": 47,
"c": [],
"path": [
38,
47
],
"p": false
},
{
"n": "37-41",
"f": 37,
"t": 41,
"c": [],
"path": [
37,
41
],
"p": false
},
{
"n": "47x36",
"f": 47,
"t": 36,
"c": [
41
],
"path": [
47,
36
],
"p": false
}
],
"theme": "Un pion à la bande et un pion dans le centre",
"pub": "2-7 23-28 7-11 28-32 11-16 27-31 16x38 31-37 38-47 37-41 47x36",
"win": "white",
"exp": "Un pion à la bande et un pion dans le centre"
},
"int_structure_bande_centre_l1_ex11": {
"id": "int_structure_bande_centre_l1_ex11",
"ch": 1,
"title": "SIJBRANDS — combinaison (p.97 #12)",
"start": {
"wm": [
8
],
"wk": [],
"bm": [
23,
29
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "8-3",
"f": 8,
"t": 3,
"c": [],
"path": [
8,
3
],
"p": true
},
{
"n": "23-28",
"f": 23,
"t": 28,
"c": [],
"path": [
23,
28
],
"p": false
},
{
"n": "3-14",
"f": 3,
"t": 14,
"c": [],
"path": [
3,
14
],
"p": false
},
{
"n": "28-33",
"f": 28,
"t": 33,
"c": [],
"path": [
28,
33
],
"p": false
},
{
"n": "14-20",
"f": 14,
"t": 20,
"c": [],
"path": [
14,
20
],
"p": false
},
{
"n": "29-34",
"f": 29,
"t": 34,
"c": [],
"path": [
29,
34
],
"p": false
},
{
"n": "20x38",
"f": 20,
"t": 38,
"c": [
33
],
"path": [
20,
38
],
"p": false
},
{
"n": "34-40",
"f": 34,
"t": 40,
"c": [],
"path": [
34,
40
],
"p": false
},
{
"n": "38-33",
"f": 38,
"t": 33,
"c": [],
"path": [
38,
33
],
"p": false
},
{
"n": "40-45",
"f": 40,
"t": 45,
"c": [],
"path": [
40,
45
],
"p": false
},
{
"n": "33-50",
"f": 33,
"t": 50,
"c": [],
"path": [
33,
50
],
"p": false
}
],
"theme": "Un pion à la bande et un pion dans le centre",
"pub": "8-3 23-28 3-14 28-33 14-20 29-34 20x38 34-40 38-33 40-45 33-50",
"win": "white",
"exp": "Un pion à la bande et un pion dans le centre"
},
"int_structure_bande_centre_l1_ex12": {
"id": "int_structure_bande_centre_l1_ex12",
"ch": 1,
"title": "SIJBRANDS — combinaison (p.98 #16)",
"start": {
"wm": [
19,
47
],
"wk": [],
"bm": [
26,
36
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "19-14",
"f": 19,
"t": 14,
"c": [],
"path": [
19,
14
],
"p": false
},
{
"n": "26-31",
"f": 26,
"t": 31,
"c": [],
"path": [
26,
31
],
"p": false
},
{
"n": "14-10",
"f": 14,
"t": 10,
"c": [],
"path": [
14,
10
],
"p": false
},
{
"n": "31-37",
"f": 31,
"t": 37,
"c": [],
"path": [
31,
37
],
"p": false
},
{
"n": "10-5",
"f": 10,
"t": 5,
"c": [],
"path": [
10,
5
],
"p": true
},
{
"n": "36-41",
"f": 36,
"t": 41,
"c": [],
"path": [
36,
41
],
"p": false
},
{
"n": "47x36",
"f": 47,
"t": 36,
"c": [
41
],
"path": [
47,
36
],
"p": false
},
{
"n": "37-42",
"f": 37,
"t": 42,
"c": [],
"path": [
37,
42
],
"p": false
},
{
"n": "5-37",
"f": 5,
"t": 37,
"c": [],
"path": [
5,
37
],
"p": false
},
{
"n": "42x31",
"f": 42,
"t": 31,
"c": [
37
],
"path": [
42,
31
],
"p": false
},
{
"n": "36x27",
"f": 36,
"t": 27,
"c": [
31
],
"path": [
36,
27
],
"p": false
}
],
"theme": "Un pion à la bande et un pion dans le centre",
"pub": "19-14 26-31 14-10 31-37 10-5 36-41 47x36 37-42 5-37 42x31 36x27",
"win": "white",
"exp": "Un pion à la bande et un pion dans le centre"
},
"int_structure_bande_centre_l1_ex13": {
"id": "int_structure_bande_centre_l1_ex13",
"ch": 1,
"title": "SIJBRANDS — combinaison (p.98 #19)",
"start": {
"wm": [
8,
17
],
"wk": [],
"bm": [
6,
14
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "8-2",
"f": 8,
"t": 2,
"c": [],
"path": [
8,
2
],
"p": true
}
],
"theme": "Un pion à la bande et un pion dans le centre",
"pub": "8-2",
"win": "white",
"exp": "Un pion à la bande et un pion dans le centre"
},
"int_structure_bande_centre_l1_ex14": {
"id": "int_structure_bande_centre_l1_ex14",
"ch": 1,
"title": "SIJBRANDS — combinaison (p.100 #10)",
"start": {
"wm": [
7,
26
],
"wk": [],
"bm": [
13,
38
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "7-2",
"f": 7,
"t": 2,
"c": [],
"path": [
7,
2
],
"p": true
}
],
"theme": "Un pion à la bande et un pion dans le centre",
"pub": "7-2",
"win": "white",
"exp": "Un pion à la bande et un pion dans le centre"
},
"int_structure_bande_centre_l1_ex15": {
"id": "int_structure_bande_centre_l1_ex15",
"ch": 1,
"title": "SIJBRANDS — combinaison (p.100 #9)",
"start": {
"wm": [
22
],
"wk": [
5
],
"bm": [
21,
31,
36
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "5-23",
"f": 5,
"t": 23,
"c": [],
"path": [
5,
23
],
"p": false
},
{
"n": "36-41",
"f": 36,
"t": 41,
"c": [],
"path": [
36,
41
],
"p": false
},
{
"n": "23x46",
"f": 23,
"t": 46,
"c": [
41
],
"path": [
23,
46
],
"p": false
},
{
"n": "21-27",
"f": 21,
"t": 27,
"c": [],
"path": [
21,
27
],
"p": false
},
{
"n": "22-18",
"f": 22,
"t": 18,
"c": [],
"path": [
22,
18
],
"p": false
},
{
"n": "31-36",
"f": 31,
"t": 36,
"c": [],
"path": [
31,
36
],
"p": false
},
{
"n": "18-12",
"f": 18,
"t": 12,
"c": [],
"path": [
18,
12
],
"p": false
},
{
"n": "27-31",
"f": 27,
"t": 31,
"c": [],
"path": [
27,
31
],
"p": false
},
{
"n": "12-7",
"f": 12,
"t": 7,
"c": [],
"path": [
12,
7
],
"p": false
},
{
"n": "31-37",
"f": 31,
"t": 37,
"c": [],
"path": [
31,
37
],
"p": false
},
{
"n": "46x28",
"f": 46,
"t": 28,
"c": [
37
],
"path": [
46,
28
],
"p": false
},
{
"n": "36-41",
"f": 36,
"t": 41,
"c": [],
"path": [
36,
41
],
"p": false
},
{
"n": "28x46",
"f": 28,
"t": 46,
"c": [
41
],
"path": [
28,
46
],
"p": false
}
],
"theme": "Un pion à la bande et un pion dans le centre",
"pub": "5-23 36-41 23x46 21-27 22-18 31-36 18-12 27-31 12-7 31-37 46x28 36-41 28x46",
"win": "white",
"exp": "Un pion à la bande et un pion dans le centre"
},
"int_structure_bande_centre_l1_ex16": {
"id": "int_structure_bande_centre_l1_ex16",
"ch": 1,
"title": "SIJBRANDS — combinaison (p.101 #11)",
"start": {
"wm": [
7,
22
],
"wk": [],
"bm": [
21,
34
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "7-1",
"f": 7,
"t": 1,
"c": [],
"path": [
7,
1
],
"p": true
}
],
"theme": "Un pion à la bande et un pion dans le centre",
"pub": "7-1",
"win": "white",
"exp": "Un pion à la bande et un pion dans le centre"
}
}
}

export default DATA
