// Auto-generated by backend/curriculum/build_parcours_manuels.py — do not edit by hand.
import type { ManuelData } from '../ManuelInteractif'

const DATA: ManuelData = {
"book": "Combinaisons : les fondamentaux",
"level": "Débutant",
"chapters": [
{
"n": 0,
"title": "Présentation"
},
{
"n": 1,
"title": "Présentation"
},
{
"n": 2,
"title": "Méthode d’identification de la rafle et des points d’appuis"
},
{
"n": 3,
"title": "Les cases de départ et d’arrivée"
},
{
"n": 4,
"title": "L’envoi a dame"
},
{
"n": 5,
"title": "La méthode des points de contact"
},
{
"n": 6,
"title": "Le déplacement des points d’appui par collage"
},
{
"n": 7,
"title": "L’association envoi a dame et collage"
},
{
"n": 8,
"title": "Les temps de repos créés par une attaque"
},
{
"n": 9,
"title": "La création des temps de repos"
},
{
"n": 10,
"title": "Les mécanismes de mémorisation du cerveau"
},
{
"n": 11,
"title": "Récapitulatif"
}
],
"blocks": [
{
"type": "h1",
"ch": 0,
"runs": [
{
"t": "Combinaisons : les fondamentaux"
}
]
},
{
"type": "p",
"ch": 0,
"runs": [
{
"t": "Identifier la rafle, l'envoi à dame, les points de contact et les temps de repos."
}
]
},
{
"type": "p",
"ch": 0,
"runs": [
{
"b": 1,
"t": "Objectif. "
},
{
"t": "Comprendre les mécanismes de base de la combinaison (rafle, envoi à dame, collage, points de contact, temps de repos)."
}
]
},
{
"type": "h2",
"ch": 1,
"runs": [
{
"t": "Présentation"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "Pour comprendre comment s’articulent les combinaisons, nous allons commencer notre tour d’horizon avec les combinaisons en 2 temps. 1 – AU JEU DE DAMES, ON NE VOIT QUE CE QUE L’ON REGARDE Cette phrase peut paraître simpliste et même inutile. Je dois avouer que je suis toujours surpris, après autant d’années de pratique du jeu, de pouvoir être encore victime de combinaisons en 2 temps. Ce n’est dû qu’à de l’inattention. Cela signifie qu’il est nécessaire de tout examiner, pour savoir s’il y a ou non une combinaison. Il est impossible de le savoir en fixant une position statique, sans déplacer mentalement les pions. Il n’est pas possible de faire des impasses sans prendre le risque d’oublier une combinaison. Les deux exemples qui suivent vont nous permettre de bien comprendre :"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "Cette position s’est présentée entre Wouter SIPMA et Alexander GEORGIEV, multiple champion du monde, lors d’un match de départage en parties rapides. Les noirs viennent d’entrer en lunette et offrent à leur adversaire un gain direct par 32-28, forçant les noirs à prendre 3 pions par (21x34), obtenant ainsi la position du troisième diagramme dans lequel les blancs reprennent la dame par 38x40."
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "Ce deuxième exemple est tiré d’une partie que j’ai jouée en amicale. Avec les noirs, mon dernier coup était (23-28). Apparemment, les blancs semblent perdus. Pourtant, ils peuvent renverser la situation en 2 temps, par un gambit : 16-11 (6x17) 27-22, position du second diagramme, où les noirs doivent se résoudre à perdre un pion."
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "2 – LA METHODOLOGIE POUR TROUVER Rien ne prédestine notre esprit à trouver des combinaisons au jeu de dames. Sacrifier des pions pour en prendre plus, ou pour faire une dame, n’est pas inscrit dans nos gênes. Pas plus que la prise majoritaire. Il va donc falloir habituer notre cerveau à une démarche qui n’est pas spontanée. La répétition des exercices conduit rapidement à des résultats probants. Il faut prendre conscience que le premier coup à rechercher provoque obligatoirement un contact entre deux pions. Le coup adverse correspond nécessairement à une prise dans laquelle le nombre de pions à prendre est primordial. Le second coup est une prise décisive. En résumant, nous avons une mise en contact, puis une prise par le camp adverse, et enfin une prise (rafle)."
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "CONTACT : le premier coup des Blancs, 25-20. PRISE DES NOIRS : la prise majoritaire de 3 pions (26x39) PRISE DES BLANCS : 20x7 3 – LES MECANISMES Les combinaisons sont toujours constituées d’un ou plusieurs mécanismes suivis d’une ou plusieurs rafles. Dans les exemples qui suivent, on trouvera 3 mécanismes de base : LE COLLAGE, LA PRISE MAJORITAIRE et LE GAMBIT : 4 – LE MODE OPERATOIRE Le but de ces exercices est d’habituer le cerveau à sacrifier des pions, à intégrer la prise majoritaire et à suivre mentalement le déplacement des pions. L’intention est également de prendre conscience que tout est possible, que même les coups les moins « naturels » peuvent être des solutions. Dans cet esprit, je vous conseille de rechercher les combinaisons directement sur un support informatique ou sur papier. Sans stress et sans contrainte de temps. Prenez le temps de visualiser mentalement les déplacements. Je vous recommande également, une fois la combinaison trouvée, de fixer la position de départ, de la mémoriser pendant quelques secondes, et ensuite de la reproduire sur un damier normal. Cet exercice de mémoire visuelle vous sera très utile par la suite. Vous prendrez conscience de la manière dont vous fixez les images, de manière globale ou par groupes de pions. L’idéal est évidemment d’avoir une mémoire visuelle globalisante, mais ce n’est pas donné à tout le monde. Cela n’a pas de grande conséquence car le cerveau trouve d’autres chemins pour reconstituer les positions. Il faut simplement lui donner l’occasion de le faire régulièrement. Cette démarche permet ensuite de soulager la mémoire de travail pendant les parties officielles."
}
]
},
{
"type": "h2",
"ch": 2,
"runs": [
{
"t": "Méthode d’identification de la rafle et des points d’appuis"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "Les combinaisons en 3 temps se distinguent de celles en 2 temps. Les combinaisons en 2 temps sont basées sur deux principes, à savoir la prise majoritaire et le collage. Il n’y a pas de difficulté particulière. Il suffit de rester concentré et de porter son attention sur tous les coups jouables, y compris les plus inattendus, jusqu’à visualiser la solution. Le cerveau assimile alors de manière de plus en plus automatique le mécanisme de prise majoritaire. Les efforts consentis pour envisager mentalement le déplacement des pièces sont de moins en moins importants. Les combinaisons en 3 temps participent à l’amélioration de la vision. Elles nécessitent en plus de raisonner pour réduire le champ d’investigation. En effet, à partir de 3 temps, la recherche systématique de la solution peut devenir fastidieuse, et finalement peu productive. Pour découvrir la solution, on va focaliser son attention en premier lieu sur les rafles possibles et sur les points d’appui qui peuvent servir de départ à ces rafles. Examinons l’exemple ci-dessous :"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "Quels sont les points d’appui qui peuvent servir de point de départ à une rafle ? Nous avons les pions 35 et 48. Une rafle commençant par le pion 35 ne peut aboutir que sur les cases 2, 4, 11, 13, 15, 22 ou 24. On comprend immédiatement qu’aucune rafle partant de la case 35 n’a de sens. Une rafle partant de la case 48 peut accéder aux cases 6, 8, 10, 17, 19, 26, 28, 30. Une rafle 48x10 est donc concevable. C’est ce que montre le second diagramme. Il reste ensuite à chercher de quelle manière acheminer des pions noirs en 31 et 42 pour rendre la rafle possible. Solution : 1. 31-27 (22x31) 2. 35-30 (24x42) 3. 48x10. La méthode comprend donc 2 étapes : 1 – identifier la rafle et les points d’appui. 2 – utiliser les mécanismes connus pour rendre possible la rafle Nous verrons par la suite que cette manière de procéder n’est pas la seule possible, mais qu’il est malgré tout essentiel de maîtriser celle-ci pour évoluer ensuite vers des combinaisons plus élaborées."
}
]
},
{
"type": "h2",
"ch": 3,
"runs": [
{
"t": "Les cases de départ et d’arrivée"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "Nous avons vu précédemment qu’il est important de rationaliser la solution en commençant par concevoir la rafle. Les rafles ont toujours un point de départ et un point d’arrivée. Ce sont ces points qu’il est important de repérer. Ci-dessous les cases de départ et d’arrivée sur les lignes impaires :"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "Ci-dessous les cases de départ et d’arrivée sur les lignes paires :"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "Par exemple, une rafle partant du pion 43 peut aboutir sur les cases 1, 3, 5, 12, 14, 21, 23, 25, 32, 34, 41 ou 45, à l’exclusion de toute autre case. Autre exemple : un coup de dame sur la case 2 ne peut provenir que de l’une des cases 11, 13, 15, 22, 24, 31, 33, 35, 42, 44. Une rafle aboutissant sur une ligne paire ne peut avoir comme départ qu’une case également située sur une ligne paire."
}
]
},
{
"type": "h2",
"ch": 4,
"runs": [
{
"t": "L’envoi a dame"
}
]
},
{
"type": "p",
"ch": 4,
"runs": [
{
"t": "Nous avons vu que l’une des manières de trouver les solutions consiste à rechercher en premier lieu la rafle plausible, et ce n’est qu’ensuite que l’on recherche comment mettre en place les pions pour que cette rafle devienne possible. Cette deuxième phase fait appel à ce que l’on a coutume d’appeler « mécanisme ». L’un des mécanismes toujours étonnants repose sur l’envoi à dame, puis sur la reprise de cette dame avec avantage. Examinons l’exemple suivant :"
}
]
},
{
"type": "p",
"ch": 4,
"runs": [
{
"t": "43x5"
}
]
},
{
"type": "p",
"ch": 4,
"runs": [
{
"t": "L’envoi à dame"
}
]
},
{
"type": "p",
"ch": 4,
"runs": [
{
"t": "A partir de la position du premier diagramme, on peut espérer faire un coup de dame en 5. Il ne manque qu’une pièce noire en 39 pour réaliser la rafle du second diagramme. La solution est d’envoyer le pion 26 à dame puis de l’envoyer sur cette case 39. Solution : 36-31 (26x46) 42-37 (46x39) 43x5."
}
]
},
{
"type": "p",
"ch": 4,
"runs": [
{
"t": "L’envoi à dame"
}
]
},
{
"type": "p",
"ch": 4,
"runs": [
{
"t": "35x4"
}
]
},
{
"type": "p",
"ch": 4,
"runs": [
{
"t": "La position du premier diagramme est gagnante pour les blancs. Malgré le peu de pions en jeu, la solution n’est pas très évidente. Tout d’abord, il faut avoir l’idée d’un coup de dame sur la case 4. Le point d’appui de la rafle ne peut être que le pion 35. Pour que la rafle 35x4 devienne possible, il faut d’une part éliminer les pions 13 et 22, et d’autre part amener une pièce sur la case 30. Solution : Phase 1 : élimination des 2 pions 13 et 22 par 33-29 (24x33) 38x18 (13x22) Phase 2 : acheminement d’une pièce en 30 par l’envoi à dame 37-31 (26x48) suivi de 40-35 (48x30) Phase 3 : exécution de la rafle 35x4."
}
]
},
{
"type": "h2",
"ch": 5,
"runs": [
{
"t": "La méthode des points de contact"
}
]
},
{
"type": "p",
"ch": 5,
"runs": [
{
"t": "Nous avons vu précédemment qu’il était recommandé de commencer par chercher la rafle, avec les tenants et les aboutissants. Cette manière de procéder présente le risque de passer à côté de nombreuses combinaisons, peu spectaculaires, mais très fréquentes. Une autre idée consiste donc à rechercher les points de contact entre les pions blancs et les pions noirs, puis à sacrifier mentalement les pions, sans fatalement rechercher une issue favorable. Cette façon de raisonner permet de recenser les mécanismes possibles et d’éclairer sur d’éventuelles suites avantageuses. Examinons l’exemple suivant :"
}
]
},
{
"type": "p",
"ch": 5,
"runs": [
{
"t": "Dans cette situation, la rafle finale n’est pas évidente. De plus, il y a de nombreux points d’appui possibles. Concevoir une rafle en 6 avec un point d’appui en 39, est loin d’être intuitif. Par contre, en commençant par la recherche des points de contact et par la manière dont on peut sacrifier les pions, on ouvre de nouvelles perspectives. Ainsi, les blancs peuvent donner leurs pions de différentes manières. Par exemple 34-30, 29-23, 37-32 ou l’inattendu 31-27. Cette prise majoritaire de 4 pions rend ensuite évidente la rafle 39x6. Solution : 31-27 (22x24) 34-30 (25x34) 39x6 Les deux méthodes sont complémentaires et ne s’annulent pas l’une l’autre. On passe généralement de l’une à l’autre. A la fois du raisonnement et de la recherche systématique."
}
]
},
{
"type": "h2",
"ch": 6,
"runs": [
{
"t": "Le déplacement des points d’appui par collage"
}
]
},
{
"type": "p",
"ch": 6,
"runs": [
{
"t": "Les points d’appui servant de départ pour la rafle, ne sont pas toujours évidents à déterminer. C’est notamment le cas lorsque ces points d’appui reposent sur des collages. Examinons l’exemple suivant :"
}
]
},
{
"type": "p",
"ch": 6,
"runs": [
{
"t": "Dans la position du premier diagramme, on voit bien se dessiner une rafle aboutissant à 5. Oui mais, à partir de quel point d’appui ? La case 34 devient ce point d’appui en provoquant une prise majoritaire associée à un collage par 39-34. Solution : 37-31 (26x17) 39-34 (21x43) 34x5"
}
]
},
{
"type": "h2",
"ch": 7,
"runs": [
{
"t": "L’association envoi a dame et collage"
}
]
},
{
"type": "p",
"ch": 7,
"runs": [
{
"t": "Nous avons vu que les points d’appui pour une rafle peuvent s’obtenir grâce aux collages. Ce genre de situation se crée assez fréquemment en associant le collage à un envoi à dame préalable. Par exemple :"
}
]
},
{
"type": "p",
"ch": 7,
"runs": [
{
"t": "Dans le premier diagramme, si les Blancs envoient le pion 26 à dame à 48, on se rend compte que les noirs seront en prise de deux pions blancs 20 et 34. Cette situation est propice aux collages. Solution : 37-31 (26x48) 33-28 [position du 2e diagramme] 48x14 [position du 3e diagramme] 28x10"
}
]
},
{
"type": "h2",
"ch": 8,
"runs": [
{
"t": "Les temps de repos créés par une attaque"
}
]
},
{
"type": "p",
"ch": 8,
"runs": [
{
"t": "Faisons le point sur ce que nous avons vu précédemment : • • • •"
}
]
},
{
"type": "p",
"ch": 8,
"runs": [
{
"t": "Concevoir la rafle finale est bien utile pour trouver les combinaisons Visualiser mentalement les manières de sacrifier des pions est un moyen préalable pour déterminer de quels mécanismes on dispose pour effectuer une combinaison Un collage permet de créer un point d’appui qui sert de départ à la rafle L’envoi à dame est un mécanisme inattendu très utile pour créer des collages ou acheminer des pièces."
}
]
},
{
"type": "p",
"ch": 8,
"runs": [
{
"t": "Nous allons poursuivre notre investigation avec les combinaisons qui font appel à des temps de repos. Tout d’abord les temps de repos créés par une attaque :"
}
]
},
{
"type": "p",
"ch": 8,
"runs": [
{
"t": "Les Noirs viennent d’attaquer le pion 25. Les Blancs disposent donc d’un temps de repos. Ils ont ainsi la faculté de jouer 2 coups de suite, car le coup suivant des Noirs est nécessairement la prise (25x34). Solution : 42-37 [diagramme n°2] (25x34) 40x20 (15x24) 28-22 [diagramme n°3] (17x28) 32x14"
}
]
},
{
"type": "p",
"ch": 8,
"runs": [
{
"t": "L’exemple suivant est un peu plus difficile, mais très instructif. Les Noirs viennent d’attaquer le pion 23 par (13-19). Cette attaque donne aux Blancs un temps de repos. Mais le nombre de coups jouables pour les Blancs est important et une recherche systématique peu fructueuse. Il est important dans ce genre de cas de concevoir la rafle finale. Ici, on recherche un coup de dame à 2. Le point d’appui possible est le pion 35. Il faut donc placer un pion en 19 et acheminer une pièce noire sur la case 30. Première étape : placer un pion en 19 par 42-37 (19x28) 29-23 (28x19) [second diagramme] Seconde étape : amener une pièce en 30 via 37-31 (26x37) 48-42 (37x48) 39-34 (48x30) Troisième étape : effectuer la rafle 35x2 [troisième diagramme]"
}
]
},
{
"type": "h2",
"ch": 9,
"runs": [
{
"t": "La création des temps de repos"
}
]
},
{
"type": "p",
"ch": 9,
"runs": [
{
"t": "Nous avons abordé la fois précédente les combinaisons avec temps de repos. Nous avons vu que l’attaque d’un pion par l’adversaire crée naturellement un temps de repos. Cette situation permet de jouer 2 coups de suite et offre évidemment énormément d’opportunités de combinaison. Il est possible de créer des temps de repos, même lorsque l’adversaire n’attaque aucun pion. Un exemple classique :"
}
]
},
{
"type": "p",
"ch": 9,
"runs": [
{
"t": "Les Blancs jouent ici 37-31, les noirs prennent 2 pions par (26x28) et obtiennent la position du second diagramme. Les Noirs sont en prise et les Blancs disposent donc d’un temps de repos. Les Blancs jouent alors 38-33, ce qui nous amène à la position du 3e diagramme dans lequel les Noirs sont forcés de prendre par (21x32), permettant ainsi aux Blancs de damer à 4 par 33x4."
}
]
},
{
"type": "p",
"ch": 9,
"runs": [
{
"t": "Dans ce genre de position bien connue, les Blancs se créent un temps de repos par 32-28 (23x21). On obtient la position du 2e diagramme. Les Noirs sont en prise, ils en profitent pour jouer 34-29 (position du 3e diagramme). Première phase : Deuxième phase : Troisième phase :"
}
]
},
{
"type": "p",
"ch": 9,
"runs": [
{
"t": "créer un temps de repos par 32-28 (23x21) profiter de la prise obligatoire des Noirs en jouant 34-29 dérouler les prises (18x27) 29x7"
}
]
},
{
"type": "p",
"ch": 9,
"runs": [
{
"t": "Nous verrons plus tard que les temps de repos permettent également de mettre en place des mécanismes suivis de combinaisons."
}
]
},
{
"type": "h2",
"ch": 10,
"runs": [
{
"t": "Les mécanismes de mémorisation du cerveau"
}
]
},
{
"type": "p",
"ch": 10,
"runs": [
{
"t": "Nous allons à présent nous intéresser au fonctionnement du cerveau. Pour quelles raisons éprouvons-nous des difficultés à résoudre les problèmes au jeu de dames, et surtout de quelle manière parvenons-nous à surmonter ces difficultés ? Le cerveau est mis à rude contribution dans la pratique du jeu de dames. Tous les mécanismes de mémorisation sont mobilisés. Les mémoires à long terme et à court terme sont ainsi sollicitées. Lors du calcul des variantes, on a recours à ce que les neuropsychologues appellent la mémoire de travail. C’est grâce à ce type de mémoire qu’il est possible de retenir pendant quelques secondes les informations qui sont utiles à la compréhension et au raisonnement. Cette mémoire de travail joue un rôle prépondérant dans l’accomplissement des tâches quotidiennes. La quantité d’informations que l’on peut stocker et la durée pendant laquelle elles sont disponibles, sont limitées. En moyenne, on considère que l’on peut stocker jusqu’à 7 unités d’information différentes pendant 18 secondes. Au-delà de ces 18 secondes, il est nécessaire de répéter les informations. En prenant l’exemple d’un serveur dans un bar, celui-ci sera normalement capable de retenir les commandes de 7 consommateurs pendant qu’il traversera la salle en une vingtaine de secondes. Ces limites de 7 informations pendant 18 secondes ne sont pas figées. Elles correspondent à une moyenne et il est admis que l’entraînement permet d’améliorer les performances. En tout état de cause, rien ne prédispose une personne à envisager une combinaison en 10 temps, pas plus qu’il ne paraît évident de garder en mémoire la commande d’une dizaine de consommateurs. Une phase d’apprentissage, puis un entraînement régulier sont nécessaires pour entretenir un bon niveau de mémorisation. Selon le psychologue Allan BADDELEY, la mémoire de travail peut être modélisée de la manière suivante :"
}
]
},
{
"type": "p",
"ch": 10,
"runs": [
{
"t": "L’administrateur central sélectionne, contrôle et intègre les opérations de traitement. La boucle phonologique emmagasine les informations verbales. Le Calepin visuo-spatial enregistre les informations visuelles et spatiales. Il permet de conserver des images mentales temporairement. Le Buffer épisodique sert de mémoire tampon avant un stockage éventuel dans la mémoire à long terme. Ce buffer peut également intégrer des informations provenant de la mémoire à long terme. Le passage de la mémoire à court terme à la mémoire à long terme n'est pas systématique. Ce processus est actif et s'opère : • • •"
}
]
},
{
"type": "p",
"ch": 10,
"runs": [
{
"t": "Soit si l'encodage est approfondi (visualisation, hiérarchisation), Soit si l'information est répétée, Soit si elle a une valeur affective importante pour le sujet."
}
]
},
{
"type": "p",
"ch": 10,
"runs": [
{
"t": "En appliquant ce modèle au calcul des variantes, on comprend mieux les raisons pour lesquelles on éprouve des difficultés à anticiper plusieurs coups à l’avance. A chaque mouvement correspond une information. Au-delà de 3 ou 4 coups, soit 6 à 8 mouvements, la mémoire de travail est saturée. Cela signifie qu’il est nécessaire d’utiliser le buffer épisodique pour soulager la mémoire de travail. La mémoire à long terme est également utile. Les mécanismes de prise majoritaire, collage, envoi à dame, temps de repos, qui constituent les mécanismes de base pour exécuter des combinaisons, sont progressivement stockés dans la mémoire à long terme. La pratique régulière du jeu rend ces mécanismes automatiquement disponibles, de manière pratiquement inconsciente. En conclusion, on peut retenir les éléments suivants : • • •"
}
]
},
{
"type": "p",
"ch": 10,
"runs": [
{
"t": "Pour les combinaisons en 2, 3 ou 4 temps qui comprennent au maximum 7 mouvements, c’est à dire 7 unités de mémorisation, on peut concevoir de visualiser les combinaisons d’un seul jet. Le buffer est utilisé pour stocker les coups envisagés et classés comme potentiellement utiles. La mémoire à long terme intervient pour rappeler les situations déjà connues et que l’on peut exploiter de manière automatique."
}
]
},
{
"type": "h2",
"ch": 11,
"runs": [
{
"t": "Récapitulatif"
}
]
},
{
"type": "p",
"ch": 11,
"runs": [
{
"t": "C’est le moment de faire un récapitulatif avant d’attaquer progressivement les combinaisons en 4 temps. Nous avons vu jusqu’à présent de nombreux mécanismes élaborés qui ne sont absolument pas intuitifs. Il s’agit notamment de la prise majoritaire, du collage, de l’envoi à dame et de l’intégration de ces mécanismes lors d’une attaque ou en provoquant un temps de repos. De plus, nous avons mis en évidence l’intérêt de se focaliser d’abord sur la, ou les rafles possibles. Nous avons également pris conscience de l’importance du point d’appui qui sert de base à la rafle. Ce point d’appui pouvant être un pion de bande, une formation de pionnage ou encore un collage. Enfin, nous avons établi une méthode pour chercher les combinaisons. Partir de la fin en concevant la rafle, ou partir du début en identifiant les mécanismes exploitables. L’association de ces 2 approches constitue généralement un bon moyen de trouver les combinaisons. Trouver une combinaison en 3 temps n’est pas évident car il faut se familiariser avec tout ce que je viens d’évoquer. Une période d’apprentissage est nécessaire. Toutes les combinaisons en 3 temps qui vont suivre ne feront pas intervenir de nouveaux mécanismes."
}
]
}
],
"positions": {}
}

export default DATA
