// Auto-generated by backend/curriculum/build_parcours_manuels.py — do not edit by hand.
import type { ManuelData } from '../ManuelInteractif'

const DATA: ManuelData = {
"book": "Le marchand de bois et les enchaînements",
"level": "Avancé",
"chapters": [
{
"n": 0,
"title": "Présentation"
},
{
"n": 1,
"title": "Le marchand de bois"
},
{
"n": 2,
"title": "Le faux marchand de bois"
},
{
"n": 3,
"title": "Les enchaînements d'aile"
},
{
"n": 4,
"title": "Le marchand de bois approfondi"
},
{
"n": 5,
"title": "Pratiquez les enchaînements"
}
],
"blocks": [
{
"type": "h1",
"ch": 0,
"runs": [
{
"t": "Le marchand de bois et les enchaînements"
}
]
},
{
"type": "p",
"ch": 0,
"runs": [
{
"t": "La structure reine du jeu de blocage et ses combinaisons."
}
]
},
{
"type": "p",
"ch": 0,
"runs": [
{
"b": 1,
"t": "Objectif. "
},
{
"t": "Comprendre le marchand de bois, le faux marchand de bois et les enchaînements d'aile — structures et combinaisons associées."
}
]
},
{
"type": "h2",
"ch": 1,
"runs": [
{
"t": "Le marchand de bois"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "La formation du marchand de bois et ses combinaisons favorables. Étudiez ces positions types tirées des « Enchaînements » de Grégoire."
}
]
},
{
"type": "board",
"id": "av_marchand_de_bois_l1_pos0",
"ch": 1
},
{
"type": "board",
"id": "av_marchand_de_bois_l1_pos1",
"ch": 1
},
{
"type": "board",
"id": "av_marchand_de_bois_l1_pos2",
"ch": 1
},
{
"type": "board",
"id": "av_marchand_de_bois_l1_pos3",
"ch": 1
},
{
"type": "board",
"id": "av_marchand_de_bois_l1_pos4",
"ch": 1
},
{
"type": "board",
"id": "av_marchand_de_bois_l1_pos5",
"ch": 1
},
{
"type": "board",
"id": "av_marchand_de_bois_l1_pos6",
"ch": 1
},
{
"type": "board",
"id": "av_marchand_de_bois_l1_pos7",
"ch": 1
},
{
"type": "h2",
"ch": 2,
"runs": [
{
"t": "Le faux marchand de bois"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "Le faux marchand de bois : ses combinaisons et ses conséquences, à connaître pour l'attaquer ou l'éviter."
}
]
},
{
"type": "board",
"id": "av_marchand_de_bois_l2_pos0",
"ch": 2
},
{
"type": "board",
"id": "av_marchand_de_bois_l2_pos1",
"ch": 2
},
{
"type": "board",
"id": "av_marchand_de_bois_l2_pos2",
"ch": 2
},
{
"type": "board",
"id": "av_marchand_de_bois_l2_pos3",
"ch": 2
},
{
"type": "board",
"id": "av_marchand_de_bois_l2_pos4",
"ch": 2
},
{
"type": "board",
"id": "av_marchand_de_bois_l2_pos5",
"ch": 2
},
{
"type": "board",
"id": "av_marchand_de_bois_l2_pos6",
"ch": 2
},
{
"type": "board",
"id": "av_marchand_de_bois_l2_pos7",
"ch": 2
},
{
"type": "h2",
"ch": 3,
"runs": [
{
"t": "Les enchaînements d'aile"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "Les enchaînements de l'aile droite et du centre, et les sorties d'enchaînement — comment nouer et dénouer le jeu."
}
]
},
{
"type": "board",
"id": "av_marchand_de_bois_l3_pos0",
"ch": 3
},
{
"type": "board",
"id": "av_marchand_de_bois_l3_pos1",
"ch": 3
},
{
"type": "board",
"id": "av_marchand_de_bois_l3_pos2",
"ch": 3
},
{
"type": "board",
"id": "av_marchand_de_bois_l3_pos3",
"ch": 3
},
{
"type": "board",
"id": "av_marchand_de_bois_l3_pos4",
"ch": 3
},
{
"type": "board",
"id": "av_marchand_de_bois_l3_pos5",
"ch": 3
},
{
"type": "board",
"id": "av_marchand_de_bois_l3_pos6",
"ch": 3
},
{
"type": "board",
"id": "av_marchand_de_bois_l3_pos7",
"ch": 3
},
{
"type": "h2",
"ch": 4,
"runs": [
{
"t": "Le marchand de bois approfondi"
}
]
},
{
"type": "p",
"ch": 4,
"runs": [
{
"t": "Le marchand de bois et le faux marchand de bois vus par le tome 2 du « Sens du jeu » : nuances positionnelles et plans."
}
]
},
{
"type": "board",
"id": "av_marchand_de_bois_l4_pos0",
"ch": 4
},
{
"type": "board",
"id": "av_marchand_de_bois_l4_pos1",
"ch": 4
},
{
"type": "board",
"id": "av_marchand_de_bois_l4_pos2",
"ch": 4
},
{
"type": "board",
"id": "av_marchand_de_bois_l4_pos3",
"ch": 4
},
{
"type": "board",
"id": "av_marchand_de_bois_l4_pos4",
"ch": 4
},
{
"type": "board",
"id": "av_marchand_de_bois_l4_pos5",
"ch": 4
},
{
"type": "board",
"id": "av_marchand_de_bois_l4_pos6",
"ch": 4
},
{
"type": "board",
"id": "av_marchand_de_bois_l4_pos7",
"ch": 4
},
{
"type": "h2",
"ch": 5,
"runs": [
{
"t": "Pratiquez les enchaînements"
}
]
},
{
"type": "p",
"ch": 5,
"runs": [
{
"t": "Les combinaisons d'enchaînement à résoudre, vérifiées par le moteur."
}
]
},
{
"type": "board",
"id": "av_marchand_de_bois_l5_ex0",
"ch": 5
},
{
"type": "board",
"id": "av_marchand_de_bois_l5_ex1",
"ch": 5
},
{
"type": "board",
"id": "av_marchand_de_bois_l5_ex2",
"ch": 5
},
{
"type": "board",
"id": "av_marchand_de_bois_l5_ex3",
"ch": 5
},
{
"type": "board",
"id": "av_marchand_de_bois_l5_ex4",
"ch": 5
}
],
"positions": {
"av_marchand_de_bois_l1_pos0": {
"id": "av_marchand_de_bois_l1_pos0",
"ch": 1,
"title": "Le marchand de bois",
"start": {
"wm": [
26,
31,
32,
36,
39,
44,
48
],
"wk": [],
"bm": [
11,
12,
13,
16,
17,
18,
22
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Le marchand de bois"
},
"av_marchand_de_bois_l1_pos1": {
"id": "av_marchand_de_bois_l1_pos1",
"ch": 1,
"title": "Le marchand de bois",
"start": {
"wm": [
26,
31,
32,
33,
36,
44,
48
],
"wk": [],
"bm": [
11,
12,
13,
16,
17,
18,
22
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Le marchand de bois"
},
"av_marchand_de_bois_l1_pos2": {
"id": "av_marchand_de_bois_l1_pos2",
"ch": 1,
"title": "Le marchand de bois",
"start": {
"wm": [
26,
31,
32,
36,
39,
44,
48
],
"wk": [],
"bm": [
13,
16,
17,
18,
19,
22,
24
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Le marchand de bois"
},
"av_marchand_de_bois_l1_pos3": {
"id": "av_marchand_de_bois_l1_pos3",
"ch": 1,
"title": "Le marchand de bois",
"start": {
"wm": [
35,
36,
38,
39,
40,
43,
45,
48
],
"wk": [],
"bm": [
15,
18,
19,
23,
24,
25,
28,
29
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Le marchand de bois"
},
"av_marchand_de_bois_l1_pos4": {
"id": "av_marchand_de_bois_l1_pos4",
"ch": 1,
"title": "Le marchand de bois",
"start": {
"wm": [
29,
31,
32,
33,
34,
35,
36,
37,
38,
39,
40,
41,
42,
43,
45,
46,
47,
48,
49,
50
],
"wk": [],
"bm": [
1,
2,
3,
4,
5,
6,
7,
8,
9,
10,
11,
12,
13,
15,
16,
17,
18,
20,
24,
25
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Le marchand de bois"
},
"av_marchand_de_bois_l1_pos5": {
"id": "av_marchand_de_bois_l1_pos5",
"ch": 1,
"title": "Le marchand de bois",
"start": {
"wm": [
31,
32,
33,
34,
35,
36,
37,
38,
39,
40,
41,
42,
43,
44,
45,
46,
47,
48,
49,
50
],
"wk": [],
"bm": [
1,
2,
3,
4,
5,
6,
7,
8,
9,
10,
11,
12,
13,
14,
15,
16,
17,
18,
19,
20
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Le marchand de bois"
},
"av_marchand_de_bois_l1_pos6": {
"id": "av_marchand_de_bois_l1_pos6",
"ch": 1,
"title": "Comment se dégager du marchand de bois ?",
"start": {
"wm": [
25,
26,
27,
31,
33,
36,
38,
39,
43,
45,
47,
48,
49,
50
],
"wk": [],
"bm": [
2,
3,
4,
6,
8,
12,
13,
15,
16,
17,
18,
19,
22,
23
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Comment se dégager du marchand de bois ?"
},
"av_marchand_de_bois_l1_pos7": {
"id": "av_marchand_de_bois_l1_pos7",
"ch": 1,
"title": "Comment se dégager du marchand de bois ?",
"start": {
"wm": [
31,
32,
33,
34,
35,
36,
37,
38,
39,
40,
41,
42,
43,
44,
45,
46,
47,
48,
49,
50
],
"wk": [],
"bm": [
1,
2,
3,
4,
5,
6,
7,
8,
9,
10,
11,
12,
13,
14,
15,
16,
17,
18,
19,
20
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Comment se dégager du marchand de bois ?"
},
"av_marchand_de_bois_l2_pos0": {
"id": "av_marchand_de_bois_l2_pos0",
"ch": 2,
"title": "Le faux marchand de bois",
"start": {
"wm": [
25,
31,
32,
33,
36,
38,
39,
40,
41,
42,
43,
45,
47,
48,
49
],
"wk": [],
"bm": [
2,
3,
6,
8,
9,
11,
12,
13,
14,
15,
16,
17,
18,
19,
22
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Le faux marchand de bois"
},
"av_marchand_de_bois_l2_pos1": {
"id": "av_marchand_de_bois_l2_pos1",
"ch": 2,
"title": "Le faux marchand de bois",
"start": {
"wm": [
25,
31,
32,
33,
36,
38,
39,
40,
41,
42,
43,
45,
47,
48,
49
],
"wk": [],
"bm": [
2,
3,
7,
8,
9,
11,
12,
13,
14,
15,
16,
17,
18,
19,
22
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Le faux marchand de bois"
},
"av_marchand_de_bois_l2_pos2": {
"id": "av_marchand_de_bois_l2_pos2",
"ch": 2,
"title": "Le faux marchand de bois",
"start": {
"wm": [
31,
32,
33,
34,
35,
36,
37,
38,
39,
40,
41,
42,
43,
44,
45,
46,
47,
48,
49,
50
],
"wk": [],
"bm": [
1,
2,
3,
4,
5,
6,
7,
8,
9,
10,
11,
12,
13,
14,
15,
16,
17,
18,
19,
20
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Le faux marchand de bois"
},
"av_marchand_de_bois_l2_pos3": {
"id": "av_marchand_de_bois_l2_pos3",
"ch": 2,
"title": "Les combinaisons du faux marchand de bois",
"start": {
"wm": [
25,
27,
31,
33,
35,
36,
39,
42,
43,
44,
48,
49
],
"wk": [],
"bm": [
2,
3,
4,
7,
8,
9,
12,
13,
15,
16,
18,
22
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Les combinaisons du faux marchand de bois"
},
"av_marchand_de_bois_l2_pos4": {
"id": "av_marchand_de_bois_l2_pos4",
"ch": 2,
"title": "Les combinaisons du faux marchand de bois",
"start": {
"wm": [
24,
27,
31,
33,
35,
36,
39,
42,
43,
44,
48,
49
],
"wk": [],
"bm": [
2,
3,
4,
7,
8,
9,
12,
13,
15,
16,
18,
22
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Les combinaisons du faux marchand de bois"
},
"av_marchand_de_bois_l2_pos5": {
"id": "av_marchand_de_bois_l2_pos5",
"ch": 2,
"title": "Les combinaisons du faux marchand de bois",
"start": {
"wm": [
27,
31,
35,
36,
38,
39,
44,
45,
48
],
"wk": [],
"bm": [
5,
6,
13,
15,
16,
18,
19,
22,
29
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Les combinaisons du faux marchand de bois"
},
"av_marchand_de_bois_l2_pos6": {
"id": "av_marchand_de_bois_l2_pos6",
"ch": 2,
"title": "Les combinaisons du faux marchand de bois",
"start": {
"wm": [
27,
29,
31,
33,
35,
36,
38,
39,
43,
45,
46,
48,
49
],
"wk": [],
"bm": [
3,
5,
6,
7,
8,
13,
15,
16,
17,
18,
19,
20,
22
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Les combinaisons du faux marchand de bois"
},
"av_marchand_de_bois_l2_pos7": {
"id": "av_marchand_de_bois_l2_pos7",
"ch": 2,
"title": "Les combinaisons du faux marchand de bois",
"start": {
"wm": [
27,
29,
31,
33,
35,
36,
38,
39,
43,
45,
46,
49
],
"wk": [],
"bm": [
5,
6,
7,
9,
13,
16,
17,
18,
19,
20,
22,
24
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Les combinaisons du faux marchand de bois"
},
"av_marchand_de_bois_l3_pos0": {
"id": "av_marchand_de_bois_l3_pos0",
"ch": 3,
"title": "Les enchaînements de l'aile droite",
"start": {
"wm": [
27,
29,
32,
33,
34,
35,
36,
37,
38,
39,
42,
43
],
"wk": [],
"bm": [
3,
7,
8,
9,
12,
13,
15,
18,
19,
20,
24,
26
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Les enchaînements de l'aile droite"
},
"av_marchand_de_bois_l3_pos1": {
"id": "av_marchand_de_bois_l3_pos1",
"ch": 3,
"title": "Les enchaînements de l'aile droite",
"start": {
"wm": [
31,
32,
33,
34,
35,
36,
37,
38,
39,
40,
41,
42,
43,
44,
45,
46,
47,
48,
49,
50
],
"wk": [],
"bm": [
1,
2,
3,
4,
5,
6,
7,
8,
9,
10,
11,
12,
13,
14,
15,
16,
17,
18,
19,
20
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Les enchaînements de l'aile droite"
},
"av_marchand_de_bois_l3_pos2": {
"id": "av_marchand_de_bois_l3_pos2",
"ch": 3,
"title": "Les enchaînements de l'aile droite",
"start": {
"wm": [
29,
31,
32,
33,
34,
35,
36,
37,
38,
39,
40,
41,
42,
44,
45,
46,
47,
48,
49,
50
],
"wk": [],
"bm": [
1,
2,
3,
4,
5,
6,
7,
8,
9,
10,
11,
12,
13,
15,
16,
17,
18,
20,
23,
24
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Les enchaînements de l'aile droite"
},
"av_marchand_de_bois_l3_pos3": {
"id": "av_marchand_de_bois_l3_pos3",
"ch": 3,
"title": "Les enchaînements de l'aile droite",
"start": {
"wm": [
30,
33,
34,
35,
37,
38,
39,
40,
45
],
"wk": [],
"bm": [
12,
13,
15,
16,
17,
18,
19,
20,
25
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Les enchaînements de l'aile droite"
},
"av_marchand_de_bois_l3_pos4": {
"id": "av_marchand_de_bois_l3_pos4",
"ch": 3,
"title": "Les enchaînements de l'aile droite",
"start": {
"wm": [
30,
31,
32,
33,
34,
35,
36,
37,
38,
39,
40,
41,
42,
43,
45,
46,
47,
48,
49,
50
],
"wk": [],
"bm": [
1,
2,
3,
4,
5,
6,
7,
8,
9,
10,
11,
12,
13,
14,
16,
17,
18,
19,
24,
25
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Les enchaînements de l'aile droite"
},
"av_marchand_de_bois_l3_pos5": {
"id": "av_marchand_de_bois_l3_pos5",
"ch": 3,
"title": "Les enchaînements de l'aile droite",
"start": {
"wm": [
31,
32,
33,
34,
35,
36,
37,
38,
39,
40,
41,
42,
43,
44,
45,
46,
47,
48,
49,
50
],
"wk": [],
"bm": [
1,
2,
3,
4,
5,
6,
7,
8,
9,
10,
11,
12,
13,
14,
15,
16,
17,
18,
19,
20
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Les enchaînements de l'aile droite"
},
"av_marchand_de_bois_l3_pos6": {
"id": "av_marchand_de_bois_l3_pos6",
"ch": 3,
"title": "L'enchaînement du centre gauche",
"start": {
"wm": [
31,
32,
33,
34,
35,
36,
37,
38,
39,
40,
41,
42,
43,
44,
45,
46,
47,
48,
49,
50
],
"wk": [],
"bm": [
1,
2,
3,
4,
5,
6,
7,
8,
9,
10,
11,
12,
13,
14,
15,
16,
17,
18,
19,
20
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "L'enchaînement du centre gauche"
},
"av_marchand_de_bois_l3_pos7": {
"id": "av_marchand_de_bois_l3_pos7",
"ch": 3,
"title": "L'enchaînement du centre gauche",
"start": {
"wm": [
27,
28,
31,
33,
34,
35,
36,
37,
38,
40,
41,
42,
43,
44,
45,
47,
48,
49,
50
],
"wk": [],
"bm": [
2,
3,
4,
5,
6,
7,
8,
9,
10,
11,
12,
13,
14,
16,
17,
18,
19,
22,
24
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "L'enchaînement du centre gauche"
},
"av_marchand_de_bois_l4_pos0": {
"id": "av_marchand_de_bois_l4_pos0",
"ch": 4,
"title": "Le faux marchand de bois (faux MdB)",
"start": {
"wm": [
27,
31,
36
],
"wk": [],
"bm": [
16,
18,
22
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Le faux marchand de bois (faux MdB)"
},
"av_marchand_de_bois_l4_pos1": {
"id": "av_marchand_de_bois_l4_pos1",
"ch": 4,
"title": "Le faux marchand de bois (faux MdB)",
"start": {
"wm": [
27,
31,
36,
48
],
"wk": [],
"bm": [
16,
17,
18,
22
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Le faux marchand de bois (faux MdB)"
},
"av_marchand_de_bois_l4_pos2": {
"id": "av_marchand_de_bois_l4_pos2",
"ch": 4,
"title": "Le faux marchand de bois (faux MdB)",
"start": {
"wm": [
24,
25,
27,
31,
36,
39,
43
],
"wk": [],
"bm": [
8,
13,
14,
16,
17,
18,
22
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Le faux marchand de bois (faux MdB)"
},
"av_marchand_de_bois_l4_pos3": {
"id": "av_marchand_de_bois_l4_pos3",
"ch": 4,
"title": "Le faux marchand de bois (faux MdB)",
"start": {
"wm": [
25,
27,
31,
35,
36,
38,
39,
40,
48
],
"wk": [],
"bm": [
8,
14,
16,
17,
18,
19,
22,
23,
24
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Le faux marchand de bois (faux MdB)"
},
"av_marchand_de_bois_l4_pos4": {
"id": "av_marchand_de_bois_l4_pos4",
"ch": 4,
"title": "Le faux marchand de bois (faux MdB)",
"start": {
"wm": [
31,
32,
36,
38,
39,
43
],
"wk": [],
"bm": [
6,
9,
16,
17,
18,
22
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Le faux marchand de bois (faux MdB)"
},
"av_marchand_de_bois_l4_pos5": {
"id": "av_marchand_de_bois_l4_pos5",
"ch": 4,
"title": "Le faux marchand de bois (faux MdB)",
"start": {
"wm": [
26,
27,
29,
33,
35,
39,
40,
43,
45
],
"wk": [],
"bm": [
4,
11,
12,
13,
15,
18,
19,
20,
24
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Le faux marchand de bois (faux MdB)"
},
"av_marchand_de_bois_l4_pos6": {
"id": "av_marchand_de_bois_l4_pos6",
"ch": 4,
"title": "Le faux marchand de bois (faux MdB)",
"start": {
"wm": [
27,
29,
31,
32,
33,
35,
36,
43,
45,
47
],
"wk": [],
"bm": [
6,
12,
13,
15,
16,
17,
18,
19,
20,
22
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Le faux marchand de bois (faux MdB)"
},
"av_marchand_de_bois_l4_pos7": {
"id": "av_marchand_de_bois_l4_pos7",
"ch": 4,
"title": "Le faux marchand de bois (faux MdB)",
"start": {
"wm": [
27,
31,
33,
34,
36,
39,
43
],
"wk": [],
"bm": [
6,
13,
16,
18,
19,
22,
23
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Le faux marchand de bois (faux MdB)"
},
"av_marchand_de_bois_l5_ex0": {
"id": "av_marchand_de_bois_l5_ex0",
"ch": 5,
"title": "ENCHAINEMENTS — combinaison (p.49 #2)",
"start": {
"wm": [
25,
27,
31,
33,
35,
36,
38,
40,
41,
42,
43,
44,
45,
47,
48,
49
],
"wk": [],
"bm": [
1,
2,
3,
4,
7,
8,
9,
11,
12,
13,
15,
16,
18,
19,
20,
22
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "25x14x23",
"f": 25,
"t": 23,
"c": [
19,
20
],
"path": [
25,
14,
23
],
"p": false
},
{
"n": "18x29",
"f": 18,
"t": 29,
"c": [
23
],
"path": [
18,
29
],
"p": false
},
{
"n": "27x18",
"f": 27,
"t": 18,
"c": [
22
],
"path": [
27,
18
],
"p": false
},
{
"n": "12x23",
"f": 12,
"t": 23,
"c": [
18
],
"path": [
12,
23
],
"p": false
},
{
"n": "33x24",
"f": 33,
"t": 24,
"c": [
29
],
"path": [
33,
24
],
"p": false
}
],
"theme": "Les combinaisons du faux marchand de bois",
"pub": "25x14x23 18x29 27x18 12x23 33x24",
"win": "white",
"exp": "Les combinaisons du faux marchand de bois"
},
"av_marchand_de_bois_l5_ex1": {
"id": "av_marchand_de_bois_l5_ex1",
"ch": 5,
"title": "ENCHAINEMENTS — combinaison (p.50 #1)",
"start": {
"wm": [
25,
27,
31,
33,
35,
36,
38,
40,
41,
42,
43,
44,
45,
46,
48,
49
],
"wk": [],
"bm": [
1,
2,
3,
4,
7,
8,
9,
11,
12,
13,
15,
16,
18,
19,
20,
22
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "25x14x23",
"f": 25,
"t": 23,
"c": [
19,
20
],
"path": [
25,
14,
23
],
"p": false
},
{
"n": "18x29",
"f": 18,
"t": 29,
"c": [
23
],
"path": [
18,
29
],
"p": false
},
{
"n": "27x18",
"f": 27,
"t": 18,
"c": [
22
],
"path": [
27,
18
],
"p": false
},
{
"n": "12x23",
"f": 12,
"t": 23,
"c": [
18
],
"path": [
12,
23
],
"p": false
},
{
"n": "33x24",
"f": 33,
"t": 24,
"c": [
29
],
"path": [
33,
24
],
"p": false
}
],
"theme": "Les combinaisons du faux marchand de bois",
"pub": "25x14x23 18x29 27x18 12x23 33x24",
"win": "white",
"exp": "Les combinaisons du faux marchand de bois"
},
"av_marchand_de_bois_l5_ex2": {
"id": "av_marchand_de_bois_l5_ex2",
"ch": 5,
"title": "ENCHAINEMENTS — combinaison (p.70 #1)",
"start": {
"wm": [
26,
27,
28,
31,
32,
33,
34,
37,
38,
39,
41,
42,
43,
48
],
"wk": [],
"bm": [
2,
3,
6,
7,
8,
12,
13,
14,
15,
16,
17,
18,
19,
21,
24
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "28-22",
"f": 28,
"t": 22,
"c": [],
"path": [
28,
22
],
"p": false
},
{
"n": "17x28",
"f": 17,
"t": 28,
"c": [
22
],
"path": [
17,
28
],
"p": false
},
{
"n": "26x17",
"f": 26,
"t": 17,
"c": [
21
],
"path": [
26,
17
],
"p": false
},
{
"n": "12x21",
"f": 12,
"t": 21,
"c": [
17
],
"path": [
12,
21
],
"p": false
},
{
"n": "32x23x12x1",
"f": 32,
"t": 1,
"c": [
18,
28,
7
],
"path": [
32,
23,
12,
1
],
"p": true
},
{
"n": "21x32",
"f": 21,
"t": 32,
"c": [
27
],
"path": [
21,
32
],
"p": false
},
{
"n": "37x28",
"f": 37,
"t": 28,
"c": [
32
],
"path": [
37,
28
],
"p": false
}
],
"theme": "L'enchaînement de l'aile droite",
"pub": "28-22 17x28 26x17 12x21 32x23x12x1 21x32 37x28",
"win": "white",
"exp": "L'enchaînement de l'aile droite"
},
"av_marchand_de_bois_l5_ex3": {
"id": "av_marchand_de_bois_l5_ex3",
"ch": 5,
"title": "ENCHAINEMENTS — combinaison (p.80 #1)",
"start": {
"wm": [
21,
26,
27,
30,
31,
34,
35,
36,
38,
40,
43,
44,
45,
48
],
"wk": [],
"bm": [
3,
6,
7,
8,
9,
12,
13,
14,
17,
19,
20,
23,
24,
25
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "34-29",
"f": 34,
"t": 29,
"c": [],
"path": [
34,
29
],
"p": false
},
{
"n": "24x33x42",
"f": 24,
"t": 42,
"c": [
29,
38
],
"path": [
24,
33,
42
],
"p": false
},
{
"n": "48x37",
"f": 48,
"t": 37,
"c": [
42
],
"path": [
48,
37
],
"p": false
},
{
"n": "25x34",
"f": 25,
"t": 34,
"c": [
30
],
"path": [
25,
34
],
"p": false
},
{
"n": "40x29x18",
"f": 40,
"t": 18,
"c": [
34,
23
],
"path": [
40,
29,
18
],
"p": false
},
{
"n": "13x22",
"f": 13,
"t": 22,
"c": [
18
],
"path": [
13,
22
],
"p": false
},
{
"n": "27x18",
"f": 27,
"t": 18,
"c": [
22
],
"path": [
27,
18
],
"p": false
},
{
"n": "12x23",
"f": 12,
"t": 23,
"c": [
18
],
"path": [
12,
23
],
"p": false
},
{
"n": "21x12x1",
"f": 21,
"t": 1,
"c": [
17,
7
],
"path": [
21,
12,
1
],
"p": true
}
],
"theme": "L'enchaînement de l'aile droite",
"pub": "34-29 24x33x42 48x37 25x34 40x29x18 13x22 27x18 12x23 21x12x1",
"win": "white",
"exp": "L'enchaînement de l'aile droite"
},
"av_marchand_de_bois_l5_ex4": {
"id": "av_marchand_de_bois_l5_ex4",
"ch": 5,
"title": "ENCHAINEMENTS — combinaison (p.84 #2)",
"start": {
"wm": [
27,
28,
30,
31,
32,
33,
34,
35,
38,
40,
42,
43,
45,
48
],
"wk": [],
"bm": [
3,
8,
9,
10,
11,
12,
14,
16,
18,
19,
20,
23,
25,
26
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "30-24",
"f": 30,
"t": 24,
"c": [],
"path": [
30,
24
],
"p": false
},
{
"n": "19x30x39",
"f": 19,
"t": 39,
"c": [
24,
34
],
"path": [
19,
30,
39
],
"p": false
},
{
"n": "43x34",
"f": 43,
"t": 34,
"c": [
39
],
"path": [
43,
34
],
"p": false
},
{
"n": "26x37",
"f": 26,
"t": 37,
"c": [
31
],
"path": [
26,
37
],
"p": false
},
{
"n": "28x19",
"f": 28,
"t": 19,
"c": [
23
],
"path": [
28,
19
],
"p": false
},
{
"n": "37x28x39x30",
"f": 37,
"t": 30,
"c": [
32,
33,
34
],
"path": [
37,
28,
39,
30
],
"p": false
},
{
"n": "35x24x15x4x13x2",
"f": 35,
"t": 2,
"c": [
20,
8,
9,
10,
30
],
"path": [
35,
24,
15,
4,
13,
2
],
"p": true
},
{
"n": "14x23",
"f": 14,
"t": 23,
"c": [
19
],
"path": [
14,
23
],
"p": false
}
],
"theme": "L'enchaînement de l'aile droite",
"pub": "30-24 19x30x39 43x34 26x37 28x19 37x28x39x30 35x24x15x4x13x2 14x23",
"win": "white",
"exp": "L'enchaînement de l'aile droite"
}
}
}

export default DATA
