// Auto-generated by backend/curriculum/build_parcours_manuels.py — do not edit by hand.
import type { ManuelData } from '../ManuelInteractif'

const DATA: ManuelData = {
"book": "Coups avancés et structures",
"level": "Débutant",
"chapters": [
{
"n": 0,
"title": "Présentation"
},
{
"n": 1,
"title": "La méthode D-P-A (DéblaiementPositionnement-Acheminement)"
},
{
"n": 2,
"title": "Le coup de la bombe"
},
{
"n": 3,
"title": "Le coup Springer"
},
{
"n": 4,
"title": "Le coup Avid"
},
{
"n": 5,
"title": "Le coup de croc"
},
{
"n": 6,
"title": "Le coup Philippe avec prises multiples"
},
{
"n": 7,
"title": "La fourchette"
},
{
"n": 8,
"title": "Les structures de pions associées au coup Philippe"
}
],
"blocks": [
{
"type": "h1",
"ch": 0,
"runs": [
{
"t": "Coups avancés et structures"
}
]
},
{
"type": "p",
"ch": 0,
"runs": [
{
"t": "Méthode D-P-A, coups de la bombe, Springer, Avid, croc, fourchette."
}
]
},
{
"type": "p",
"ch": 0,
"runs": [
{
"b": 1,
"t": "Objectif. "
},
{
"t": "Aborder les combinaisons en 4-5 temps et les structures de pions associées."
}
]
},
{
"type": "h2",
"ch": 1,
"runs": [
{
"t": "La méthode D-P-A (DéblaiementPositionnement-Acheminement)"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "Le passage des combinaisons en 4 temps à celles en 5, constitue normalement une véritable étape. Les limites de la mémoire de travail sont théoriquement atteintes. Il devient nécessaire d’adopter une autre approche dans la résolution des combinaisons. Il est possible que vous ayez déjà, de manière inconsciente, élaboré des solutions pour simplifier les recherches. Avant d’aller plus loin, revenons une nouvelle fois sur les fondamentaux. A chaque étape, dans la recherche d’une combinaison, nous sommes confrontés à cette contradiction en une vision large qui nous permet de ne rien oublier et une vision en profondeur qui nous permet d’appréhender la rafle finale. Comment concilier ces deux manières de réfléchir ? Autant avoir l’esprit clair sur cette question et connaître nos limites. Les deux manières d’anticiper les coups sont incompatibles. On peut seulement passer de l’une à l’autre. Et l’efficacité d’une vision profonde sera le résultat d’un bon raisonnement. Nous avons mis en évidence environ 90% des mécanismes utilisés dans les combinaisons, et nous nous sommes habitués à identifier la rafle finale avec sa case de départ et sa case d’arrivée. Cette méthode nous permet d’approcher les solutions par le raisonnement. La difficulté concerne toujours la visualisation mentale du damier après des échanges. Certains pions se sont déplacés et d’autres ont disparu. Il devient nécessaire de faire des synthèses de position intermédiaires. C’est-à-dire concevoir la position au 4e temps en remettant en place mentalement les pions déplacés et disparus."
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "Il est important de réduire le nombre d’informations à mémoriser. Le raisonnement et l’expérience nous conduisent à supposer un coup de dame à 4. La case de départ ne peut être que la case 35. La rafle finale sera donc 35x4. Pour y parvenir, il faut faire sauter les pions 13 et 24 et amener un pion sur la case 30. Raisonner, puis visualiser. 1. 27-21"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "16x27"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "2. 32x12"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "18x7"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "Mentalement, il faut imaginer la nouvelle position dans laquelle il reste 8 pions chez les blancs qui n’ont pas bougé. On le voit clairement dans le second diagramme. Pour les noirs, les pions 16 et 17 ont disparu. Il reste le pion 16 passé en 7. 3. 33-29"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "24x33"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "4. 38x18"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "13x22"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "A nouveau, la position s’éclaircit. Les pions noirs 13 et 24 ont disparu. La visualisation des pions blancs restants est assez évidente. Il ne manque qu’à acheminer le pion 26 en 30 par : 5. 37-31"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "26x30"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "6. 35x4"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "Il existe une autre manière d’appréhender les combinaisons. Il s’agit de scinder leur déroulement en plusieurs étapes. Tout d’abord, la phase de déblaiement qui est destinée à éliminer les pions gênants, ensuite la phase de positionnement qui sert à mettre en place les pions manquants à la rafle, et enfin la phase finale d’acheminement du pion de départ de la rafle. En raisonnant de la sorte avec la combinaison décrite ci-dessus, nous avons : • • •"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "Phase de déblaiement : les 2 pionnages 27-21 et 33-29 Phase de positionnement : aucune Phase d’acheminement : 37-31 qui amène le pion 26 en 30."
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "Un autre exemple :"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "Dans cette position, il y a un coup de dame sur la case 5. C’est inattendu. La solution passe nécessairement par amener un pion en 19 et par acheminer un pion à 34. Solution : Phase de déblaiement : 24-19 (13x24) Phase de positionnement : 28-22 (17x28) 33x13 (8x19). Le pion 19 est en place (Diag. 2) Phase d’acheminement : 27-21 (16x38) 39-33 (38x29) 34x5."
}
]
},
{
"type": "h2",
"ch": 2,
"runs": [
{
"t": "Le coup de la bombe"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "Le coup de la bombe est une combinaison qui comprend assez souvent 5 temps, et quelquefois plus. Le mécanisme de la rafle est assez singulier car il se déroule en 2 étapes."
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "Après 27-21 (16x27), on obtient la position du second diagramme. Les blancs font alors une première partie de rafle en capturant 2 pions par 32x12. Les noirs sont alors forcés de prendre 2 pions par (23x41) ou (23x43). Avec la seconde prise, on arrive à la position du 3 e diagramme dans laquelle les blancs reprennent à nouveau 2 pions. Le bilan de cette combinaison est positif puisqu’il permet de gagner un pion. Le même principe permet également de gagner un pion dans ce genre de position :"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "Après 27-21 (16x27) on obtient la position du second diagramme. Toujours la prise 32x12 (23x41) amenant la position du troisième diagramme dans lequel la prise (12x23) conduit au gain de pion."
}
]
},
{
"type": "h2",
"ch": 3,
"runs": [
{
"t": "Le coup Springer"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "Le coup SPRINGER est une combinaison en 5 temps qui se rencontre en fin de milieu de partie classique. Bénédictus SPRINGER avait effectué cette combinaison lors du championnat du Monde 1928 contre Alfred MOLIMARD."
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "Cette combinaison est assez inattendue car la rafle finale 38x7 du 3 e diagramme, se présente rarement. De plus, la présence d’un pion en 12 masque cette rafle. Cette combinaison est à connaître car, en partie, on risque souvent de passer à côté. Solution : Phase de déblaiement : 27-22 (18x27) 32x21 (23x41) [cette prise de 2 pions est la clé du mécanisme] Phase de positionnement : 21-17 (ad lib) Phase d’acheminement : 42-37 (41x32) 38x7 Le coup Springer se présente également avec une rafle plus spectaculaire :"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "La combinaison repose sur le même mécanisme que précédemment. Seule la rafle finale du 3 e diagramme est différente. C’est cette seconde forme de combinaison que SPRINGER avait réalisée dans sa partie."
}
]
},
{
"type": "h2",
"ch": 4,
"runs": [
{
"t": "Le coup Avid"
}
]
},
{
"type": "p",
"ch": 4,
"runs": [
{
"t": "Le coup AVID est une combinaison en 5 temps ou plus qui se rencontre en fin de milieu de partie classique. Son mécanisme repose sur un coup de talon. Le déroulement est assez déroutant. Il est utile de le connaître."
}
]
},
{
"type": "p",
"ch": 4,
"runs": [
{
"t": "du 3e diagramme n’est pas évidente à découvrir. L’acheminement du pion 24 en 31 est de surcroit surprenant. Solution : Phase de déblaiement : aucune Phase de positionnement : 37-31 (26x37) 32x41 (23x21) diag. N°2 Phase d’acheminement : 33-29 (24x42) 41-37 (42x31) 36x7 Le coup Avid se présente également avec une rafle plus spectaculaire :"
}
]
},
{
"type": "p",
"ch": 4,
"runs": [
{
"t": "La combinaison repose sur le même mécanisme que précédemment. Seule la rafle finale du 3 e diagramme est différente."
}
]
},
{
"type": "h2",
"ch": 5,
"runs": [
{
"t": "Le coup de croc"
}
]
},
{
"type": "p",
"ch": 5,
"runs": [
{
"t": "Le coup de croc est une combinaison en 4 ou 5 temps avec choix de prises multiples. Cette combinaison gagne un pion, quelle que soit la prise. Ce coup s’apparente un peu à la « fourchette », au jeu d’échecs. En voici un exemple caractéristique :"
}
]
},
{
"type": "p",
"ch": 5,
"runs": [
{
"t": "L’attaque des noirs offre l’opportunité de jouer n’importe quel coup pour les blancs. Le premier coup est 27-22, position du 2e diagramme. Ce coup est évidemment surprenant. Il laisse un premier choix de 2 prises. (18x27) est évidemment la plus mauvaise option, puisqu’elle est suivie de 31x22 (25x34) 40x7 (11x2) 28-23 (19x28) 33x31 avec un gain de 2 pions. Sur l’autre prise, (25x34) 40x20, on arrive à la position du 3 e diagramme dans laquelle les Noirs ont à nouveau le choix entre 2 prises. Mais chacune d’entre elles laisse le gain de pion ensuite par 22-17 (11x22) 28x26. Le coup de croc se rencontre également dans ce genre de situation :"
}
]
},
{
"type": "p",
"ch": 5,
"runs": [
{
"t": "Sur un même principe, les blancs gagnent un pion par 27-21, car la suite 21-17 (12x21) 26x28 ne peut être évitée."
}
]
},
{
"type": "h2",
"ch": 6,
"runs": [
{
"t": "Le coup Philippe avec prises multiples"
}
]
},
{
"type": "p",
"ch": 6,
"runs": [
{
"t": "Le coup Philippe est une combinaison bien connue. Sa présence, en cas de prises multiples, est moins familière. En voici un exemple caractéristique :"
}
]
},
{
"type": "p",
"ch": 6,
"runs": [
{
"t": "Sur l’attaque des noirs, les blancs forcent le jeu en jouant : 1. 27-22 C’est la position du second diagramme. On voit que les noirs sont forcés de prendre par : 1…"
}
]
},
{
"type": "p",
"ch": 6,
"runs": [
{
"t": "25x34"
}
]
},
{
"type": "p",
"ch": 6,
"runs": [
{
"t": "2. 40x20"
}
]
},
{
"type": "p",
"ch": 6,
"runs": [
{
"t": "15x24"
}
]
},
{
"type": "p",
"ch": 6,
"runs": [
{
"t": "L’autre prise ne change rien. Les blancs ont à présent un temps de repos pour jouer : 3. 43-39"
}
]
},
{
"type": "p",
"ch": 6,
"runs": [
{
"t": "18x29"
}
]
},
{
"type": "p",
"ch": 6,
"runs": [
{
"t": "4. 32x21"
}
]
},
{
"type": "p",
"ch": 6,
"runs": [
{
"t": "16x27"
}
]
},
{
"type": "p",
"ch": 6,
"runs": [
{
"t": "Les blancs concluent à présent par : 5. 33-29"
}
]
},
{
"type": "p",
"ch": 6,
"runs": [
{
"t": "24x33"
}
]
},
{
"type": "p",
"ch": 6,
"runs": [
{
"t": "6. 13x35"
}
]
},
{
"type": "p",
"ch": 6,
"runs": [
{
"t": "Un autre exemple :"
}
]
},
{
"type": "p",
"ch": 6,
"runs": [
{
"t": "Le début de la combinaison est identique jusqu’à la position du second diagramme. Le trait est alors aux blancs et ceux-ci doivent envisager les 2 prises (14x25) et (15x24). Les blancs jouent donc 44-40 et forcent la prise (15x24). On obtient alors la position du 3e diag. dans lequel les blancs jouent 35-30, et après (24x33) 38x16, le pion 27 est indéfendable."
}
]
},
{
"type": "h2",
"ch": 7,
"runs": [
{
"t": "La fourchette"
}
]
},
{
"type": "p",
"ch": 7,
"runs": [
{
"t": "Les combinaisons dans lesquelles on offre le choix entre 2 prises sont toujours surprenantes. Le thème rappelle celui de la « fourchette » aux échecs. Les rafles sont souvent imaginées à partir des positions de départ. Lorsqu’un pion est attaqué, on pense en premier lieu à le protéger. Proposer le sacrifice simultané d’un autre pion, est pour le moins inattendu. En voici un exemple caractéristique :"
}
]
},
{
"type": "p",
"ch": 7,
"runs": [
{
"t": "Sur l’attaque des Noirs, les blancs forcent le jeu en jouant : 1. 29-23"
}
]
},
{
"type": "p",
"ch": 7,
"runs": [
{
"t": "18x29"
}
]
},
{
"type": "p",
"ch": 7,
"runs": [
{
"t": "Sur l’autre prise (18x27), les blancs gagnent directement un pion par 23x25 2. 22-18"
}
]
},
{
"type": "p",
"ch": 7,
"runs": [
{
"t": "13x22"
}
]
},
{
"type": "p",
"ch": 7,
"runs": [
{
"t": "3. 28x17"
}
]
},
{
"type": "p",
"ch": 7,
"runs": [
{
"t": "4. 35-30"
}
]
},
{
"type": "p",
"ch": 7,
"runs": [
{
"t": "24x35"
}
]
},
{
"type": "p",
"ch": 7,
"runs": [
{
"t": "5. 33x4"
}
]
},
{
"type": "p",
"ch": 7,
"runs": [
{
"t": "21x12"
}
]
},
{
"type": "p",
"ch": 7,
"runs": [
{
"t": "L’exemple suivant est encore plus étonnant :"
}
]
},
{
"type": "p",
"ch": 7,
"runs": [
{
"t": "Dans le premier diagramme, les blancs jouent : 1. 27-22 et si : A – (18x27) 29x18 (13x33) prise de 2 pions amenant le diag.2 B – (19x30) 28x19 (13x33) prise de 2 pions amenant le diag. 3"
}
]
},
{
"type": "h2",
"ch": 8,
"runs": [
{
"t": "Les structures de pions associées au coup Philippe"
}
]
},
{
"type": "p",
"ch": 8,
"runs": [
{
"t": "Il est intéressant d’identifier les formations de pions qui peuvent être à l’origine de certaines combinaisons. Par exemple, le coup Philippe est souvent associé à une même structure de pions."
}
]
},
{
"type": "p",
"ch": 8,
"runs": [
{
"t": "La formation des blancs 34-35-40-45 n’est souvent pas très forte en fin de milieu de partie car elle mobilise 4 pions sur l’aile droite. Ces pions ne sont pas très avancés et ne concourent donc pas à un éventuel passage à dame. Cette formation de 4 pions peut quelquefois jouer un rôle actif lorsqu’elle est associée au pion 27, face à une position des noirs dans le genre du second diagramme. Le troisième diagramme en donne un exemple : Les noirs ne peuvent jouer ni (9-14), ni (7-11) en raison du coup Philippe 27-22, suivi de 34-30. Si les noirs jouent (12-17), les blancs ont ici un coup de dame dévastateur par 34-30 (25x34) 40x29 (23x34) 27-22 (17x39) 38-33 (39x28) 32x1. Sur (19-24), les blancs gagnent directement un pion par 34-30."
}
]
},
{
"type": "p",
"ch": 8,
"runs": [
{
"t": "Le premier diagramme présente une structure caractéristique de contrôle du centre – diagramme n°2 - dans laquelle les menaces de coup Philippe jouent un rôle prépondérant. La position du 3e diagramme l’illustre parfaitement : La menace directe du coup Philippe 27-22 et 33-29 ne peut être parée : 1… 3. 33x22 5. 44-40"
}
]
},
{
"type": "p",
"ch": 8,
"runs": [
{
"t": "11-17 18x27 35x33"
}
]
},
{
"type": "p",
"ch": 8,
"runs": [
{
"t": "2. 27-22 4. 34-30 6. 38x9"
}
]
},
{
"type": "p",
"ch": 8,
"runs": [
{
"t": "17x28 24x35"
}
]
}
],
"positions": {}
}

export default DATA
