// Auto-generated by backend/curriculum/build_parcours_manuels.py — do not edit by hand.
import type { ManuelData } from '../ManuelInteractif'

const DATA: ManuelData = {
"book": "Le pion d'angle 46",
"level": "Intermédiaire",
"chapters": [
{
"n": 0,
"title": "Présentation"
},
{
"n": 1,
"title": "Le pion d'angle 46 (1ère partie)"
},
{
"n": 2,
"title": "Le pion d'angle 46 (seconde partie)"
},
{
"n": 3,
"title": "Le pion d'angle 46 (3e partie)"
}
],
"blocks": [
{
"type": "h1",
"ch": 0,
"runs": [
{
"t": "Le pion d'angle 46"
}
]
},
{
"type": "p",
"ch": 0,
"runs": [
{
"t": "Le pion clé de l'aile droite, en trois temps."
}
]
},
{
"type": "p",
"ch": 0,
"runs": [
{
"b": 1,
"t": "Objectif. "
},
{
"t": "Comprendre le rôle du pion d'angle 46 et savoir quand l'avancer, le garder ou l'échanger."
}
]
},
{
"type": "h2",
"ch": 1,
"runs": [
{
"t": "Le pion d'angle 46 (1ère partie)"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "Chapitre 1 : le pion d’angle 46 (1ère partie) Le pion 46 est souvent affublé de surnoms peu élogieux du genre « traînard », « retardataire », « fainéant », « flemmard », etc. Ce pion sur la case 46 est sans doute le pion de départ le plus mal placé. Il possède une valeur défensive restreinte et sa mise en jeu dans de bonnes conditions se révèle bien souvent un casse-tête. Paradoxalement, la mise en jeu du pion 5 est souvent moins problématique. Quels sont les enjeux pour les blancs ? Les blancs doivent à tout prix éviter de se retrouver dans la situation suivante :"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "Les blancs ont négligé de développer leur pion d’angle 46. Il en résulte qu’ils jouent avec l’équivalent d’un pion de moins. La situation est ici aggravée car toute l’aile gauche des blancs est inactive. Le retour au centre n’apporte pas grand-chose. Les blancs ont d’énormes difficultés à construire un contre jeu utile. Je vous suggère deux parties instructives sur ce thème : Daouda Soumah - Alexander Baliakin 0-2 (8e Barnsteen toernooi Boboli Bunschoten 2007) http://toernooibase.kndb.nl/applet/oerterpapplet2.0/oerterp.php?taal=&kl=1&Id=401&r=4&jr=7&wed=6 2654&weda=&zetten=&aav=&view=4 Alfred Barrow - Baba Sy 0-2 (KSH 1973) http://toernooibase.kndb.nl/applet/oerterpapplet2.0/oerterp.php?taal=&kl=23&Id=572&r=4&jr=0&wed= 164055&weda=&zetten=&aav=&view=4"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "Le retard de développement du pion 46 est malheureusement bien souvent associé à un mauvais développement de l’aile gauche. L’exemple ci-dessous illustre cette situation :"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "Trait aux blancs"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "Trait aux blancs"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "Dans le premier diagramme, le trèfle noir 16-21-26 empêche le développement de l’aile gauche et met bien en évidence l’inactivité des pions 36 et 46. Toutefois le développement des blancs 36-31 puis 46-41 et 41-36, avec l’intention de débloquer l’aile gauche par 27-22x22, ne doit pas être pris à la légère. Le meilleur moyen de contrer ce développement est de libérer la case 18 afin d’empêcher l’échange 27-22. Par exemple : 1. 36-31"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "24-29"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "Un coup qui vise à affaiblir la position des blancs sur leur aile droite. L’avancée immédiate (23-29) est moins intéressante car après 46-41, le coup (18-23) livre un coup direct par 35-30 (24x22) 27x7, avec une fin de partie assez obscure. 2. 40-34 4. 46-41"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "29x40 23-29"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "3. 35x44 5. 41-36"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "14-20 18-23"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "Position du 2e diagramme. L’aile gauche des noirs reste immobilisée, Mais la position est encore loin d’être gagnée. Une partie sur ce thème : Alex van Prinsenbeek - Roel Boomstra 0-2 (MTB Open International Tournament DDB 2013 Round 4) http://toernooibase.kndb.nl/applet/oerterpapplet2.0/oerterp.php?taal=&kl=23&Id=3535&r=4&jr=14&we d=701774&weda=&zetten=&aav=&view=4"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "Le développement de l’aile gauche et la mise en jeu du pion 46 ne garantissent pas toujours le rétablissement de l’équilibre positionnel. L’exemple ci-dessous montre une situation assez habituelle :"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "Trait aux blancs"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "Trait aux blancs"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "Dans le premier diagramme, on remarque la lourdeur de l’aile gauche et le retard de développement du pion 46. La formation d’échange 37-42-48 leur permet de développer leur aile gauche, mais la situation qui en résulte laisse des séquelles : 1. 37-31 3. 31-26"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "26x37 3-8"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "2. 42x31 4. 26x17"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "17-21 12x21"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "On obtient alors la position du 2e diagramme dans laquelle l’aile gauche des blancs reste inactive, tandis que les noirs disposent d’une intéressante mobilité sur l’autre aile. Il n’est évidemment pas question de parler de gain. L’intention est seulement de mettre en évidence les difficultés rencontrées lors de la mise en jeu du pion 46. J’ajouterai seulement une variante assez spectaculaire basée sur le coup SPRINGER : 46-41 (21-26) 41-37 (15-20) 48-43 (20-25) 43-39 (24-29) ! 33x24 (19x30) 28x10 (30-34) 39x30 (25x34) 40x29 (9-14) 10x19 (13x22). Il existe un autre cas de figure où les noirs peuvent profiter d’un mauvais développement du pion 46. Examinons la situation suivante :"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "Trait aux blancs"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "Trait aux blancs"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "Trait aux blancs"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "D’une manière très logique, les blancs mettent en jeu leu pion 46 par : 1. 46-41"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "7-12"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "2. 41-37"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "12-17"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "On obtient alors la forme de position standard du second diagramme. 3. 43-39"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "17-22"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "4. 28x17"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "11x22"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "3e diagramme. Les noirs ont pris possession des 3 cases importantes 22-23-24. Avec la suite habituelle : 5. 31-26"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "22x31"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "6. 36x27"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "Cela laisse les blancs avec une aile gauche lourde et peu active."
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "Au cours de cette première partie, nous avons mis en évidence que : • •"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "La mise en jeu du pion 46 est étroitement liée au bon développement de l’aile gauche. Le développement de l’aile gauche n’est pas une simple affaire."
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "La seconde partie sera consacrée aux débuts de parties dans lesquels la mise en jeu du pion 46 se révèle délicate En troisième et dernière partie, nous confirmerons que, au jeu de dames, rien n’est jamais vraiment tout blanc ou tout noir, et qu’il existe quelques cas où la mise en jeu « sur le tard » du pion 46, se révèle avantageuse."
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "En complément, je vous recommande l’examen des parties suivantes : Husson M. – Ghestem Pierre (FRA-ch, 1943) http://e-dama.net/e/dama/arhiva_partija.vm?uid=4ws2489ihxjt1fpi2wum4hdw4 Romijn Kees - Kats Michael (Brunssum, 1988) 1.32-28 17-22 2.28x17 12x21 3.37-32 7-12 4.41-37 1-7 5.34-30 11-17 6.40-34 7-11 7.45-40 19-23 8.3025 14-19 9.25x14 9x20 10.31-27 10-14 11.33-28 5-10 12.39-33 4-9 13.43-39 20-24 14.49-43 21-26 15.50-45 14-20 16.34-29 23x34 17.39x30 10-14 18.44-39 18-23 19.37-31 26x37 20.42x31 12-18 21.3025 8-12 22.47-42 2-8 23.31-26 24-29 24.33x24 20x29 25.40-34 29x40 26.35x44 15-20 27.39-33 20-24 28.44-40 14-20 29.25x14 9x20 30.43-39 20-25 31.46-41 3-9 32.41-37 17-22 33.28x17 11x31 34.36x27 24-29 35.33x24 19x30 36.40-34 30-35 37.27-22 18x27 38.32x21 16x27 39.45-40 35x33 40.38x7 8-12 41.7x18 13x22 42.42-38 22-28 43.34-29 25-30 44.26-21 27x16 45.38-32 28-33 46.29x38 30-34 47.3228 34-39 0-2 Partie extraite de la base de données TURBO-DAMBASE de Klaas BOR van den Kerkhoff Dick – Evert Bronstring (NLD-chT 2e klasse C, 2001) 1.32-28 20-24 2.37-32 18-23 3.41-37 13-18 4.31-27 8-13 5.34-29 23x34 6.40x20 15x24 7.39-34 10-15 8.44-39 2-8 9.49-44 17-21 10.44-40 21-26 11.37-31 26x37 12.42x31 14-20 13.46-41 5-10 14.41-37 1014 15.47-42 4-10 16.50-44 20-25 17.34-30 25x34 18.40x20 15x24 19.44-40 18-23 20.39-34 12-18 21.34-30 7-12 22.30-25 12-17 23.31-26 17-22 24.28x17 11x31 25.36x27 10-15 26.43-39 8-12 27.3328 1-7 28.39-33 7-11 29.48-43 12-17 30.37-31 14-20 31.25x14 9x20 32.43-39 20-25 33.40-34 15-20 34.45-40 3-8 35.42-37 17-22 36.28x17 11x22 0-2 (1.31/1.20) Partie extraite de la base de données TURBO-DAMBASE de Klaas BOR"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "Grosman Yuval - Koyfman Ygal (Cote d'Or, 1987) 1.32-28 17-22 2.28x17 11x22 3.37-32 12-17 4.33-28 22x33 5.39x28 7-12 6.43-39 19-23 7.28x19 14x23 8.39-33 10-14 9.41-37 14-19 10.44-39 5-10 11.50-44 10-14 12.49-43 6-11 13.33-28 20-24 14.34-30 16-21 15.31-27 21-26 16.39-33 1-6 17.44-39 14-20 18.37-31 26x37 19.42x31 9-14 20.31-26 4-9 21.3025 2-7 22.47-42 24-29 23.33x24 20x29 24.40-34 29x40 25.35x44 15-20 26.39-33 20-24 27.44-39 1116 28.46-41 7-11 29.41-37 14-20 30.25x14 9x20 31.39-34 20-25 32.45-40 [ 32.43-39 17-22 33.28x17 11x31 34.36x27 24-29 35.33x24 19x30 ] 32...17-22 33.28x17 11x31 34.36x27 24-29 35.33x24 19x39 36.43x34 23-29 37.34x23 18x29 38.48-43 25-30 39.43-39 16-21 40.26x17 12x21 41.27x16 30-35 42.16-11 35x33 43.11-7 8-12 44.7x9 3x14 45.32-27 33-39 46.27-22 39-44 47.22-18 44-49 48.37-32 29-33 49.38x29 0-2 Partie extraite de la base de données TURBO-DAMBASE de Klaas BOR Dorland,C. - Roozenburg Piet (1951) 1.34-29 16-21 2.33-28 21-26 3.38-33 20-24 4.29x20 15x24 5.40-34 18-23 6.34-29 23x34 7.39x30 1218 8.44-39 18-23 9.42-38 17-21 10.47-42 7-12 11.31-27 11-16 12.45-40 13-18 13.40-34 9-13 14.3025 4-9 15.34-29 23x34 16.39x30 18-23 17.43-39 12-18 18.39-34 8-12 19.34-29 23x34 20.30x39 18-23 21.49-44 10-15 22.44-40 12-18 23.40-34 1-7 24.34-30 7-12 25.50-45 2-8 26.39-34 24-29 27.33x24 1420 28.25x14 9x40 29.35x44 15-20 30.30-25 20-24 31.44-40 5-10 32.37-31 26x37 33.42x31 21-26 34.41-37 10-14 35.48-43 24-29 36.40-34 29x40 37.45x34 23-29 38.34x23 18x29 39.43-39 3-9 40.2822 19-24 41.38-33 29x38 42.32x43 24-29 43.43-38 13-19 44.38-32 19-24 45.39-33 29x38 46.32x43 24-29 47.43-39 9-13 0-2"
}
]
},
{
"type": "board",
"id": "int_sdj_pion_46_l1_dia0",
"ch": 1
},
{
"type": "board",
"id": "int_sdj_pion_46_l1_dia1",
"ch": 1
},
{
"type": "board",
"id": "int_sdj_pion_46_l1_dia2",
"ch": 1
},
{
"type": "board",
"id": "int_sdj_pion_46_l1_dia3",
"ch": 1
},
{
"type": "board",
"id": "int_sdj_pion_46_l1_dia4",
"ch": 1
},
{
"type": "board",
"id": "int_sdj_pion_46_l1_dia5",
"ch": 1
},
{
"type": "board",
"id": "int_sdj_pion_46_l1_ex0",
"ch": 1
},
{
"type": "board",
"id": "int_sdj_pion_46_l1_ex1",
"ch": 1
},
{
"type": "board",
"id": "int_sdj_pion_46_l1_ex2",
"ch": 1
},
{
"type": "board",
"id": "int_sdj_pion_46_l1_ex3",
"ch": 1
},
{
"type": "h2",
"ch": 2,
"runs": [
{
"t": "Le pion d'angle 46 (seconde partie)"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "Chapitre 2 : le pion d’angle 46 (seconde partie) Nous avons vu que la sortie du pion 46 dans de bonnes conditions, dépend du développement de l’aile gauche. Certains débuts de partie sont particulièrement délicats à négocier pour les blancs. Nous allons en découvrir quelques-uns."
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "1 – DEBUT 32-28 (19-23x23) 1. 32-28 3. 37-32"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "19-23 10-14"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "2. 28x19 4. 41-37"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "14x23 17-21"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "Le dernier coup des noirs contrarie la sortie du pion 46. Quel plan de jeu adopter avec les blancs ?"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "1.1 - PREMIERE IDEE : 31-26"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "Ce coup est évidemment parfaitement jouable. Il présente toutefois l’inconvénient de faciliter le jeu des noirs en leur permettant de s’implanter au centre par : 5…"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "21-27"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "6. 32x21"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "16x27 diag. N°2"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "1.2 - DEUXIEME IDEE : 33-28"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "5. 33-28"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "5-10"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "6. 28x19"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "14x23"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "Les noirs occupent le centre. Il sera difficile de les en déloger. De plus, le problème de la mise en jeu du pion 46 n’est pas résolu."
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "1.3 - TROISIEME IDEE : le contre jeu offensif par 34-29x30 5. 34-29"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "23x34"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "6. 39x30"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "Cet échange présente l’intérêt de gêner le jeu des noirs sur leur aile gauche et de préparer un contre jeu offensif au centre. Un exemple de développement : 6… 8. 40-34 10. 47-41"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "14-19 11-17 12-18"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "7. 44-39 9. 45-40"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "21-26 18-23"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "Les coups préliminaires sur l’aile droite ont permis de préparer le retour au centre par : 11. 32-28 13. 41x32"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "23x32"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "12. 37x28"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "26x37"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "2 – DEBUT 32-28 (20-25) 1. 32-28 3. 41-37"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "20-25 10-14"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "2. 37-32 4. 46-41"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "14-20 5-10"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "Dans ce début, les blancs sortent leur pion 46 dès le 4e temps."
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "Mais comment poursuivre ? Après : 5. 31-27"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "19-23"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "6. 28x19"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "14x23"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "Les blancs doivent être attentifs au développement de leur aile gauche qui n’est pas aisé."
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "3 – DEBUT 32-28 (17-21) 1. 32-28 3. 41-37 5. 28x19"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "17-21 6-11 14x23 diagramme"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "2. 37-32 4. 31-27"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "11-17 19-23"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "Le pion 46 est difficile à mettre en œuvre, tandis que la grande diagonale des noirs est bien développée."
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "4 – DEBUT 33-28 (17-21) 1. 33-28 17-21 3. 31-27 19-23 Diagramme"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "2. 39-33 4. 28x19"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "21-26 14x23"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "On retrouve à nouveau la même idée pour contrarier la sortie du pion 46"
}
]
},
{
"type": "board",
"id": "int_sdj_pion_46_l2_dia0",
"ch": 2
},
{
"type": "board",
"id": "int_sdj_pion_46_l2_dia1",
"ch": 2
},
{
"type": "board",
"id": "int_sdj_pion_46_l2_dia2",
"ch": 2
},
{
"type": "board",
"id": "int_sdj_pion_46_l2_dia3",
"ch": 2
},
{
"type": "board",
"id": "int_sdj_pion_46_l2_dia4",
"ch": 2
},
{
"type": "board",
"id": "int_sdj_pion_46_l2_dia5",
"ch": 2
},
{
"type": "board",
"id": "int_sdj_pion_46_l2_dia6",
"ch": 2
},
{
"type": "board",
"id": "int_sdj_pion_46_l2_dia7",
"ch": 2
},
{
"type": "board",
"id": "int_sdj_pion_46_l2_dia8",
"ch": 2
},
{
"type": "board",
"id": "int_sdj_pion_46_l2_dia9",
"ch": 2
},
{
"type": "board",
"id": "int_sdj_pion_46_l2_ex0",
"ch": 2
},
{
"type": "board",
"id": "int_sdj_pion_46_l2_ex1",
"ch": 2
},
{
"type": "board",
"id": "int_sdj_pion_46_l2_ex2",
"ch": 2
},
{
"type": "board",
"id": "int_sdj_pion_46_l2_ex3",
"ch": 2
},
{
"type": "board",
"id": "int_sdj_pion_46_l2_ex4",
"ch": 2
},
{
"type": "h2",
"ch": 3,
"runs": [
{
"t": "Le pion d'angle 46 (3e partie)"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "Chapitre 3 : le pion d’angle 46 (3e partie) La sortie du pion 46 est parfois problématique. Est-ce nécessairement un désavantage ? Nous allons découvrir certaines situations dans lesquelles la présence d’un pion à 46 ne pose absolument aucun problème."
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "1 – EN FIN DE MILIEU DE PARTIE CLASSIQUE"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "Dans ce genre de position, le pion 46 peut se révéler une force si les noirs manquent de temps de réserve. Effectivement, le pion blanc 46 représente 2 temps de réserve 46-41-36, et le cas échéant, un troisième temps de réserve par 36-31."
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "Trait aux noirs Dans l’exemple suivant, le pion 46 se révèle très utile. 1… 12-17 2. 39-34 Un coup bien souvent plus fort que 39-33, dans les fins de milieu classique. Voir par exemple la partie Roozenburg – Keller à Damas 1950. 2… 17-21 3. 38-33 3-8 4. 28-22 8-12 5. 33-28 24-29 6. 46-41 etc. Les blancs ont une position avantageuse. Ils bloquent le jeu des noirs et disposent d’une importante réserve de coups, grâce au pion 46. Trait aux noirs Un autre exemple analogue au précédent. 1…"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "12-17"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "2. 46-41"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "17-21"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "3. 39-34 Un coup de blocage important. 3…"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "3-8"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "4. 28-22 etc."
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "On Remarque au passage que le pion 9 est devenu un pion “arrière” inutile."
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "Trait aux noirs Toujours sur le même principe de forcer l’adversaire à épuiser ses coups de réserve. 1… 12-17 2. 46-41 8-12 3. 41-36 17-21 4. 45-40 17-21 5. 40-34 17-22 Sur (3-8) suit 28-22x22 6. 28x17 21x12 7. 33-28 23-29 En effet (12-17) n’est pas possible à cause de 27-22. 8. 34x23 18x29 9. 28-22 Interdit la sortie (13-18) et donne l’avantage aux blancs. A présent, 3 parties à visualiser, sur le même thème : Piet Roozenburg – RC Keller 2-0 (Damas, 1950) http://toernooibase.kndb.nl/applet/oerterpapplet2.0/oerterp.php?taal=&kl=1&Id=2019&r=10&jr=0&wed =290253&weda=&zetten=&aav=&view=4 Kees Pippel – Evert Bronstring 0-2 (NLD-ch sf Groep 1, 1977) http://toernooibase.kndb.nl/applet/oerterpapplet2.0/oerterp.php?taal=&kl=17&Id=1271&r=9&jr=0&wed =177712&weda=&zetten=&aav=&view=4 Harry de Waard – Evert Bronstring (NLD-chT Hoofdklasse, 1980) http://toernooibase.kndb.nl/applet/oerterpapplet2.0/oerterp.php?taal=&kl=1&Id=1549&r=2&jr=0&wed= 229543&weda=&zetten=&aav=&view=4"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "2 – EN DEBUT DE PARTIE CLASSIQUE Il y a un début intéressant à connaître, dans lequel on a l’impression que les blancs prennent des risques inconsidérés en se laissant bloquer sur leur aile gauche. Mais au fur et à mesure, on s’aperçoit que les noirs ne peuvent pas en tirer profit, bien au contraire. Et dans ce début, le pion 46 reste à la traîne. 1. 32-28"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "18-23"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "2. 38-32"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "12-18"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "3. 42-38"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "Un coup inhabituel. Il est plus « normal » de jouer 31-27 puis 43-38. 3… 6. 31-27 9. 41-36"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "7-12 25x34"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "4. 47-42 7. 39x30"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "1-7 17-21"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "5. 34-30 8. 36-31"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "20-25 21-26"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "Les blancs ont leur côté gauche enchaîné, mais les noirs ne pourront pas tenir cette position. A un moment donné, ils seront obligés de jouer (11-17). A ce moment, les blancs se libéreront par 27-22 (18x27) 31x11, suivi de 36-31, 31-27 et la sortie du pion 46. Cet échange sur l’aile gauche force les noirs à reprendre en avant et leur supprime des formations de pionnage."
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "2 parties instructives sur ce thème : Alexander Georgiev – German Struchkov RUS-ch, 18-04-2009 http://toernooibase.kndb.nl/applet/oerterpapplet2.0/oerterp.php?taal=&kl=46&Id=1317&r=10&jr=9&we d=183548&weda=&zetten=&aav=&view=4 Jos Stokkel – Peter van der Stap 2-0 (Javaanse Jongens, 1991) http://toernooibase.kndb.nl/applet/oerterpapplet2.0/oerterp.php?taal=&kl=1&Id=1716&r=2&jr=0&wed= 258112&weda=&zetten=&aav=&view=4 Nous aurons l’occasion d’y revenir plus tard, mais le pion 46 peut également jouer un rôle dans le contrôle du centre adverse, dans les positions de faux marchand de bois, dans les parties de flanc, et dans bien d’autres formes de jeu que nous découvrirons plus . CE QU’IL FAUT RETENIR : La mise en jeu du pion 46 ne confère aucun avantage. Par contre, l’immobilisation du pion 46 est le résultat d’une aile gauche non développée, et cela peut conduire à un désavantage si cela n’est pas compensé par un contre jeu sur l’autre aile."
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "POSITION DE SYNTHESE La position qui va suivre va nous permettre de mieux comprendre quels sont les enjeux positionnels qui gravitent autour du pion 46. Il ne sera pas question de faire une analyse, mais plutôt de montrer au fur et à mesure les problèmes rencontrés par chaque camp et la manière de raisonner pour les résoudre. Examinons la position de base :"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "Trait aux blancs La position est à peu près symétrique. Le pion 46 n’est pas développé mais le pion noir 8 est difficile à mettre en jeu. On peut donc considérer que la position est a priori équilibrée. Que jouer avec les blancs ?"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "Procédons par élimination : A – 39-34 livre un coup de la bombe par (24-30) 35x24 (19x39) 28x10 (39x28) 32x23 (21x41) 46x37 (15x4) etc. B – 36-31 n’est pas correct car les noirs obtiennent une position très avantageuse après (2126) 46-41 (12-17) 41-36 (17-22) 28x17 (11x22). C – 46-41 ou 48-43 n’entrent pas vraiment en ligne de compte car (21-26) vient immobiliser l’aile gauche des blancs. D – 40-34 se heurte à (11-17) et si : D1 – 37-31 les noirs effectuent un coup de l’Espagnol par (17-22) 28x26 (24-29) 33x24 (19x30) 35x24 (14-20) 25x14 (9x40) 45x34 (23-28) 32x23 (18x40). D2 – 34-30 (21-26) 37-31 (26x37) 42x31 les noirs se précipitent sur la manœuvre ultra classique (17-22) 28x17 (12x21) qui entrave l’aile gauche des blancs car l’attaque 31-26 est impossible à cause (23-28) etc. Il reste donc 37-31. Ce coup est le plus logique pour développer l’aile gauche des blancs et préparer la sortie du pion 46. Donc : 1. 37-31"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "21-26"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "Les noirs n’ont aucun intérêt à permettre 31-26. 2. 40-34 39-34 livrerait à nouveau un coup de la bombe. Les conséquences sont assez difficiles à évaluer mentalement : (26x37) 42x31 (24-30) 35x24 (19x39) 28x10 (39x26) 10-5 (11-17), la dame est à présent forcément reprise et les blancs sont ensuite confrontés à la double menace d’attaque du pion 27 et du passage à dame. 2…"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "26x37"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "3. 42x31"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "12-17"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "Un coup important qui rend stérilise la formation 36-31-27"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "Comment poursuivre avec les blancs ? Les noirs ne menacent pas directement. Le choix des blancs est assez vaste. 4. 34-30 La sortie 46-41 ne serait pas très appropriée en raison de (17-21) qui interdit 31-26 en raison du coup de dame (15-20) 26x17 (11x31) 36x27 (16-21) 27x16 (18-22) 28x17 (23-29) 34x23 (19x46). Après 48-43 (8-12), la sortie 46-41 n’est toujours pas fameuse à cause de (17-21) qui interdit encore 31-26 par un coup de dame ultra classique (3-8) 26x17 (11x31) 36x27 (16-21) 27x16 (18-22) 28x17 (12x21) 16x27 (23-29) 34x23 (19x46). D’autre part, après 48-43 (8-12), l’avancée à 22 par 27-22 (18x27) 31x22 serait contrée par (24-29) 33x24 (19x30) 28x10 (17x37) 35x24 (15x4). 4…"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "24-29"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "5. 33x24"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "14-20"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "6. 25x14"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "9x29"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "Trait aux blancs Par cette manœuvre, les noirs menacent (29-33) et empêchent l’attaque 39-33 par (17-21) 33x24 (21-26) etc. Les blancs n’ont d’autre solution que d’échanger le pion 29. 7. 39-34"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "29x40"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "8. 45x34"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "17-21"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "Les noirs forcent finalement la sortie du pion 46 et prennent le contrôle de l’aile gauche des blancs. 9. 46-41"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "15-20"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "10. 41-37"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "11. 27-22"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "18x27"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "12. 31x22"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "20-24"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "C’est effectivement le bon moment de placer un pion à 22 car (812) 38-33 (12-18) n’est pas possible en raison de 33-29 (18x38) 29x9 (3x14) 28-23 (19x28) 30x10. D’autre part, après (8-12) 38-33 (12-17), les blancs ont un petit coup de talon par 34-29 (23x25) 33-29 (24x33) 28x39 (17x28) 32x14. 12…"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "3-9"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "13. 38-33"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "Préférable à 48-42, car (24-29) 30-25 (29x40) 35x44 (23-29) placerait les blancs en bien mauvaise posture. 13…"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "11-17"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "(21-26) permettrait le gambit 37-31 (26x37) 32x41 (23x32) 34-29 etc. 14. 22x11"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "6x17"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "Les blancs sont parvenus à mettre en jeu tous leurs pions de l’aile gauche, mais leurs tourments ne sont pourtant pas terminés. Je vous laisse le soin d’analyser la suite…"
}
]
},
{
"type": "board",
"id": "int_sdj_pion_46_l3_dia0",
"ch": 3
},
{
"type": "board",
"id": "int_sdj_pion_46_l3_dia1",
"ch": 3
},
{
"type": "board",
"id": "int_sdj_pion_46_l3_dia2",
"ch": 3
},
{
"type": "board",
"id": "int_sdj_pion_46_l3_dia3",
"ch": 3
},
{
"type": "board",
"id": "int_sdj_pion_46_l3_dia4",
"ch": 3
},
{
"type": "board",
"id": "int_sdj_pion_46_l3_dia5",
"ch": 3
},
{
"type": "board",
"id": "int_sdj_pion_46_l3_dia6",
"ch": 3
},
{
"type": "board",
"id": "int_sdj_pion_46_l3_dia7",
"ch": 3
},
{
"type": "board",
"id": "int_sdj_pion_46_l3_dia8",
"ch": 3
},
{
"type": "board",
"id": "int_sdj_pion_46_l3_ex0",
"ch": 3
},
{
"type": "board",
"id": "int_sdj_pion_46_l3_ex1",
"ch": 3
},
{
"type": "board",
"id": "int_sdj_pion_46_l3_ex2",
"ch": 3
},
{
"type": "board",
"id": "int_sdj_pion_46_l3_ex3",
"ch": 3
}
],
"positions": {
"int_sdj_pion_46_l1_dia0": {
"id": "int_sdj_pion_46_l1_dia0",
"ch": 1,
"title": "Diag. 1",
"start": {
"wm": [
27,
32,
35,
36,
37,
38,
40,
42,
43,
45,
46,
48
],
"wk": [],
"bm": [
3,
8,
9,
10,
11,
13,
16,
18,
23,
24,
26
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Diag. 1"
},
"int_sdj_pion_46_l1_dia1": {
"id": "int_sdj_pion_46_l1_dia1",
"ch": 1,
"title": "Trait aux blancs",
"start": {
"wm": [
27,
28,
32,
35,
36,
37,
38,
39,
40,
42,
45,
46,
48
],
"wk": [],
"bm": [
3,
9,
12,
13,
14,
15,
16,
18,
19,
21,
23,
24,
26
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Trait aux blancs"
},
"int_sdj_pion_46_l1_dia2": {
"id": "int_sdj_pion_46_l1_dia2",
"ch": 1,
"title": "Trait aux blancs",
"start": {
"wm": [
27,
28,
31,
32,
36,
37,
38,
39,
42,
44,
45,
48
],
"wk": [],
"bm": [
3,
9,
12,
13,
15,
16,
19,
20,
21,
23,
26,
29
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Trait aux blancs"
},
"int_sdj_pion_46_l1_dia3": {
"id": "int_sdj_pion_46_l1_dia3",
"ch": 1,
"title": "Trait aux blancs",
"start": {
"wm": [
27,
28,
32,
33,
35,
36,
37,
38,
40,
42,
45,
46,
48
],
"wk": [],
"bm": [
3,
9,
12,
13,
14,
15,
16,
17,
18,
19,
23,
24,
26
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Trait aux blancs"
},
"int_sdj_pion_46_l1_dia4": {
"id": "int_sdj_pion_46_l1_dia4",
"ch": 1,
"title": "Trait aux blancs",
"start": {
"wm": [
27,
28,
32,
33,
35,
36,
38,
40,
45,
46,
48
],
"wk": [],
"bm": [
8,
9,
13,
14,
15,
16,
18,
19,
21,
23,
24
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Trait aux blancs"
},
"int_sdj_pion_46_l1_dia5": {
"id": "int_sdj_pion_46_l1_dia5",
"ch": 1,
"title": "révèle délicate",
"start": {
"wm": [
25,
26,
27,
32,
33,
35,
37,
38,
39,
40,
42,
45,
48
],
"wk": [],
"bm": [
1,
3,
6,
8,
9,
10,
13,
14,
16,
18,
19,
23,
24
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "révèle délicate"
},
"int_sdj_pion_46_l1_ex0": {
"id": "int_sdj_pion_46_l1_ex0",
"ch": 1,
"title": "LE PION D'ANGLE 46 (1) – D1",
"start": {
"wm": [
25,
27,
30,
33,
35,
37,
38,
39,
40,
45,
48
],
"wk": [],
"bm": [
5,
7,
8,
9,
13,
14,
15,
17,
19,
23,
24
],
"bk": [],
"turn": "black"
},
"moves": [
{
"n": "24-29",
"f": 24,
"t": 29,
"c": [],
"path": [
24,
29
],
"p": false
},
{
"n": "33x24",
"f": 33,
"t": 24,
"c": [
29
],
"path": [
33,
24
],
"p": false
}
],
"theme": "sdj_ch108",
"pub": "24-29 33x24 19x39 43x34 12-18 28x19 13x24",
"win": "black"
},
"int_sdj_pion_46_l1_ex1": {
"id": "int_sdj_pion_46_l1_ex1",
"ch": 1,
"title": "LE PION D'ANGLE 46 (1) – D2",
"start": {
"wm": [
27,
28,
32,
33,
34,
35,
36,
37,
40,
43,
46,
48
],
"wk": [],
"bm": [
3,
7,
8,
12,
13,
16,
19,
21,
23,
24,
25,
26
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "27-22",
"f": 27,
"t": 22,
"c": [],
"path": [
27,
22
],
"p": false
}
],
"theme": "sdj_ch108",
"pub": "27-22 17x28 33x22",
"win": "white"
},
"int_sdj_pion_46_l1_ex2": {
"id": "int_sdj_pion_46_l1_ex2",
"ch": 1,
"title": "LE PION D'ANGLE 46 (1) – D3",
"start": {
"wm": [
31,
32,
33,
34,
35,
36,
37,
38,
39,
42,
43,
46,
47,
48,
49,
50
],
"wk": [],
"bm": [
3,
4,
6,
8,
9,
11,
12,
13,
14,
15,
16,
18,
19,
23,
24,
26
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "47-41",
"f": 47,
"t": 41,
"c": [],
"path": [
47,
41
],
"p": false
}
],
"theme": "sdj_ch108",
"pub": "47-41 26x37 34-29 23x34 40x20 15x24 27-22 18x27 32x12 8x17",
"win": "white"
},
"int_sdj_pion_46_l1_ex3": {
"id": "int_sdj_pion_46_l1_ex3",
"ch": 1,
"title": "LE PION D'ANGLE 46 (1) – D4",
"start": {
"wm": [
25,
27,
28,
30,
31,
32,
33,
35,
36,
38,
39,
40,
41,
43,
44,
45,
46,
47,
48
],
"wk": [],
"bm": [
1,
3,
4,
5,
6,
8,
9,
10,
11,
13,
14,
15,
16,
17,
18,
19,
23,
24,
26
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "39-34",
"f": 39,
"t": 34,
"c": [],
"path": [
39,
34
],
"p": false
}
],
"theme": "sdj_ch108",
"pub": "39-34 32-28 23x32 37x28 26x37 41x32",
"win": "white"
},
"int_sdj_pion_46_l2_dia0": {
"id": "int_sdj_pion_46_l2_dia0",
"ch": 2,
"title": "1 – DEBUT 32-28 (19-23x23)",
"start": {
"wm": [
31,
32,
33,
34,
35,
36,
37,
38,
39,
40,
42,
43,
44,
45,
46,
47,
48,
49,
50
],
"wk": [],
"bm": [
1,
2,
3,
4,
5,
6,
7,
8,
9,
11,
12,
13,
14,
15,
16,
18,
20,
21,
23
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "1 – DEBUT 32-28 (19-23x23)"
},
"int_sdj_pion_46_l2_dia1": {
"id": "int_sdj_pion_46_l2_dia1",
"ch": 2,
"title": "Diag. 2",
"start": {
"wm": [
26,
32,
33,
34,
35,
36,
37,
38,
39,
40,
42,
43,
44,
45,
46,
47,
48,
49,
50
],
"wk": [],
"bm": [
1,
2,
3,
4,
5,
6,
7,
8,
9,
11,
12,
13,
14,
15,
16,
18,
20,
21,
23
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Diag. 2"
},
"int_sdj_pion_46_l2_dia2": {
"id": "int_sdj_pion_46_l2_dia2",
"ch": 2,
"title": "Diag. 3",
"start": {
"wm": [
26,
33,
34,
35,
36,
37,
38,
39,
40,
42,
43,
44,
45,
46,
47,
48,
49,
50
],
"wk": [],
"bm": [
1,
2,
3,
4,
5,
6,
7,
8,
9,
11,
12,
13,
14,
15,
18,
20,
23,
27
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Diag. 3"
},
"int_sdj_pion_46_l2_dia3": {
"id": "int_sdj_pion_46_l2_dia3",
"ch": 2,
"title": "Diag. 4",
"start": {
"wm": [
28,
31,
32,
34,
35,
36,
37,
38,
39,
40,
42,
43,
44,
45,
46,
47,
48,
49,
50
],
"wk": [],
"bm": [
1,
2,
3,
4,
5,
6,
7,
8,
9,
11,
12,
13,
14,
15,
16,
18,
20,
21,
23
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Diag. 4"
},
"int_sdj_pion_46_l2_dia4": {
"id": "int_sdj_pion_46_l2_dia4",
"ch": 2,
"title": "Diag. 5",
"start": {
"wm": [
31,
32,
34,
35,
36,
37,
38,
39,
40,
42,
43,
44,
45,
46,
47,
48,
49,
50
],
"wk": [],
"bm": [
1,
2,
3,
4,
6,
7,
8,
9,
10,
11,
12,
13,
15,
16,
18,
20,
21,
23
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Diag. 5"
},
"int_sdj_pion_46_l2_dia5": {
"id": "int_sdj_pion_46_l2_dia5",
"ch": 2,
"title": "Diag. 6",
"start": {
"wm": [
30,
31,
32,
33,
35,
36,
37,
38,
40,
42,
43,
44,
45,
46,
47,
48,
49,
50
],
"wk": [],
"bm": [
1,
2,
3,
4,
5,
6,
7,
8,
9,
11,
12,
13,
14,
15,
16,
18,
20,
21
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Diag. 6"
},
"int_sdj_pion_46_l2_dia6": {
"id": "int_sdj_pion_46_l2_dia6",
"ch": 2,
"title": "Diag. 7",
"start": {
"wm": [
30,
31,
32,
33,
34,
35,
36,
37,
38,
39,
40,
41,
42,
43,
46,
48,
49,
50
],
"wk": [],
"bm": [
1,
2,
3,
4,
5,
6,
7,
8,
9,
13,
15,
16,
17,
18,
19,
20,
23,
26
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Diag. 7"
},
"int_sdj_pion_46_l2_dia7": {
"id": "int_sdj_pion_46_l2_dia7",
"ch": 2,
"title": "2 – DEBUT 32-28 (20-25)",
"start": {
"wm": [
28,
31,
32,
33,
34,
35,
36,
37,
38,
39,
40,
41,
42,
43,
44,
45,
47,
48,
49,
50
],
"wk": [],
"bm": [
1,
2,
3,
4,
6,
7,
8,
9,
10,
11,
12,
13,
14,
15,
16,
17,
18,
19,
20,
25
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "2 – DEBUT 32-28 (20-25)"
},
"int_sdj_pion_46_l2_dia8": {
"id": "int_sdj_pion_46_l2_dia8",
"ch": 2,
"title": "3 – DEBUT 32-28 (17-21)",
"start": {
"wm": [
27,
32,
33,
34,
35,
36,
37,
38,
39,
40,
42,
43,
44,
45,
46,
47,
48,
49,
50
],
"wk": [],
"bm": [
1,
2,
3,
4,
5,
7,
8,
9,
10,
11,
12,
13,
15,
16,
17,
18,
20,
21,
23
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "3 – DEBUT 32-28 (17-21)"
},
"int_sdj_pion_46_l2_dia9": {
"id": "int_sdj_pion_46_l2_dia9",
"ch": 2,
"title": "4 – DEBUT 33-28 (17-21)",
"start": {
"wm": [
27,
32,
33,
34,
35,
36,
37,
38,
40,
41,
42,
43,
44,
45,
46,
47,
48,
49,
50
],
"wk": [],
"bm": [
1,
2,
3,
4,
5,
6,
7,
8,
9,
10,
11,
12,
13,
15,
16,
18,
20,
23,
26
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "4 – DEBUT 33-28 (17-21)"
},
"int_sdj_pion_46_l2_ex0": {
"id": "int_sdj_pion_46_l2_ex0",
"ch": 2,
"title": "LE PION D'ANGLE 46 (2) – D1",
"start": {
"wm": [
27,
28,
32,
33,
34,
35,
36,
37,
39,
40,
42,
43,
44,
45,
46,
47,
48,
49,
50
],
"wk": [],
"bm": [
1,
2,
3,
4,
6,
7,
8,
9,
10,
11,
12,
13,
15,
16,
18,
19,
20,
23,
26
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "27-22",
"f": 27,
"t": 22,
"c": [],
"path": [
27,
22
],
"p": false
}
],
"theme": "sdj_ch109",
"pub": "27-22 18x27 38-33 27x29 37-31 23x32 34x5 32-28",
"win": "white"
},
"int_sdj_pion_46_l2_ex1": {
"id": "int_sdj_pion_46_l2_ex1",
"ch": 2,
"title": "LE PION D'ANGLE 46 (2) – D2",
"start": {
"wm": [
27,
28,
32,
34,
35,
36,
37,
38,
39,
40,
42,
43,
44,
45,
46,
47,
48,
49,
50
],
"wk": [],
"bm": [
1,
2,
3,
4,
6,
7,
8,
9,
10,
11,
12,
13,
15,
16,
18,
19,
20,
21,
23
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "27-22",
"f": 27,
"t": 22,
"c": [],
"path": [
27,
22
],
"p": false
}
],
"theme": "sdj_ch109",
"pub": "27-22 31-27 27-22 18x29 37-31 26x37 42x31 23x32 34x5",
"win": "white"
},
"int_sdj_pion_46_l2_ex2": {
"id": "int_sdj_pion_46_l2_ex2",
"ch": 2,
"title": "LE PION D'ANGLE 46 (2) – D3",
"start": {
"wm": [
27,
28,
32,
34,
35,
36,
37,
38,
39,
40,
42,
44,
45,
46,
47,
48,
49,
50
],
"wk": [],
"bm": [
1,
2,
3,
4,
6,
7,
8,
9,
10,
13,
15,
16,
18,
19,
20,
21,
23,
26
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "27-22",
"f": 27,
"t": 22,
"c": [],
"path": [
27,
22
],
"p": false
}
],
"theme": "sdj_ch109",
"pub": "27-22 27-22 18x27 38-33 27x29 37-31 23x32 34x5",
"win": "white"
},
"int_sdj_pion_46_l2_ex3": {
"id": "int_sdj_pion_46_l2_ex3",
"ch": 2,
"title": "LE PION D'ANGLE 46 (2) – D4",
"start": {
"wm": [
27,
28,
32,
33,
34,
35,
36,
37,
38,
39,
40,
42,
44,
45,
46,
47,
48,
49,
50
],
"wk": [],
"bm": [
1,
2,
3,
4,
6,
7,
8,
9,
10,
12,
13,
15,
16,
17,
18,
19,
20,
23,
26
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "37-31",
"f": 37,
"t": 31,
"c": [],
"path": [
37,
31
],
"p": false
}
],
"theme": "sdj_ch109",
"pub": "37-31 5-10 12x21",
"win": "white"
},
"int_sdj_pion_46_l2_ex4": {
"id": "int_sdj_pion_46_l2_ex4",
"ch": 2,
"title": "LE PION D'ANGLE 46 (2) – D5",
"start": {
"wm": [
27,
28,
32,
33,
34,
35,
36,
37,
38,
40,
42,
44,
45,
46,
47,
48,
49,
50
],
"wk": [],
"bm": [
1,
2,
3,
4,
6,
8,
9,
10,
12,
13,
15,
16,
18,
19,
20,
21,
23,
26
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "33-29",
"f": 33,
"t": 29,
"c": [],
"path": [
33,
29
],
"p": false
}
],
"theme": "sdj_ch109",
"pub": "33-29 27-22 18x27 32x21 23x43 49x38 16x27 38-32 27x29 34x5",
"win": "white"
},
"int_sdj_pion_46_l3_dia0": {
"id": "int_sdj_pion_46_l3_dia0",
"ch": 3,
"title": "Trait aux noirs",
"start": {
"wm": [
27,
28,
32,
37,
46
],
"wk": [],
"bm": [
19,
23,
24
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Trait aux noirs"
},
"int_sdj_pion_46_l3_dia1": {
"id": "int_sdj_pion_46_l3_dia1",
"ch": 3,
"title": "Trait aux noirs",
"start": {
"wm": [
25,
27,
28,
30,
32,
35,
37,
38,
39,
46
],
"wk": [],
"bm": [
3,
12,
13,
14,
16,
18,
19,
23,
24,
26
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Trait aux noirs"
},
"int_sdj_pion_46_l3_dia2": {
"id": "int_sdj_pion_46_l3_dia2",
"ch": 3,
"title": "Diag. 3",
"start": {
"wm": [
25,
27,
28,
30,
32,
33,
35,
37,
38,
39,
46
],
"wk": [],
"bm": [
3,
9,
12,
13,
14,
16,
18,
19,
23,
24,
26
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Diag. 3"
},
"int_sdj_pion_46_l3_dia3": {
"id": "int_sdj_pion_46_l3_dia3",
"ch": 3,
"title": "Trait aux noirs",
"start": {
"wm": [
25,
27,
28,
30,
32,
33,
35,
37,
38,
39,
45,
46
],
"wk": [],
"bm": [
3,
8,
9,
12,
13,
14,
16,
18,
19,
23,
24,
26
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Trait aux noirs"
},
"int_sdj_pion_46_l3_dia4": {
"id": "int_sdj_pion_46_l3_dia4",
"ch": 3,
"title": "Sur (3-8) suit 28-22x22",
"start": {
"wm": [
27,
28,
30,
31,
32,
33,
35,
36,
37,
38,
40,
42,
43,
44,
45,
46,
48,
49,
50
],
"wk": [],
"bm": [
2,
3,
4,
5,
6,
7,
8,
9,
10,
11,
12,
13,
14,
15,
16,
18,
19,
23,
26
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Sur (3-8) suit 28-22x22"
},
"int_sdj_pion_46_l3_dia5": {
"id": "int_sdj_pion_46_l3_dia5",
"ch": 3,
"title": "Diag. 6",
"start": {
"wm": [
25,
27,
28,
31,
32,
33,
34,
35,
36,
38,
39,
45,
46,
48
],
"wk": [],
"bm": [
3,
6,
8,
9,
11,
13,
14,
15,
16,
17,
18,
19,
23,
24
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Diag. 6"
},
"int_sdj_pion_46_l3_dia6": {
"id": "int_sdj_pion_46_l3_dia6",
"ch": 3,
"title": "Trait aux blancs",
"start": {
"wm": [
27,
28,
30,
31,
32,
35,
36,
38,
39,
45,
46,
48
],
"wk": [],
"bm": [
3,
6,
8,
11,
13,
15,
16,
17,
18,
19,
23,
29
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Trait aux blancs"
},
"int_sdj_pion_46_l3_dia7": {
"id": "int_sdj_pion_46_l3_dia7",
"ch": 3,
"title": "Diag. 8",
"start": {
"wm": [
27,
28,
30,
31,
32,
34,
35,
36,
37,
38,
48
],
"wk": [],
"bm": [
3,
6,
8,
11,
13,
16,
18,
19,
21,
23,
24
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Diag. 8"
},
"int_sdj_pion_46_l3_dia8": {
"id": "int_sdj_pion_46_l3_dia8",
"ch": 3,
"title": "Diag. 9",
"start": {
"wm": [
28,
30,
32,
33,
34,
35,
36,
37,
48
],
"wk": [],
"bm": [
8,
9,
13,
16,
17,
19,
21,
23,
24
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Diag. 9"
},
"int_sdj_pion_46_l3_ex0": {
"id": "int_sdj_pion_46_l3_ex0",
"ch": 3,
"title": "LE PION D'ANGLE 46 (3) – D1",
"start": {
"wm": [
27,
28,
32,
33,
34,
35,
36,
37,
38,
39,
40,
42,
43,
45,
48,
49
],
"wk": [],
"bm": [
2,
3,
6,
8,
9,
10,
12,
13,
15,
16,
17,
18,
19,
23,
24,
25
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "35-30",
"f": 35,
"t": 30,
"c": [],
"path": [
35,
30
],
"p": false
}
],
"theme": "sdj_ch110",
"pub": "35-30 24x35 33-29 23x34 39x30 35x24 28-22 17x28 32x5",
"win": "white"
},
"int_sdj_pion_46_l3_ex1": {
"id": "int_sdj_pion_46_l3_ex1",
"ch": 3,
"title": "LE PION D'ANGLE 46 (3) – D2",
"start": {
"wm": [
25,
27,
28,
32,
33,
35,
36,
37,
38,
39,
42,
43,
45,
48,
49
],
"wk": [],
"bm": [
2,
3,
6,
8,
9,
10,
12,
13,
15,
16,
17,
18,
19,
23,
24
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "35-30",
"f": 35,
"t": 30,
"c": [],
"path": [
35,
30
],
"p": false
}
],
"theme": "sdj_ch110",
"pub": "35-30 25x34 40x20 15x24 35-30 24x35 33-29 23x34 39x30 35x24",
"win": "white"
},
"int_sdj_pion_46_l3_ex2": {
"id": "int_sdj_pion_46_l3_ex2",
"ch": 3,
"title": "LE PION D'ANGLE 46 (3) – D3",
"start": {
"wm": [
25,
27,
28,
30,
31,
32,
33,
35,
36,
37,
38,
39,
40,
42,
43,
45,
48
],
"wk": [],
"bm": [
2,
3,
4,
6,
7,
8,
9,
10,
11,
12,
13,
14,
16,
17,
19,
23,
24
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "25-20",
"f": 25,
"t": 20,
"c": [],
"path": [
25,
20
],
"p": false
}
],
"theme": "sdj_ch110",
"pub": "25-20 23x34 39x30 25x34 28-22 17x39 38-33 39x28 32x5",
"win": "white"
},
"int_sdj_pion_46_l3_ex3": {
"id": "int_sdj_pion_46_l3_ex3",
"ch": 3,
"title": "LE PION D'ANGLE 46 (3) – D4",
"start": {
"wm": [
27,
28,
32,
33,
34,
35,
36,
37,
38,
39,
42,
43,
45,
47,
48,
49
],
"wk": [],
"bm": [
2,
3,
6,
8,
9,
10,
12,
13,
15,
16,
17,
18,
19,
23,
24,
25
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "34-29",
"f": 34,
"t": 29,
"c": [],
"path": [
34,
29
],
"p": false
}
],
"theme": "sdj_ch110",
"pub": "34-29 14x34 40x18 12x23 35-30 24x35 33-29 23x34 39x30 35x24",
"win": "white"
}
}
}

export default DATA
