// Auto-generated by backend/curriculum/build_parcours_manuels.py — do not edit by hand.
import type { ManuelData } from '../ManuelInteractif'

const DATA: ManuelData = {
"book": "Bloquer et empêcher le débordement",
"level": "Intermédiaire",
"chapters": [
{
"n": 0,
"title": "Présentation"
},
{
"n": 1,
"title": "Bloquer des pions"
},
{
"n": 2,
"title": "Empêcher le débordement"
}
],
"blocks": [
{
"type": "h1",
"ch": 0,
"runs": [
{
"t": "Bloquer et empêcher le débordement"
}
]
},
{
"type": "p",
"ch": 0,
"runs": [
{
"t": "Neutraliser l'aile adverse."
}
]
},
{
"type": "p",
"ch": 0,
"runs": [
{
"b": 1,
"t": "Objectif. "
},
{
"t": "Bloquer les pions adverses et empêcher un débordement sur l'aile."
}
]
},
{
"type": "h2",
"ch": 1,
"runs": [
{
"t": "Bloquer des pions"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "Immobiliser une chaîne de pions adverses pour la rendre inoffensive et garder l'initiative."
}
]
},
{
"type": "board",
"id": "int_blocage_l1_ex0",
"ch": 1
},
{
"type": "board",
"id": "int_blocage_l1_ex1",
"ch": 1
},
{
"type": "board",
"id": "int_blocage_l1_ex2",
"ch": 1
},
{
"type": "board",
"id": "int_blocage_l1_ex3",
"ch": 1
},
{
"type": "board",
"id": "int_blocage_l1_ex4",
"ch": 1
},
{
"type": "board",
"id": "int_blocage_l1_ex5",
"ch": 1
},
{
"type": "board",
"id": "int_blocage_l1_ex6",
"ch": 1
},
{
"type": "board",
"id": "int_blocage_l1_ex7",
"ch": 1
},
{
"type": "board",
"id": "int_blocage_l1_ex8",
"ch": 1
},
{
"type": "board",
"id": "int_blocage_l1_pos9",
"ch": 1
},
{
"type": "board",
"id": "int_blocage_l1_pos10",
"ch": 1
},
{
"type": "board",
"id": "int_blocage_l1_pos11",
"ch": 1
},
{
"type": "board",
"id": "int_blocage_l1_pos12",
"ch": 1
},
{
"type": "board",
"id": "int_blocage_l1_pos13",
"ch": 1
},
{
"type": "board",
"id": "int_blocage_l1_pos14",
"ch": 1
},
{
"type": "h2",
"ch": 2,
"runs": [
{
"t": "Empêcher le débordement"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "Le débordement perce votre aile. Apprenez à le voir venir et à le couper à temps."
}
]
},
{
"type": "board",
"id": "int_blocage_l2_ex0",
"ch": 2
},
{
"type": "board",
"id": "int_blocage_l2_ex1",
"ch": 2
},
{
"type": "board",
"id": "int_blocage_l2_ex2",
"ch": 2
},
{
"type": "board",
"id": "int_blocage_l2_ex3",
"ch": 2
},
{
"type": "board",
"id": "int_blocage_l2_ex4",
"ch": 2
},
{
"type": "board",
"id": "int_blocage_l2_pos5",
"ch": 2
},
{
"type": "board",
"id": "int_blocage_l2_pos6",
"ch": 2
},
{
"type": "board",
"id": "int_blocage_l2_pos7",
"ch": 2
},
{
"type": "board",
"id": "int_blocage_l2_pos8",
"ch": 2
},
{
"type": "board",
"id": "int_blocage_l2_pos9",
"ch": 2
},
{
"type": "board",
"id": "int_blocage_l2_pos10",
"ch": 2
}
],
"positions": {
"int_blocage_l1_ex0": {
"id": "int_blocage_l1_ex0",
"ch": 1,
"title": "SIJBRANDS — combinaison (p.120 #1)",
"start": {
"wm": [
33,
42,
43
],
"wk": [],
"bm": [
23,
32
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "43-39",
"f": 43,
"t": 39,
"c": [],
"path": [
43,
39
],
"p": false
},
{
"n": "32-38",
"f": 32,
"t": 38,
"c": [],
"path": [
32,
38
],
"p": false
},
{
"n": "42-37",
"f": 42,
"t": 37,
"c": [],
"path": [
42,
37
],
"p": false
},
{
"n": "38x29",
"f": 38,
"t": 29,
"c": [
33
],
"path": [
38,
29
],
"p": false
},
{
"n": "37-32",
"f": 37,
"t": 32,
"c": [],
"path": [
37,
32
],
"p": false
},
{
"n": "29-34",
"f": 29,
"t": 34,
"c": [],
"path": [
29,
34
],
"p": false
},
{
"n": "39x30",
"f": 39,
"t": 30,
"c": [
34
],
"path": [
39,
30
],
"p": false
},
{
"n": "23-29",
"f": 23,
"t": 29,
"c": [],
"path": [
23,
29
],
"p": false
},
{
"n": "32-28",
"f": 32,
"t": 28,
"c": [],
"path": [
32,
28
],
"p": false
},
{
"n": "29-33",
"f": 29,
"t": 33,
"c": [],
"path": [
29,
33
],
"p": false
},
{
"n": "28x39",
"f": 28,
"t": 39,
"c": [
33
],
"path": [
28,
39
],
"p": false
}
],
"theme": "Bloquer des pions",
"pub": "43-39 32-38 42-37 38x29 37-32 29-34 39x30 23-29 32-28 29-33 28x39",
"win": "white",
"exp": "Bloquer des pions"
},
"int_blocage_l1_ex1": {
"id": "int_blocage_l1_ex1",
"ch": 1,
"title": "SIJBRANDS — combinaison (p.120 #2)",
"start": {
"wm": [
28,
32,
37
],
"wk": [],
"bm": [
16,
17,
26
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "32-27",
"f": 32,
"t": 27,
"c": [],
"path": [
32,
27
],
"p": false
},
{
"n": "17-21",
"f": 17,
"t": 21,
"c": [],
"path": [
17,
21
],
"p": false
},
{
"n": "27-22",
"f": 27,
"t": 22,
"c": [],
"path": [
27,
22
],
"p": false
},
{
"n": "21-27",
"f": 21,
"t": 27,
"c": [],
"path": [
21,
27
],
"p": false
},
{
"n": "22x31",
"f": 22,
"t": 31,
"c": [
27
],
"path": [
22,
31
],
"p": false
},
{
"n": "16-21",
"f": 16,
"t": 21,
"c": [],
"path": [
16,
21
],
"p": false
},
{
"n": "28-23",
"f": 28,
"t": 23,
"c": [],
"path": [
28,
23
],
"p": false
},
{
"n": "21-27",
"f": 21,
"t": 27,
"c": [],
"path": [
21,
27
],
"p": false
},
{
"n": "31x22",
"f": 31,
"t": 22,
"c": [
27
],
"path": [
31,
22
],
"p": false
},
{
"n": "26-31",
"f": 26,
"t": 31,
"c": [],
"path": [
26,
31
],
"p": false
},
{
"n": "37x26",
"f": 37,
"t": 26,
"c": [
31
],
"path": [
37,
26
],
"p": false
}
],
"theme": "Bloquer des pions",
"pub": "32-27 17-21 27-22 21-27 22x31 16-21 28-23 21-27 31x22 26-31 37x26",
"win": "white",
"exp": "Bloquer des pions"
},
"int_blocage_l1_ex2": {
"id": "int_blocage_l1_ex2",
"ch": 1,
"title": "SIJBRANDS — combinaison (p.120 #3)",
"start": {
"wm": [
38,
50
],
"wk": [],
"bm": [
20,
35
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "50-44",
"f": 50,
"t": 44,
"c": [],
"path": [
50,
44
],
"p": false
},
{
"n": "20-24",
"f": 20,
"t": 24,
"c": [],
"path": [
20,
24
],
"p": false
},
{
"n": "38-33",
"f": 38,
"t": 33,
"c": [],
"path": [
38,
33
],
"p": false
},
{
"n": "24-30",
"f": 24,
"t": 30,
"c": [],
"path": [
24,
30
],
"p": false
},
{
"n": "33-29",
"f": 33,
"t": 29,
"c": [],
"path": [
33,
29
],
"p": false
},
{
"n": "30-34",
"f": 30,
"t": 34,
"c": [],
"path": [
30,
34
],
"p": false
},
{
"n": "29x40",
"f": 29,
"t": 40,
"c": [
34
],
"path": [
29,
40
],
"p": false
}
],
"theme": "Bloquer des pions",
"pub": "50-44 20-24 38-33 24-30 33-29 30-34 29x40",
"win": "white",
"exp": "Bloquer des pions"
},
"int_blocage_l1_ex3": {
"id": "int_blocage_l1_ex3",
"ch": 1,
"title": "SIJBRANDS — combinaison (p.120 #4)",
"start": {
"wm": [
37,
47,
48
],
"wk": [],
"bm": [
27,
38
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "47-41",
"f": 47,
"t": 41,
"c": [],
"path": [
47,
41
],
"p": false
},
{
"n": "38-42",
"f": 38,
"t": 42,
"c": [],
"path": [
38,
42
],
"p": false
},
{
"n": "41-36",
"f": 41,
"t": 36,
"c": [],
"path": [
41,
36
],
"p": false
},
{
"n": "42x31",
"f": 42,
"t": 31,
"c": [
37
],
"path": [
42,
31
],
"p": false
},
{
"n": "48-42",
"f": 48,
"t": 42,
"c": [],
"path": [
48,
42
],
"p": false
},
{
"n": "27-32",
"f": 27,
"t": 32,
"c": [],
"path": [
27,
32
],
"p": false
},
{
"n": "36x27x38",
"f": 36,
"t": 38,
"c": [
32,
31
],
"path": [
36,
27,
38
],
"p": false
}
],
"theme": "Bloquer des pions",
"pub": "47-41 38-42 41-36 42x31 48-42 27-32 36x27x38",
"win": "white",
"exp": "Bloquer des pions"
},
"int_blocage_l1_ex4": {
"id": "int_blocage_l1_ex4",
"ch": 1,
"title": "SIJBRANDS — combinaison (p.121 #10)",
"start": {
"wm": [
35,
44,
45
],
"wk": [],
"bm": [
24,
34
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "44-40",
"f": 44,
"t": 40,
"c": [],
"path": [
44,
40
],
"p": false
},
{
"n": "24-29",
"f": 24,
"t": 29,
"c": [],
"path": [
24,
29
],
"p": false
},
{
"n": "35-30",
"f": 35,
"t": 30,
"c": [],
"path": [
35,
30
],
"p": false
},
{
"n": "34x25",
"f": 34,
"t": 25,
"c": [
30
],
"path": [
34,
25
],
"p": false
},
{
"n": "40-34",
"f": 40,
"t": 34,
"c": [],
"path": [
40,
34
],
"p": false
},
{
"n": "29x40",
"f": 29,
"t": 40,
"c": [
34
],
"path": [
29,
40
],
"p": false
},
{
"n": "45x34",
"f": 45,
"t": 34,
"c": [
40
],
"path": [
45,
34
],
"p": false
},
{
"n": "25-30",
"f": 25,
"t": 30,
"c": [],
"path": [
25,
30
],
"p": false
},
{
"n": "34x25",
"f": 34,
"t": 25,
"c": [
30
],
"path": [
34,
25
],
"p": false
}
],
"theme": "Bloquer des pions",
"pub": "44-40 24-29 35-30 34x25 40-34 29x40 45x34 25-30 34x25",
"win": "white",
"exp": "Bloquer des pions"
},
"int_blocage_l1_ex5": {
"id": "int_blocage_l1_ex5",
"ch": 1,
"title": "SIJBRANDS — combinaison (p.121 #12)",
"start": {
"wm": [
26,
31,
36
],
"wk": [],
"bm": [
6,
16,
22
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "31-27",
"f": 31,
"t": 27,
"c": [],
"path": [
31,
27
],
"p": false
},
{
"n": "22x31",
"f": 22,
"t": 31,
"c": [
27
],
"path": [
22,
31
],
"p": false
},
{
"n": "36x27",
"f": 36,
"t": 27,
"c": [
31
],
"path": [
36,
27
],
"p": false
},
{
"n": "6-11",
"f": 6,
"t": 11,
"c": [],
"path": [
6,
11
],
"p": false
},
{
"n": "26-21",
"f": 26,
"t": 21,
"c": [],
"path": [
26,
21
],
"p": false
},
{
"n": "11-17",
"f": 11,
"t": 17,
"c": [],
"path": [
11,
17
],
"p": false
},
{
"n": "21x12",
"f": 21,
"t": 12,
"c": [
17
],
"path": [
21,
12
],
"p": false
},
{
"n": "16-21",
"f": 16,
"t": 21,
"c": [],
"path": [
16,
21
],
"p": false
},
{
"n": "27x16",
"f": 27,
"t": 16,
"c": [
21
],
"path": [
27,
16
],
"p": false
}
],
"theme": "Bloquer des pions",
"pub": "31-27 22x31 36x27 6-11 26-21 11-17 21x12 16-21 27x16",
"win": "white",
"exp": "Bloquer des pions"
},
"int_blocage_l1_ex6": {
"id": "int_blocage_l1_ex6",
"ch": 1,
"title": "SIJBRANDS — combinaison (p.121 #5)",
"start": {
"wm": [
23,
39,
40
],
"wk": [],
"bm": [
13,
25,
30
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "23-19",
"f": 23,
"t": 19,
"c": [],
"path": [
23,
19
],
"p": false
},
{
"n": "13x24",
"f": 13,
"t": 24,
"c": [
19
],
"path": [
13,
24
],
"p": false
},
{
"n": "40-35",
"f": 40,
"t": 35,
"c": [],
"path": [
40,
35
],
"p": false
},
{
"n": "24-29",
"f": 24,
"t": 29,
"c": [],
"path": [
24,
29
],
"p": false
},
{
"n": "35x24x33",
"f": 35,
"t": 33,
"c": [
29,
30
],
"path": [
35,
24,
33
],
"p": false
},
{
"n": "25-30",
"f": 25,
"t": 30,
"c": [],
"path": [
25,
30
],
"p": false
},
{
"n": "33-28",
"f": 33,
"t": 28,
"c": [],
"path": [
33,
28
],
"p": false
},
{
"n": "30-35",
"f": 30,
"t": 35,
"c": [],
"path": [
30,
35
],
"p": false
},
{
"n": "39-34",
"f": 39,
"t": 34,
"c": [],
"path": [
39,
34
],
"p": false
},
{
"n": "35-40",
"f": 35,
"t": 40,
"c": [],
"path": [
35,
40
],
"p": false
},
{
"n": "34x45",
"f": 34,
"t": 45,
"c": [
40
],
"path": [
34,
45
],
"p": false
}
],
"theme": "Bloquer des pions",
"pub": "23-19 13x24 40-35 24-29 35x24x33 25-30 33-28 30-35 39-34 35-40 34x45",
"win": "white",
"exp": "Bloquer des pions"
},
"int_blocage_l1_ex7": {
"id": "int_blocage_l1_ex7",
"ch": 1,
"title": "SIJBRANDS — combinaison (p.121 #6)",
"start": {
"wm": [
31,
33,
36
],
"wk": [],
"bm": [
18,
22,
23
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "31-27",
"f": 31,
"t": 27,
"c": [],
"path": [
31,
27
],
"p": false
},
{
"n": "22x31",
"f": 22,
"t": 31,
"c": [
27
],
"path": [
22,
31
],
"p": false
},
{
"n": "36x27",
"f": 36,
"t": 27,
"c": [
31
],
"path": [
36,
27
],
"p": false
},
{
"n": "23-29",
"f": 23,
"t": 29,
"c": [],
"path": [
23,
29
],
"p": false
},
{
"n": "33x24",
"f": 33,
"t": 24,
"c": [
29
],
"path": [
33,
24
],
"p": false
},
{
"n": "18-23",
"f": 18,
"t": 23,
"c": [],
"path": [
18,
23
],
"p": false
},
{
"n": "27-22",
"f": 27,
"t": 22,
"c": [],
"path": [
27,
22
],
"p": false
},
{
"n": "23-28",
"f": 23,
"t": 28,
"c": [],
"path": [
23,
28
],
"p": false
},
{
"n": "22x33",
"f": 22,
"t": 33,
"c": [
28
],
"path": [
22,
33
],
"p": false
}
],
"theme": "Bloquer des pions",
"pub": "31-27 22x31 36x27 23-29 33x24 18-23 27-22 23-28 22x33",
"win": "white",
"exp": "Bloquer des pions"
},
"int_blocage_l1_ex8": {
"id": "int_blocage_l1_ex8",
"ch": 1,
"title": "SIJBRANDS — combinaison (p.121 #7)",
"start": {
"wm": [
31,
36,
48
],
"wk": [],
"bm": [
16,
26
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "31-27",
"f": 31,
"t": 27,
"c": [],
"path": [
31,
27
],
"p": false
},
{
"n": "26-31",
"f": 26,
"t": 31,
"c": [],
"path": [
26,
31
],
"p": false
},
{
"n": "27-21",
"f": 27,
"t": 21,
"c": [],
"path": [
27,
21
],
"p": false
},
{
"n": "16x27",
"f": 16,
"t": 27,
"c": [
21
],
"path": [
16,
27
],
"p": false
},
{
"n": "48-42",
"f": 48,
"t": 42,
"c": [],
"path": [
48,
42
],
"p": false
},
{
"n": "27-32",
"f": 27,
"t": 32,
"c": [],
"path": [
27,
32
],
"p": false
},
{
"n": "36x27x38",
"f": 36,
"t": 38,
"c": [
32,
31
],
"path": [
36,
27,
38
],
"p": false
}
],
"theme": "Bloquer des pions",
"pub": "31-27 26-31 27-21 16x27 48-42 27-32 36x27x38",
"win": "white",
"exp": "Bloquer des pions"
},
"int_blocage_l1_pos9": {
"id": "int_blocage_l1_pos9",
"ch": 1,
"title": "Bloquer des pions",
"start": {
"wm": [
33,
42,
43
],
"wk": [],
"bm": [
23,
32
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "43-39",
"f": 43,
"t": 39,
"c": [],
"path": [
43,
39
],
"p": false
},
{
"n": "32-38",
"f": 32,
"t": 38,
"c": [],
"path": [
32,
38
],
"p": false
},
{
"n": "42-37",
"f": 42,
"t": 37,
"c": [],
"path": [
42,
37
],
"p": false
},
{
"n": "38x29",
"f": 38,
"t": 29,
"c": [
33
],
"path": [
38,
29
],
"p": false
},
{
"n": "37-32",
"f": 37,
"t": 32,
"c": [],
"path": [
37,
32
],
"p": false
},
{
"n": "29-34",
"f": 29,
"t": 34,
"c": [],
"path": [
29,
34
],
"p": false
},
{
"n": "39x30",
"f": 39,
"t": 30,
"c": [
34
],
"path": [
39,
30
],
"p": false
},
{
"n": "23-29",
"f": 23,
"t": 29,
"c": [],
"path": [
23,
29
],
"p": false
},
{
"n": "32-28",
"f": 32,
"t": 28,
"c": [],
"path": [
32,
28
],
"p": false
},
{
"n": "29-33",
"f": 29,
"t": 33,
"c": [],
"path": [
29,
33
],
"p": false
},
{
"n": "28x39",
"f": 28,
"t": 39,
"c": [
33
],
"path": [
28,
39
],
"p": false
}
],
"theme": "Bloquer des pions",
"pub": "43-39 32-38 42-37 38x29 37-32 29-34 39x30 23-29 32-28 29-33 28x39",
"win": "white"
},
"int_blocage_l1_pos10": {
"id": "int_blocage_l1_pos10",
"ch": 1,
"title": "Bloquer des pions",
"start": {
"wm": [
28,
32,
37
],
"wk": [],
"bm": [
16,
17,
26
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "32-27",
"f": 32,
"t": 27,
"c": [],
"path": [
32,
27
],
"p": false
},
{
"n": "17-21",
"f": 17,
"t": 21,
"c": [],
"path": [
17,
21
],
"p": false
},
{
"n": "27-22",
"f": 27,
"t": 22,
"c": [],
"path": [
27,
22
],
"p": false
},
{
"n": "21-27",
"f": 21,
"t": 27,
"c": [],
"path": [
21,
27
],
"p": false
},
{
"n": "22x31",
"f": 22,
"t": 31,
"c": [
27
],
"path": [
22,
31
],
"p": false
},
{
"n": "16-21",
"f": 16,
"t": 21,
"c": [],
"path": [
16,
21
],
"p": false
},
{
"n": "28-23",
"f": 28,
"t": 23,
"c": [],
"path": [
28,
23
],
"p": false
},
{
"n": "21-27",
"f": 21,
"t": 27,
"c": [],
"path": [
21,
27
],
"p": false
},
{
"n": "31x22",
"f": 31,
"t": 22,
"c": [
27
],
"path": [
31,
22
],
"p": false
},
{
"n": "26-31",
"f": 26,
"t": 31,
"c": [],
"path": [
26,
31
],
"p": false
},
{
"n": "37x26",
"f": 37,
"t": 26,
"c": [
31
],
"path": [
37,
26
],
"p": false
}
],
"theme": "Bloquer des pions",
"pub": "32-27 17-21 27-22 21-27 22x31 16-21 28-23 21-27 31x22 26-31 37x26",
"win": "white"
},
"int_blocage_l1_pos11": {
"id": "int_blocage_l1_pos11",
"ch": 1,
"title": "Bloquer des pions",
"start": {
"wm": [
38,
50
],
"wk": [],
"bm": [
20,
35
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "50-44",
"f": 50,
"t": 44,
"c": [],
"path": [
50,
44
],
"p": false
},
{
"n": "20-24",
"f": 20,
"t": 24,
"c": [],
"path": [
20,
24
],
"p": false
},
{
"n": "38-33",
"f": 38,
"t": 33,
"c": [],
"path": [
38,
33
],
"p": false
},
{
"n": "24-30",
"f": 24,
"t": 30,
"c": [],
"path": [
24,
30
],
"p": false
},
{
"n": "33-29",
"f": 33,
"t": 29,
"c": [],
"path": [
33,
29
],
"p": false
},
{
"n": "30-34",
"f": 30,
"t": 34,
"c": [],
"path": [
30,
34
],
"p": false
},
{
"n": "29x40",
"f": 29,
"t": 40,
"c": [
34
],
"path": [
29,
40
],
"p": false
}
],
"theme": "Bloquer des pions",
"pub": "50-44 20-24 38-33 24-30 33-29 30-34 29x40",
"win": "white"
},
"int_blocage_l1_pos12": {
"id": "int_blocage_l1_pos12",
"ch": 1,
"title": "Bloquer des pions",
"start": {
"wm": [
37,
47,
48
],
"wk": [],
"bm": [
27,
38
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "47-41",
"f": 47,
"t": 41,
"c": [],
"path": [
47,
41
],
"p": false
},
{
"n": "38-42",
"f": 38,
"t": 42,
"c": [],
"path": [
38,
42
],
"p": false
},
{
"n": "41-36",
"f": 41,
"t": 36,
"c": [],
"path": [
41,
36
],
"p": false
},
{
"n": "42x31",
"f": 42,
"t": 31,
"c": [
37
],
"path": [
42,
31
],
"p": false
},
{
"n": "48-42",
"f": 48,
"t": 42,
"c": [],
"path": [
48,
42
],
"p": false
},
{
"n": "27-32",
"f": 27,
"t": 32,
"c": [],
"path": [
27,
32
],
"p": false
},
{
"n": "36x27x38",
"f": 36,
"t": 38,
"c": [
32,
31
],
"path": [
36,
27,
38
],
"p": false
}
],
"theme": "Bloquer des pions",
"pub": "47-41 38-42 41-36 42x31 48-42 27-32 36x27x38",
"win": "white"
},
"int_blocage_l1_pos13": {
"id": "int_blocage_l1_pos13",
"ch": 1,
"title": "Bloquer des pions",
"start": {
"wm": [
35,
44,
45
],
"wk": [],
"bm": [
24,
34
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "44-40",
"f": 44,
"t": 40,
"c": [],
"path": [
44,
40
],
"p": false
},
{
"n": "24-29",
"f": 24,
"t": 29,
"c": [],
"path": [
24,
29
],
"p": false
},
{
"n": "35-30",
"f": 35,
"t": 30,
"c": [],
"path": [
35,
30
],
"p": false
},
{
"n": "34x25",
"f": 34,
"t": 25,
"c": [
30
],
"path": [
34,
25
],
"p": false
},
{
"n": "40-34",
"f": 40,
"t": 34,
"c": [],
"path": [
40,
34
],
"p": false
},
{
"n": "29x40",
"f": 29,
"t": 40,
"c": [
34
],
"path": [
29,
40
],
"p": false
},
{
"n": "45x34",
"f": 45,
"t": 34,
"c": [
40
],
"path": [
45,
34
],
"p": false
},
{
"n": "25-30",
"f": 25,
"t": 30,
"c": [],
"path": [
25,
30
],
"p": false
},
{
"n": "34x25",
"f": 34,
"t": 25,
"c": [
30
],
"path": [
34,
25
],
"p": false
}
],
"theme": "Bloquer des pions",
"pub": "44-40 24-29 35-30 34x25 40-34 29x40 45x34 25-30 34x25",
"win": "white"
},
"int_blocage_l1_pos14": {
"id": "int_blocage_l1_pos14",
"ch": 1,
"title": "Bloquer des pions",
"start": {
"wm": [
25,
28,
29
],
"wk": [],
"bm": [
13,
14,
18
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Bloquer des pions"
},
"int_blocage_l2_ex0": {
"id": "int_blocage_l2_ex0",
"ch": 2,
"title": "SIJBRANDS — combinaison (p.80 #2)",
"start": {
"wm": [
37,
38,
42
],
"wk": [],
"bm": [
26,
27
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "38-33",
"f": 38,
"t": 33,
"c": [],
"path": [
38,
33
],
"p": false
},
{
"n": "27-31",
"f": 27,
"t": 31,
"c": [],
"path": [
27,
31
],
"p": false
},
{
"n": "42-38",
"f": 42,
"t": 38,
"c": [],
"path": [
42,
38
],
"p": false
},
{
"n": "31x42",
"f": 31,
"t": 42,
"c": [
37
],
"path": [
31,
42
],
"p": false
},
{
"n": "38x47",
"f": 38,
"t": 47,
"c": [
42
],
"path": [
38,
47
],
"p": false
},
{
"n": "26-31",
"f": 26,
"t": 31,
"c": [],
"path": [
26,
31
],
"p": false
},
{
"n": "47-42",
"f": 47,
"t": 42,
"c": [],
"path": [
47,
42
],
"p": false
},
{
"n": "31-36",
"f": 31,
"t": 36,
"c": [],
"path": [
31,
36
],
"p": false
},
{
"n": "42-37",
"f": 42,
"t": 37,
"c": [],
"path": [
42,
37
],
"p": false
},
{
"n": "36-41",
"f": 36,
"t": 41,
"c": [],
"path": [
36,
41
],
"p": false
},
{
"n": "37x46",
"f": 37,
"t": 46,
"c": [
41
],
"path": [
37,
46
],
"p": false
}
],
"theme": "Empêcher un débordement",
"pub": "38-33 27-31 42-38 31x42 38x47 26-31 47-42 31-36 42-37 36-41 37x46",
"win": "white",
"exp": "Empêcher un débordement"
},
"int_blocage_l2_ex1": {
"id": "int_blocage_l2_ex1",
"ch": 2,
"title": "SIJBRANDS — combinaison (p.81 #10)",
"start": {
"wm": [
23,
36,
40
],
"wk": [],
"bm": [
20,
24
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "40-35",
"f": 40,
"t": 35,
"c": [],
"path": [
40,
35
],
"p": false
},
{
"n": "20-25",
"f": 20,
"t": 25,
"c": [],
"path": [
20,
25
],
"p": false
},
{
"n": "36-31",
"f": 36,
"t": 31,
"c": [],
"path": [
36,
31
],
"p": false
},
{
"n": "25-30",
"f": 25,
"t": 30,
"c": [],
"path": [
25,
30
],
"p": false
},
{
"n": "23-19",
"f": 23,
"t": 19,
"c": [],
"path": [
23,
19
],
"p": false
},
{
"n": "24x13",
"f": 24,
"t": 13,
"c": [
19
],
"path": [
24,
13
],
"p": false
},
{
"n": "35x24",
"f": 35,
"t": 24,
"c": [
30
],
"path": [
35,
24
],
"p": false
},
{
"n": "13-18",
"f": 13,
"t": 18,
"c": [],
"path": [
13,
18
],
"p": false
},
{
"n": "31-27",
"f": 31,
"t": 27,
"c": [],
"path": [
31,
27
],
"p": false
},
{
"n": "18-23",
"f": 18,
"t": 23,
"c": [],
"path": [
18,
23
],
"p": false
},
{
"n": "27-22",
"f": 27,
"t": 22,
"c": [],
"path": [
27,
22
],
"p": false
},
{
"n": "23-28",
"f": 23,
"t": 28,
"c": [],
"path": [
23,
28
],
"p": false
},
{
"n": "22x33",
"f": 22,
"t": 33,
"c": [
28
],
"path": [
22,
33
],
"p": false
}
],
"theme": "Empêcher un débordement",
"pub": "40-35 20-25 36-31 25-30 23-19 24x13 35x24 13-18 31-27 18-23 27-22 23-28 22x33",
"win": "white",
"exp": "Empêcher un débordement"
},
"int_blocage_l2_ex2": {
"id": "int_blocage_l2_ex2",
"ch": 2,
"title": "SIJBRANDS — combinaison (p.81 #3)",
"start": {
"wm": [
23,
28,
32
],
"wk": [],
"bm": [
4,
21,
26
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "32-27",
"f": 32,
"t": 27,
"c": [],
"path": [
32,
27
],
"p": false
},
{
"n": "21x32",
"f": 21,
"t": 32,
"c": [
27
],
"path": [
21,
32
],
"p": false
},
{
"n": "28x37",
"f": 28,
"t": 37,
"c": [
32
],
"path": [
28,
37
],
"p": false
},
{
"n": "4-10",
"f": 4,
"t": 10,
"c": [],
"path": [
4,
10
],
"p": false
},
{
"n": "23-19",
"f": 23,
"t": 19,
"c": [],
"path": [
23,
19
],
"p": false
},
{
"n": "10-15",
"f": 10,
"t": 15,
"c": [],
"path": [
10,
15
],
"p": false
},
{
"n": "19-14",
"f": 19,
"t": 14,
"c": [],
"path": [
19,
14
],
"p": false
},
{
"n": "15-20",
"f": 15,
"t": 20,
"c": [],
"path": [
15,
20
],
"p": false
},
{
"n": "14x25",
"f": 14,
"t": 25,
"c": [
20
],
"path": [
14,
25
],
"p": false
},
{
"n": "26-31",
"f": 26,
"t": 31,
"c": [],
"path": [
26,
31
],
"p": false
},
{
"n": "37x26",
"f": 37,
"t": 26,
"c": [
31
],
"path": [
37,
26
],
"p": false
}
],
"theme": "Empêcher un débordement",
"pub": "32-27 21x32 28x37 4-10 23-19 10-15 19-14 15-20 14x25 26-31 37x26",
"win": "white",
"exp": "Empêcher un débordement"
},
"int_blocage_l2_ex3": {
"id": "int_blocage_l2_ex3",
"ch": 2,
"title": "SIJBRANDS — combinaison (p.81 #6)",
"start": {
"wm": [
25,
33,
34
],
"wk": [],
"bm": [
13,
19,
30
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "33-29",
"f": 33,
"t": 29,
"c": [],
"path": [
33,
29
],
"p": false
},
{
"n": "30x39",
"f": 30,
"t": 39,
"c": [
34
],
"path": [
30,
39
],
"p": false
},
{
"n": "29-24",
"f": 29,
"t": 24,
"c": [],
"path": [
29,
24
],
"p": false
},
{
"n": "19x30",
"f": 19,
"t": 30,
"c": [
24
],
"path": [
19,
30
],
"p": false
},
{
"n": "25x34x43",
"f": 25,
"t": 43,
"c": [
30,
39
],
"path": [
25,
34,
43
],
"p": false
},
{
"n": "13-18",
"f": 13,
"t": 18,
"c": [],
"path": [
13,
18
],
"p": false
},
{
"n": "43-38",
"f": 43,
"t": 38,
"c": [],
"path": [
43,
38
],
"p": false
},
{
"n": "18-23",
"f": 18,
"t": 23,
"c": [],
"path": [
18,
23
],
"p": false
},
{
"n": "38-33",
"f": 38,
"t": 33,
"c": [],
"path": [
38,
33
],
"p": false
},
{
"n": "23-28",
"f": 23,
"t": 28,
"c": [],
"path": [
23,
28
],
"p": false
},
{
"n": "33x22",
"f": 33,
"t": 22,
"c": [
28
],
"path": [
33,
22
],
"p": false
}
],
"theme": "Empêcher un débordement",
"pub": "33-29 30x39 29-24 19x30 25x34x43 13-18 43-38 18-23 38-33 23-28 33x22",
"win": "white",
"exp": "Empêcher un débordement"
},
"int_blocage_l2_ex4": {
"id": "int_blocage_l2_ex4",
"ch": 2,
"title": "SIJBRANDS — combinaison (p.81 #9)",
"start": {
"wm": [
38,
41,
48
],
"wk": [],
"bm": [
16,
31
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "48-42",
"f": 48,
"t": 42,
"c": [],
"path": [
48,
42
],
"p": false
},
{
"n": "31-36",
"f": 31,
"t": 36,
"c": [],
"path": [
31,
36
],
"p": false
},
{
"n": "41-37",
"f": 41,
"t": 37,
"c": [],
"path": [
41,
37
],
"p": false
},
{
"n": "16-21",
"f": 16,
"t": 21,
"c": [],
"path": [
16,
21
],
"p": false
},
{
"n": "38-32",
"f": 38,
"t": 32,
"c": [],
"path": [
38,
32
],
"p": false
},
{
"n": "21-26",
"f": 21,
"t": 26,
"c": [],
"path": [
21,
26
],
"p": false
},
{
"n": "32-27",
"f": 32,
"t": 27,
"c": [],
"path": [
32,
27
],
"p": false
},
{
"n": "26-31",
"f": 26,
"t": 31,
"c": [],
"path": [
26,
31
],
"p": false
},
{
"n": "37x26",
"f": 37,
"t": 26,
"c": [
31
],
"path": [
37,
26
],
"p": false
},
{
"n": "36-41",
"f": 36,
"t": 41,
"c": [],
"path": [
36,
41
],
"p": false
},
{
"n": "42-37",
"f": 42,
"t": 37,
"c": [],
"path": [
42,
37
],
"p": false
},
{
"n": "41x32x21",
"f": 41,
"t": 21,
"c": [
27,
37
],
"path": [
41,
32,
21
],
"p": false
},
{
"n": "26x17",
"f": 26,
"t": 17,
"c": [
21
],
"path": [
26,
17
],
"p": false
}
],
"theme": "Empêcher un débordement",
"pub": "48-42 31-36 41-37 16-21 38-32 21-26 32-27 26-31 37x26 36-41 42-37 41x32x21 26x17",
"win": "white",
"exp": "Empêcher un débordement"
},
"int_blocage_l2_pos5": {
"id": "int_blocage_l2_pos5",
"ch": 2,
"title": "Empêcher un débordement",
"start": {
"wm": [
27,
28,
33,
37,
39
],
"wk": [],
"bm": [
6,
16,
25,
26,
30
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Empêcher un débordement"
},
"int_blocage_l2_pos6": {
"id": "int_blocage_l2_pos6",
"ch": 2,
"title": "Empêcher un débordement",
"start": {
"wm": [
23,
36,
40
],
"wk": [],
"bm": [
20,
24
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "40-35",
"f": 40,
"t": 35,
"c": [],
"path": [
40,
35
],
"p": false
},
{
"n": "20-25",
"f": 20,
"t": 25,
"c": [],
"path": [
20,
25
],
"p": false
},
{
"n": "36-31",
"f": 36,
"t": 31,
"c": [],
"path": [
36,
31
],
"p": false
},
{
"n": "25-30",
"f": 25,
"t": 30,
"c": [],
"path": [
25,
30
],
"p": false
},
{
"n": "23-19",
"f": 23,
"t": 19,
"c": [],
"path": [
23,
19
],
"p": false
},
{
"n": "24x13",
"f": 24,
"t": 13,
"c": [
19
],
"path": [
24,
13
],
"p": false
},
{
"n": "35x24",
"f": 35,
"t": 24,
"c": [
30
],
"path": [
35,
24
],
"p": false
},
{
"n": "13-18",
"f": 13,
"t": 18,
"c": [],
"path": [
13,
18
],
"p": false
},
{
"n": "31-27",
"f": 31,
"t": 27,
"c": [],
"path": [
31,
27
],
"p": false
},
{
"n": "18-23",
"f": 18,
"t": 23,
"c": [],
"path": [
18,
23
],
"p": false
},
{
"n": "27-22",
"f": 27,
"t": 22,
"c": [],
"path": [
27,
22
],
"p": false
},
{
"n": "23-28",
"f": 23,
"t": 28,
"c": [],
"path": [
23,
28
],
"p": false
},
{
"n": "22x33",
"f": 22,
"t": 33,
"c": [
28
],
"path": [
22,
33
],
"p": false
}
],
"theme": "Empêcher un débordement",
"pub": "40-35 20-25 36-31 25-30 23-19 24x13 35x24 13-18 31-27 18-23 27-22 23-28 22x33",
"win": "white"
},
"int_blocage_l2_pos7": {
"id": "int_blocage_l2_pos7",
"ch": 2,
"title": "Empêcher un débordement",
"start": {
"wm": [
37,
38,
42
],
"wk": [],
"bm": [
26,
27
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "38-33",
"f": 38,
"t": 33,
"c": [],
"path": [
38,
33
],
"p": false
},
{
"n": "27-31",
"f": 27,
"t": 31,
"c": [],
"path": [
27,
31
],
"p": false
},
{
"n": "42-38",
"f": 42,
"t": 38,
"c": [],
"path": [
42,
38
],
"p": false
},
{
"n": "31x42",
"f": 31,
"t": 42,
"c": [
37
],
"path": [
31,
42
],
"p": false
},
{
"n": "38x47",
"f": 38,
"t": 47,
"c": [
42
],
"path": [
38,
47
],
"p": false
},
{
"n": "26-31",
"f": 26,
"t": 31,
"c": [],
"path": [
26,
31
],
"p": false
},
{
"n": "47-42",
"f": 47,
"t": 42,
"c": [],
"path": [
47,
42
],
"p": false
},
{
"n": "31-36",
"f": 31,
"t": 36,
"c": [],
"path": [
31,
36
],
"p": false
},
{
"n": "42-37",
"f": 42,
"t": 37,
"c": [],
"path": [
42,
37
],
"p": false
},
{
"n": "36-41",
"f": 36,
"t": 41,
"c": [],
"path": [
36,
41
],
"p": false
},
{
"n": "37x46",
"f": 37,
"t": 46,
"c": [
41
],
"path": [
37,
46
],
"p": false
}
],
"theme": "Empêcher un débordement",
"pub": "38-33 27-31 42-38 31x42 38x47 26-31 47-42 31-36 42-37 36-41 37x46",
"win": "white"
},
"int_blocage_l2_pos8": {
"id": "int_blocage_l2_pos8",
"ch": 2,
"title": "Empêcher un débordement",
"start": {
"wm": [
33,
38,
48,
49
],
"wk": [],
"bm": [
26,
31
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Empêcher un débordement"
},
"int_blocage_l2_pos9": {
"id": "int_blocage_l2_pos9",
"ch": 2,
"title": "Empêcher un débordement",
"start": {
"wm": [
23,
28,
32
],
"wk": [],
"bm": [
4,
21,
26
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "32-27",
"f": 32,
"t": 27,
"c": [],
"path": [
32,
27
],
"p": false
},
{
"n": "21x32",
"f": 21,
"t": 32,
"c": [
27
],
"path": [
21,
32
],
"p": false
},
{
"n": "28x37",
"f": 28,
"t": 37,
"c": [
32
],
"path": [
28,
37
],
"p": false
},
{
"n": "4-10",
"f": 4,
"t": 10,
"c": [],
"path": [
4,
10
],
"p": false
},
{
"n": "23-19",
"f": 23,
"t": 19,
"c": [],
"path": [
23,
19
],
"p": false
},
{
"n": "10-15",
"f": 10,
"t": 15,
"c": [],
"path": [
10,
15
],
"p": false
},
{
"n": "19-14",
"f": 19,
"t": 14,
"c": [],
"path": [
19,
14
],
"p": false
},
{
"n": "15-20",
"f": 15,
"t": 20,
"c": [],
"path": [
15,
20
],
"p": false
},
{
"n": "14x25",
"f": 14,
"t": 25,
"c": [
20
],
"path": [
14,
25
],
"p": false
},
{
"n": "26-31",
"f": 26,
"t": 31,
"c": [],
"path": [
26,
31
],
"p": false
},
{
"n": "37x26",
"f": 37,
"t": 26,
"c": [
31
],
"path": [
37,
26
],
"p": false
}
],
"theme": "Empêcher un débordement",
"pub": "32-27 21x32 28x37 4-10 23-19 10-15 19-14 15-20 14x25 26-31 37x26",
"win": "white"
},
"int_blocage_l2_pos10": {
"id": "int_blocage_l2_pos10",
"ch": 2,
"title": "Empêcher un débordement",
"start": {
"wm": [
32,
43,
44,
49
],
"wk": [],
"bm": [
9,
21,
27,
34
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Empêcher un débordement"
}
}
}

export default DATA
