// Auto-generated by backend/curriculum/build_parcours_manuels.py — do not edit by hand.
import type { ManuelData } from '../ManuelInteractif'

const DATA: ManuelData = {
"book": "Les grands manuels stratégiques",
"level": "Intermédiaire",
"chapters": [
{
"n": 0,
"title": "Présentation"
},
{
"n": 1,
"title": "Le système classique (Sijbrands)"
},
{
"n": 2,
"title": "Le système Roozenburg"
},
{
"n": 3,
"title": "Le système Keller"
},
{
"n": 4,
"title": "Plans de milieu de partie (Springer)"
}
],
"blocks": [
{
"type": "h1",
"ch": 0,
"runs": [
{
"t": "Les grands manuels stratégiques"
}
]
},
{
"type": "p",
"ch": 0,
"runs": [
{
"t": "Lire les maîtres : systèmes, plans et méthode."
}
]
},
{
"type": "p",
"ch": 0,
"runs": [
{
"b": 1,
"t": "Objectif. "
},
{
"t": "Parcourir en prose les grands manuels de systèmes (Sijbrands, Roozenburg, Keller, Springer) — ouverture, plans de milieu, finales — et y puiser les idées de fond, au-delà du calcul tactique."
}
]
},
{
"type": "h2",
"ch": 1,
"runs": [
{
"t": "Le système classique (Sijbrands)"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "Le socle du jeu positionnel : centre, ailes et équilibre, expliqués par Ton Sijbrands. Lisez le manuel chapitre par chapitre, chaque idée illustrée par sa position."
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "Manuel théorique complet : "
},
{
"b": 1,
"t": "Sijbrands"
},
{
"t": " — à lire dans la section « Manuels théoriques »."
}
]
},
{
"type": "h2",
"ch": 2,
"runs": [
{
"t": "Le système Roozenburg"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "Position de tour, contrôle du centre et attaque : le système qui porte le nom du champion du monde Piet Roozenburg."
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "Manuel théorique complet : "
},
{
"b": 1,
"t": "Roozenburg"
},
{
"t": " — à lire dans la section « Manuels théoriques »."
}
]
},
{
"type": "h2",
"ch": 3,
"runs": [
{
"t": "Le système Keller"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "Le pion 2, le contre-jeu et la structure typique du système Keller. Un répertoire complet en prose."
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "Manuel théorique complet : "
},
{
"b": 1,
"t": "Keller"
},
{
"t": " — à lire dans la section « Manuels théoriques »."
}
]
},
{
"type": "h2",
"ch": 4,
"runs": [
{
"t": "Plans de milieu de partie (Springer)"
}
]
},
{
"type": "p",
"ch": 4,
"runs": [
{
"t": "Manœuvres, plans types et idées générales du milieu de partie. Le manuel de référence pour structurer sa réflexion."
}
]
},
{
"type": "p",
"ch": 4,
"runs": [
{
"t": "Manuel théorique complet : "
},
{
"b": 1,
"t": "Springer"
},
{
"t": " — à lire dans la section « Manuels théoriques »."
}
]
}
],
"positions": {}
}

export default DATA
