// Auto-generated by backend/curriculum/build_parcours_manuels.py — do not edit by hand.
import type { ManuelData } from '../ManuelInteractif'

const DATA: ManuelData = {
"book": "Les pions clés",
"level": "Intermédiaire",
"chapters": [
{
"n": 0,
"title": "Présentation"
},
{
"n": 1,
"title": "Les pions de base 49 et 50"
},
{
"n": 2,
"title": "Le pion blanc 36"
},
{
"n": 3,
"title": "Le pion de bande 26"
}
],
"blocks": [
{
"type": "h1",
"ch": 0,
"runs": [
{
"t": "Les pions clés"
}
]
},
{
"type": "p",
"ch": 0,
"runs": [
{
"t": "Pions de base 49/50, pion 36, pion de bande 26."
}
]
},
{
"type": "p",
"ch": 0,
"runs": [
{
"b": 1,
"t": "Objectif. "
},
{
"t": "Maîtriser le rôle stratégique des pions de base et de bande dans la structure."
}
]
},
{
"type": "h2",
"ch": 1,
"runs": [
{
"t": "Les pions de base 49 et 50"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "Chapitre 8 : les pions de base 49 et 50 Les pions de base 49 et 50 ont souvent une valeur équivalente. Il existe pourtant quelques différences que nous allons mettre en évidence :"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "1 – En système classique"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "Trait aux noirs"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "Trait aux noirs"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "Cette situation se rencontre fréquemment en partie classique. Dans le premier diagramme, les noirs ont mis en jeu leur pion 2. Cela leur permet de développer leur aile droite par (12-17), car l’éventuel échange 27-22 détruirait le centre des blancs. Dans le second diagramme, les noirs ont mis en jeu leur pion 1. Le développement de leur aile droite passe nécessairement par (11-17). Dans ce cas, les blancs ont à leur disposition l’excellent échange 27-22 (18x27) 31x11, qui présente le triple avantage de supprimer la possibilité de créer une colonne de choc 6-11-17, d’éliminer les menaces de coup royal, et enfin de mettre en jeu favorablement le pion 36 vers la case 27."
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "Trait aux noirs"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "Trait aux noirs"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "Cette situation se rencontre également fréquemment. Dans le premier diagramme, les noirs ont leur aile droite immobilisée et ne peuvent mettre en jeu ni leur pion 11 à cause du coup de dame direct, ni leur pion 12 à cause du coup de la bombe. Dans le second diagramme, les noirs ont la faculté de jouer (11-17), avec toutefois les mêmes inconvénients cités précédemment."
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "Trait aux blancs"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "Trait aux blancs"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "On mesure ici l’importance du pion 49 pour s’emparer de l’aile droite. Dans le premier diagramme, après 34-30 (20-25), les blancs ont le choix entre 39-34 et 49-43. Dans le second diagramme, les blancs qu’une seule alternative, celle de jouer 34-30 (20-25) 39-34, etc."
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "2 – En partie de flanc En partie de flanc, le pion 49 est beaucoup plus utile que le pion 50. Examinons les positions suivantes :"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "Trait aux blancs"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "Trait aux blancs Alexander Georgiev – Guntis Valneris (2013)"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "1er diagramme : grâce à leur formation 38-43-49, les blancs ont la faculté d’éliminer le pion taquin adverse 27 par 38-32 (27x38) 43x32 et de se rendre maître du centre. On note également que le pion 49 empêche des combinaisons avec rafle finale 20x49. 2e diagramme : les blancs ont pris l’avantage par : 29. 37-32 (27x38) 30. 43x32 (11-16) 31. 42-38 (611) 32. 32-28 (16-21) 33. 49-43 (21-27) 34. 43-39 (13-19) 35. 24x13 (18x9) 36. 29-23 etc. 27-32 37.38x18 14-19 38.23x14 12x32 39.31-27 2-0"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "3 – En fin de partie En fin de partie, le pion 50 joue indéniablement plus un rôle que le pion 49 pour contenir l’avancée adverse sur le flanc droit."
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "Dans le 1er diagramme, on voit que le pion peut rester sur la case 50 sans que le pion 35 puisse passer. Avec le pion à 49, il serait nécessaire de jouer à 44. Dans le second diagramme, si les noirs jouent (24-29), les blancs peuvent prendre le pion par 34x23 sans crainte de l’avancée (35-40) car 50-45 est alors possible avec la suite (30-34) 39x30 (35x24) 3329 etc. Avec le pion à 49, les blancs seraient forcés d’accepter l’échange par (24-29) 33x24 (30x19) pour éviter le passage à dame. Ton SIJBRANDS – D. van DOMMELEN Sim time Ton Sijbrands Amsterdam, 08-11-1979 Trait aux noirs 38… 13-18 40. 28-22 (?)"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "39. 21-17"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "9-13"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "Meilleur est 31-26 40…"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "7-11 ?"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "Les noirs ont une échappatoire par (25-30) 34x25 (35-40) etc."
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "49. 27-22"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "16x18"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "41. 31-26 43. 34x45 45. 32-28 47. 18x9 50. 4x49"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "11-16 25-30 18-23 29x38 19-23"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "42. 26-21 35-40 44. 50-44 23-29 46. 22-18 23x34 48. 9-4 24-29 51. 44-39 (2-0)"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "Trait aux blancs Les blancs peuvent profiter de la situation en jouant : 1. 28-22"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "1-7"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "2. 33-28"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "Et les blancs profitent du fait que (24-29) 50-45 (29x40) 45x34 (2530) 34x25 (35-40) échoue simplement après 39-34 (40x29) 25-20 avec la suite imparable 20-14."
}
]
},
{
"type": "board",
"id": "int_sdj_pions_cles_l1_dia0",
"ch": 1
},
{
"type": "board",
"id": "int_sdj_pions_cles_l1_dia1",
"ch": 1
},
{
"type": "board",
"id": "int_sdj_pions_cles_l1_dia2",
"ch": 1
},
{
"type": "board",
"id": "int_sdj_pions_cles_l1_dia3",
"ch": 1
},
{
"type": "board",
"id": "int_sdj_pions_cles_l1_dia4",
"ch": 1
},
{
"type": "board",
"id": "int_sdj_pions_cles_l1_dia5",
"ch": 1
},
{
"type": "board",
"id": "int_sdj_pions_cles_l1_dia6",
"ch": 1
},
{
"type": "board",
"id": "int_sdj_pions_cles_l1_dia7",
"ch": 1
},
{
"type": "board",
"id": "int_sdj_pions_cles_l1_dia8",
"ch": 1
},
{
"type": "board",
"id": "int_sdj_pions_cles_l1_dia9",
"ch": 1
},
{
"type": "board",
"id": "int_sdj_pions_cles_l1_dia10",
"ch": 1
},
{
"type": "board",
"id": "int_sdj_pions_cles_l1_dia11",
"ch": 1
},
{
"type": "board",
"id": "int_sdj_pions_cles_l1_dia12",
"ch": 1
},
{
"type": "board",
"id": "int_sdj_pions_cles_l1_dia13",
"ch": 1
},
{
"type": "board",
"id": "int_sdj_pions_cles_l1_ex0",
"ch": 1
},
{
"type": "board",
"id": "int_sdj_pions_cles_l1_ex1",
"ch": 1
},
{
"type": "board",
"id": "int_sdj_pions_cles_l1_ex2",
"ch": 1
},
{
"type": "board",
"id": "int_sdj_pions_cles_l1_ex3",
"ch": 1
},
{
"type": "board",
"id": "int_sdj_pions_cles_l1_ex4",
"ch": 1
},
{
"type": "board",
"id": "int_sdj_pions_cles_l1_ex5",
"ch": 1
},
{
"type": "h2",
"ch": 2,
"runs": [
{
"t": "Le pion blanc 36"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "Chapitre 1 : le pion blanc 36 La valeur défensive du pion 36 est incontestable. Le seul risque encouru pour les blancs est qu’en fin de milieu de partie, il ne participe pas au jeu et qu’il soit qualifié de pion arrière."
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "Trait aux noirs"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "Trait aux blancs"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "Les deux positions semblent comparables. Pourtant, dans le premier diagramme, le pion 36 participe à l’action tandis que dans le second diagramme, il ne joue aucun rôle. Examinons cela de plus près : Diagramme n°1 : par exemple (3-9) 34-30 (24-29) [en effet, la présence d’un pion à 36 interdit la sortie (23-29) par 28-23 etc.] 30-25 etc. Ou encore : (3-8) 34-30 (24-29) 30-25 (18-22) 27x18 (23x12) 25-20 (19-24) 20-14 (29-34) 14-10 (34-39) 48-43 etc. Diagramme n°2 : le pion blanc 36 ne participe pas au jeu. Après par exemple 38-33 (13-18) ! 25-20 [après 34-30 suit (12-17) 36-31 (17-22) 28x17 (21x12) 33-28 (12-17)] (24x15) ! 34-30 (14-20) etc."
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "Trait aux noirs Cette position est gagnante pour les noirs : 1…"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "7-12 !!"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "Le coup naturel (8-12) conduit à la nulle après la suite étonnante 36-31 (7-11) 30-25 (11-17) 34-30 (17-21) 28-22 etc. 2. 30-25 Après 36-31 (12-17) 30-25, les noirs gagnent simplement par (1722) 28x17 (24-30) 35x24 (19x28) 2… 4. 28x17 6. 35x24 8. 31x42"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "16-21 ! 12x21 19x28 23-28"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "Et la position des blancs est sans espoir."
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "3. 27x16 5. 16x27 7. 37-31 9. 42-37"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "18-22 24-30 28x37 8-12"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "Graaskamp - Sipma (Salou 2017) 43e temps - trait au noirs Les noirs ont exploité la faiblesse du pion 36 de la manière suivante : 43… 45. 39-33 47. 33-28"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "1-7 20-24"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "44. 49-43 46. 38-32"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "7-12 13-18 !"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "Les blancs doivent à tout prix éviter l’échange (24-29) 33x24 (2328) 32x23 (18x20) qui isolerait totalement du jeu le pion 36. 47… 49. 45-40 51. 36-31"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "23-29 24-30 18-23"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "48. 43-38 50. 40-35 52. 27-22"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "14-19 ! 30-34 34-39 etc."
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "Viacheslav Shchegolev – Andries Andreiko match départage cht URSS 1964 46e temps – trait aux blancs Le pion 15 est inactif. 46. 45-40 !"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "15-20"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "47. 40-35"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "Les blancs viennent clouer le trio de pions 20-24-25. 47… 49. 32-28 !"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "17-22"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "48. 28x17"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "21x12"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "A l’identique de l’exemple précédent, les blancs construisent la formation 28-33-39. 51. 28-23"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "19x28"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "49… 13-19 52. 33x31 les noirs abandonnent."
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "50. 27-22 ! 18x27"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "Piet Roozenburg – RC Keller Tournoi de Damas 1950 44e temps – trait aux blancs Cette position 10x10 est aujourd’hui considérée comme une position standard. Elle n’est pas gagnante, mais la nulle est très difficile à trouver si on ne connaît pas la solution. L’intérêt de cette position est de montrer l’utilité du pion 36 lorsque l’on dispose d’un nombre de temps de réserve suffisant. 44. 39-34 ! Le pion 36 prémunit les blancs contre le gambit (16-21) 27x16 (1822) par 34-29 ! 44…"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "17-21"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "45. 28-22 !"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "24-29"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "48. 38-33 51. 22x11"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "20-24 16x7"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "Un coup logique mais perdant. La nulle s’obtient en jouant (14-20) et si : A – 38-33 (23-29) 34x25 (12-17) 30x8 (17x48) etc. B – 30-25 (24-29) 25x14 (29x40) 35x44 (19x10) 43-39 (23-29) ! etc. 46. 43-39 49. 33-28 ! 52. 27x16"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "29x40 24x35 7-12"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "47. 35x44 50. 39-34 53. 36-31 !"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "14-20 12-17"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "Le pion 36 joue à présent un rôle décisif. 53…"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "12-17"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "54. 31-27 etc."
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "Iser Kouperman – A. Winderman Championnat URSS 1954 47e temps – trait aux blancs La valeur des pions 36 et 15 n’est pas du tout la même. Les blancs ont forcé le jeu par : 47. 27-22 !"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "15-20"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "48. 22x11"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "16x7"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "49. 36-31 !"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "7-11"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "50. 31-27"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "11-16"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "51. 39-34 !"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "13-18"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "52. 34-30"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "23-29"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "53. 28-22"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "18-23"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "54. 33-28 etc."
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "Vladimir Kaplan – Sergeï Mansjien Championnat URSS 1964 47e temps – trait aux blancs Un autre exemple qui illustre l’importance défensive du pion 36 lorque l’on dispose d’un réservoir de temps de réserve. 47. 48-43 !"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "17-21"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "Sur (24-29) suit simplement 27-22 (18x27) 32x12 (23x41) 36x47. Par ailleurs, le gambit (16-21) 27x16 (18-22) est contré par le collage 25-20. 48. 38-33 23-29 48. 43-38 18-23 49. 27-22 + Fred IVENS – Krijn TOET (1968) 45e temps – trait aux blancs Encore une belle illustration de la force du pion 36 en fin de milieu de partie classique. 45. 40-34 ! 17-21 Le gambit (16-21) 27x16 (18-22) est encore contré par 25-20 46. 38-33 ! 3-8 48. 35-30 !! 24x35 50. 37x26 23-28 52. 17x8 13x2 54. 34x23 19x37 56. 39-34 etc."
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "2. 22-17 11x22 5. 36x16 etc. ="
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "47. 28-22 49. 22-17 51. 33x22 53. 26x17 55. 36-31 !"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "8-12 26-31 18-23 23-29 37x26"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "Trait aux blancs Dans cette position critique pour les blancs, le pion 36 permet aux blancs d’annuler par : 1. 27-22 ! Après 39-34 (13-18), la position des blancs est très probablement perdante. 1… 12-18 Après (16-21) suit directement 33-29 (24x31) 36x20 Après (12-17) 39-34 (8-12) 36-31 ! les blancs n’ont plus rien à craindre Après (11-17) 22x11 (16x7) suit 28-22 !! (12-18) [ sur (7-11) suit 22-18 et 33-29, sur le gain de pion (23-28) 32x23 (19x17) suit le coup de dame 37-31 (26x37) 38-32 (37x28) 33x2] 22-17 etc. = 3. 28x17 16-21 4. 33-29 ! 24x31"
}
]
},
{
"type": "board",
"id": "int_sdj_pions_cles_l2_dia0",
"ch": 2
},
{
"type": "board",
"id": "int_sdj_pions_cles_l2_dia1",
"ch": 2
},
{
"type": "board",
"id": "int_sdj_pions_cles_l2_dia2",
"ch": 2
},
{
"type": "board",
"id": "int_sdj_pions_cles_l2_dia3",
"ch": 2
},
{
"type": "board",
"id": "int_sdj_pions_cles_l2_dia4",
"ch": 2
},
{
"type": "board",
"id": "int_sdj_pions_cles_l2_dia5",
"ch": 2
},
{
"type": "board",
"id": "int_sdj_pions_cles_l2_dia6",
"ch": 2
},
{
"type": "board",
"id": "int_sdj_pions_cles_l2_dia7",
"ch": 2
},
{
"type": "board",
"id": "int_sdj_pions_cles_l2_dia8",
"ch": 2
},
{
"type": "board",
"id": "int_sdj_pions_cles_l2_dia9",
"ch": 2
},
{
"type": "board",
"id": "int_sdj_pions_cles_l2_ex0",
"ch": 2
},
{
"type": "board",
"id": "int_sdj_pions_cles_l2_ex1",
"ch": 2
},
{
"type": "board",
"id": "int_sdj_pions_cles_l2_ex2",
"ch": 2
},
{
"type": "board",
"id": "int_sdj_pions_cles_l2_ex3",
"ch": 2
},
{
"type": "board",
"id": "int_sdj_pions_cles_l2_ex4",
"ch": 2
},
{
"type": "board",
"id": "int_sdj_pions_cles_l2_ex5",
"ch": 2
},
{
"type": "h2",
"ch": 3,
"runs": [
{
"t": "Le pion de bande 26"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "Chapitre 2 : le pion de bande 26 Le pion de bande 26 joue un rôle important dans le choix des plans de jeu. La valeur de ce pion est ambiguë. Il peut s’agir d’un pion faible que l’on peut utiliser ou au contraire un pion bien gênant pour le camp adverse. Examinons les 2 cas suivants :"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "Trait aux noirs"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "Trait aux blancs"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "Dans le premier diagramme, la masse de pions noirs est inefficace. Le pion 26 gêne le développement des noirs sur leur aile droite. Nous verrons plus loin des extraits de parties qui soulignent bien cette situation inconfortable des noirs. A l’inverse, dans le second diagramme, la formation des noirs 6-11-16-17 met sous pression la position blanche. 43-39 est interdit par le coup Philippe (24-29) 33x24 (19x30) 35x24 (17-21) 26x17 (11x44). Après 1. 31-27 (18-23) 2. 43-39 (13-18), la position des blancs est intenable."
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "1 - Le pion 26 avantageux Nous allons à présent développer les avantages que l’on peut tirer de positions dans le genre du premier diagramme : Guntis Valneris – Ove Verdel Riga 1998 e 30 temps – trait aux blancs Les noirs ont a priori une bonne position centrale, mais tout vole en éclat après : 30. 33-29 ! 32. 29-24 !"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "23x34 19x30"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "31. 40x29 33. 25x34"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "3-9"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "Les blancs mettent ainsi en évidence certaines faiblesses dans la position des noirs. On note ainsi le retard de développement des pion 6 et 11 ainsi qu’une gêne des noirs sur leur aile droite. 33… 35. 38-33"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "14-19 15-20"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "Diagramme suivant :"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "34. 47-42 36. 43-38"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "9-14 20-24"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "Les blancs ont construit l’importante formation 33-38-42 car la maîtrise de la case 29 revêt une importance capitale pour les blancs. 37. 33-29 ! 39. 42-38 41. 29x20 43. 38-33 45. 32-27 !"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "24x33 20-25 25x14 12-18"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "38. 38x29 40. 45-40 42. 40-35 44. 34-29 !"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "14-20 19-24 14-20 20-25"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "La position des noirs est entièrement sous contrôle. 45… 47. 27x18"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "18-23 16-21"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "46. 29x9 48. 26x17"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "17-22 11x4"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "Etc. B+ Leonid Kats – Andris Andreiko Cht URSS 1965 37e temps – trait aux noirs 37…"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "15-20 !"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "Introduit la menace (18-22) 39-33 (25-30) 35x15 (14-20) 15x24 (19x48). Cette menace n’est pas immédiatement effective car après (1822), les blancs disposent du collage 16-11. Mais après par exemple 38. 37-31 (7-11) 39. 16x7 (12x1) la menace serait alors bien réelle. 40. 32x23 43. 34x23 46. 37-32 49. 40-34"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "18x29 9-13 25-30 17-22"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "38. 43-38 41. 34x23 44. 38-33 47. 32-27 50. 34x25"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "20-24 13-18 13-18 29-33 22x31 N+"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "39. 28-23 42. 39-34 45. 33-28 48. 28x39"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "19x28 18x29 18x29 12-18"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "L’analyse qui suit provient de l’ancienne revue belge « Blancs et Noirs », et elle est extraite d’une chronique sur la théorie du jeu rédigée par l’ex champion soviétique Vladimir Kaplan : Kaplan – Kiriev ½ finale championnat URSS 1973 Après avoir concentré d’importantes forces sur l’aile droite, les blancs ont occupé l’importante case 29 : 1. 34-29"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "23x34"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "2. 40x29"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "A présent, les noirs peuvent évidemment riposter en occupant la case 24 par (19-24), mais dans ce cas, après 39-34, ils seront confrontés à une forte pression sur leur aile gauche. La formation éventuelle par (14-20) suivi de (19-24) serait efficace. Les blancs qui n’ont pas de pion en 35 auront les moyens d’occuper la case clé 23 au bon moment. 2…"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "12-18"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "3. 41-37"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "Le coup opportun qui empêche les noirs d’occuper la case 22 par (17-22) en raison de 37-31 suivi de 32-27 avec une position désagréable pour les noirs. 3…"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "19-23"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "4. 44-40"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "A noter que 39-34 est interdit par (18-22) 29x27 (17-21) 26x17 (11x42) 4…"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "23x34"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "5. 40x29"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "14-19"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "6. 45-40"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "19-23 ?"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "7. 40-35 !"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "23x34"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "8. 39x30"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "Les blancs renforcent ainsi la pression sur l’aile droite. 8…"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "15-20"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "Ce coup facilite le jeu des blancs. Les noirs auraient sans doute mieux fait d’avancer à 22. 9. 37-31"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "18-23"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "10. 43-39"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "13-19"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "11. 46-41"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "20-24"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "Les noirs sont parvenus à occuper les cases centrales 23 et 24, mais ceci n’est que provisoire. 12. 41-37"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "2-7 ?!"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "Il était plus rationnel de consolider les pions centraux par (9-14) et (4-10), empêchant ainsi les blancs de reconquérir la case 29. 13. 47-42 16. 33-29 !"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "7-12 24x33"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "14. 39-34 17. 38x29"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "12-18"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "15. 31-27"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "8-12"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "En occupant à nouveau la case 29, les blancs obtiennent une grande liberté d’action sur leur aile droite. 17…"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "9-13"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "18. 49-43"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "3-8"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "19. 30-25"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "4-9 ?"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "Une faute sérieuse. Les noirs auraient dû se dégager par (19-24), (23-28) et (17-21). 20. 37-31 17-22 23. 35-30 14-20 26. 38-33 etc. B+"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "21. 42-37 24. 25x14"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "11-17 19x10"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "22. 43-38 25. 30-24"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "9-14 10-14"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "Vadim Virny – Vladimir Kolesnik Cht URSS 1983 43e temps – trait aux noirs La position suivante est très intéressante d’un point de vue théorique. Les noirs se dégagent ici par : 43…"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "14-20"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "44. 25x14"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "24-29"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "45. 33x24"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "23-28"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "46. 32x23"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "18x9"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "47. 27x18"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "12x23"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "Après ce dégagement classique, la position est alors la suivante :"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "Les noirs se retrouvent en mauvaise posture avec leur formation 6-11-16-17 inutile face à une formation de contrôle 26-31-36-37. 48. 37-32 ?! Un coup spéculatif. 48…"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "9-14 ?"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "Les noirs ont ici les moyens d’équilibrer le jeu en osant le coup peu orthodoxe 48… (16-21) ! car après 49. 31-27 (11-16) ! 50. 3833 (7-11) 51. 36-31 [l’attaque 33-28 livre le coup Philippe (17-22) 27x29 (9-14) 26x17 (11x35)] (23-28) ! etc.= 49. 32-27 ! 51. 38-33 53. 33x22"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "14-19 16-21 17x28"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "50. 39-34 19-24 52. 27x16 23-28 54. 31-27 etc. B+"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "Je vous recommande également pour analyse personnelle la partie Shchegolev-Getmanski jouée lors du tournoi sur invitation à Doorwerth en 2007 : https://toernooibase.kndb.nl/opvraag/applet.php?kl=23&Id=308&r=7&jr=7&wed=51106&view="
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "2 - Le pion 26 désavantageux Le pion de bande 25 (pour les noirs) est dans certains cas un pion de bande faible lorsqu’il est associé à 1 pion central 23."
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "Dans cette position, on voit bien que la formation 34-35-40-45 permet de menacer directement le pion central adverse. On remarque cependant que cette formation mobilise 4 pions, et qu’en dehors de la pression qu’elle permet sur le pion 23, elle n’est pas d’une grande utilité."
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "Dans la position suivante, les blancs isolent le pion central adverse en jouant : 1. 27-22 !"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "18x27"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "2. 31x22"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "16-21"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "Un coup forcé car (6-11), (7-11), ou (8-12) livre un coup Philippe presque direct par 27-21 ou 27-22, suivi de 34-30 (25x34) 40x27. 3. 33-29 Et les noirs n’ont plus les moyens de défendre leur pion 23."
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "Dans cette position, la présence d’un pion à 24 nécessite la formation 33-38-42 pour menacer le pion 23. Les blancs commencent par isoler le pion central adverse en jouant : 1. 27-22 !"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "18x27"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "2. 31x22"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "11-16"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "Une astucieuse défense qui empêche 34-30 ou 33-29 en raison du coup de dame à 48 par (25-30) ou (24-30) selon le cas. 3. 33-28 5. 22-18 !"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "8-13 13x33"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "4. 36-31 6. 38x18"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "Avec un avantage positionnel gagnant."
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "7-11"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "La position suivante prolonge l’idée des deux précédents diagrammes avec une possibilité tactique très usuelle : 1. 27-22"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "21-26"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "2. 34-30 !"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "25x34"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "3. 40x18"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "8-12"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "4. 45-40"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "12x23"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "5. 40-34"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "20-25"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "6. 33-29"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "7-11"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "7. 29x18"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "11-17"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "8. 22x11"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "16x7"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "9. 38-33"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "13x22"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "10. 37-31 !"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "26x30"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "11. 35x4 +"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "Dans la partie qui suit, la manière assez insolite avec laquelle les blancs exploitent la faiblesse combinée des pions 23 et 25, est très remarquable : Andris Andreiko – Walis Zwirboelis (Cht URSS 1968) 1. 32-28 4. 43-38 7. 42x31 10. 46-41 13. 41-36"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "18-23 17-21 20-24 5-10 2-7 diagramme"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "2. 38-32 5.37-31 8. 47-42 11. 31-26"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "12-18 21-26 14-20 20-25"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "3. 31-27 6. 49-43 9. 41-37 12. 36-31"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "14. 27-22"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "18x27"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "15. 31x22"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "7-12 26x37 10-14 15-20"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "Par cet échange, les blancs entament une action contre le pion 23 en s’appuyant sur le pion 25. 15… 12-18 16. 37-31 18x27 17. 31x22 8-12 18. 22-18 ! 13x22 19. 28x8 3x12 20. 33-29 24x33 21. 38x18 12x23 22. 32-27 ! Sur 39-33, les noirs se dégagent par (23-28) car la prise 33x22 livre un coup de dame par (25-30) 35x15 (14-20) 15x13 (9x47). 22… 11-17 23. 42-37 7-11 24. 37-31 diag. Suivant"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "24…"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "20-24"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "Sur (10-15), suit 27-22 (17x28) 26-21 (16x27) 31x33 et la menace 34-30 (25x34) 40x18 est imparable. 25. 34-30 ! 27. 44-40 ! 29. 50-44"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "25x34 1-7 19-24"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "26. 40x20 28. 39-34 30. 44-39"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "14x25 10-14"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "Les noirs doivent à présent se résigner à perdre un pion. En partie, ils ont joué : 30… 32. 26-21"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "24-29 16x27"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "31. 27-22 17x28 33. 31x24 etc. B+"
}
]
},
{
"type": "board",
"id": "int_sdj_pions_cles_l3_dia0",
"ch": 3
},
{
"type": "board",
"id": "int_sdj_pions_cles_l3_dia1",
"ch": 3
},
{
"type": "board",
"id": "int_sdj_pions_cles_l3_dia2",
"ch": 3
},
{
"type": "board",
"id": "int_sdj_pions_cles_l3_dia3",
"ch": 3
},
{
"type": "board",
"id": "int_sdj_pions_cles_l3_dia4",
"ch": 3
},
{
"type": "board",
"id": "int_sdj_pions_cles_l3_dia5",
"ch": 3
},
{
"type": "board",
"id": "int_sdj_pions_cles_l3_dia6",
"ch": 3
},
{
"type": "board",
"id": "int_sdj_pions_cles_l3_dia7",
"ch": 3
},
{
"type": "board",
"id": "int_sdj_pions_cles_l3_dia8",
"ch": 3
},
{
"type": "board",
"id": "int_sdj_pions_cles_l3_dia9",
"ch": 3
},
{
"type": "board",
"id": "int_sdj_pions_cles_l3_dia10",
"ch": 3
},
{
"type": "board",
"id": "int_sdj_pions_cles_l3_dia11",
"ch": 3
},
{
"type": "board",
"id": "int_sdj_pions_cles_l3_dia12",
"ch": 3
},
{
"type": "board",
"id": "int_sdj_pions_cles_l3_dia13",
"ch": 3
},
{
"type": "board",
"id": "int_sdj_pions_cles_l3_ex0",
"ch": 3
},
{
"type": "board",
"id": "int_sdj_pions_cles_l3_ex1",
"ch": 3
},
{
"type": "board",
"id": "int_sdj_pions_cles_l3_ex2",
"ch": 3
},
{
"type": "board",
"id": "int_sdj_pions_cles_l3_ex3",
"ch": 3
},
{
"type": "board",
"id": "int_sdj_pions_cles_l3_ex4",
"ch": 3
}
],
"positions": {
"int_sdj_pions_cles_l1_dia0": {
"id": "int_sdj_pions_cles_l1_dia0",
"ch": 1,
"title": "1 – En système classique",
"start": {
"wm": [
27,
28,
30,
31,
32,
33,
35,
36,
38,
39,
40,
42,
43,
45,
48,
49
],
"wk": [],
"bm": [
1,
3,
6,
7,
8,
9,
11,
12,
13,
14,
15,
16,
18,
19,
23,
24
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "1 – En système classique"
},
"int_sdj_pions_cles_l1_dia1": {
"id": "int_sdj_pions_cles_l1_dia1",
"ch": 1,
"title": "Trait aux noirs",
"start": {
"wm": [
27,
28,
30,
31,
32,
33,
35,
36,
38,
39,
40,
42,
43,
45,
48,
49
],
"wk": [],
"bm": [
2,
3,
6,
7,
8,
9,
11,
12,
13,
14,
15,
16,
18,
19,
23,
24
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Trait aux noirs"
},
"int_sdj_pions_cles_l1_dia2": {
"id": "int_sdj_pions_cles_l1_dia2",
"ch": 1,
"title": "Trait aux noirs",
"start": {
"wm": [
25,
27,
28,
31,
32,
33,
35,
36,
37,
38,
39,
40,
42,
43,
45,
48,
49
],
"wk": [],
"bm": [
1,
3,
6,
7,
8,
9,
11,
12,
13,
14,
15,
16,
18,
19,
23,
24,
26
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Trait aux noirs"
},
"int_sdj_pions_cles_l1_dia3": {
"id": "int_sdj_pions_cles_l1_dia3",
"ch": 1,
"title": "Trait aux noirs",
"start": {
"wm": [
25,
27,
28,
31,
32,
33,
35,
36,
37,
38,
39,
40,
42,
43,
45,
48,
49
],
"wk": [],
"bm": [
2,
3,
6,
7,
8,
9,
11,
12,
13,
14,
15,
16,
18,
19,
23,
24,
26
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Trait aux noirs"
},
"int_sdj_pions_cles_l1_dia4": {
"id": "int_sdj_pions_cles_l1_dia4",
"ch": 1,
"title": "Trait aux blancs",
"start": {
"wm": [
27,
28,
32,
33,
34,
35,
37,
38,
39,
45,
49
],
"wk": [],
"bm": [
3,
13,
15,
16,
18,
19,
20,
21,
23,
24,
26
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Trait aux blancs"
},
"int_sdj_pions_cles_l1_dia5": {
"id": "int_sdj_pions_cles_l1_dia5",
"ch": 1,
"title": "Trait aux blancs",
"start": {
"wm": [
27,
28,
32,
33,
34,
35,
37,
38,
39,
45,
50
],
"wk": [],
"bm": [
3,
13,
15,
16,
18,
19,
20,
21,
23,
24,
26
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Trait aux blancs"
},
"int_sdj_pions_cles_l1_dia6": {
"id": "int_sdj_pions_cles_l1_dia6",
"ch": 1,
"title": "Trait aux blancs",
"start": {
"wm": [
1,
3,
4,
5,
7,
10,
11,
12,
13,
14,
15,
16,
17,
18,
19,
20,
21,
22,
23,
24,
25,
26,
27,
28,
29,
30,
31,
32,
33,
34,
35,
39,
40,
41,
43,
44,
50
],
"wk": [],
"bm": [],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Trait aux blancs"
},
"int_sdj_pions_cles_l1_dia7": {
"id": "int_sdj_pions_cles_l1_dia7",
"ch": 1,
"title": "Trait aux blancs",
"start": {
"wm": [
1,
3,
4,
5,
7,
8,
9,
11,
12,
13,
14,
15,
16,
17,
18,
19,
20,
21,
22,
23,
24,
25,
26,
27,
28,
29,
30,
31,
32,
33,
34,
35,
36,
37,
38,
39,
40,
42,
43,
44,
45,
46,
47,
48,
49,
50
],
"wk": [],
"bm": [],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Trait aux blancs"
},
"int_sdj_pions_cles_l1_dia8": {
"id": "int_sdj_pions_cles_l1_dia8",
"ch": 1,
"title": "Diag. 9",
"start": {
"wm": [
24,
26,
29,
31,
33,
34,
36,
38,
39,
43,
44,
45,
49
],
"wk": [],
"bm": [
3,
6,
9,
12,
13,
15,
16,
17,
18,
20,
22,
25,
27
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Diag. 9"
},
"int_sdj_pions_cles_l1_dia9": {
"id": "int_sdj_pions_cles_l1_dia9",
"ch": 1,
"title": "Diag. 10",
"start": {
"wm": [
24,
26,
29,
31,
33,
36,
37,
42,
43,
45,
47,
49
],
"wk": [],
"bm": [
3,
6,
7,
11,
12,
13,
14,
15,
17,
18,
22,
27
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Diag. 10"
},
"int_sdj_pions_cles_l1_dia10": {
"id": "int_sdj_pions_cles_l1_dia10",
"ch": 1,
"title": "Trait aux noirs",
"start": {
"wm": [
50
],
"wk": [],
"bm": [
35
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Trait aux noirs"
},
"int_sdj_pions_cles_l1_dia11": {
"id": "int_sdj_pions_cles_l1_dia11",
"ch": 1,
"title": "Meilleur est 31-26",
"start": {
"wm": [
26,
27,
33,
34,
39,
50
],
"wk": [],
"bm": [
7,
13,
24,
25,
30,
35
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Meilleur est 31-26"
},
"int_sdj_pions_cles_l1_dia12": {
"id": "int_sdj_pions_cles_l1_dia12",
"ch": 1,
"title": "Trait aux blancs",
"start": {
"wm": [
21,
27,
28,
31,
32,
33,
34,
38,
39,
50
],
"wk": [],
"bm": [
6,
7,
8,
9,
13,
19,
23,
24,
25,
35
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Trait aux blancs"
},
"int_sdj_pions_cles_l1_dia13": {
"id": "int_sdj_pions_cles_l1_dia13",
"ch": 1,
"title": "Diag. 14",
"start": {
"wm": [
26,
27,
28,
32,
33,
34,
38,
39,
50
],
"wk": [],
"bm": [
1,
8,
13,
18,
19,
23,
24,
25,
35
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Diag. 14"
},
"int_sdj_pions_cles_l1_ex0": {
"id": "int_sdj_pions_cles_l1_ex0",
"ch": 1,
"title": "LES PIONS 49 ET 50 – D1",
"start": {
"wm": [
22,
27,
28,
32,
33,
34,
35,
37,
38,
40,
45,
49
],
"wk": [],
"bm": [
3,
8,
13,
15,
16,
19,
21,
23,
24,
25,
26,
29
],
"bk": [],
"turn": "black"
},
"moves": [
{
"n": "15-20",
"f": 15,
"t": 20,
"c": [],
"path": [
15,
20
],
"p": false
}
],
"theme": "sdj_ch115",
"pub": "15-20 33x13 9x18 28x19 18-23 19x28 7-11 16x18 17-22 28x17",
"win": "black"
},
"int_sdj_pions_cles_l1_ex1": {
"id": "int_sdj_pions_cles_l1_ex1",
"ch": 1,
"title": "LES PIONS 49 ET 50 – D2",
"start": {
"wm": [
16,
27,
28,
32,
33,
36,
37,
38,
39,
45,
48
],
"wk": [],
"bm": [
1,
2,
4,
7,
8,
9,
12,
17,
19,
23,
24
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "27-22",
"f": 27,
"t": 22,
"c": [],
"path": [
27,
22
],
"p": false
}
],
"theme": "sdj_ch115",
"pub": "27-22 25x34 22-17 21x12 35-30 24x44 33x24 19x30 49x7",
"win": "white"
},
"int_sdj_pions_cles_l1_ex2": {
"id": "int_sdj_pions_cles_l1_ex2",
"ch": 1,
"title": "LES PIONS 49 ET 50 – D3",
"start": {
"wm": [
27,
30,
32,
33,
34,
35,
37,
39,
42,
43,
46,
47,
48,
49
],
"wk": [],
"bm": [
2,
5,
6,
8,
12,
13,
15,
16,
18,
19,
21,
23,
24,
26
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "37-31",
"f": 37,
"t": 31,
"c": [],
"path": [
37,
31
],
"p": false
}
],
"theme": "sdj_ch115",
"pub": "37-31 32-27 21x32 43-38 32x34 33-28 22x33 44-39 34x43 49x7",
"win": "white"
},
"int_sdj_pions_cles_l1_ex3": {
"id": "int_sdj_pions_cles_l1_ex3",
"ch": 1,
"title": "LES PIONS 49 ET 50 – D4",
"start": {
"wm": [
25,
26,
31,
32,
33,
36,
39,
43,
44,
46,
49
],
"wk": [],
"bm": [
8,
12,
13,
14,
16,
17,
19,
20,
21,
22,
23
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "32-27",
"f": 32,
"t": 27,
"c": [],
"path": [
32,
27
],
"p": false
}
],
"theme": "sdj_ch115",
"pub": "32-27 26x28 33x22 21x32 39-33 18x27 33-29 24x33 43-38 32x43",
"win": "white"
},
"int_sdj_pions_cles_l1_ex4": {
"id": "int_sdj_pions_cles_l1_ex4",
"ch": 1,
"title": "LES PIONS 49 ET 50 – D5",
"start": {
"wm": [
27,
32,
33,
34,
36,
37,
39,
42,
48,
49,
50
],
"wk": [],
"bm": [
3,
6,
9,
10,
12,
13,
16,
21,
23,
26,
35
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "34-29",
"f": 34,
"t": 29,
"c": [],
"path": [
34,
29
],
"p": false
}
],
"theme": "sdj_ch115",
"pub": "34-29 23x34 28-23 19x26 44-40 35x44 50x6",
"win": "white"
},
"int_sdj_pions_cles_l1_ex5": {
"id": "int_sdj_pions_cles_l1_ex5",
"ch": 1,
"title": "LES PIONS 49 ET 50 – D6",
"start": {
"wm": [
25,
27,
28,
31,
32,
33,
34,
36,
38,
42,
44,
45,
48,
49,
50
],
"wk": [],
"bm": [
1,
2,
3,
9,
11,
12,
13,
14,
15,
16,
18,
19,
23,
24,
35
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "34-29",
"f": 34,
"t": 29,
"c": [],
"path": [
34,
29
],
"p": false
}
],
"theme": "sdj_ch115",
"pub": "34-29 26x28 33x22 21x32 22-18 13x22 34-29 23x43 49x7",
"win": "white"
},
"int_sdj_pions_cles_l2_dia0": {
"id": "int_sdj_pions_cles_l2_dia0",
"ch": 2,
"title": "Trait aux noirs",
"start": {
"wm": [
27,
28,
32,
34,
35,
36,
37,
48
],
"wk": [],
"bm": [
3,
16,
18,
19,
21,
23,
24,
26
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Trait aux noirs"
},
"int_sdj_pions_cles_l2_dia1": {
"id": "int_sdj_pions_cles_l2_dia1",
"ch": 2,
"title": "Trait aux blancs",
"start": {
"wm": [
25,
27,
28,
32,
34,
35,
36,
37,
38
],
"wk": [],
"bm": [
12,
13,
14,
16,
19,
21,
23,
24,
26
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Trait aux blancs"
},
"int_sdj_pions_cles_l2_dia2": {
"id": "int_sdj_pions_cles_l2_dia2",
"ch": 2,
"title": "Trait aux noirs",
"start": {
"wm": [
27,
28,
30,
32,
33,
34,
35,
36,
37,
38
],
"wk": [],
"bm": [
7,
8,
13,
14,
16,
18,
19,
23,
24,
26
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Trait aux noirs"
},
"int_sdj_pions_cles_l2_dia3": {
"id": "int_sdj_pions_cles_l2_dia3",
"ch": 2,
"title": "Graaskamp - Sipma (Salou 2017)",
"start": {
"wm": [
26,
27,
36,
38,
39,
45,
49
],
"wk": [],
"bm": [
1,
13,
14,
16,
17,
20,
23
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Graaskamp - Sipma (Salou 2017)"
},
"int_sdj_pions_cles_l2_dia4": {
"id": "int_sdj_pions_cles_l2_dia4",
"ch": 2,
"title": "Viacheslav Shchegolev – Andries Andreiko",
"start": {
"wm": [
27,
28,
32,
33,
34,
37,
38,
39,
45
],
"wk": [],
"bm": [
13,
15,
16,
17,
18,
21,
24,
25,
26
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Viacheslav Shchegolev – Andries Andreiko"
},
"int_sdj_pions_cles_l2_dia5": {
"id": "int_sdj_pions_cles_l2_dia5",
"ch": 2,
"title": "match départage cht URSS 1964",
"start": {
"wm": [
27,
28,
30,
32,
35,
36,
37,
38,
39,
43
],
"wk": [],
"bm": [
12,
13,
14,
16,
17,
18,
19,
23,
24,
26
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "match départage cht URSS 1964"
},
"int_sdj_pions_cles_l2_dia6": {
"id": "int_sdj_pions_cles_l2_dia6",
"ch": 2,
"title": "Iser Kouperman – A. Winderman",
"start": {
"wm": [
25,
27,
28,
32,
33,
35,
36,
37,
38,
39
],
"wk": [],
"bm": [
13,
14,
15,
16,
17,
19,
21,
23,
24,
26
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Iser Kouperman – A. Winderman"
},
"int_sdj_pions_cles_l2_dia7": {
"id": "int_sdj_pions_cles_l2_dia7",
"ch": 2,
"title": "Championnat URSS 1954",
"start": {
"wm": [
25,
27,
28,
32,
36,
37,
38,
40,
48
],
"wk": [],
"bm": [
13,
14,
16,
17,
18,
19,
23,
24,
26
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Championnat URSS 1954"
},
"int_sdj_pions_cles_l2_dia8": {
"id": "int_sdj_pions_cles_l2_dia8",
"ch": 2,
"title": "Vladimir Kaplan – Sergeï Mansjien",
"start": {
"wm": [
25,
27,
28,
32,
35,
36,
37,
38,
39,
40
],
"wk": [],
"bm": [
3,
13,
14,
16,
17,
18,
19,
23,
24,
26
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Vladimir Kaplan – Sergeï Mansjien"
},
"int_sdj_pions_cles_l2_dia9": {
"id": "int_sdj_pions_cles_l2_dia9",
"ch": 2,
"title": "Championnat URSS 1964",
"start": {
"wm": [
25,
27,
28,
32,
33,
35,
36,
37,
38,
39
],
"wk": [],
"bm": [
8,
11,
12,
13,
14,
16,
19,
23,
24,
26
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Championnat URSS 1964"
},
"int_sdj_pions_cles_l2_ex0": {
"id": "int_sdj_pions_cles_l2_ex0",
"ch": 2,
"title": "LE PION BLANC 36 – D1",
"start": {
"wm": [
26,
32,
33,
34,
35,
36,
37,
38,
40,
42,
43,
44,
45,
48
],
"wk": [],
"bm": [
3,
4,
5,
6,
8,
9,
10,
11,
13,
15,
17,
21,
22,
23
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "33-28",
"f": 33,
"t": 28,
"c": [],
"path": [
33,
28
],
"p": false
}
],
"theme": "sdj_ch116",
"pub": "33-28 13x22 28x17 33-29 24x31 36x7",
"win": "white"
},
"int_sdj_pions_cles_l2_ex1": {
"id": "int_sdj_pions_cles_l2_ex1",
"ch": 2,
"title": "LE PION BLANC 36 – D2",
"start": {
"wm": [
22,
28,
32,
33,
35,
36,
37,
38,
39,
48
],
"wk": [],
"bm": [
3,
6,
8,
11,
12,
13,
19,
23,
24,
25
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "22-18",
"f": 22,
"t": 18,
"c": [],
"path": [
22,
18
],
"p": false
}
],
"theme": "sdj_ch116",
"pub": "22-18 22x33 38x18 13x22 32-28 22x33 42-38 33x31 36x7",
"win": "white"
},
"int_sdj_pions_cles_l2_ex2": {
"id": "int_sdj_pions_cles_l2_ex2",
"ch": 2,
"title": "LE PION BLANC 36 – D3",
"start": {
"wm": [
28,
29,
31,
33,
35,
36,
37,
38,
43,
45,
48
],
"wk": [],
"bm": [
11,
12,
13,
15,
17,
18,
19,
20,
21,
22,
25
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "29-23",
"f": 29,
"t": 23,
"c": [],
"path": [
29,
23
],
"p": false
}
],
"theme": "sdj_ch116",
"pub": "29-23 26x37 32x41 23x21 33-29 24x42 41-37 42x31 36x7",
"win": "white"
},
"int_sdj_pions_cles_l2_ex3": {
"id": "int_sdj_pions_cles_l2_ex3",
"ch": 2,
"title": "LE PION BLANC 36 – D4",
"start": {
"wm": [
27,
28,
32,
33,
34,
35,
36,
37,
38,
43
],
"wk": [],
"bm": [
11,
13,
14,
15,
17,
18,
19,
23,
24,
26
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "37-31",
"f": 37,
"t": 31,
"c": [],
"path": [
37,
31
],
"p": false
}
],
"theme": "sdj_ch116",
"pub": "37-31 18x29 33x24 22x42 31-26 19x30 35x24 20x29 43-39 42x31",
"win": "white"
},
"int_sdj_pions_cles_l2_ex4": {
"id": "int_sdj_pions_cles_l2_ex4",
"ch": 2,
"title": "LE PION BLANC 36 – D5",
"start": {
"wm": [
28,
29,
32,
33,
34,
35,
36,
37,
38,
40,
48
],
"wk": [],
"bm": [
11,
12,
13,
14,
15,
17,
18,
19,
20,
21,
22
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "28-23",
"f": 28,
"t": 23,
"c": [],
"path": [
28,
23
],
"p": false
}
],
"theme": "sdj_ch116",
"pub": "28-23 19x39 49-43 39x48 29-23 18x29 31-26 48x31 36x9",
"win": "white"
},
"int_sdj_pions_cles_l2_ex5": {
"id": "int_sdj_pions_cles_l2_ex5",
"ch": 2,
"title": "LE PION BLANC 36 – D6",
"start": {
"wm": [
28,
29,
31,
33,
35,
36,
37,
38,
45,
49
],
"wk": [],
"bm": [
11,
12,
13,
15,
17,
18,
19,
20,
21,
22
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "29-23",
"f": 29,
"t": 23,
"c": [],
"path": [
29,
23
],
"p": false
},
{
"n": "18x29",
"f": 18,
"t": 29,
"c": [
23
],
"path": [
18,
29
],
"p": false
},
{
"n": "33x24",
"f": 33,
"t": 24,
"c": [
29
],
"path": [
33,
24
],
"p": false
}
],
"theme": "sdj_ch116",
"pub": "29-23 18x29 33x24 22x31 36x9 19x39 9-3",
"win": "white"
},
"int_sdj_pions_cles_l3_dia0": {
"id": "int_sdj_pions_cles_l3_dia0",
"ch": 3,
"title": "Trait aux noirs",
"start": {
"wm": [
26,
32,
33,
36,
37,
38
],
"wk": [],
"bm": [
6,
8,
11,
12,
16,
17
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Trait aux noirs"
},
"int_sdj_pions_cles_l3_dia1": {
"id": "int_sdj_pions_cles_l3_dia1",
"ch": 3,
"title": "Trait aux blancs",
"start": {
"wm": [
25,
26,
28,
31,
32,
33,
35,
36,
38,
42,
43
],
"wk": [],
"bm": [
6,
8,
11,
12,
13,
14,
16,
17,
18,
19,
24
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Trait aux blancs"
},
"int_sdj_pions_cles_l3_dia2": {
"id": "int_sdj_pions_cles_l3_dia2",
"ch": 3,
"title": "Guntis Valneris – Ove Verdel",
"start": {
"wm": [
25,
26,
31,
32,
33,
36,
38,
40,
43,
45,
47,
48
],
"wk": [],
"bm": [
3,
6,
8,
11,
12,
13,
14,
15,
16,
17,
19,
23
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Guntis Valneris – Ove Verdel"
},
"int_sdj_pions_cles_l3_dia3": {
"id": "int_sdj_pions_cles_l3_dia3",
"ch": 3,
"title": "Etc. B+",
"start": {
"wm": [
26,
31,
32,
33,
34,
36,
38,
42,
45,
48
],
"wk": [],
"bm": [
6,
8,
11,
12,
13,
14,
16,
17,
19,
24
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Etc. B+"
},
"int_sdj_pions_cles_l3_dia4": {
"id": "int_sdj_pions_cles_l3_dia4",
"ch": 3,
"title": "Leonid Kats – Andris Andreiko",
"start": {
"wm": [
16,
28,
32,
34,
35,
37,
39,
40,
43,
45
],
"wk": [],
"bm": [
7,
9,
12,
13,
14,
15,
17,
18,
19,
25
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Leonid Kats – Andris Andreiko"
},
"int_sdj_pions_cles_l3_dia5": {
"id": "int_sdj_pions_cles_l3_dia5",
"ch": 3,
"title": "Cht URSS 1965",
"start": {
"wm": [
26,
32,
33,
34,
36,
38,
39,
40,
41,
43,
44,
45,
46,
47,
49
],
"wk": [],
"bm": [
2,
3,
4,
6,
8,
9,
11,
12,
13,
14,
15,
16,
17,
19,
23
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Cht URSS 1965"
},
"int_sdj_pions_cles_l3_dia6": {
"id": "int_sdj_pions_cles_l3_dia6",
"ch": 3,
"title": "26. 38-33 etc. B+",
"start": {
"wm": [
25,
26,
27,
31,
32,
33,
36,
37,
38,
39,
40
],
"wk": [],
"bm": [
6,
7,
11,
12,
14,
16,
17,
18,
22,
23,
24
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "26. 38-33 etc. B+"
},
"int_sdj_pions_cles_l3_dia7": {
"id": "int_sdj_pions_cles_l3_dia7",
"ch": 3,
"title": "Vadim Virny – Vladimir Kolesnik",
"start": {
"wm": [
26,
31,
36,
37,
38,
39,
40
],
"wk": [],
"bm": [
6,
7,
9,
11,
16,
17,
23
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Vadim Virny – Vladimir Kolesnik"
},
"int_sdj_pions_cles_l3_dia8": {
"id": "int_sdj_pions_cles_l3_dia8",
"ch": 3,
"title": "Diag. 9",
"start": {
"wm": [
34,
35,
40,
45
],
"wk": [],
"bm": [
23,
25
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Diag. 9"
},
"int_sdj_pions_cles_l3_dia9": {
"id": "int_sdj_pions_cles_l3_dia9",
"ch": 3,
"title": "Diag. 10",
"start": {
"wm": [
27,
31,
32,
33,
34,
35,
36,
38,
40,
45
],
"wk": [],
"bm": [
6,
7,
8,
9,
13,
16,
18,
19,
23,
25
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Diag. 10"
},
"int_sdj_pions_cles_l3_dia10": {
"id": "int_sdj_pions_cles_l3_dia10",
"ch": 3,
"title": "Diag. 11",
"start": {
"wm": [
27,
31,
32,
33,
34,
35,
36,
38,
40,
42,
45
],
"wk": [],
"bm": [
6,
7,
8,
9,
11,
15,
18,
19,
23,
24,
25
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Diag. 11"
},
"int_sdj_pions_cles_l3_dia11": {
"id": "int_sdj_pions_cles_l3_dia11",
"ch": 3,
"title": "11. 35x4 +",
"start": {
"wm": [
27,
32,
33,
34,
35,
37,
38,
40,
42,
45
],
"wk": [],
"bm": [
7,
8,
9,
13,
16,
19,
20,
21,
23,
25
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "11. 35x4 +"
},
"int_sdj_pions_cles_l3_dia12": {
"id": "int_sdj_pions_cles_l3_dia12",
"ch": 3,
"title": "24. 37-31 diag. Suivant",
"start": {
"wm": [
26,
27,
28,
31,
32,
33,
34,
35,
36,
37,
38,
39,
40,
42,
43,
44,
45,
48,
50
],
"wk": [],
"bm": [
1,
3,
4,
6,
7,
8,
9,
10,
11,
12,
13,
14,
16,
18,
19,
20,
23,
24,
25
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "24. 37-31 diag. Suivant"
},
"int_sdj_pions_cles_l3_dia13": {
"id": "int_sdj_pions_cles_l3_dia13",
"ch": 3,
"title": "Diag. 14",
"start": {
"wm": [
26,
27,
31,
34,
35,
36,
39,
40,
43,
44,
45,
48,
50
],
"wk": [],
"bm": [
1,
4,
6,
9,
10,
11,
14,
16,
17,
19,
20,
23,
25
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Diag. 14"
},
"int_sdj_pions_cles_l3_ex0": {
"id": "int_sdj_pions_cles_l3_ex0",
"ch": 3,
"title": "LE PION DE BANDE 26 – D1",
"start": {
"wm": [
25,
26,
28,
32,
35,
36,
37,
38,
39,
42,
44,
45
],
"wk": [],
"bm": [
3,
6,
9,
11,
13,
14,
16,
17,
18,
19,
23,
24
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "39-34",
"f": 39,
"t": 34,
"c": [],
"path": [
39,
34
],
"p": false
}
],
"theme": "sdj_ch117",
"pub": "39-34 18x27 33-29 24x22 35-30 25x34 40x20 15x24 32-28 22x33",
"win": "white"
},
"int_sdj_pions_cles_l3_ex1": {
"id": "int_sdj_pions_cles_l3_ex1",
"ch": 3,
"title": "LE PION DE BANDE 26 – D2",
"start": {
"wm": [
27,
28,
32,
33,
35,
37,
38,
40,
42,
43,
45,
48
],
"wk": [],
"bm": [
12,
13,
14,
15,
16,
17,
18,
19,
21,
23,
24,
25
],
"bk": [],
"turn": "black"
},
"moves": [
{
"n": "23-29",
"f": 23,
"t": 29,
"c": [],
"path": [
23,
29
],
"p": false
}
],
"theme": "sdj_ch117",
"pub": "23-29 26x17 11x33 38x20 19-24 20x29 23x43",
"win": "black"
},
"int_sdj_pions_cles_l3_ex2": {
"id": "int_sdj_pions_cles_l3_ex2",
"ch": 3,
"title": "LE PION DE BANDE 26 – D3",
"start": {
"wm": [
27,
32,
33,
34,
35,
37,
38,
39,
43,
44,
45,
48
],
"wk": [],
"bm": [
3,
9,
12,
13,
15,
16,
18,
19,
20,
23,
25,
26
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "34-30",
"f": 34,
"t": 30,
"c": [],
"path": [
34,
30
],
"p": false
},
{
"n": "25x34",
"f": 25,
"t": 34,
"c": [
30
],
"path": [
25,
34
],
"p": false
}
],
"theme": "sdj_ch117",
"pub": "34-30 25x34 40x18 13x22 32-28 22-27 43-39 19-24 28-22 27x18",
"win": "white"
},
"int_sdj_pions_cles_l3_ex3": {
"id": "int_sdj_pions_cles_l3_ex3",
"ch": 3,
"title": "LE PION DE BANDE 26 – D4",
"start": {
"wm": [
32,
33,
34,
35,
36,
37,
38,
40,
43,
45
],
"wk": [],
"bm": [
3,
7,
8,
9,
13,
15,
19,
23,
25,
26
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "34-30",
"f": 34,
"t": 30,
"c": [],
"path": [
34,
30
],
"p": false
}
],
"theme": "sdj_ch117",
"pub": "34-30 12-17 27-21 16x27 32x12 18x7 34-30 25x34 40x18 13x22",
"win": "white"
},
"int_sdj_pions_cles_l3_ex4": {
"id": "int_sdj_pions_cles_l3_ex4",
"ch": 3,
"title": "LE PION DE BANDE 26 – D5",
"start": {
"wm": [
27,
28,
32,
34,
35,
36,
37,
38,
39,
40,
43,
45,
47,
48
],
"wk": [],
"bm": [
3,
9,
11,
13,
14,
15,
16,
18,
19,
20,
21,
23,
25,
26
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "39-33",
"f": 39,
"t": 33,
"c": [],
"path": [
39,
33
],
"p": false
},
{
"n": "11-17",
"f": 11,
"t": 17,
"c": [],
"path": [
11,
17
],
"p": false
},
{
"n": "47-42",
"f": 47,
"t": 42,
"c": [],
"path": [
47,
42
],
"p": false
},
{
"n": "20-24",
"f": 20,
"t": 24,
"c": [],
"path": [
20,
24
],
"p": false
},
{
"n": "27-22",
"f": 27,
"t": 22,
"c": [],
"path": [
27,
22
],
"p": false
},
{
"n": "18x27",
"f": 18,
"t": 27,
"c": [
22
],
"path": [
18,
27
],
"p": false
},
{
"n": "37-31",
"f": 37,
"t": 31,
"c": [],
"path": [
37,
31
],
"p": false
},
{
"n": "26x37",
"f": 26,
"t": 37,
"c": [
31
],
"path": [
26,
37
],
"p": false
},
{
"n": "42x11",
"f": 42,
"t": 11,
"c": [
17,
27,
37
],
"path": [
42,
31,
22,
11
],
"p": false
},
{
"n": "16x7",
"f": 16,
"t": 7,
"c": [
11
],
"path": [
16,
7
],
"p": false
}
],
"theme": "sdj_ch117",
"pub": "39-33 11-17 47-42 20-24 27-22 18x27 37-31 26x37 42x11 16x7",
"win": "white"
}
}
}

export default DATA
