// Auto-generated by backend/curriculum/build_parcours_manuels.py — do not edit by hand.
import type { ManuelData } from '../ManuelInteractif'

const DATA: ManuelData = {
"book": "Les fins de partie",
"level": "Avancé",
"chapters": [
{
"n": 0,
"title": "Présentation"
},
{
"n": 1,
"title": "Dame et pions"
},
{
"n": 2,
"title": "Les finales à comité"
},
{
"n": 3,
"title": "Pions contre pions et grande diagonale"
},
{
"n": 4,
"title": "Pratiquez les fins de partie"
}
],
"blocks": [
{
"type": "h1",
"ch": 0,
"runs": [
{
"t": "Les fins de partie"
}
]
},
{
"type": "p",
"ch": 0,
"runs": [
{
"t": "Dame contre pions, finales à comité, la grande diagonale."
}
]
},
{
"type": "p",
"ch": 0,
"runs": [
{
"b": 1,
"t": "Objectif. "
},
{
"t": "Maîtriser les fins de partie à dames : dame contre pions, finales à comité et la traversée de la grande diagonale, positions lues avec détection des dames."
}
]
},
{
"type": "h2",
"ch": 1,
"runs": [
{
"t": "Dame et pions"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "Les finales où une dame lutte contre des pions, ou dame et pions contre dame et pions. Comptez les temps et cherchez le gain ou la nulle."
}
]
},
{
"type": "board",
"id": "av_fins_de_partie_l1_pos0",
"ch": 1
},
{
"type": "board",
"id": "av_fins_de_partie_l1_pos1",
"ch": 1
},
{
"type": "board",
"id": "av_fins_de_partie_l1_pos2",
"ch": 1
},
{
"type": "board",
"id": "av_fins_de_partie_l1_pos3",
"ch": 1
},
{
"type": "board",
"id": "av_fins_de_partie_l1_pos4",
"ch": 1
},
{
"type": "board",
"id": "av_fins_de_partie_l1_pos5",
"ch": 1
},
{
"type": "board",
"id": "av_fins_de_partie_l1_pos6",
"ch": 1
},
{
"type": "board",
"id": "av_fins_de_partie_l1_pos7",
"ch": 1
},
{
"type": "h2",
"ch": 2,
"runs": [
{
"t": "Les finales à comité"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "Les finales dites « à comité », où plusieurs pions se soutiennent face à la dame. Des positions types à jouer sur le damier."
}
]
},
{
"type": "board",
"id": "av_fins_de_partie_l2_pos0",
"ch": 2
},
{
"type": "board",
"id": "av_fins_de_partie_l2_pos1",
"ch": 2
},
{
"type": "board",
"id": "av_fins_de_partie_l2_pos2",
"ch": 2
},
{
"type": "board",
"id": "av_fins_de_partie_l2_pos3",
"ch": 2
},
{
"type": "board",
"id": "av_fins_de_partie_l2_pos4",
"ch": 2
},
{
"type": "board",
"id": "av_fins_de_partie_l2_pos5",
"ch": 2
},
{
"type": "board",
"id": "av_fins_de_partie_l2_pos6",
"ch": 2
},
{
"type": "board",
"id": "av_fins_de_partie_l2_pos7",
"ch": 2
},
{
"type": "h2",
"ch": 3,
"runs": [
{
"t": "Pions contre pions et grande diagonale"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "Les finales de pions et la traversée de la grande diagonale — la ressource décisive quand la dame apparaît."
}
]
},
{
"type": "board",
"id": "av_fins_de_partie_l3_pos0",
"ch": 3
},
{
"type": "board",
"id": "av_fins_de_partie_l3_pos1",
"ch": 3
},
{
"type": "board",
"id": "av_fins_de_partie_l3_pos2",
"ch": 3
},
{
"type": "board",
"id": "av_fins_de_partie_l3_pos3",
"ch": 3
},
{
"type": "board",
"id": "av_fins_de_partie_l3_pos4",
"ch": 3
},
{
"type": "board",
"id": "av_fins_de_partie_l3_pos5",
"ch": 3
},
{
"type": "board",
"id": "av_fins_de_partie_l3_pos6",
"ch": 3
},
{
"type": "board",
"id": "av_fins_de_partie_l3_pos7",
"ch": 3
},
{
"type": "h2",
"ch": 4,
"runs": [
{
"t": "Pratiquez les fins de partie"
}
]
},
{
"type": "p",
"ch": 4,
"runs": [
{
"t": "Les finales du livre à résoudre : trouvez la manœuvre gagnante (ou salvatrice), vérifiée par le moteur."
}
]
},
{
"type": "board",
"id": "av_fins_de_partie_l4_ex0",
"ch": 4
},
{
"type": "board",
"id": "av_fins_de_partie_l4_ex1",
"ch": 4
},
{
"type": "board",
"id": "av_fins_de_partie_l4_ex2",
"ch": 4
},
{
"type": "board",
"id": "av_fins_de_partie_l4_ex3",
"ch": 4
},
{
"type": "board",
"id": "av_fins_de_partie_l4_ex4",
"ch": 4
},
{
"type": "board",
"id": "av_fins_de_partie_l4_ex5",
"ch": 4
},
{
"type": "board",
"id": "av_fins_de_partie_l4_ex6",
"ch": 4
},
{
"type": "board",
"id": "av_fins_de_partie_l4_ex7",
"ch": 4
},
{
"type": "board",
"id": "av_fins_de_partie_l4_ex8",
"ch": 4
},
{
"type": "board",
"id": "av_fins_de_partie_l4_ex9",
"ch": 4
},
{
"type": "board",
"id": "av_fins_de_partie_l4_ex10",
"ch": 4
},
{
"type": "board",
"id": "av_fins_de_partie_l4_ex11",
"ch": 4
},
{
"type": "board",
"id": "av_fins_de_partie_l4_ex12",
"ch": 4
},
{
"type": "board",
"id": "av_fins_de_partie_l4_ex13",
"ch": 4
},
{
"type": "board",
"id": "av_fins_de_partie_l4_ex14",
"ch": 4
},
{
"type": "board",
"id": "av_fins_de_partie_l4_ex15",
"ch": 4
},
{
"type": "board",
"id": "av_fins_de_partie_l4_ex16",
"ch": 4
},
{
"type": "board",
"id": "av_fins_de_partie_l4_ex17",
"ch": 4
},
{
"type": "board",
"id": "av_fins_de_partie_l4_ex18",
"ch": 4
},
{
"type": "board",
"id": "av_fins_de_partie_l4_ex19",
"ch": 4
},
{
"type": "board",
"id": "av_fins_de_partie_l4_ex20",
"ch": 4
},
{
"type": "board",
"id": "av_fins_de_partie_l4_ex21",
"ch": 4
},
{
"type": "board",
"id": "av_fins_de_partie_l4_ex22",
"ch": 4
},
{
"type": "board",
"id": "av_fins_de_partie_l4_ex23",
"ch": 4
},
{
"type": "board",
"id": "av_fins_de_partie_l4_ex24",
"ch": 4
},
{
"type": "board",
"id": "av_fins_de_partie_l4_ex25",
"ch": 4
},
{
"type": "board",
"id": "av_fins_de_partie_l4_ex26",
"ch": 4
},
{
"type": "board",
"id": "av_fins_de_partie_l4_ex27",
"ch": 4
},
{
"type": "board",
"id": "av_fins_de_partie_l4_ex28",
"ch": 4
},
{
"type": "board",
"id": "av_fins_de_partie_l4_ex29",
"ch": 4
},
{
"type": "board",
"id": "av_fins_de_partie_l4_ex30",
"ch": 4
},
{
"type": "board",
"id": "av_fins_de_partie_l4_ex31",
"ch": 4
},
{
"type": "board",
"id": "av_fins_de_partie_l4_ex32",
"ch": 4
},
{
"type": "board",
"id": "av_fins_de_partie_l4_ex33",
"ch": 4
},
{
"type": "board",
"id": "av_fins_de_partie_l4_ex34",
"ch": 4
},
{
"type": "board",
"id": "av_fins_de_partie_l4_ex35",
"ch": 4
},
{
"type": "board",
"id": "av_fins_de_partie_l4_ex36",
"ch": 4
},
{
"type": "board",
"id": "av_fins_de_partie_l4_ex37",
"ch": 4
},
{
"type": "board",
"id": "av_fins_de_partie_l4_ex38",
"ch": 4
},
{
"type": "board",
"id": "av_fins_de_partie_l4_ex39",
"ch": 4
},
{
"type": "board",
"id": "av_fins_de_partie_l4_ex40",
"ch": 4
},
{
"type": "board",
"id": "av_fins_de_partie_l4_ex41",
"ch": 4
},
{
"type": "board",
"id": "av_fins_de_partie_l4_ex42",
"ch": 4
},
{
"type": "board",
"id": "av_fins_de_partie_l4_ex43",
"ch": 4
},
{
"type": "board",
"id": "av_fins_de_partie_l4_ex44",
"ch": 4
},
{
"type": "board",
"id": "av_fins_de_partie_l4_ex45",
"ch": 4
},
{
"type": "board",
"id": "av_fins_de_partie_l4_ex46",
"ch": 4
},
{
"type": "board",
"id": "av_fins_de_partie_l4_ex47",
"ch": 4
},
{
"type": "board",
"id": "av_fins_de_partie_l4_ex48",
"ch": 4
}
],
"positions": {
"av_fins_de_partie_l1_pos0": {
"id": "av_fins_de_partie_l1_pos0",
"ch": 1,
"title": "1 dame contre 2 pions",
"start": {
"wm": [
24,
27
],
"wk": [
41
],
"bm": [
15,
16,
18
],
"bk": [
21
],
"turn": "white"
},
"moves": [
{
"n": "41-36",
"f": 41,
"t": 36,
"c": [],
"path": [
41,
36
],
"p": false
},
{
"n": "21x38x20",
"f": 21,
"t": 20,
"c": [
24,
27
],
"path": [
21,
38,
20
],
"p": false
},
{
"n": "36x9x25",
"f": 36,
"t": 25,
"c": [
18,
20
],
"path": [
36,
9,
25
],
"p": false
}
],
"theme": "1 dame contre 2 pions",
"pub": "41-36 21x38x20 36x9x25",
"win": "white"
},
"av_fins_de_partie_l1_pos1": {
"id": "av_fins_de_partie_l1_pos1",
"ch": 1,
"title": "1 dame contre 2 pions",
"start": {
"wm": [
10,
35
],
"wk": [
36
],
"bm": [
16,
33
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "10-4",
"f": 10,
"t": 4,
"c": [],
"path": [
10,
4
],
"p": true
}
],
"theme": "1 dame contre 2 pions",
"pub": "10-4",
"win": "white"
},
"av_fins_de_partie_l1_pos2": {
"id": "av_fins_de_partie_l1_pos2",
"ch": 1,
"title": "1 dame contre 2 pions",
"start": {
"wm": [
24,
47
],
"wk": [
48
],
"bm": [
7,
15,
21,
38
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "1 dame contre 2 pions"
},
"av_fins_de_partie_l1_pos3": {
"id": "av_fins_de_partie_l1_pos3",
"ch": 1,
"title": "1 dame contre 2 pions",
"start": {
"wm": [
24,
34,
38,
39,
40
],
"wk": [
28
],
"bm": [
15,
25,
26
],
"bk": [
47
],
"turn": "white"
},
"moves": [],
"theme": "1 dame contre 2 pions"
},
"av_fins_de_partie_l1_pos4": {
"id": "av_fins_de_partie_l1_pos4",
"ch": 1,
"title": "1 dame contre 2 pions",
"start": {
"wm": [
25,
37
],
"wk": [
24,
46
],
"bm": [
9,
15,
26
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "37-31",
"f": 37,
"t": 31,
"c": [],
"path": [
37,
31
],
"p": false
},
{
"n": "26x37",
"f": 26,
"t": 37,
"c": [
31
],
"path": [
26,
37
],
"p": false
},
{
"n": "46x14x3",
"f": 46,
"t": 3,
"c": [
9,
37
],
"path": [
46,
14,
3
],
"p": false
},
{
"n": "15-20",
"f": 15,
"t": 20,
"c": [],
"path": [
15,
20
],
"p": false
},
{
"n": "24x15",
"f": 24,
"t": 15,
"c": [
20
],
"path": [
24,
15
],
"p": false
}
],
"theme": "1 dame contre 2 pions",
"pub": "37-31 26x37 46x14x3 15-20 24x15",
"win": "white"
},
"av_fins_de_partie_l1_pos5": {
"id": "av_fins_de_partie_l1_pos5",
"ch": 1,
"title": "1 dame contre 2 pions",
"start": {
"wm": [
39,
45
],
"wk": [
9
],
"bm": [
6,
15,
17,
24,
32,
35
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "1 dame contre 2 pions"
},
"av_fins_de_partie_l1_pos6": {
"id": "av_fins_de_partie_l1_pos6",
"ch": 1,
"title": "1 dame contre 2 pions",
"start": {
"wm": [],
"wk": [
16
],
"bm": [
9,
28
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "1 dame contre 2 pions"
},
"av_fins_de_partie_l1_pos7": {
"id": "av_fins_de_partie_l1_pos7",
"ch": 1,
"title": "1 dame contre 2 pions",
"start": {
"wm": [
42,
47
],
"wk": [
31
],
"bm": [
19,
28,
37
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "1 dame contre 2 pions"
},
"av_fins_de_partie_l2_pos0": {
"id": "av_fins_de_partie_l2_pos0",
"ch": 2,
"title": "les finales de type « comité",
"start": {
"wm": [
19,
23,
38
],
"wk": [],
"bm": [
27
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "19-13",
"f": 19,
"t": 13,
"c": [],
"path": [
19,
13
],
"p": false
},
{
"n": "27-31",
"f": 27,
"t": 31,
"c": [],
"path": [
27,
31
],
"p": false
},
{
"n": "13-8",
"f": 13,
"t": 8,
"c": [],
"path": [
13,
8
],
"p": false
},
{
"n": "31-37",
"f": 31,
"t": 37,
"c": [],
"path": [
31,
37
],
"p": false
},
{
"n": "8-2",
"f": 8,
"t": 2,
"c": [],
"path": [
8,
2
],
"p": true
},
{
"n": "37-41",
"f": 37,
"t": 41,
"c": [],
"path": [
37,
41
],
"p": false
},
{
"n": "38-33",
"f": 38,
"t": 33,
"c": [],
"path": [
38,
33
],
"p": false
},
{
"n": "41-46",
"f": 41,
"t": 46,
"c": [],
"path": [
41,
46
],
"p": true
},
{
"n": "2-19",
"f": 2,
"t": 19,
"c": [],
"path": [
2,
19
],
"p": false
},
{
"n": "46-32",
"f": 46,
"t": 32,
"c": [],
"path": [
46,
32
],
"p": false
},
{
"n": "19-5",
"f": 19,
"t": 5,
"c": [],
"path": [
19,
5
],
"p": false
},
{
"n": "32x19",
"f": 32,
"t": 19,
"c": [
23
],
"path": [
32,
19
],
"p": false
},
{
"n": "5x23",
"f": 5,
"t": 23,
"c": [
19
],
"path": [
5,
23
],
"p": false
}
],
"theme": "les finales de type « comité",
"pub": "19-13 27-31 13-8 31-37 8-2 37-41 38-33 41-46 2-19 46-32 19-5 32x19 5x23",
"win": "white"
},
"av_fins_de_partie_l2_pos1": {
"id": "av_fins_de_partie_l2_pos1",
"ch": 2,
"title": "les finales de type « comité",
"start": {
"wm": [
15,
34
],
"wk": [],
"bm": [
2,
37
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "les finales de type « comité"
},
"av_fins_de_partie_l2_pos2": {
"id": "av_fins_de_partie_l2_pos2",
"ch": 2,
"title": "les finales de type « comité",
"start": {
"wm": [
8,
19,
24
],
"wk": [],
"bm": [
31
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "8-2",
"f": 8,
"t": 2,
"c": [],
"path": [
8,
2
],
"p": true
}
],
"theme": "les finales de type « comité",
"pub": "8-2",
"win": "white"
},
"av_fins_de_partie_l2_pos3": {
"id": "av_fins_de_partie_l2_pos3",
"ch": 2,
"title": "les finales de type « comité",
"start": {
"wm": [
13,
42
],
"wk": [],
"bm": [
21,
31
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "les finales de type « comité"
},
"av_fins_de_partie_l2_pos4": {
"id": "av_fins_de_partie_l2_pos4",
"ch": 2,
"title": "les finales de type « comité",
"start": {
"wm": [
15,
35
],
"wk": [
46
],
"bm": [
27,
31,
36
],
"bk": [],
"turn": "black"
},
"moves": [],
"theme": "les finales de type « comité"
},
"av_fins_de_partie_l2_pos5": {
"id": "av_fins_de_partie_l2_pos5",
"ch": 2,
"title": "les finales de type « comité",
"start": {
"wm": [
39,
45
],
"wk": [
14
],
"bm": [
27,
31,
36
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "les finales de type « comité"
},
"av_fins_de_partie_l2_pos6": {
"id": "av_fins_de_partie_l2_pos6",
"ch": 2,
"title": "les finales de type « comité",
"start": {
"wm": [
24,
29
],
"wk": [
19
],
"bm": [
22,
27,
36
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "les finales de type « comité"
},
"av_fins_de_partie_l2_pos7": {
"id": "av_fins_de_partie_l2_pos7",
"ch": 2,
"title": "les finales de type « comité",
"start": {
"wm": [
32,
38
],
"wk": [
27
],
"bm": [
26,
36
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "les finales de type « comité"
},
"av_fins_de_partie_l3_pos0": {
"id": "av_fins_de_partie_l3_pos0",
"ch": 3,
"title": "« pions contre pions »",
"start": {
"wm": [
31,
48,
49
],
"wk": [],
"bm": [
32,
33
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "31-27",
"f": 31,
"t": 27,
"c": [],
"path": [
31,
27
],
"p": false
},
{
"n": "32x21",
"f": 32,
"t": 21,
"c": [
27
],
"path": [
32,
21
],
"p": false
},
{
"n": "49-43",
"f": 49,
"t": 43,
"c": [],
"path": [
49,
43
],
"p": false
},
{
"n": "33-39",
"f": 33,
"t": 39,
"c": [],
"path": [
33,
39
],
"p": false
},
{
"n": "43x34",
"f": 43,
"t": 34,
"c": [
39
],
"path": [
43,
34
],
"p": false
},
{
"n": "21-27",
"f": 21,
"t": 27,
"c": [],
"path": [
21,
27
],
"p": false
},
{
"n": "34-29",
"f": 34,
"t": 29,
"c": [],
"path": [
34,
29
],
"p": false
},
{
"n": "27-31",
"f": 27,
"t": 31,
"c": [],
"path": [
27,
31
],
"p": false
},
{
"n": "48-42",
"f": 48,
"t": 42,
"c": [],
"path": [
48,
42
],
"p": false
},
{
"n": "31-36",
"f": 31,
"t": 36,
"c": [],
"path": [
31,
36
],
"p": false
},
{
"n": "42-37",
"f": 42,
"t": 37,
"c": [],
"path": [
42,
37
],
"p": false
},
{
"n": "36-41",
"f": 36,
"t": 41,
"c": [],
"path": [
36,
41
],
"p": false
},
{
"n": "37x46",
"f": 37,
"t": 46,
"c": [
41
],
"path": [
37,
46
],
"p": false
}
],
"theme": "« pions contre pions »",
"pub": "31-27 32x21 49-43 33-39 43x34 21-27 34-29 27-31 48-42 31-36 42-37 36-41 37x46",
"win": "white"
},
"av_fins_de_partie_l3_pos1": {
"id": "av_fins_de_partie_l3_pos1",
"ch": 3,
"title": "« pions contre pions »",
"start": {
"wm": [
32,
40,
42
],
"wk": [],
"bm": [
33,
35
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "32-28",
"f": 32,
"t": 28,
"c": [],
"path": [
32,
28
],
"p": false
},
{
"n": "33x22",
"f": 33,
"t": 22,
"c": [
28
],
"path": [
33,
22
],
"p": false
},
{
"n": "40-34",
"f": 40,
"t": 34,
"c": [],
"path": [
40,
34
],
"p": false
},
{
"n": "22-27",
"f": 22,
"t": 27,
"c": [],
"path": [
22,
27
],
"p": false
},
{
"n": "42-37",
"f": 42,
"t": 37,
"c": [],
"path": [
42,
37
],
"p": false
},
{
"n": "35-40",
"f": 35,
"t": 40,
"c": [],
"path": [
35,
40
],
"p": false
},
{
"n": "34x45",
"f": 34,
"t": 45,
"c": [
40
],
"path": [
34,
45
],
"p": false
},
{
"n": "27-31",
"f": 27,
"t": 31,
"c": [],
"path": [
27,
31
],
"p": false
},
{
"n": "37x26",
"f": 37,
"t": 26,
"c": [
31
],
"path": [
37,
26
],
"p": false
}
],
"theme": "« pions contre pions »",
"pub": "32-28 33x22 40-34 22-27 42-37 35-40 34x45 27-31 37x26",
"win": "white"
},
"av_fins_de_partie_l3_pos2": {
"id": "av_fins_de_partie_l3_pos2",
"ch": 3,
"title": "« pions contre pions »",
"start": {
"wm": [
25,
34,
45
],
"wk": [],
"bm": [
15,
24
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "45-40",
"f": 45,
"t": 40,
"c": [],
"path": [
45,
40
],
"p": false
},
{
"n": "24-30",
"f": 24,
"t": 30,
"c": [],
"path": [
24,
30
],
"p": false
},
{
"n": "34-29",
"f": 34,
"t": 29,
"c": [],
"path": [
34,
29
],
"p": false
},
{
"n": "30-35",
"f": 30,
"t": 35,
"c": [],
"path": [
30,
35
],
"p": false
},
{
"n": "40-34",
"f": 40,
"t": 34,
"c": [],
"path": [
40,
34
],
"p": false
},
{
"n": "35-40",
"f": 35,
"t": 40,
"c": [],
"path": [
35,
40
],
"p": false
},
{
"n": "34x45",
"f": 34,
"t": 45,
"c": [
40
],
"path": [
34,
45
],
"p": false
},
{
"n": "15-20",
"f": 15,
"t": 20,
"c": [],
"path": [
15,
20
],
"p": false
},
{
"n": "25x14",
"f": 25,
"t": 14,
"c": [
20
],
"path": [
25,
14
],
"p": false
}
],
"theme": "« pions contre pions »",
"pub": "45-40 24-30 34-29 30-35 40-34 35-40 34x45 15-20 25x14",
"win": "white"
},
"av_fins_de_partie_l3_pos3": {
"id": "av_fins_de_partie_l3_pos3",
"ch": 3,
"title": "« pions contre pions »",
"start": {
"wm": [
30,
34,
48
],
"wk": [],
"bm": [
14,
20
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "48-43",
"f": 48,
"t": 43,
"c": [],
"path": [
48,
43
],
"p": false
},
{
"n": "14-19",
"f": 14,
"t": 19,
"c": [],
"path": [
14,
19
],
"p": false
},
{
"n": "43-38",
"f": 43,
"t": 38,
"c": [],
"path": [
43,
38
],
"p": false
},
{
"n": "20-24",
"f": 20,
"t": 24,
"c": [],
"path": [
20,
24
],
"p": false
},
{
"n": "38-33",
"f": 38,
"t": 33,
"c": [],
"path": [
38,
33
],
"p": false
},
{
"n": "24x35",
"f": 24,
"t": 35,
"c": [
30
],
"path": [
24,
35
],
"p": false
},
{
"n": "33-29",
"f": 33,
"t": 29,
"c": [],
"path": [
33,
29
],
"p": false
},
{
"n": "35-40",
"f": 35,
"t": 40,
"c": [],
"path": [
35,
40
],
"p": false
},
{
"n": "34x45",
"f": 34,
"t": 45,
"c": [
40
],
"path": [
34,
45
],
"p": false
},
{
"n": "19-23",
"f": 19,
"t": 23,
"c": [],
"path": [
19,
23
],
"p": false
},
{
"n": "29x18",
"f": 29,
"t": 18,
"c": [
23
],
"path": [
29,
18
],
"p": false
}
],
"theme": "« pions contre pions »",
"pub": "48-43 14-19 43-38 20-24 38-33 24x35 33-29 35-40 34x45 19-23 29x18",
"win": "white"
},
"av_fins_de_partie_l3_pos4": {
"id": "av_fins_de_partie_l3_pos4",
"ch": 3,
"title": "« pions contre pions »",
"start": {
"wm": [
35,
43,
44,
46,
48
],
"wk": [],
"bm": [
25,
36,
40
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "« pions contre pions »"
},
"av_fins_de_partie_l3_pos5": {
"id": "av_fins_de_partie_l3_pos5",
"ch": 3,
"title": "« pions contre pions »",
"start": {
"wm": [
45,
49
],
"wk": [],
"bm": [
14,
35
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "49-44",
"f": 49,
"t": 44,
"c": [],
"path": [
49,
44
],
"p": false
},
{
"n": "14-19",
"f": 14,
"t": 19,
"c": [],
"path": [
14,
19
],
"p": false
},
{
"n": "44-39",
"f": 44,
"t": 39,
"c": [],
"path": [
44,
39
],
"p": false
},
{
"n": "19-24",
"f": 19,
"t": 24,
"c": [],
"path": [
19,
24
],
"p": false
},
{
"n": "39-34",
"f": 39,
"t": 34,
"c": [],
"path": [
39,
34
],
"p": false
},
{
"n": "35-40",
"f": 35,
"t": 40,
"c": [],
"path": [
35,
40
],
"p": false
},
{
"n": "34-30",
"f": 34,
"t": 30,
"c": [],
"path": [
34,
30
],
"p": false
},
{
"n": "24x35",
"f": 24,
"t": 35,
"c": [
30
],
"path": [
24,
35
],
"p": false
},
{
"n": "45x34",
"f": 45,
"t": 34,
"c": [
40
],
"path": [
45,
34
],
"p": false
},
{
"n": "35-40",
"f": 35,
"t": 40,
"c": [],
"path": [
35,
40
],
"p": false
},
{
"n": "34x45",
"f": 34,
"t": 45,
"c": [
40
],
"path": [
34,
45
],
"p": false
}
],
"theme": "« pions contre pions »",
"pub": "49-44 14-19 44-39 19-24 39-34 35-40 34-30 24x35 45x34 35-40 34x45",
"win": "white"
},
"av_fins_de_partie_l3_pos6": {
"id": "av_fins_de_partie_l3_pos6",
"ch": 3,
"title": "1 pion contre 1 avec 3 temps d’avance",
"start": {
"wm": [
28,
35
],
"wk": [],
"bm": [
18,
20
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "1 pion contre 1 avec 3 temps d’avance"
},
"av_fins_de_partie_l3_pos7": {
"id": "av_fins_de_partie_l3_pos7",
"ch": 3,
"title": "1 pion contre 1 avec 3 temps d’avance",
"start": {
"wm": [
25,
32,
35
],
"wk": [],
"bm": [
18,
24
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "1 pion contre 1 avec 3 temps d’avance"
},
"av_fins_de_partie_l4_ex0": {
"id": "av_fins_de_partie_l4_ex0",
"ch": 4,
"title": "1 dame contre 2 pions – D1",
"start": {
"wm": [
24,
27
],
"wk": [
41
],
"bm": [
15,
16,
18
],
"bk": [
21
],
"turn": "white"
},
"moves": [
{
"n": "41-36",
"f": 41,
"t": 36,
"c": [],
"path": [
41,
36
],
"p": false
},
{
"n": "21x38x20",
"f": 21,
"t": 20,
"c": [
24,
27
],
"path": [
21,
38,
20
],
"p": false
},
{
"n": "36x9x25",
"f": 36,
"t": 25,
"c": [
18,
20
],
"path": [
36,
9,
25
],
"p": false
}
],
"theme": "1 dame contre 2 pions",
"pub": "41-36 21x38x20 36x9x25",
"win": "white",
"exp": "1 dame contre 2 pions"
},
"av_fins_de_partie_l4_ex1": {
"id": "av_fins_de_partie_l4_ex1",
"ch": 4,
"title": "1 dame contre 2 pions – D2",
"start": {
"wm": [
10,
35
],
"wk": [
36
],
"bm": [
16,
33
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "10-4",
"f": 10,
"t": 4,
"c": [],
"path": [
10,
4
],
"p": true
}
],
"theme": "1 dame contre 2 pions",
"pub": "10-4",
"win": "white",
"exp": "1 dame contre 2 pions"
},
"av_fins_de_partie_l4_ex2": {
"id": "av_fins_de_partie_l4_ex2",
"ch": 4,
"title": "1 dame contre 2 pions – D3",
"start": {
"wm": [
25,
37
],
"wk": [
24,
46
],
"bm": [
9,
15,
26
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "37-31",
"f": 37,
"t": 31,
"c": [],
"path": [
37,
31
],
"p": false
},
{
"n": "26x37",
"f": 26,
"t": 37,
"c": [
31
],
"path": [
26,
37
],
"p": false
},
{
"n": "46x14x3",
"f": 46,
"t": 3,
"c": [
9,
37
],
"path": [
46,
14,
3
],
"p": false
},
{
"n": "15-20",
"f": 15,
"t": 20,
"c": [],
"path": [
15,
20
],
"p": false
},
{
"n": "24x15",
"f": 24,
"t": 15,
"c": [
20
],
"path": [
24,
15
],
"p": false
}
],
"theme": "1 dame contre 2 pions",
"pub": "37-31 26x37 46x14x3 15-20 24x15",
"win": "white",
"exp": "1 dame contre 2 pions"
},
"av_fins_de_partie_l4_ex3": {
"id": "av_fins_de_partie_l4_ex3",
"ch": 4,
"title": "1 dame contre 2 pions – D4",
"start": {
"wm": [
8
],
"wk": [],
"bm": [
9,
28
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "8-3",
"f": 8,
"t": 3,
"c": [],
"path": [
8,
3
],
"p": true
}
],
"theme": "1 dame contre 2 pions",
"pub": "8-3",
"win": "white",
"exp": "1 dame contre 2 pions"
},
"av_fins_de_partie_l4_ex4": {
"id": "av_fins_de_partie_l4_ex4",
"ch": 4,
"title": "1 dame contre 2 pions – D5",
"start": {
"wm": [
6,
33
],
"wk": [],
"bm": [
12,
18,
34
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "6-1",
"f": 6,
"t": 1,
"c": [],
"path": [
6,
1
],
"p": true
}
],
"theme": "1 dame contre 2 pions",
"pub": "6-1",
"win": "white",
"exp": "1 dame contre 2 pions"
},
"av_fins_de_partie_l4_ex5": {
"id": "av_fins_de_partie_l4_ex5",
"ch": 4,
"title": "1 dame contre 2 pions – D6",
"start": {
"wm": [
9,
23
],
"wk": [],
"bm": [
12,
31
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "9-4",
"f": 9,
"t": 4,
"c": [],
"path": [
9,
4
],
"p": true
}
],
"theme": "1 dame contre 2 pions",
"pub": "9-4",
"win": "white",
"exp": "1 dame contre 2 pions"
},
"av_fins_de_partie_l4_ex6": {
"id": "av_fins_de_partie_l4_ex6",
"ch": 4,
"title": "1 dame contre 2 pions – D7",
"start": {
"wm": [
8,
37
],
"wk": [],
"bm": [
22,
36
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "8-2",
"f": 8,
"t": 2,
"c": [],
"path": [
8,
2
],
"p": true
}
],
"theme": "1 dame contre 2 pions",
"pub": "8-2",
"win": "white",
"exp": "1 dame contre 2 pions"
},
"av_fins_de_partie_l4_ex7": {
"id": "av_fins_de_partie_l4_ex7",
"ch": 4,
"title": "« pions contre pions » – D1",
"start": {
"wm": [
31,
48,
49
],
"wk": [],
"bm": [
32,
33
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "31-27",
"f": 31,
"t": 27,
"c": [],
"path": [
31,
27
],
"p": false
},
{
"n": "32x21",
"f": 32,
"t": 21,
"c": [
27
],
"path": [
32,
21
],
"p": false
},
{
"n": "49-43",
"f": 49,
"t": 43,
"c": [],
"path": [
49,
43
],
"p": false
},
{
"n": "33-39",
"f": 33,
"t": 39,
"c": [],
"path": [
33,
39
],
"p": false
},
{
"n": "43x34",
"f": 43,
"t": 34,
"c": [
39
],
"path": [
43,
34
],
"p": false
},
{
"n": "21-27",
"f": 21,
"t": 27,
"c": [],
"path": [
21,
27
],
"p": false
},
{
"n": "34-29",
"f": 34,
"t": 29,
"c": [],
"path": [
34,
29
],
"p": false
},
{
"n": "27-31",
"f": 27,
"t": 31,
"c": [],
"path": [
27,
31
],
"p": false
},
{
"n": "48-42",
"f": 48,
"t": 42,
"c": [],
"path": [
48,
42
],
"p": false
},
{
"n": "31-36",
"f": 31,
"t": 36,
"c": [],
"path": [
31,
36
],
"p": false
},
{
"n": "42-37",
"f": 42,
"t": 37,
"c": [],
"path": [
42,
37
],
"p": false
},
{
"n": "36-41",
"f": 36,
"t": 41,
"c": [],
"path": [
36,
41
],
"p": false
},
{
"n": "37x46",
"f": 37,
"t": 46,
"c": [
41
],
"path": [
37,
46
],
"p": false
}
],
"theme": "« pions contre pions »",
"pub": "31-27 32x21 49-43 33-39 43x34 21-27 34-29 27-31 48-42 31-36 42-37 36-41 37x46",
"win": "white",
"exp": "« pions contre pions »"
},
"av_fins_de_partie_l4_ex8": {
"id": "av_fins_de_partie_l4_ex8",
"ch": 4,
"title": "« pions contre pions » – D2",
"start": {
"wm": [
32,
40,
42
],
"wk": [],
"bm": [
33,
35
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "32-28",
"f": 32,
"t": 28,
"c": [],
"path": [
32,
28
],
"p": false
},
{
"n": "33x22",
"f": 33,
"t": 22,
"c": [
28
],
"path": [
33,
22
],
"p": false
},
{
"n": "40-34",
"f": 40,
"t": 34,
"c": [],
"path": [
40,
34
],
"p": false
},
{
"n": "22-27",
"f": 22,
"t": 27,
"c": [],
"path": [
22,
27
],
"p": false
},
{
"n": "42-37",
"f": 42,
"t": 37,
"c": [],
"path": [
42,
37
],
"p": false
},
{
"n": "35-40",
"f": 35,
"t": 40,
"c": [],
"path": [
35,
40
],
"p": false
},
{
"n": "34x45",
"f": 34,
"t": 45,
"c": [
40
],
"path": [
34,
45
],
"p": false
},
{
"n": "27-31",
"f": 27,
"t": 31,
"c": [],
"path": [
27,
31
],
"p": false
},
{
"n": "37x26",
"f": 37,
"t": 26,
"c": [
31
],
"path": [
37,
26
],
"p": false
}
],
"theme": "« pions contre pions »",
"pub": "32-28 33x22 40-34 22-27 42-37 35-40 34x45 27-31 37x26",
"win": "white",
"exp": "« pions contre pions »"
},
"av_fins_de_partie_l4_ex9": {
"id": "av_fins_de_partie_l4_ex9",
"ch": 4,
"title": "« pions contre pions » – D3",
"start": {
"wm": [
25,
34,
45
],
"wk": [],
"bm": [
15,
24
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "45-40",
"f": 45,
"t": 40,
"c": [],
"path": [
45,
40
],
"p": false
},
{
"n": "24-30",
"f": 24,
"t": 30,
"c": [],
"path": [
24,
30
],
"p": false
},
{
"n": "34-29",
"f": 34,
"t": 29,
"c": [],
"path": [
34,
29
],
"p": false
},
{
"n": "30-35",
"f": 30,
"t": 35,
"c": [],
"path": [
30,
35
],
"p": false
},
{
"n": "40-34",
"f": 40,
"t": 34,
"c": [],
"path": [
40,
34
],
"p": false
},
{
"n": "35-40",
"f": 35,
"t": 40,
"c": [],
"path": [
35,
40
],
"p": false
},
{
"n": "34x45",
"f": 34,
"t": 45,
"c": [
40
],
"path": [
34,
45
],
"p": false
},
{
"n": "15-20",
"f": 15,
"t": 20,
"c": [],
"path": [
15,
20
],
"p": false
},
{
"n": "25x14",
"f": 25,
"t": 14,
"c": [
20
],
"path": [
25,
14
],
"p": false
}
],
"theme": "« pions contre pions »",
"pub": "45-40 24-30 34-29 30-35 40-34 35-40 34x45 15-20 25x14",
"win": "white",
"exp": "« pions contre pions »"
},
"av_fins_de_partie_l4_ex10": {
"id": "av_fins_de_partie_l4_ex10",
"ch": 4,
"title": "« pions contre pions » – D4",
"start": {
"wm": [
30,
34,
48
],
"wk": [],
"bm": [
14,
20
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "48-43",
"f": 48,
"t": 43,
"c": [],
"path": [
48,
43
],
"p": false
},
{
"n": "14-19",
"f": 14,
"t": 19,
"c": [],
"path": [
14,
19
],
"p": false
},
{
"n": "43-38",
"f": 43,
"t": 38,
"c": [],
"path": [
43,
38
],
"p": false
},
{
"n": "20-24",
"f": 20,
"t": 24,
"c": [],
"path": [
20,
24
],
"p": false
},
{
"n": "38-33",
"f": 38,
"t": 33,
"c": [],
"path": [
38,
33
],
"p": false
},
{
"n": "24x35",
"f": 24,
"t": 35,
"c": [
30
],
"path": [
24,
35
],
"p": false
},
{
"n": "33-29",
"f": 33,
"t": 29,
"c": [],
"path": [
33,
29
],
"p": false
},
{
"n": "35-40",
"f": 35,
"t": 40,
"c": [],
"path": [
35,
40
],
"p": false
},
{
"n": "34x45",
"f": 34,
"t": 45,
"c": [
40
],
"path": [
34,
45
],
"p": false
},
{
"n": "19-23",
"f": 19,
"t": 23,
"c": [],
"path": [
19,
23
],
"p": false
},
{
"n": "29x18",
"f": 29,
"t": 18,
"c": [
23
],
"path": [
29,
18
],
"p": false
}
],
"theme": "« pions contre pions »",
"pub": "48-43 14-19 43-38 20-24 38-33 24x35 33-29 35-40 34x45 19-23 29x18",
"win": "white",
"exp": "« pions contre pions »"
},
"av_fins_de_partie_l4_ex11": {
"id": "av_fins_de_partie_l4_ex11",
"ch": 4,
"title": "« pions contre pions » – D5",
"start": {
"wm": [
45,
49
],
"wk": [],
"bm": [
14,
35
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "49-44",
"f": 49,
"t": 44,
"c": [],
"path": [
49,
44
],
"p": false
},
{
"n": "14-19",
"f": 14,
"t": 19,
"c": [],
"path": [
14,
19
],
"p": false
},
{
"n": "44-39",
"f": 44,
"t": 39,
"c": [],
"path": [
44,
39
],
"p": false
},
{
"n": "19-24",
"f": 19,
"t": 24,
"c": [],
"path": [
19,
24
],
"p": false
},
{
"n": "39-34",
"f": 39,
"t": 34,
"c": [],
"path": [
39,
34
],
"p": false
},
{
"n": "35-40",
"f": 35,
"t": 40,
"c": [],
"path": [
35,
40
],
"p": false
},
{
"n": "34-30",
"f": 34,
"t": 30,
"c": [],
"path": [
34,
30
],
"p": false
},
{
"n": "24x35",
"f": 24,
"t": 35,
"c": [
30
],
"path": [
24,
35
],
"p": false
},
{
"n": "45x34",
"f": 45,
"t": 34,
"c": [
40
],
"path": [
45,
34
],
"p": false
},
{
"n": "35-40",
"f": 35,
"t": 40,
"c": [],
"path": [
35,
40
],
"p": false
},
{
"n": "34x45",
"f": 34,
"t": 45,
"c": [
40
],
"path": [
34,
45
],
"p": false
}
],
"theme": "« pions contre pions »",
"pub": "49-44 14-19 44-39 19-24 39-34 35-40 34-30 24x35 45x34 35-40 34x45",
"win": "white",
"exp": "« pions contre pions »"
},
"av_fins_de_partie_l4_ex12": {
"id": "av_fins_de_partie_l4_ex12",
"ch": 4,
"title": "1 dame et 1 pion contre 2 pions – D1",
"start": {
"wm": [
30
],
"wk": [
35
],
"bm": [
15,
36
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "30-24",
"f": 30,
"t": 24,
"c": [],
"path": [
30,
24
],
"p": false
},
{
"n": "15-20",
"f": 15,
"t": 20,
"c": [],
"path": [
15,
20
],
"p": false
},
{
"n": "24x15",
"f": 24,
"t": 15,
"c": [
20
],
"path": [
24,
15
],
"p": false
},
{
"n": "36-41",
"f": 36,
"t": 41,
"c": [],
"path": [
36,
41
],
"p": false
},
{
"n": "35-19",
"f": 35,
"t": 19,
"c": [],
"path": [
35,
19
],
"p": false
},
{
"n": "41-46",
"f": 41,
"t": 46,
"c": [],
"path": [
41,
46
],
"p": true
},
{
"n": "19-5",
"f": 19,
"t": 5,
"c": [],
"path": [
19,
5
],
"p": false
},
{
"n": "46-41",
"f": 46,
"t": 41,
"c": [],
"path": [
46,
41
],
"p": false
},
{
"n": "5x46",
"f": 5,
"t": 46,
"c": [
41
],
"path": [
5,
46
],
"p": false
}
],
"theme": "1 dame et 1 pion contre 2 pions",
"pub": "30-24 15-20 24x15 36-41 35-19 41-46 19-5 46-41 5x46",
"win": "white",
"exp": "1 dame et 1 pion contre 2 pions"
},
"av_fins_de_partie_l4_ex13": {
"id": "av_fins_de_partie_l4_ex13",
"ch": 4,
"title": "1 dame et 1 pion contre 2 pions – D2",
"start": {
"wm": [
7,
36
],
"wk": [],
"bm": [
21,
33
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "7-2",
"f": 7,
"t": 2,
"c": [],
"path": [
7,
2
],
"p": true
}
],
"theme": "1 dame et 1 pion contre 2 pions",
"pub": "7-2",
"win": "white",
"exp": "1 dame et 1 pion contre 2 pions"
},
"av_fins_de_partie_l4_ex14": {
"id": "av_fins_de_partie_l4_ex14",
"ch": 4,
"title": "les finales de type « comité – D1",
"start": {
"wm": [
19,
23,
38
],
"wk": [],
"bm": [
27
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "19-13",
"f": 19,
"t": 13,
"c": [],
"path": [
19,
13
],
"p": false
},
{
"n": "27-31",
"f": 27,
"t": 31,
"c": [],
"path": [
27,
31
],
"p": false
},
{
"n": "13-8",
"f": 13,
"t": 8,
"c": [],
"path": [
13,
8
],
"p": false
},
{
"n": "31-37",
"f": 31,
"t": 37,
"c": [],
"path": [
31,
37
],
"p": false
},
{
"n": "8-2",
"f": 8,
"t": 2,
"c": [],
"path": [
8,
2
],
"p": true
},
{
"n": "37-41",
"f": 37,
"t": 41,
"c": [],
"path": [
37,
41
],
"p": false
},
{
"n": "38-33",
"f": 38,
"t": 33,
"c": [],
"path": [
38,
33
],
"p": false
},
{
"n": "41-46",
"f": 41,
"t": 46,
"c": [],
"path": [
41,
46
],
"p": true
},
{
"n": "2-19",
"f": 2,
"t": 19,
"c": [],
"path": [
2,
19
],
"p": false
},
{
"n": "46-32",
"f": 46,
"t": 32,
"c": [],
"path": [
46,
32
],
"p": false
},
{
"n": "19-5",
"f": 19,
"t": 5,
"c": [],
"path": [
19,
5
],
"p": false
},
{
"n": "32x19",
"f": 32,
"t": 19,
"c": [
23
],
"path": [
32,
19
],
"p": false
},
{
"n": "5x23",
"f": 5,
"t": 23,
"c": [
19
],
"path": [
5,
23
],
"p": false
}
],
"theme": "les finales de type « comité",
"pub": "19-13 27-31 13-8 31-37 8-2 37-41 38-33 41-46 2-19 46-32 19-5 32x19 5x23",
"win": "white",
"exp": "les finales de type « comité"
},
"av_fins_de_partie_l4_ex15": {
"id": "av_fins_de_partie_l4_ex15",
"ch": 4,
"title": "les finales de type « comité – D2",
"start": {
"wm": [
8,
19,
24
],
"wk": [],
"bm": [
31
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "8-2",
"f": 8,
"t": 2,
"c": [],
"path": [
8,
2
],
"p": true
}
],
"theme": "les finales de type « comité",
"pub": "8-2",
"win": "white",
"exp": "les finales de type « comité"
},
"av_fins_de_partie_l4_ex16": {
"id": "av_fins_de_partie_l4_ex16",
"ch": 4,
"title": "les finales de type « comité – D3",
"start": {
"wm": [
10,
49
],
"wk": [],
"bm": [
28,
36
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "10-5",
"f": 10,
"t": 5,
"c": [],
"path": [
10,
5
],
"p": true
}
],
"theme": "les finales de type « comité",
"pub": "10-5",
"win": "white",
"exp": "les finales de type « comité"
},
"av_fins_de_partie_l4_ex17": {
"id": "av_fins_de_partie_l4_ex17",
"ch": 4,
"title": "les finales du type « comité – D1",
"start": {
"wm": [
10,
29
],
"wk": [],
"bm": [
25,
35
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "10-5",
"f": 10,
"t": 5,
"c": [],
"path": [
10,
5
],
"p": true
}
],
"theme": "les finales du type « comité",
"pub": "10-5",
"win": "white",
"exp": "les finales du type « comité"
},
"av_fins_de_partie_l4_ex18": {
"id": "av_fins_de_partie_l4_ex18",
"ch": 4,
"title": "les finales du type « comité – D1",
"start": {
"wm": [
10,
29
],
"wk": [],
"bm": [
25,
35
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "10-5",
"f": 10,
"t": 5,
"c": [],
"path": [
10,
5
],
"p": true
}
],
"theme": "les finales du type « comité",
"pub": "10-5",
"win": "white",
"exp": "les finales du type « comité"
},
"av_fins_de_partie_l4_ex19": {
"id": "av_fins_de_partie_l4_ex19",
"ch": 4,
"title": "les finales du type « comité – D1",
"start": {
"wm": [
10,
29
],
"wk": [],
"bm": [
25,
35
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "10-5",
"f": 10,
"t": 5,
"c": [],
"path": [
10,
5
],
"p": true
}
],
"theme": "les finales du type « comité",
"pub": "10-5",
"win": "white",
"exp": "les finales du type « comité"
},
"av_fins_de_partie_l4_ex20": {
"id": "av_fins_de_partie_l4_ex20",
"ch": 4,
"title": "les finales du type « comité – D2",
"start": {
"wm": [
21,
26,
45
],
"wk": [],
"bm": [
6,
30
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "21-17",
"f": 21,
"t": 17,
"c": [],
"path": [
21,
17
],
"p": false
},
{
"n": "30-34",
"f": 30,
"t": 34,
"c": [],
"path": [
30,
34
],
"p": false
},
{
"n": "45-40",
"f": 45,
"t": 40,
"c": [],
"path": [
45,
40
],
"p": false
},
{
"n": "34x45",
"f": 34,
"t": 45,
"c": [
40
],
"path": [
34,
45
],
"p": false
},
{
"n": "26-21",
"f": 26,
"t": 21,
"c": [],
"path": [
26,
21
],
"p": false
},
{
"n": "45-50",
"f": 45,
"t": 50,
"c": [],
"path": [
45,
50
],
"p": true
},
{
"n": "21-16",
"f": 21,
"t": 16,
"c": [],
"path": [
21,
16
],
"p": false
},
{
"n": "50x11",
"f": 50,
"t": 11,
"c": [
17
],
"path": [
50,
11
],
"p": false
},
{
"n": "16x7",
"f": 16,
"t": 7,
"c": [
11
],
"path": [
16,
7
],
"p": false
},
{
"n": "6-11",
"f": 6,
"t": 11,
"c": [],
"path": [
6,
11
],
"p": false
},
{
"n": "7x16",
"f": 7,
"t": 16,
"c": [
11
],
"path": [
7,
16
],
"p": false
}
],
"theme": "les finales du type « comité",
"pub": "21-17 30-34 45-40 34x45 26-21 45-50 21-16 50x11 16x7 6-11 7x16",
"win": "white",
"exp": "les finales du type « comité"
},
"av_fins_de_partie_l4_ex21": {
"id": "av_fins_de_partie_l4_ex21",
"ch": 4,
"title": "les finales du type « comité – D3",
"start": {
"wm": [
6,
7,
32
],
"wk": [],
"bm": [
44
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "7-2",
"f": 7,
"t": 2,
"c": [],
"path": [
7,
2
],
"p": true
}
],
"theme": "les finales du type « comité",
"pub": "7-2",
"win": "white",
"exp": "les finales du type « comité"
},
"av_fins_de_partie_l4_ex22": {
"id": "av_fins_de_partie_l4_ex22",
"ch": 4,
"title": "les finales du type « comité – D1",
"start": {
"wm": [
10,
29
],
"wk": [],
"bm": [
25,
35
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "10-5",
"f": 10,
"t": 5,
"c": [],
"path": [
10,
5
],
"p": true
}
],
"theme": "les finales du type « comité",
"pub": "10-5",
"win": "white",
"exp": "les finales du type « comité"
},
"av_fins_de_partie_l4_ex23": {
"id": "av_fins_de_partie_l4_ex23",
"ch": 4,
"title": "les finales du type « comité – D2",
"start": {
"wm": [
21,
26,
45
],
"wk": [],
"bm": [
6,
30
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "21-17",
"f": 21,
"t": 17,
"c": [],
"path": [
21,
17
],
"p": false
},
{
"n": "30-34",
"f": 30,
"t": 34,
"c": [],
"path": [
30,
34
],
"p": false
},
{
"n": "45-40",
"f": 45,
"t": 40,
"c": [],
"path": [
45,
40
],
"p": false
},
{
"n": "34x45",
"f": 34,
"t": 45,
"c": [
40
],
"path": [
34,
45
],
"p": false
},
{
"n": "26-21",
"f": 26,
"t": 21,
"c": [],
"path": [
26,
21
],
"p": false
},
{
"n": "45-50",
"f": 45,
"t": 50,
"c": [],
"path": [
45,
50
],
"p": true
},
{
"n": "21-16",
"f": 21,
"t": 16,
"c": [],
"path": [
21,
16
],
"p": false
},
{
"n": "50x11",
"f": 50,
"t": 11,
"c": [
17
],
"path": [
50,
11
],
"p": false
},
{
"n": "16x7",
"f": 16,
"t": 7,
"c": [
11
],
"path": [
16,
7
],
"p": false
},
{
"n": "6-11",
"f": 6,
"t": 11,
"c": [],
"path": [
6,
11
],
"p": false
},
{
"n": "7x16",
"f": 7,
"t": 16,
"c": [
11
],
"path": [
7,
16
],
"p": false
}
],
"theme": "les finales du type « comité",
"pub": "21-17 30-34 45-40 34x45 26-21 45-50 21-16 50x11 16x7 6-11 7x16",
"win": "white",
"exp": "les finales du type « comité"
},
"av_fins_de_partie_l4_ex24": {
"id": "av_fins_de_partie_l4_ex24",
"ch": 4,
"title": "la traversée de la grande diagonale – D1",
"start": {
"wm": [
9,
38
],
"wk": [],
"bm": [
16,
31,
36
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "9-4",
"f": 9,
"t": 4,
"c": [],
"path": [
9,
4
],
"p": true
}
],
"theme": "la traversée de la grande diagonale",
"pub": "9-4",
"win": "white",
"exp": "la traversée de la grande diagonale"
},
"av_fins_de_partie_l4_ex25": {
"id": "av_fins_de_partie_l4_ex25",
"ch": 4,
"title": "1 dame et 1 pion contre 3 pions – D1",
"start": {
"wm": [
9,
26
],
"wk": [],
"bm": [
12,
16,
25
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "9-4",
"f": 9,
"t": 4,
"c": [],
"path": [
9,
4
],
"p": true
}
],
"theme": "1 dame et 1 pion contre 3 pions",
"pub": "9-4",
"win": "white",
"exp": "1 dame et 1 pion contre 3 pions"
},
"av_fins_de_partie_l4_ex26": {
"id": "av_fins_de_partie_l4_ex26",
"ch": 4,
"title": "1 dame et 1 pion contre 3 pions – D2",
"start": {
"wm": [
10,
20
],
"wk": [],
"bm": [
13,
33,
38
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "10-4",
"f": 10,
"t": 4,
"c": [],
"path": [
10,
4
],
"p": true
}
],
"theme": "1 dame et 1 pion contre 3 pions",
"pub": "10-4",
"win": "white",
"exp": "1 dame et 1 pion contre 3 pions"
},
"av_fins_de_partie_l4_ex27": {
"id": "av_fins_de_partie_l4_ex27",
"ch": 4,
"title": "1 dame et 3 pions contre 1 dame et 1 – D1",
"start": {
"wm": [
8,
9
],
"wk": [],
"bm": [
5,
32
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "8-2",
"f": 8,
"t": 2,
"c": [],
"path": [
8,
2
],
"p": true
}
],
"theme": "1 dame et 3 pions contre 1 dame et 1",
"pub": "8-2",
"win": "white",
"exp": "1 dame et 3 pions contre 1 dame et 1"
},
"av_fins_de_partie_l4_ex28": {
"id": "av_fins_de_partie_l4_ex28",
"ch": 4,
"title": "1 dame et 3 pions contre 1 dame et 1 – D2",
"start": {
"wm": [
7
],
"wk": [],
"bm": [
6,
9
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "7-1",
"f": 7,
"t": 1,
"c": [],
"path": [
7,
1
],
"p": true
}
],
"theme": "1 dame et 3 pions contre 1 dame et 1",
"pub": "7-1",
"win": "white",
"exp": "1 dame et 3 pions contre 1 dame et 1"
},
"av_fins_de_partie_l4_ex29": {
"id": "av_fins_de_partie_l4_ex29",
"ch": 4,
"title": "1 dame et 3 pions contre 1 dame et 1 – D3",
"start": {
"wm": [
7
],
"wk": [],
"bm": [
6,
9
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "7-1",
"f": 7,
"t": 1,
"c": [],
"path": [
7,
1
],
"p": true
}
],
"theme": "1 dame et 3 pions contre 1 dame et 1",
"pub": "7-1",
"win": "white",
"exp": "1 dame et 3 pions contre 1 dame et 1"
},
"av_fins_de_partie_l4_ex30": {
"id": "av_fins_de_partie_l4_ex30",
"ch": 4,
"title": "1 dame et 3 pions contre 1 dame et 1 – D4",
"start": {
"wm": [
38,
42,
43
],
"wk": [],
"bm": [
23,
27
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "38-33",
"f": 38,
"t": 33,
"c": [],
"path": [
38,
33
],
"p": false
},
{
"n": "27-32",
"f": 27,
"t": 32,
"c": [],
"path": [
27,
32
],
"p": false
},
{
"n": "43-39",
"f": 43,
"t": 39,
"c": [],
"path": [
43,
39
],
"p": false
},
{
"n": "32-38",
"f": 32,
"t": 38,
"c": [],
"path": [
32,
38
],
"p": false
},
{
"n": "42-37",
"f": 42,
"t": 37,
"c": [],
"path": [
42,
37
],
"p": false
},
{
"n": "38x29",
"f": 38,
"t": 29,
"c": [
33
],
"path": [
38,
29
],
"p": false
},
{
"n": "37-32",
"f": 37,
"t": 32,
"c": [],
"path": [
37,
32
],
"p": false
},
{
"n": "29-34",
"f": 29,
"t": 34,
"c": [],
"path": [
29,
34
],
"p": false
},
{
"n": "39x30",
"f": 39,
"t": 30,
"c": [
34
],
"path": [
39,
30
],
"p": false
},
{
"n": "23-29",
"f": 23,
"t": 29,
"c": [],
"path": [
23,
29
],
"p": false
},
{
"n": "32-28",
"f": 32,
"t": 28,
"c": [],
"path": [
32,
28
],
"p": false
},
{
"n": "29-33",
"f": 29,
"t": 33,
"c": [],
"path": [
29,
33
],
"p": false
},
{
"n": "28x39",
"f": 28,
"t": 39,
"c": [
33
],
"path": [
28,
39
],
"p": false
}
],
"theme": "1 dame et 3 pions contre 1 dame et 1",
"pub": "38-33 27-32 43-39 32-38 42-37 38x29 37-32 29-34 39x30 23-29 32-28 29-33 28x39",
"win": "white",
"exp": "1 dame et 3 pions contre 1 dame et 1"
},
"av_fins_de_partie_l4_ex31": {
"id": "av_fins_de_partie_l4_ex31",
"ch": 4,
"title": "1 dame et 3 pions contre 1 dame et 1 – D1",
"start": {
"wm": [
8,
9
],
"wk": [],
"bm": [
5,
32
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "8-2",
"f": 8,
"t": 2,
"c": [],
"path": [
8,
2
],
"p": true
}
],
"theme": "1 dame et 3 pions contre 1 dame et 1",
"pub": "8-2",
"win": "white",
"exp": "1 dame et 3 pions contre 1 dame et 1"
},
"av_fins_de_partie_l4_ex32": {
"id": "av_fins_de_partie_l4_ex32",
"ch": 4,
"title": "1 dame et 3 pions contre 1 dame et 1 – D2",
"start": {
"wm": [
7
],
"wk": [],
"bm": [
6,
9
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "7-1",
"f": 7,
"t": 1,
"c": [],
"path": [
7,
1
],
"p": true
}
],
"theme": "1 dame et 3 pions contre 1 dame et 1",
"pub": "7-1",
"win": "white",
"exp": "1 dame et 3 pions contre 1 dame et 1"
},
"av_fins_de_partie_l4_ex33": {
"id": "av_fins_de_partie_l4_ex33",
"ch": 4,
"title": "1 dame et 3 pions contre 1 dame et 1 – D1",
"start": {
"wm": [
8,
9
],
"wk": [],
"bm": [
5,
32
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "8-2",
"f": 8,
"t": 2,
"c": [],
"path": [
8,
2
],
"p": true
}
],
"theme": "1 dame et 3 pions contre 1 dame et 1",
"pub": "8-2",
"win": "white",
"exp": "1 dame et 3 pions contre 1 dame et 1"
},
"av_fins_de_partie_l4_ex34": {
"id": "av_fins_de_partie_l4_ex34",
"ch": 4,
"title": "1 dame et 3 pions contre 1 dame et 1 – D2",
"start": {
"wm": [
7
],
"wk": [],
"bm": [
6,
9
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "7-1",
"f": 7,
"t": 1,
"c": [],
"path": [
7,
1
],
"p": true
}
],
"theme": "1 dame et 3 pions contre 1 dame et 1",
"pub": "7-1",
"win": "white",
"exp": "1 dame et 3 pions contre 1 dame et 1"
},
"av_fins_de_partie_l4_ex35": {
"id": "av_fins_de_partie_l4_ex35",
"ch": 4,
"title": "1 dame et 3 pions contre 1 dame et 1 – D3",
"start": {
"wm": [
7
],
"wk": [],
"bm": [
6,
9
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "7-1",
"f": 7,
"t": 1,
"c": [],
"path": [
7,
1
],
"p": true
}
],
"theme": "1 dame et 3 pions contre 1 dame et 1",
"pub": "7-1",
"win": "white",
"exp": "1 dame et 3 pions contre 1 dame et 1"
},
"av_fins_de_partie_l4_ex36": {
"id": "av_fins_de_partie_l4_ex36",
"ch": 4,
"title": "1 dame et 3 pions contre 1 dame et 1 – D4",
"start": {
"wm": [
38,
42,
43
],
"wk": [],
"bm": [
23,
27
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "38-33",
"f": 38,
"t": 33,
"c": [],
"path": [
38,
33
],
"p": false
},
{
"n": "27-32",
"f": 27,
"t": 32,
"c": [],
"path": [
27,
32
],
"p": false
},
{
"n": "43-39",
"f": 43,
"t": 39,
"c": [],
"path": [
43,
39
],
"p": false
},
{
"n": "32-38",
"f": 32,
"t": 38,
"c": [],
"path": [
32,
38
],
"p": false
},
{
"n": "42-37",
"f": 42,
"t": 37,
"c": [],
"path": [
42,
37
],
"p": false
},
{
"n": "38x29",
"f": 38,
"t": 29,
"c": [
33
],
"path": [
38,
29
],
"p": false
},
{
"n": "37-32",
"f": 37,
"t": 32,
"c": [],
"path": [
37,
32
],
"p": false
},
{
"n": "29-34",
"f": 29,
"t": 34,
"c": [],
"path": [
29,
34
],
"p": false
},
{
"n": "39x30",
"f": 39,
"t": 30,
"c": [
34
],
"path": [
39,
30
],
"p": false
},
{
"n": "23-29",
"f": 23,
"t": 29,
"c": [],
"path": [
23,
29
],
"p": false
},
{
"n": "32-28",
"f": 32,
"t": 28,
"c": [],
"path": [
32,
28
],
"p": false
},
{
"n": "29-33",
"f": 29,
"t": 33,
"c": [],
"path": [
29,
33
],
"p": false
},
{
"n": "28x39",
"f": 28,
"t": 39,
"c": [
33
],
"path": [
28,
39
],
"p": false
}
],
"theme": "1 dame et 3 pions contre 1 dame et 1",
"pub": "38-33 27-32 43-39 32-38 42-37 38x29 37-32 29-34 39x30 23-29 32-28 29-33 28x39",
"win": "white",
"exp": "1 dame et 3 pions contre 1 dame et 1"
},
"av_fins_de_partie_l4_ex37": {
"id": "av_fins_de_partie_l4_ex37",
"ch": 4,
"title": "1 dame et 3 pions contre 1 dame et 1 – D5",
"start": {
"wm": [
43,
44,
47
],
"wk": [],
"bm": [
28,
31
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "43-38",
"f": 43,
"t": 38,
"c": [],
"path": [
43,
38
],
"p": false
},
{
"n": "31-37",
"f": 31,
"t": 37,
"c": [],
"path": [
31,
37
],
"p": false
},
{
"n": "44-40",
"f": 44,
"t": 40,
"c": [],
"path": [
44,
40
],
"p": false
},
{
"n": "37-42",
"f": 37,
"t": 42,
"c": [],
"path": [
37,
42
],
"p": false
},
{
"n": "38-33",
"f": 38,
"t": 33,
"c": [],
"path": [
38,
33
],
"p": false
},
{
"n": "28x39",
"f": 28,
"t": 39,
"c": [
33
],
"path": [
28,
39
],
"p": false
},
{
"n": "47x38",
"f": 47,
"t": 38,
"c": [
42
],
"path": [
47,
38
],
"p": false
},
{
"n": "39-43",
"f": 39,
"t": 43,
"c": [],
"path": [
39,
43
],
"p": false
},
{
"n": "38x49",
"f": 38,
"t": 49,
"c": [
43
],
"path": [
38,
49
],
"p": false
}
],
"theme": "1 dame et 3 pions contre 1 dame et 1",
"pub": "43-38 31-37 44-40 37-42 38-33 28x39 47x38 39-43 38x49",
"win": "white",
"exp": "1 dame et 3 pions contre 1 dame et 1"
},
"av_fins_de_partie_l4_ex38": {
"id": "av_fins_de_partie_l4_ex38",
"ch": 4,
"title": "1 dame et 3 pions contre 1 dame et 1 – D1",
"start": {
"wm": [
8,
9
],
"wk": [],
"bm": [
5,
32
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "8-2",
"f": 8,
"t": 2,
"c": [],
"path": [
8,
2
],
"p": true
}
],
"theme": "1 dame et 3 pions contre 1 dame et 1",
"pub": "8-2",
"win": "white",
"exp": "1 dame et 3 pions contre 1 dame et 1"
},
"av_fins_de_partie_l4_ex39": {
"id": "av_fins_de_partie_l4_ex39",
"ch": 4,
"title": "1 dame et 3 pions contre 1 dame et 1 – D2",
"start": {
"wm": [
7
],
"wk": [],
"bm": [
6,
9
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "7-1",
"f": 7,
"t": 1,
"c": [],
"path": [
7,
1
],
"p": true
}
],
"theme": "1 dame et 3 pions contre 1 dame et 1",
"pub": "7-1",
"win": "white",
"exp": "1 dame et 3 pions contre 1 dame et 1"
},
"av_fins_de_partie_l4_ex40": {
"id": "av_fins_de_partie_l4_ex40",
"ch": 4,
"title": "1 dame et 3 pions contre 1 dame et 1 – D3",
"start": {
"wm": [
7
],
"wk": [],
"bm": [
6,
9
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "7-1",
"f": 7,
"t": 1,
"c": [],
"path": [
7,
1
],
"p": true
}
],
"theme": "1 dame et 3 pions contre 1 dame et 1",
"pub": "7-1",
"win": "white",
"exp": "1 dame et 3 pions contre 1 dame et 1"
},
"av_fins_de_partie_l4_ex41": {
"id": "av_fins_de_partie_l4_ex41",
"ch": 4,
"title": "1 dame et 3 pions contre 1 dame et 1 – D1",
"start": {
"wm": [
8,
9
],
"wk": [],
"bm": [
5,
32
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "8-2",
"f": 8,
"t": 2,
"c": [],
"path": [
8,
2
],
"p": true
}
],
"theme": "1 dame et 3 pions contre 1 dame et 1",
"pub": "8-2",
"win": "white",
"exp": "1 dame et 3 pions contre 1 dame et 1"
},
"av_fins_de_partie_l4_ex42": {
"id": "av_fins_de_partie_l4_ex42",
"ch": 4,
"title": "1 dame et 3 pions contre 1 dame et 1 – D2",
"start": {
"wm": [
7
],
"wk": [],
"bm": [
6,
9
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "7-1",
"f": 7,
"t": 1,
"c": [],
"path": [
7,
1
],
"p": true
}
],
"theme": "1 dame et 3 pions contre 1 dame et 1",
"pub": "7-1",
"win": "white",
"exp": "1 dame et 3 pions contre 1 dame et 1"
},
"av_fins_de_partie_l4_ex43": {
"id": "av_fins_de_partie_l4_ex43",
"ch": 4,
"title": "1 dame et 3 pions contre 1 dame et 1 – D3",
"start": {
"wm": [
7
],
"wk": [],
"bm": [
6,
9
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "7-1",
"f": 7,
"t": 1,
"c": [],
"path": [
7,
1
],
"p": true
}
],
"theme": "1 dame et 3 pions contre 1 dame et 1",
"pub": "7-1",
"win": "white",
"exp": "1 dame et 3 pions contre 1 dame et 1"
},
"av_fins_de_partie_l4_ex44": {
"id": "av_fins_de_partie_l4_ex44",
"ch": 4,
"title": "1 dame et 3 pions contre 1 dame et 1 – D4",
"start": {
"wm": [
38,
42,
43
],
"wk": [],
"bm": [
23,
27
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "38-33",
"f": 38,
"t": 33,
"c": [],
"path": [
38,
33
],
"p": false
},
{
"n": "27-32",
"f": 27,
"t": 32,
"c": [],
"path": [
27,
32
],
"p": false
},
{
"n": "43-39",
"f": 43,
"t": 39,
"c": [],
"path": [
43,
39
],
"p": false
},
{
"n": "32-38",
"f": 32,
"t": 38,
"c": [],
"path": [
32,
38
],
"p": false
},
{
"n": "42-37",
"f": 42,
"t": 37,
"c": [],
"path": [
42,
37
],
"p": false
},
{
"n": "38x29",
"f": 38,
"t": 29,
"c": [
33
],
"path": [
38,
29
],
"p": false
},
{
"n": "37-32",
"f": 37,
"t": 32,
"c": [],
"path": [
37,
32
],
"p": false
},
{
"n": "29-34",
"f": 29,
"t": 34,
"c": [],
"path": [
29,
34
],
"p": false
},
{
"n": "39x30",
"f": 39,
"t": 30,
"c": [
34
],
"path": [
39,
30
],
"p": false
},
{
"n": "23-29",
"f": 23,
"t": 29,
"c": [],
"path": [
23,
29
],
"p": false
},
{
"n": "32-28",
"f": 32,
"t": 28,
"c": [],
"path": [
32,
28
],
"p": false
},
{
"n": "29-33",
"f": 29,
"t": 33,
"c": [],
"path": [
29,
33
],
"p": false
},
{
"n": "28x39",
"f": 28,
"t": 39,
"c": [
33
],
"path": [
28,
39
],
"p": false
}
],
"theme": "1 dame et 3 pions contre 1 dame et 1",
"pub": "38-33 27-32 43-39 32-38 42-37 38x29 37-32 29-34 39x30 23-29 32-28 29-33 28x39",
"win": "white",
"exp": "1 dame et 3 pions contre 1 dame et 1"
},
"av_fins_de_partie_l4_ex45": {
"id": "av_fins_de_partie_l4_ex45",
"ch": 4,
"title": "1 dame et 3 pions contre 1 dame et 1 – D1",
"start": {
"wm": [
8,
9
],
"wk": [],
"bm": [
5,
32
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "8-2",
"f": 8,
"t": 2,
"c": [],
"path": [
8,
2
],
"p": true
}
],
"theme": "1 dame et 3 pions contre 1 dame et 1",
"pub": "8-2",
"win": "white",
"exp": "1 dame et 3 pions contre 1 dame et 1"
},
"av_fins_de_partie_l4_ex46": {
"id": "av_fins_de_partie_l4_ex46",
"ch": 4,
"title": "1 dame et 3 pions contre 1 dame et 1 – D1",
"start": {
"wm": [
8,
9
],
"wk": [],
"bm": [
5,
32
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "8-2",
"f": 8,
"t": 2,
"c": [],
"path": [
8,
2
],
"p": true
}
],
"theme": "1 dame et 3 pions contre 1 dame et 1",
"pub": "8-2",
"win": "white",
"exp": "1 dame et 3 pions contre 1 dame et 1"
},
"av_fins_de_partie_l4_ex47": {
"id": "av_fins_de_partie_l4_ex47",
"ch": 4,
"title": "1 dame et 3 pions contre 1 dame et 1 – D2",
"start": {
"wm": [
7
],
"wk": [],
"bm": [
6,
9
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "7-1",
"f": 7,
"t": 1,
"c": [],
"path": [
7,
1
],
"p": true
}
],
"theme": "1 dame et 3 pions contre 1 dame et 1",
"pub": "7-1",
"win": "white",
"exp": "1 dame et 3 pions contre 1 dame et 1"
},
"av_fins_de_partie_l4_ex48": {
"id": "av_fins_de_partie_l4_ex48",
"ch": 4,
"title": "1 dame et 3 pions contre 1 dame et 1 – D3",
"start": {
"wm": [
7
],
"wk": [],
"bm": [
6,
9
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "7-1",
"f": 7,
"t": 1,
"c": [],
"path": [
7,
1
],
"p": true
}
],
"theme": "1 dame et 3 pions contre 1 dame et 1",
"pub": "7-1",
"win": "white",
"exp": "1 dame et 3 pions contre 1 dame et 1"
}
}
}

export default DATA
