// Auto-generated by backend/curriculum/build_parcours_manuels.py — do not edit by hand.
import type { ManuelData } from '../ManuelInteractif'

const DATA: ManuelData = {
"book": "Coups nommés avancés",
"level": "Intermédiaire",
"chapters": [
{
"n": 0,
"title": "Présentation"
},
{
"n": 1,
"title": "Le coup royal"
},
{
"n": 2,
"title": "Talon et ricochet"
}
],
"blocks": [
{
"type": "h1",
"ch": 0,
"runs": [
{
"t": "Coups nommés avancés"
}
]
},
{
"type": "p",
"ch": 0,
"runs": [
{
"t": "Les combinaisons nommées en contexte de maître."
}
]
},
{
"type": "p",
"ch": 0,
"runs": [
{
"b": 1,
"t": "Objectif. "
},
{
"t": "Reconnaître le coup royal et les coups de talon/ricochet dans des positions réelles."
}
]
},
{
"type": "h2",
"ch": 1,
"runs": [
{
"t": "Le coup royal"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "Le sacrifice de dame qui rapporte gros. À reconnaître au premier coup d'œil."
}
]
},
{
"type": "board",
"id": "int_coups_avances_l1_ex0",
"ch": 1
},
{
"type": "board",
"id": "int_coups_avances_l1_ex1",
"ch": 1
},
{
"type": "board",
"id": "int_coups_avances_l1_ex2",
"ch": 1
},
{
"type": "board",
"id": "int_coups_avances_l1_ex3",
"ch": 1
},
{
"type": "board",
"id": "int_coups_avances_l1_ex4",
"ch": 1
},
{
"type": "board",
"id": "int_coups_avances_l1_ex5",
"ch": 1
},
{
"type": "board",
"id": "int_coups_avances_l1_pos6",
"ch": 1
},
{
"type": "board",
"id": "int_coups_avances_l1_pos7",
"ch": 1
},
{
"type": "board",
"id": "int_coups_avances_l1_pos8",
"ch": 1
},
{
"type": "board",
"id": "int_coups_avances_l1_pos9",
"ch": 1
},
{
"type": "board",
"id": "int_coups_avances_l1_pos10",
"ch": 1
},
{
"type": "board",
"id": "int_coups_avances_l1_pos11",
"ch": 1
},
{
"type": "h2",
"ch": 2,
"runs": [
{
"t": "Talon et ricochet"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "Deux mécanismes de rafle revisités dans des positions de maître."
}
]
},
{
"type": "board",
"id": "int_coups_avances_l2_ex0",
"ch": 2
},
{
"type": "board",
"id": "int_coups_avances_l2_ex1",
"ch": 2
},
{
"type": "board",
"id": "int_coups_avances_l2_ex2",
"ch": 2
},
{
"type": "board",
"id": "int_coups_avances_l2_ex3",
"ch": 2
},
{
"type": "board",
"id": "int_coups_avances_l2_pos4",
"ch": 2
},
{
"type": "board",
"id": "int_coups_avances_l2_pos5",
"ch": 2
},
{
"type": "board",
"id": "int_coups_avances_l2_pos6",
"ch": 2
},
{
"type": "board",
"id": "int_coups_avances_l2_pos7",
"ch": 2
},
{
"type": "board",
"id": "int_coups_avances_l2_pos8",
"ch": 2
},
{
"type": "board",
"id": "int_coups_avances_l2_pos9",
"ch": 2
}
],
"positions": {
"int_coups_avances_l1_ex0": {
"id": "int_coups_avances_l1_ex0",
"ch": 1,
"title": "SIJBRANDS — combinaison (p.33 #1)",
"start": {
"wm": [
27,
28,
32,
33,
35,
37,
38,
39,
40,
45
],
"wk": [],
"bm": [
6,
11,
12,
13,
14,
18,
19,
23,
24
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "27-22",
"f": 27,
"t": 22,
"c": [],
"path": [
27,
22
],
"p": false
},
{
"n": "18x27",
"f": 18,
"t": 27,
"c": [
22
],
"path": [
18,
27
],
"p": false
},
{
"n": "32x21",
"f": 32,
"t": 21,
"c": [
27
],
"path": [
32,
21
],
"p": false
},
{
"n": "23x32x43x34",
"f": 23,
"t": 34,
"c": [
28,
38,
39
],
"path": [
23,
32,
43,
34
],
"p": false
},
{
"n": "40x29x20x9x18x7x16",
"f": 40,
"t": 16,
"c": [
34,
24,
11,
12,
13,
14
],
"path": [
40,
29,
20,
9,
18,
7,
16
],
"p": false
}
],
"theme": "Le coup royal",
"pub": "27-22 18x27 32x21 23x32x43x34 40x29x20x9x18x7x16",
"win": "white",
"exp": "Le coup royal"
},
"int_coups_avances_l1_ex1": {
"id": "int_coups_avances_l1_ex1",
"ch": 1,
"title": "SIJBRANDS — combinaison (p.33 #2)",
"start": {
"wm": [
28,
32,
37,
38,
39,
40,
45
],
"wk": [],
"bm": [
11,
12,
13,
14,
19,
23,
24
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "32-27",
"f": 32,
"t": 27,
"c": [],
"path": [
32,
27
],
"p": false
},
{
"n": "23x32x43x34",
"f": 23,
"t": 34,
"c": [
28,
38,
39
],
"path": [
23,
32,
43,
34
],
"p": false
},
{
"n": "40x29x20x9x18x7x16",
"f": 40,
"t": 16,
"c": [
34,
24,
11,
12,
13,
14
],
"path": [
40,
29,
20,
9,
18,
7,
16
],
"p": false
}
],
"theme": "Le coup royal",
"pub": "32-27 23x32x43x34 40x29x20x9x18x7x16",
"win": "white",
"exp": "Le coup royal"
},
"int_coups_avances_l1_ex2": {
"id": "int_coups_avances_l1_ex2",
"ch": 1,
"title": "SIJBRANDS — combinaison (p.33 #3)",
"start": {
"wm": [
27,
28,
32,
35,
37,
38,
39,
40,
45
],
"wk": [],
"bm": [
6,
11,
12,
13,
14,
16,
19,
23,
24
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "27-21",
"f": 27,
"t": 21,
"c": [],
"path": [
27,
21
],
"p": false
},
{
"n": "16x27",
"f": 16,
"t": 27,
"c": [
21
],
"path": [
16,
27
],
"p": false
},
{
"n": "32x21",
"f": 32,
"t": 21,
"c": [
27
],
"path": [
32,
21
],
"p": false
},
{
"n": "23x32x43x34",
"f": 23,
"t": 34,
"c": [
28,
38,
39
],
"path": [
23,
32,
43,
34
],
"p": false
},
{
"n": "40x29x20x9x18x7x16",
"f": 40,
"t": 16,
"c": [
34,
24,
11,
12,
13,
14
],
"path": [
40,
29,
20,
9,
18,
7,
16
],
"p": false
}
],
"theme": "Le coup royal",
"pub": "27-21 16x27 32x21 23x32x43x34 40x29x20x9x18x7x16",
"win": "white",
"exp": "Le coup royal"
},
"int_coups_avances_l1_ex3": {
"id": "int_coups_avances_l1_ex3",
"ch": 1,
"title": "SIJBRANDS — combinaison (p.33 #5)",
"start": {
"wm": [
27,
28,
31,
32,
33,
36,
38,
39,
40,
45
],
"wk": [],
"bm": [
3,
11,
12,
13,
14,
16,
18,
19,
23,
24
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "27-21",
"f": 27,
"t": 21,
"c": [],
"path": [
27,
21
],
"p": false
},
{
"n": "16x27",
"f": 16,
"t": 27,
"c": [
21
],
"path": [
16,
27
],
"p": false
},
{
"n": "31x22",
"f": 31,
"t": 22,
"c": [
27
],
"path": [
31,
22
],
"p": false
},
{
"n": "18x27",
"f": 18,
"t": 27,
"c": [
22
],
"path": [
18,
27
],
"p": false
},
{
"n": "32x21",
"f": 32,
"t": 21,
"c": [
27
],
"path": [
32,
21
],
"p": false
},
{
"n": "23x32x43x34",
"f": 23,
"t": 34,
"c": [
28,
38,
39
],
"path": [
23,
32,
43,
34
],
"p": false
},
{
"n": "40x29x20x9x18x7x16",
"f": 40,
"t": 16,
"c": [
34,
24,
11,
12,
13,
14
],
"path": [
40,
29,
20,
9,
18,
7,
16
],
"p": false
}
],
"theme": "Le coup royal",
"pub": "27-21 16x27 31x22 18x27 32x21 23x32x43x34 40x29x20x9x18x7x16",
"win": "white",
"exp": "Le coup royal"
},
"int_coups_avances_l1_ex4": {
"id": "int_coups_avances_l1_ex4",
"ch": 1,
"title": "SIJBRANDS — combinaison (p.33 #6)",
"start": {
"wm": [
27,
28,
32,
33,
37,
38,
39,
40,
45,
48
],
"wk": [],
"bm": [
7,
12,
13,
14,
17,
18,
19,
23,
24,
26
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "27-22",
"f": 27,
"t": 22,
"c": [],
"path": [
27,
22
],
"p": false
},
{
"n": "18x27",
"f": 18,
"t": 27,
"c": [
22
],
"path": [
18,
27
],
"p": false
},
{
"n": "32x21",
"f": 32,
"t": 21,
"c": [
27
],
"path": [
32,
21
],
"p": false
},
{
"n": "23x32x43x34",
"f": 23,
"t": 34,
"c": [
28,
38,
39
],
"path": [
23,
32,
43,
34
],
"p": false
},
{
"n": "40x29x20x9x18",
"f": 40,
"t": 18,
"c": [
24,
34,
13,
14
],
"path": [
40,
29,
20,
9,
18
],
"p": false
},
{
"n": "12x23",
"f": 12,
"t": 23,
"c": [
18
],
"path": [
12,
23
],
"p": false
},
{
"n": "21x12x1",
"f": 21,
"t": 1,
"c": [
17,
7
],
"path": [
21,
12,
1
],
"p": true
}
],
"theme": "Le coup royal",
"pub": "27-22 18x27 32x21 23x32x43x34 40x29x20x9x18 12x23 21x12x1",
"win": "white",
"exp": "Le coup royal"
},
"int_coups_avances_l1_ex5": {
"id": "int_coups_avances_l1_ex5",
"ch": 1,
"title": "SIJBRANDS — combinaison (p.146 #12)",
"start": {
"wm": [
16,
36,
48
],
"wk": [],
"bm": [
19,
37
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "16-11",
"f": 16,
"t": 11,
"c": [],
"path": [
16,
11
],
"p": false
},
{
"n": "19-23",
"f": 19,
"t": 23,
"c": [],
"path": [
19,
23
],
"p": false
},
{
"n": "11-7",
"f": 11,
"t": 7,
"c": [],
"path": [
11,
7
],
"p": false
},
{
"n": "23-28",
"f": 23,
"t": 28,
"c": [],
"path": [
23,
28
],
"p": false
},
{
"n": "7-2",
"f": 7,
"t": 2,
"c": [],
"path": [
7,
2
],
"p": true
},
{
"n": "28-33",
"f": 28,
"t": 33,
"c": [],
"path": [
28,
33
],
"p": false
},
{
"n": "2-16",
"f": 2,
"t": 16,
"c": [],
"path": [
2,
16
],
"p": false
},
{
"n": "33-39",
"f": 33,
"t": 39,
"c": [],
"path": [
33,
39
],
"p": false
},
{
"n": "16-49",
"f": 16,
"t": 49,
"c": [],
"path": [
16,
49
],
"p": false
},
{
"n": "37-42",
"f": 37,
"t": 42,
"c": [],
"path": [
37,
42
],
"p": false
},
{
"n": "48x37",
"f": 48,
"t": 37,
"c": [
42
],
"path": [
48,
37
],
"p": false
},
{
"n": "39-43",
"f": 39,
"t": 43,
"c": [],
"path": [
39,
43
],
"p": false
},
{
"n": "49x38",
"f": 49,
"t": 38,
"c": [
43
],
"path": [
49,
38
],
"p": false
}
],
"theme": "Le coup royal",
"pub": "16-11 19-23 11-7 23-28 7-2 28-33 2-16 33-39 16-49 37-42 48x37 39-43 49x38",
"win": "white",
"exp": "Le coup royal"
},
"int_coups_avances_l1_pos6": {
"id": "int_coups_avances_l1_pos6",
"ch": 1,
"title": "Le coup royal",
"start": {
"wm": [
27,
28,
32,
33,
35,
37,
38,
39,
44,
45
],
"wk": [],
"bm": [
6,
11,
12,
13,
14,
16,
18,
19,
23,
24
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Le coup royal"
},
"int_coups_avances_l1_pos7": {
"id": "int_coups_avances_l1_pos7",
"ch": 1,
"title": "Le coup royal",
"start": {
"wm": [
27,
28,
32,
33,
35,
37,
38,
39,
40,
45
],
"wk": [],
"bm": [
6,
11,
12,
13,
14,
18,
19,
23,
24
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "27-22",
"f": 27,
"t": 22,
"c": [],
"path": [
27,
22
],
"p": false
},
{
"n": "18x27",
"f": 18,
"t": 27,
"c": [
22
],
"path": [
18,
27
],
"p": false
},
{
"n": "32x21",
"f": 32,
"t": 21,
"c": [
27
],
"path": [
32,
21
],
"p": false
},
{
"n": "23x32x43x34",
"f": 23,
"t": 34,
"c": [
28,
38,
39
],
"path": [
23,
32,
43,
34
],
"p": false
},
{
"n": "40x29x20x9x18x7x16",
"f": 40,
"t": 16,
"c": [
34,
24,
11,
12,
13,
14
],
"path": [
40,
29,
20,
9,
18,
7,
16
],
"p": false
}
],
"theme": "Le coup royal",
"pub": "27-22 18x27 32x21 23x32x43x34 40x29x20x9x18x7x16",
"win": "white"
},
"int_coups_avances_l1_pos8": {
"id": "int_coups_avances_l1_pos8",
"ch": 1,
"title": "Le coup royal",
"start": {
"wm": [
28,
32,
37,
38,
39,
40,
45
],
"wk": [],
"bm": [
11,
12,
13,
14,
19,
23,
24
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "32-27",
"f": 32,
"t": 27,
"c": [],
"path": [
32,
27
],
"p": false
},
{
"n": "23x32x43x34",
"f": 23,
"t": 34,
"c": [
28,
38,
39
],
"path": [
23,
32,
43,
34
],
"p": false
},
{
"n": "40x29x20x9x18x7x16",
"f": 40,
"t": 16,
"c": [
34,
24,
11,
12,
13,
14
],
"path": [
40,
29,
20,
9,
18,
7,
16
],
"p": false
}
],
"theme": "Le coup royal",
"pub": "32-27 23x32x43x34 40x29x20x9x18x7x16",
"win": "white"
},
"int_coups_avances_l1_pos9": {
"id": "int_coups_avances_l1_pos9",
"ch": 1,
"title": "Le coup royal",
"start": {
"wm": [
27,
28,
32,
35,
37,
38,
39,
40,
45
],
"wk": [],
"bm": [
6,
11,
12,
13,
14,
16,
19,
23,
24
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "27-21",
"f": 27,
"t": 21,
"c": [],
"path": [
27,
21
],
"p": false
},
{
"n": "16x27",
"f": 16,
"t": 27,
"c": [
21
],
"path": [
16,
27
],
"p": false
},
{
"n": "32x21",
"f": 32,
"t": 21,
"c": [
27
],
"path": [
32,
21
],
"p": false
},
{
"n": "23x32x43x34",
"f": 23,
"t": 34,
"c": [
28,
38,
39
],
"path": [
23,
32,
43,
34
],
"p": false
},
{
"n": "40x29x20x9x18x7x16",
"f": 40,
"t": 16,
"c": [
34,
24,
11,
12,
13,
14
],
"path": [
40,
29,
20,
9,
18,
7,
16
],
"p": false
}
],
"theme": "Le coup royal",
"pub": "27-21 16x27 32x21 23x32x43x34 40x29x20x9x18x7x16",
"win": "white"
},
"int_coups_avances_l1_pos10": {
"id": "int_coups_avances_l1_pos10",
"ch": 1,
"title": "Le coup royal",
"start": {
"wm": [
27,
32,
33,
35,
38,
39,
40,
45,
48
],
"wk": [],
"bm": [
11,
12,
13,
14,
16,
18,
19,
23,
24
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Le coup royal"
},
"int_coups_avances_l1_pos11": {
"id": "int_coups_avances_l1_pos11",
"ch": 1,
"title": "Le coup royal",
"start": {
"wm": [
27,
28,
31,
32,
33,
36,
38,
39,
40,
45
],
"wk": [],
"bm": [
3,
11,
12,
13,
14,
16,
18,
19,
23,
24
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "27-21",
"f": 27,
"t": 21,
"c": [],
"path": [
27,
21
],
"p": false
},
{
"n": "16x27",
"f": 16,
"t": 27,
"c": [
21
],
"path": [
16,
27
],
"p": false
},
{
"n": "31x22",
"f": 31,
"t": 22,
"c": [
27
],
"path": [
31,
22
],
"p": false
},
{
"n": "18x27",
"f": 18,
"t": 27,
"c": [
22
],
"path": [
18,
27
],
"p": false
},
{
"n": "32x21",
"f": 32,
"t": 21,
"c": [
27
],
"path": [
32,
21
],
"p": false
},
{
"n": "23x32x43x34",
"f": 23,
"t": 34,
"c": [
28,
38,
39
],
"path": [
23,
32,
43,
34
],
"p": false
},
{
"n": "40x29x20x9x18x7x16",
"f": 40,
"t": 16,
"c": [
34,
24,
11,
12,
13,
14
],
"path": [
40,
29,
20,
9,
18,
7,
16
],
"p": false
}
],
"theme": "Le coup royal",
"pub": "27-21 16x27 31x22 18x27 32x21 23x32x43x34 40x29x20x9x18x7x16",
"win": "white"
},
"int_coups_avances_l2_ex0": {
"id": "int_coups_avances_l2_ex0",
"ch": 2,
"title": "SIJBRANDS — combinaison (p.14 #1)",
"start": {
"wm": [
28,
32,
37,
38,
43
],
"wk": [],
"bm": [
11,
19,
21,
23,
26
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "37-31",
"f": 37,
"t": 31,
"c": [],
"path": [
37,
31
],
"p": false
},
{
"n": "26x37",
"f": 26,
"t": 37,
"c": [
31
],
"path": [
26,
37
],
"p": false
},
{
"n": "32x41",
"f": 32,
"t": 41,
"c": [
37
],
"path": [
32,
41
],
"p": false
},
{
"n": "23x32",
"f": 23,
"t": 32,
"c": [
28
],
"path": [
23,
32
],
"p": false
},
{
"n": "38x27x16x7",
"f": 38,
"t": 7,
"c": [
32,
11,
21
],
"path": [
38,
27,
16,
7
],
"p": false
}
],
"theme": "Le coup de talon et le coup de ricochet",
"pub": "37-31 26x37 32x41 23x32 38x27x16x7",
"win": "white",
"exp": "Le coup de talon et le coup de ricochet"
},
"int_coups_avances_l2_ex1": {
"id": "int_coups_avances_l2_ex1",
"ch": 2,
"title": "SIJBRANDS — combinaison (p.14 #2)",
"start": {
"wm": [
24,
29,
32,
34,
39,
40,
44
],
"wk": [],
"bm": [
8,
9,
10,
15,
18,
20,
22
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "32-28",
"f": 32,
"t": 28,
"c": [],
"path": [
32,
28
],
"p": false
},
{
"n": "22x33",
"f": 22,
"t": 33,
"c": [
28
],
"path": [
22,
33
],
"p": false
},
{
"n": "29x38",
"f": 29,
"t": 38,
"c": [
33
],
"path": [
29,
38
],
"p": false
},
{
"n": "20x29",
"f": 20,
"t": 29,
"c": [
24
],
"path": [
20,
29
],
"p": false
},
{
"n": "34x23x12x3x14x5",
"f": 34,
"t": 5,
"c": [
18,
8,
9,
10,
29
],
"path": [
34,
23,
12,
3,
14,
5
],
"p": true
}
],
"theme": "Le coup de talon et le coup de ricochet",
"pub": "32-28 22x33 29x38 20x29 34x23x12x3x14x5",
"win": "white",
"exp": "Le coup de talon et le coup de ricochet"
},
"int_coups_avances_l2_ex2": {
"id": "int_coups_avances_l2_ex2",
"ch": 2,
"title": "SIJBRANDS — combinaison (p.14 #3)",
"start": {
"wm": [
27,
32,
33,
34,
37,
39,
44
],
"wk": [],
"bm": [
7,
13,
18,
25,
26,
30,
35
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "44-40",
"f": 44,
"t": 40,
"c": [],
"path": [
44,
40
],
"p": false
},
{
"n": "35x44",
"f": 35,
"t": 44,
"c": [
40
],
"path": [
35,
44
],
"p": false
},
{
"n": "39x50",
"f": 39,
"t": 50,
"c": [
44
],
"path": [
39,
50
],
"p": false
},
{
"n": "30x39x28",
"f": 30,
"t": 28,
"c": [
33,
34
],
"path": [
30,
39,
28
],
"p": false
},
{
"n": "32x23x12x1",
"f": 32,
"t": 1,
"c": [
18,
28,
7
],
"path": [
32,
23,
12,
1
],
"p": true
}
],
"theme": "Le coup de talon et le coup de ricochet",
"pub": "44-40 35x44 39x50 30x39x28 32x23x12x1",
"win": "white",
"exp": "Le coup de talon et le coup de ricochet"
},
"int_coups_avances_l2_ex3": {
"id": "int_coups_avances_l2_ex3",
"ch": 2,
"title": "SIJBRANDS — combinaison (p.15 #5)",
"start": {
"wm": [
28,
32,
33,
34,
40,
45
],
"wk": [],
"bm": [
9,
13,
19,
21,
23,
25
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "34-30",
"f": 34,
"t": 30,
"c": [],
"path": [
34,
30
],
"p": false
},
{
"n": "25x34",
"f": 25,
"t": 34,
"c": [
30
],
"path": [
25,
34
],
"p": false
},
{
"n": "40x29x18",
"f": 40,
"t": 18,
"c": [
34,
23
],
"path": [
40,
29,
18
],
"p": false
},
{
"n": "13x22",
"f": 13,
"t": 22,
"c": [
18
],
"path": [
13,
22
],
"p": false
},
{
"n": "28x17x26",
"f": 28,
"t": 26,
"c": [
21,
22
],
"path": [
28,
17,
26
],
"p": false
}
],
"theme": "Le coup de talon et le coup de ricochet",
"pub": "34-30 25x34 40x29x18 13x22 28x17x26",
"win": "white",
"exp": "Le coup de talon et le coup de ricochet"
},
"int_coups_avances_l2_pos4": {
"id": "int_coups_avances_l2_pos4",
"ch": 2,
"title": "Le coup de talon et le coup de ricochet",
"start": {
"wm": [
28,
32,
33,
34,
40,
45
],
"wk": [],
"bm": [
9,
13,
19,
21,
23,
25
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "34-30",
"f": 34,
"t": 30,
"c": [],
"path": [
34,
30
],
"p": false
},
{
"n": "25x34",
"f": 25,
"t": 34,
"c": [
30
],
"path": [
25,
34
],
"p": false
},
{
"n": "40x29x18",
"f": 40,
"t": 18,
"c": [
34,
23
],
"path": [
40,
29,
18
],
"p": false
},
{
"n": "13x22",
"f": 13,
"t": 22,
"c": [
18
],
"path": [
13,
22
],
"p": false
},
{
"n": "28x17x26",
"f": 28,
"t": 26,
"c": [
21,
22
],
"path": [
28,
17,
26
],
"p": false
}
],
"theme": "Le coup de talon et le coup de ricochet",
"pub": "34-30 25x34 40x29x18 13x22 28x17x26",
"win": "white"
},
"int_coups_avances_l2_pos5": {
"id": "int_coups_avances_l2_pos5",
"ch": 2,
"title": "Le coup de talon et le coup de ricochet",
"start": {
"wm": [
27,
28,
32,
33,
34,
37,
38,
39,
40,
43,
45,
47,
48
],
"wk": [],
"bm": [
3,
8,
9,
13,
14,
15,
16,
18,
19,
20,
21,
23,
25
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Le coup de talon et le coup de ricochet"
},
"int_coups_avances_l2_pos6": {
"id": "int_coups_avances_l2_pos6",
"ch": 2,
"title": "Le coup de talon et le coup de ricochet",
"start": {
"wm": [
27,
28,
32,
33,
34,
35,
36,
37,
38,
40,
45
],
"wk": [],
"bm": [
3,
9,
11,
13,
16,
18,
19,
21,
23,
25,
26
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Le coup de talon et le coup de ricochet"
},
"int_coups_avances_l2_pos7": {
"id": "int_coups_avances_l2_pos7",
"ch": 2,
"title": "Le coup de talon et le coup de ricochet",
"start": {
"wm": [
27,
28,
32,
33,
35,
38,
40,
42,
45
],
"wk": [],
"bm": [
3,
9,
11,
13,
15,
16,
19,
23,
25
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Le coup de talon et le coup de ricochet"
},
"int_coups_avances_l2_pos8": {
"id": "int_coups_avances_l2_pos8",
"ch": 2,
"title": "Le coup de talon et le coup de ricochet",
"start": {
"wm": [
27,
28,
31,
32,
33,
34,
35,
36,
38,
40,
45,
48
],
"wk": [],
"bm": [
3,
9,
13,
15,
16,
17,
18,
19,
21,
23,
24,
25
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Le coup de talon et le coup de ricochet"
},
"int_coups_avances_l2_pos9": {
"id": "int_coups_avances_l2_pos9",
"ch": 2,
"title": "Le coup de talon et le coup de ricochet",
"start": {
"wm": [
28,
32,
37,
38,
43
],
"wk": [],
"bm": [
11,
19,
21,
23,
26
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "37-31",
"f": 37,
"t": 31,
"c": [],
"path": [
37,
31
],
"p": false
},
{
"n": "26x37",
"f": 26,
"t": 37,
"c": [
31
],
"path": [
26,
37
],
"p": false
},
{
"n": "32x41",
"f": 32,
"t": 41,
"c": [
37
],
"path": [
32,
41
],
"p": false
},
{
"n": "23x32",
"f": 23,
"t": 32,
"c": [
28
],
"path": [
23,
32
],
"p": false
},
{
"n": "38x27x16x7",
"f": 38,
"t": 7,
"c": [
32,
11,
21
],
"path": [
38,
27,
16,
7
],
"p": false
}
],
"theme": "Le coup de talon et le coup de ricochet",
"pub": "37-31 26x37 32x41 23x32 38x27x16x7",
"win": "white"
}
}
}

export default DATA
