// Auto-generated by backend/curriculum/build_parcours_manuels.py — do not edit by hand.
import type { ManuelData } from '../ManuelInteractif'

const DATA: ManuelData = {
"book": "Finales et opposition",
"level": "Intermédiaire",
"chapters": [
{
"n": 0,
"title": "Présentation"
},
{
"n": 1,
"title": "L'opposition"
},
{
"n": 2,
"title": "Finales pratiques"
},
{
"n": 3,
"title": "Finales à dames"
}
],
"blocks": [
{
"type": "h1",
"ch": 0,
"runs": [
{
"t": "Finales et opposition"
}
]
},
{
"type": "p",
"ch": 0,
"runs": [
{
"t": "Convertir, ou sauver, les fins de partie."
}
]
},
{
"type": "p",
"ch": 0,
"runs": [
{
"b": 1,
"t": "Objectif. "
},
{
"t": "Gagner ou sauver les finales élémentaires grâce à l'opposition et au comptage."
}
]
},
{
"type": "h2",
"ch": 1,
"runs": [
{
"t": "L'opposition"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "L'arme reine des finales : prendre l'opposition pour gagner le tempo décisif."
}
]
},
{
"type": "board",
"id": "int_finales_l1_ex0",
"ch": 1
},
{
"type": "board",
"id": "int_finales_l1_ex1",
"ch": 1
},
{
"type": "board",
"id": "int_finales_l1_ex2",
"ch": 1
},
{
"type": "board",
"id": "int_finales_l1_ex3",
"ch": 1
},
{
"type": "board",
"id": "int_finales_l1_ex4",
"ch": 1
},
{
"type": "board",
"id": "int_finales_l1_pos5",
"ch": 1
},
{
"type": "board",
"id": "int_finales_l1_pos6",
"ch": 1
},
{
"type": "board",
"id": "int_finales_l1_pos7",
"ch": 1
},
{
"type": "board",
"id": "int_finales_l1_pos8",
"ch": 1
},
{
"type": "board",
"id": "int_finales_l1_pos9",
"ch": 1
},
{
"type": "board",
"id": "int_finales_l1_pos10",
"ch": 1
},
{
"type": "h2",
"ch": 2,
"runs": [
{
"t": "Finales pratiques"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "Dame contre pions, finales de tric-trac : les positions concrètes qui décident des parties."
}
]
},
{
"type": "board",
"id": "int_finales_l2_ex0",
"ch": 2
},
{
"type": "board",
"id": "int_finales_l2_ex1",
"ch": 2
},
{
"type": "board",
"id": "int_finales_l2_ex2",
"ch": 2
},
{
"type": "board",
"id": "int_finales_l2_ex3",
"ch": 2
},
{
"type": "board",
"id": "int_finales_l2_ex4",
"ch": 2
},
{
"type": "board",
"id": "int_finales_l2_ex5",
"ch": 2
},
{
"type": "board",
"id": "int_finales_l2_pos6",
"ch": 2
},
{
"type": "board",
"id": "int_finales_l2_pos7",
"ch": 2
},
{
"type": "board",
"id": "int_finales_l2_pos8",
"ch": 2
},
{
"type": "board",
"id": "int_finales_l2_pos9",
"ch": 2
},
{
"type": "board",
"id": "int_finales_l2_pos10",
"ch": 2
},
{
"type": "board",
"id": "int_finales_l2_pos11",
"ch": 2
},
{
"type": "h2",
"ch": 3,
"runs": [
{
"t": "Finales à dames"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "Un aperçu des fins de partie à dames — dame contre pions, dame et pions contre dame. Le niveau Avancé les approfondit."
}
]
},
{
"type": "board",
"id": "int_finales_l3_pos0",
"ch": 3
},
{
"type": "board",
"id": "int_finales_l3_pos1",
"ch": 3
},
{
"type": "board",
"id": "int_finales_l3_pos2",
"ch": 3
},
{
"type": "board",
"id": "int_finales_l3_pos3",
"ch": 3
},
{
"type": "board",
"id": "int_finales_l3_pos4",
"ch": 3
},
{
"type": "board",
"id": "int_finales_l3_pos5",
"ch": 3
}
],
"positions": {
"int_finales_l1_ex0": {
"id": "int_finales_l1_ex0",
"ch": 1,
"title": "SIJBRANDS — combinaison (p.88 #3)",
"start": {
"wm": [
24,
35,
45
],
"wk": [],
"bm": [
23
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "24-19",
"f": 24,
"t": 19,
"c": [],
"path": [
24,
19
],
"p": false
},
{
"n": "23x14",
"f": 23,
"t": 14,
"c": [
19
],
"path": [
23,
14
],
"p": false
},
{
"n": "35-30",
"f": 35,
"t": 30,
"c": [],
"path": [
35,
30
],
"p": false
},
{
"n": "14-19",
"f": 14,
"t": 19,
"c": [],
"path": [
14,
19
],
"p": false
},
{
"n": "30-24",
"f": 30,
"t": 24,
"c": [],
"path": [
30,
24
],
"p": false
},
{
"n": "19x30",
"f": 19,
"t": 30,
"c": [
24
],
"path": [
19,
30
],
"p": false
},
{
"n": "45-40",
"f": 45,
"t": 40,
"c": [],
"path": [
45,
40
],
"p": false
},
{
"n": "30-35",
"f": 30,
"t": 35,
"c": [],
"path": [
30,
35
],
"p": false
},
{
"n": "40-34",
"f": 40,
"t": 34,
"c": [],
"path": [
40,
34
],
"p": false
},
{
"n": "35-40",
"f": 35,
"t": 40,
"c": [],
"path": [
35,
40
],
"p": false
},
{
"n": "34x45",
"f": 34,
"t": 45,
"c": [
40
],
"path": [
34,
45
],
"p": false
}
],
"theme": "L’opposition",
"pub": "24-19 23x14 35-30 14-19 30-24 19x30 45-40 30-35 40-34 35-40 34x45",
"win": "white",
"exp": "L’opposition"
},
"int_finales_l1_ex1": {
"id": "int_finales_l1_ex1",
"ch": 1,
"title": "SIJBRANDS — combinaison (p.89 #4)",
"start": {
"wm": [
46,
48
],
"wk": [],
"bm": [
31,
38
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "46-41",
"f": 46,
"t": 41,
"c": [],
"path": [
46,
41
],
"p": false
},
{
"n": "31-36",
"f": 31,
"t": 36,
"c": [],
"path": [
31,
36
],
"p": false
},
{
"n": "41-37",
"f": 41,
"t": 37,
"c": [],
"path": [
41,
37
],
"p": false
},
{
"n": "38-42",
"f": 38,
"t": 42,
"c": [],
"path": [
38,
42
],
"p": false
},
{
"n": "37-31",
"f": 37,
"t": 31,
"c": [],
"path": [
37,
31
],
"p": false
},
{
"n": "36x27",
"f": 36,
"t": 27,
"c": [
31
],
"path": [
36,
27
],
"p": false
},
{
"n": "48x37",
"f": 48,
"t": 37,
"c": [
42
],
"path": [
48,
37
],
"p": false
},
{
"n": "27-31",
"f": 27,
"t": 31,
"c": [],
"path": [
27,
31
],
"p": false
},
{
"n": "37x26",
"f": 37,
"t": 26,
"c": [
31
],
"path": [
37,
26
],
"p": false
}
],
"theme": "L’opposition",
"pub": "46-41 31-36 41-37 38-42 37-31 36x27 48x37 27-31 37x26",
"win": "white",
"exp": "L’opposition"
},
"int_finales_l1_ex2": {
"id": "int_finales_l1_ex2",
"ch": 1,
"title": "SIJBRANDS — combinaison (p.89 #6)",
"start": {
"wm": [
39,
43,
44
],
"wk": [],
"bm": [
24,
30
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "44-40",
"f": 44,
"t": 40,
"c": [],
"path": [
44,
40
],
"p": false
},
{
"n": "30-35",
"f": 30,
"t": 35,
"c": [],
"path": [
30,
35
],
"p": false
},
{
"n": "40-34",
"f": 40,
"t": 34,
"c": [],
"path": [
40,
34
],
"p": false
},
{
"n": "24-29",
"f": 24,
"t": 29,
"c": [],
"path": [
24,
29
],
"p": false
},
{
"n": "34x23",
"f": 34,
"t": 23,
"c": [
29
],
"path": [
34,
23
],
"p": false
},
{
"n": "35-40",
"f": 35,
"t": 40,
"c": [],
"path": [
35,
40
],
"p": false
},
{
"n": "39-34",
"f": 39,
"t": 34,
"c": [],
"path": [
39,
34
],
"p": false
},
{
"n": "40x29x18",
"f": 40,
"t": 18,
"c": [
34,
23
],
"path": [
40,
29,
18
],
"p": false
},
{
"n": "43-38",
"f": 43,
"t": 38,
"c": [],
"path": [
43,
38
],
"p": false
},
{
"n": "18-23",
"f": 18,
"t": 23,
"c": [],
"path": [
18,
23
],
"p": false
},
{
"n": "38-33",
"f": 38,
"t": 33,
"c": [],
"path": [
38,
33
],
"p": false
},
{
"n": "23-28",
"f": 23,
"t": 28,
"c": [],
"path": [
23,
28
],
"p": false
},
{
"n": "33x22",
"f": 33,
"t": 22,
"c": [
28
],
"path": [
33,
22
],
"p": false
}
],
"theme": "L’opposition",
"pub": "44-40 30-35 40-34 24-29 34x23 35-40 39-34 40x29x18 43-38 18-23 38-33 23-28 33x22",
"win": "white",
"exp": "L’opposition"
},
"int_finales_l1_ex3": {
"id": "int_finales_l1_ex3",
"ch": 1,
"title": "SIJBRANDS — combinaison (p.89 #7)",
"start": {
"wm": [
33
],
"wk": [],
"bm": [
18
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "33-28",
"f": 33,
"t": 28,
"c": [],
"path": [
33,
28
],
"p": false
},
{
"n": "18-22",
"f": 18,
"t": 22,
"c": [],
"path": [
18,
22
],
"p": false
},
{
"n": "28x17",
"f": 28,
"t": 17,
"c": [
22
],
"path": [
28,
17
],
"p": false
}
],
"theme": "L’opposition",
"pub": "33-28 18-22 28x17",
"win": "white",
"exp": "L’opposition"
},
"int_finales_l1_ex4": {
"id": "int_finales_l1_ex4",
"ch": 1,
"title": "SIJBRANDS — combinaison (p.89 #8)",
"start": {
"wm": [
49
],
"wk": [],
"bm": [
11
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "49-43",
"f": 49,
"t": 43,
"c": [],
"path": [
49,
43
],
"p": false
},
{
"n": "11-17",
"f": 11,
"t": 17,
"c": [],
"path": [
11,
17
],
"p": false
},
{
"n": "43-38",
"f": 43,
"t": 38,
"c": [],
"path": [
43,
38
],
"p": false
},
{
"n": "17-21",
"f": 17,
"t": 21,
"c": [],
"path": [
17,
21
],
"p": false
},
{
"n": "38-32",
"f": 38,
"t": 32,
"c": [],
"path": [
38,
32
],
"p": false
},
{
"n": "21-26",
"f": 21,
"t": 26,
"c": [],
"path": [
21,
26
],
"p": false
},
{
"n": "32-27",
"f": 32,
"t": 27,
"c": [],
"path": [
32,
27
],
"p": false
},
{
"n": "26-31",
"f": 26,
"t": 31,
"c": [],
"path": [
26,
31
],
"p": false
},
{
"n": "27x36",
"f": 27,
"t": 36,
"c": [
31
],
"path": [
27,
36
],
"p": false
}
],
"theme": "L’opposition",
"pub": "49-43 11-17 43-38 17-21 38-32 21-26 32-27 26-31 27x36",
"win": "white",
"exp": "L’opposition"
},
"int_finales_l1_pos5": {
"id": "int_finales_l1_pos5",
"ch": 1,
"title": "L’opposition",
"start": {
"wm": [
48
],
"wk": [
39
],
"bm": [
20,
25,
43
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "L’opposition"
},
"int_finales_l1_pos6": {
"id": "int_finales_l1_pos6",
"ch": 1,
"title": "L’opposition",
"start": {
"wm": [
48
],
"wk": [],
"bm": [
3
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "48-42",
"f": 48,
"t": 42,
"c": [],
"path": [
48,
42
],
"p": false
},
{
"n": "3-9",
"f": 3,
"t": 9,
"c": [],
"path": [
3,
9
],
"p": false
},
{
"n": "42-38",
"f": 42,
"t": 38,
"c": [],
"path": [
42,
38
],
"p": false
},
{
"n": "9-14",
"f": 9,
"t": 14,
"c": [],
"path": [
9,
14
],
"p": false
},
{
"n": "38-33",
"f": 38,
"t": 33,
"c": [],
"path": [
38,
33
],
"p": false
},
{
"n": "14-20",
"f": 14,
"t": 20,
"c": [],
"path": [
14,
20
],
"p": false
},
{
"n": "33-29",
"f": 33,
"t": 29,
"c": [],
"path": [
33,
29
],
"p": false
},
{
"n": "20-25",
"f": 20,
"t": 25,
"c": [],
"path": [
20,
25
],
"p": false
},
{
"n": "29-24",
"f": 29,
"t": 24,
"c": [],
"path": [
29,
24
],
"p": false
},
{
"n": "25-30",
"f": 25,
"t": 30,
"c": [],
"path": [
25,
30
],
"p": false
},
{
"n": "24x35",
"f": 24,
"t": 35,
"c": [
30
],
"path": [
24,
35
],
"p": false
}
],
"theme": "L’opposition",
"pub": "48-42 3-9 42-38 9-14 38-33 14-20 33-29 20-25 29-24 25-30 24x35",
"win": "white"
},
"int_finales_l1_pos7": {
"id": "int_finales_l1_pos7",
"ch": 1,
"title": "L’opposition",
"start": {
"wm": [
48
],
"wk": [],
"bm": [
12
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "48-42",
"f": 48,
"t": 42,
"c": [],
"path": [
48,
42
],
"p": false
},
{
"n": "12-17",
"f": 12,
"t": 17,
"c": [],
"path": [
12,
17
],
"p": false
},
{
"n": "42-37",
"f": 42,
"t": 37,
"c": [],
"path": [
42,
37
],
"p": false
},
{
"n": "17-21",
"f": 17,
"t": 21,
"c": [],
"path": [
17,
21
],
"p": false
},
{
"n": "37-32",
"f": 37,
"t": 32,
"c": [],
"path": [
37,
32
],
"p": false
},
{
"n": "21-26",
"f": 21,
"t": 26,
"c": [],
"path": [
21,
26
],
"p": false
},
{
"n": "32-27",
"f": 32,
"t": 27,
"c": [],
"path": [
32,
27
],
"p": false
},
{
"n": "26-31",
"f": 26,
"t": 31,
"c": [],
"path": [
26,
31
],
"p": false
},
{
"n": "27x36",
"f": 27,
"t": 36,
"c": [
31
],
"path": [
27,
36
],
"p": false
}
],
"theme": "L’opposition",
"pub": "48-42 12-17 42-37 17-21 37-32 21-26 32-27 26-31 27x36",
"win": "white"
},
"int_finales_l1_pos8": {
"id": "int_finales_l1_pos8",
"ch": 1,
"title": "L’opposition",
"start": {
"wm": [
42,
43,
47
],
"wk": [],
"bm": [
34
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "L’opposition"
},
"int_finales_l1_pos9": {
"id": "int_finales_l1_pos9",
"ch": 1,
"title": "L’opposition",
"start": {
"wm": [
24,
35,
45
],
"wk": [],
"bm": [
23
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "24-19",
"f": 24,
"t": 19,
"c": [],
"path": [
24,
19
],
"p": false
},
{
"n": "23x14",
"f": 23,
"t": 14,
"c": [
19
],
"path": [
23,
14
],
"p": false
},
{
"n": "35-30",
"f": 35,
"t": 30,
"c": [],
"path": [
35,
30
],
"p": false
},
{
"n": "14-19",
"f": 14,
"t": 19,
"c": [],
"path": [
14,
19
],
"p": false
},
{
"n": "30-24",
"f": 30,
"t": 24,
"c": [],
"path": [
30,
24
],
"p": false
},
{
"n": "19x30",
"f": 19,
"t": 30,
"c": [
24
],
"path": [
19,
30
],
"p": false
},
{
"n": "45-40",
"f": 45,
"t": 40,
"c": [],
"path": [
45,
40
],
"p": false
},
{
"n": "30-35",
"f": 30,
"t": 35,
"c": [],
"path": [
30,
35
],
"p": false
},
{
"n": "40-34",
"f": 40,
"t": 34,
"c": [],
"path": [
40,
34
],
"p": false
},
{
"n": "35-40",
"f": 35,
"t": 40,
"c": [],
"path": [
35,
40
],
"p": false
},
{
"n": "34x45",
"f": 34,
"t": 45,
"c": [
40
],
"path": [
34,
45
],
"p": false
}
],
"theme": "L’opposition",
"pub": "24-19 23x14 35-30 14-19 30-24 19x30 45-40 30-35 40-34 35-40 34x45",
"win": "white"
},
"int_finales_l1_pos10": {
"id": "int_finales_l1_pos10",
"ch": 1,
"title": "L’opposition",
"start": {
"wm": [
46,
48
],
"wk": [],
"bm": [
31,
38
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "46-41",
"f": 46,
"t": 41,
"c": [],
"path": [
46,
41
],
"p": false
},
{
"n": "31-36",
"f": 31,
"t": 36,
"c": [],
"path": [
31,
36
],
"p": false
},
{
"n": "41-37",
"f": 41,
"t": 37,
"c": [],
"path": [
41,
37
],
"p": false
},
{
"n": "38-42",
"f": 38,
"t": 42,
"c": [],
"path": [
38,
42
],
"p": false
},
{
"n": "37-31",
"f": 37,
"t": 31,
"c": [],
"path": [
37,
31
],
"p": false
},
{
"n": "36x27",
"f": 36,
"t": 27,
"c": [
31
],
"path": [
36,
27
],
"p": false
},
{
"n": "48x37",
"f": 48,
"t": 37,
"c": [
42
],
"path": [
48,
37
],
"p": false
},
{
"n": "27-31",
"f": 27,
"t": 31,
"c": [],
"path": [
27,
31
],
"p": false
},
{
"n": "37x26",
"f": 37,
"t": 26,
"c": [
31
],
"path": [
37,
26
],
"p": false
}
],
"theme": "L’opposition",
"pub": "46-41 31-36 41-37 38-42 37-31 36x27 48x37 27-31 37x26",
"win": "white"
},
"int_finales_l2_ex0": {
"id": "int_finales_l2_ex0",
"ch": 2,
"title": "SIJBRANDS — combinaison (p.95 #2)",
"start": {
"wm": [],
"wk": [
34
],
"bm": [
17,
25
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "34-39",
"f": 34,
"t": 39,
"c": [],
"path": [
34,
39
],
"p": false
},
{
"n": "17-21",
"f": 17,
"t": 21,
"c": [],
"path": [
17,
21
],
"p": false
},
{
"n": "39-43",
"f": 39,
"t": 43,
"c": [],
"path": [
39,
43
],
"p": false
},
{
"n": "21-26",
"f": 21,
"t": 26,
"c": [],
"path": [
21,
26
],
"p": false
},
{
"n": "43-48",
"f": 43,
"t": 48,
"c": [],
"path": [
43,
48
],
"p": false
},
{
"n": "25-30",
"f": 25,
"t": 30,
"c": [],
"path": [
25,
30
],
"p": false
},
{
"n": "48x25",
"f": 48,
"t": 25,
"c": [
30
],
"path": [
48,
25
],
"p": false
},
{
"n": "26-31",
"f": 26,
"t": 31,
"c": [],
"path": [
26,
31
],
"p": false
},
{
"n": "25-14",
"f": 25,
"t": 14,
"c": [],
"path": [
25,
14
],
"p": false
},
{
"n": "31-36",
"f": 31,
"t": 36,
"c": [],
"path": [
31,
36
],
"p": false
},
{
"n": "14-23",
"f": 14,
"t": 23,
"c": [],
"path": [
14,
23
],
"p": false
},
{
"n": "36-41",
"f": 36,
"t": 41,
"c": [],
"path": [
36,
41
],
"p": false
},
{
"n": "23x46",
"f": 23,
"t": 46,
"c": [
41
],
"path": [
23,
46
],
"p": false
}
],
"theme": "Une dame contre des pions",
"pub": "34-39 17-21 39-43 21-26 43-48 25-30 48x25 26-31 25-14 31-36 14-23 36-41 23x46",
"win": "white",
"exp": "Une dame contre des pions"
},
"int_finales_l2_ex1": {
"id": "int_finales_l2_ex1",
"ch": 2,
"title": "SIJBRANDS — combinaison (p.95 #4)",
"start": {
"wm": [
8
],
"wk": [],
"bm": [
10,
16
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "8-3",
"f": 8,
"t": 3,
"c": [],
"path": [
8,
3
],
"p": true
}
],
"theme": "Une dame contre des pions",
"pub": "8-3",
"win": "white",
"exp": "Une dame contre des pions"
},
"int_finales_l2_ex2": {
"id": "int_finales_l2_ex2",
"ch": 2,
"title": "SIJBRANDS — combinaison (p.107 #2)",
"start": {
"wm": [
12,
50
],
"wk": [],
"bm": [
35,
45
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "12-7",
"f": 12,
"t": 7,
"c": [],
"path": [
12,
7
],
"p": false
},
{
"n": "35-40",
"f": 35,
"t": 40,
"c": [],
"path": [
35,
40
],
"p": false
},
{
"n": "7-1",
"f": 7,
"t": 1,
"c": [],
"path": [
7,
1
],
"p": true
},
{
"n": "40-44",
"f": 40,
"t": 44,
"c": [],
"path": [
40,
44
],
"p": false
},
{
"n": "50x39",
"f": 50,
"t": 39,
"c": [
44
],
"path": [
50,
39
],
"p": false
},
{
"n": "45-50",
"f": 45,
"t": 50,
"c": [],
"path": [
45,
50
],
"p": true
},
{
"n": "1-6",
"f": 1,
"t": 6,
"c": [],
"path": [
1,
6
],
"p": false
},
{
"n": "50x33",
"f": 50,
"t": 33,
"c": [
39
],
"path": [
50,
33
],
"p": false
},
{
"n": "6x39",
"f": 6,
"t": 39,
"c": [
33
],
"path": [
6,
39
],
"p": false
}
],
"theme": "Fins de partie dans le tric-trac",
"pub": "12-7 35-40 7-1 40-44 50x39 45-50 1-6 50x33 6x39",
"win": "white",
"exp": "Fins de partie dans le tric-trac"
},
"int_finales_l2_ex3": {
"id": "int_finales_l2_ex3",
"ch": 2,
"title": "SIJBRANDS — combinaison (p.107 #3)",
"start": {
"wm": [
10,
47
],
"wk": [],
"bm": [
25,
35
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "10-5",
"f": 10,
"t": 5,
"c": [],
"path": [
10,
5
],
"p": true
}
],
"theme": "Fins de partie dans le tric-trac",
"pub": "10-5",
"win": "white",
"exp": "Fins de partie dans le tric-trac"
},
"int_finales_l2_ex4": {
"id": "int_finales_l2_ex4",
"ch": 2,
"title": "SIJBRANDS — combinaison (p.132 #6)",
"start": {
"wm": [
24,
43,
45,
50
],
"wk": [],
"bm": [
14,
26,
32,
35
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "43-38",
"f": 43,
"t": 38,
"c": [],
"path": [
43,
38
],
"p": false
},
{
"n": "32x43",
"f": 32,
"t": 43,
"c": [
38
],
"path": [
32,
43
],
"p": false
},
{
"n": "45-40",
"f": 45,
"t": 40,
"c": [],
"path": [
45,
40
],
"p": false
},
{
"n": "35x44",
"f": 35,
"t": 44,
"c": [
40
],
"path": [
35,
44
],
"p": false
},
{
"n": "50x39x48",
"f": 50,
"t": 48,
"c": [
43,
44
],
"path": [
50,
39,
48
],
"p": false
},
{
"n": "26-31",
"f": 26,
"t": 31,
"c": [],
"path": [
26,
31
],
"p": false
},
{
"n": "48-42",
"f": 48,
"t": 42,
"c": [],
"path": [
48,
42
],
"p": false
},
{
"n": "31-36",
"f": 31,
"t": 36,
"c": [],
"path": [
31,
36
],
"p": false
},
{
"n": "42-37",
"f": 42,
"t": 37,
"c": [],
"path": [
42,
37
],
"p": false
},
{
"n": "14-20",
"f": 14,
"t": 20,
"c": [],
"path": [
14,
20
],
"p": false
},
{
"n": "24x15",
"f": 24,
"t": 15,
"c": [
20
],
"path": [
24,
15
],
"p": false
},
{
"n": "36-41",
"f": 36,
"t": 41,
"c": [],
"path": [
36,
41
],
"p": false
},
{
"n": "37x46",
"f": 37,
"t": 46,
"c": [
41
],
"path": [
37,
46
],
"p": false
}
],
"theme": "La fin de partie",
"pub": "43-38 32x43 45-40 35x44 50x39x48 26-31 48-42 31-36 42-37 14-20 24x15 36-41 37x46",
"win": "white",
"exp": "La fin de partie"
},
"int_finales_l2_ex5": {
"id": "int_finales_l2_ex5",
"ch": 2,
"title": "SIJBRANDS — combinaison (p.199 #10)",
"start": {
"wm": [
25,
35,
45
],
"wk": [],
"bm": [
5,
24
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "45-40",
"f": 45,
"t": 40,
"c": [],
"path": [
45,
40
],
"p": false
},
{
"n": "5-10",
"f": 5,
"t": 10,
"c": [],
"path": [
5,
10
],
"p": false
},
{
"n": "40-34",
"f": 40,
"t": 34,
"c": [],
"path": [
40,
34
],
"p": false
},
{
"n": "10-14",
"f": 10,
"t": 14,
"c": [],
"path": [
10,
14
],
"p": false
},
{
"n": "34-30",
"f": 34,
"t": 30,
"c": [],
"path": [
34,
30
],
"p": false
},
{
"n": "14-19",
"f": 14,
"t": 19,
"c": [],
"path": [
14,
19
],
"p": false
},
{
"n": "25-20",
"f": 25,
"t": 20,
"c": [],
"path": [
25,
20
],
"p": false
},
{
"n": "24x15",
"f": 24,
"t": 15,
"c": [
20
],
"path": [
24,
15
],
"p": false
},
{
"n": "30-24",
"f": 30,
"t": 24,
"c": [],
"path": [
30,
24
],
"p": false
},
{
"n": "19x30",
"f": 19,
"t": 30,
"c": [
24
],
"path": [
19,
30
],
"p": false
},
{
"n": "35x24",
"f": 35,
"t": 24,
"c": [
30
],
"path": [
35,
24
],
"p": false
},
{
"n": "15-20",
"f": 15,
"t": 20,
"c": [],
"path": [
15,
20
],
"p": false
},
{
"n": "24x15",
"f": 24,
"t": 15,
"c": [
20
],
"path": [
24,
15
],
"p": false
}
],
"theme": "La fin de partie",
"pub": "45-40 5-10 40-34 10-14 34-30 14-19 25-20 24x15 30-24 19x30 35x24 15-20 24x15",
"win": "white",
"exp": "La fin de partie"
},
"int_finales_l2_pos6": {
"id": "int_finales_l2_pos6",
"ch": 2,
"title": "Une dame contre des pions",
"start": {
"wm": [],
"wk": [
1
],
"bm": [
10,
21
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Une dame contre des pions"
},
"int_finales_l2_pos7": {
"id": "int_finales_l2_pos7",
"ch": 2,
"title": "Une dame contre des pions",
"start": {
"wm": [],
"wk": [
34
],
"bm": [
17,
25
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "34-39",
"f": 34,
"t": 39,
"c": [],
"path": [
34,
39
],
"p": false
},
{
"n": "17-21",
"f": 17,
"t": 21,
"c": [],
"path": [
17,
21
],
"p": false
},
{
"n": "39-43",
"f": 39,
"t": 43,
"c": [],
"path": [
39,
43
],
"p": false
},
{
"n": "21-26",
"f": 21,
"t": 26,
"c": [],
"path": [
21,
26
],
"p": false
},
{
"n": "43-48",
"f": 43,
"t": 48,
"c": [],
"path": [
43,
48
],
"p": false
},
{
"n": "25-30",
"f": 25,
"t": 30,
"c": [],
"path": [
25,
30
],
"p": false
},
{
"n": "48x25",
"f": 48,
"t": 25,
"c": [
30
],
"path": [
48,
25
],
"p": false
},
{
"n": "26-31",
"f": 26,
"t": 31,
"c": [],
"path": [
26,
31
],
"p": false
},
{
"n": "25-14",
"f": 25,
"t": 14,
"c": [],
"path": [
25,
14
],
"p": false
},
{
"n": "31-36",
"f": 31,
"t": 36,
"c": [],
"path": [
31,
36
],
"p": false
},
{
"n": "14-23",
"f": 14,
"t": 23,
"c": [],
"path": [
14,
23
],
"p": false
},
{
"n": "36-41",
"f": 36,
"t": 41,
"c": [],
"path": [
36,
41
],
"p": false
},
{
"n": "23x46",
"f": 23,
"t": 46,
"c": [
41
],
"path": [
23,
46
],
"p": false
}
],
"theme": "Une dame contre des pions",
"pub": "34-39 17-21 39-43 21-26 43-48 25-30 48x25 26-31 25-14 31-36 14-23 36-41 23x46",
"win": "white"
},
"int_finales_l2_pos8": {
"id": "int_finales_l2_pos8",
"ch": 2,
"title": "Une dame contre des pions",
"start": {
"wm": [],
"wk": [
16
],
"bm": [
6,
30
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Une dame contre des pions"
},
"int_finales_l2_pos9": {
"id": "int_finales_l2_pos9",
"ch": 2,
"title": "Une dame contre des pions",
"start": {
"wm": [],
"wk": [
38
],
"bm": [
16,
28
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "38-27",
"f": 38,
"t": 27,
"c": [],
"path": [
38,
27
],
"p": false
},
{
"n": "28-33",
"f": 28,
"t": 33,
"c": [],
"path": [
28,
33
],
"p": false
},
{
"n": "27-43",
"f": 27,
"t": 43,
"c": [],
"path": [
27,
43
],
"p": false
},
{
"n": "33-39",
"f": 33,
"t": 39,
"c": [],
"path": [
33,
39
],
"p": false
},
{
"n": "43x34",
"f": 43,
"t": 34,
"c": [
39
],
"path": [
43,
34
],
"p": false
},
{
"n": "16-21",
"f": 16,
"t": 21,
"c": [],
"path": [
16,
21
],
"p": false
},
{
"n": "34-18",
"f": 34,
"t": 18,
"c": [],
"path": [
34,
18
],
"p": false
},
{
"n": "21-26",
"f": 21,
"t": 26,
"c": [],
"path": [
21,
26
],
"p": false
},
{
"n": "18-27",
"f": 18,
"t": 27,
"c": [],
"path": [
18,
27
],
"p": false
},
{
"n": "26-31",
"f": 26,
"t": 31,
"c": [],
"path": [
26,
31
],
"p": false
},
{
"n": "27x36",
"f": 27,
"t": 36,
"c": [
31
],
"path": [
27,
36
],
"p": false
}
],
"theme": "Une dame contre des pions",
"pub": "38-27 28-33 27-43 33-39 43x34 16-21 34-18 21-26 18-27 26-31 27x36",
"win": "white"
},
"int_finales_l2_pos10": {
"id": "int_finales_l2_pos10",
"ch": 2,
"title": "Une dame contre des pions",
"start": {
"wm": [
8
],
"wk": [],
"bm": [
10,
16
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "8-3",
"f": 8,
"t": 3,
"c": [],
"path": [
8,
3
],
"p": true
}
],
"theme": "Une dame contre des pions",
"pub": "8-3",
"win": "white"
},
"int_finales_l2_pos11": {
"id": "int_finales_l2_pos11",
"ch": 2,
"title": "Une dame contre des pions",
"start": {
"wm": [
7
],
"wk": [],
"bm": [
13,
33
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Une dame contre des pions"
},
"int_finales_l3_pos0": {
"id": "int_finales_l3_pos0",
"ch": 3,
"title": "1 dame contre 2 pions",
"start": {
"wm": [
24,
27
],
"wk": [
41
],
"bm": [
15,
16,
18
],
"bk": [
21
],
"turn": "white"
},
"moves": [
{
"n": "41-36",
"f": 41,
"t": 36,
"c": [],
"path": [
41,
36
],
"p": false
},
{
"n": "21x38x20",
"f": 21,
"t": 20,
"c": [
24,
27
],
"path": [
21,
38,
20
],
"p": false
},
{
"n": "36x9x25",
"f": 36,
"t": 25,
"c": [
18,
20
],
"path": [
36,
9,
25
],
"p": false
}
],
"theme": "1 dame contre 2 pions",
"pub": "41-36 21x38x20 36x9x25",
"win": "white"
},
"int_finales_l3_pos1": {
"id": "int_finales_l3_pos1",
"ch": 3,
"title": "1 dame contre 2 pions",
"start": {
"wm": [
10,
35
],
"wk": [
36
],
"bm": [
16,
33
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "10-4",
"f": 10,
"t": 4,
"c": [],
"path": [
10,
4
],
"p": true
}
],
"theme": "1 dame contre 2 pions",
"pub": "10-4",
"win": "white"
},
"int_finales_l3_pos2": {
"id": "int_finales_l3_pos2",
"ch": 3,
"title": "1 dame contre 2 pions",
"start": {
"wm": [
24,
47
],
"wk": [
48
],
"bm": [
7,
15,
21,
38
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "1 dame contre 2 pions"
},
"int_finales_l3_pos3": {
"id": "int_finales_l3_pos3",
"ch": 3,
"title": "1 dame contre 2 pions",
"start": {
"wm": [
24,
34,
38,
39,
40
],
"wk": [
28
],
"bm": [
15,
25,
26
],
"bk": [
47
],
"turn": "white"
},
"moves": [],
"theme": "1 dame contre 2 pions"
},
"int_finales_l3_pos4": {
"id": "int_finales_l3_pos4",
"ch": 3,
"title": "1 dame contre 2 pions",
"start": {
"wm": [
25,
37
],
"wk": [
24,
46
],
"bm": [
9,
15,
26
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "37-31",
"f": 37,
"t": 31,
"c": [],
"path": [
37,
31
],
"p": false
},
{
"n": "26x37",
"f": 26,
"t": 37,
"c": [
31
],
"path": [
26,
37
],
"p": false
},
{
"n": "46x14x3",
"f": 46,
"t": 3,
"c": [
9,
37
],
"path": [
46,
14,
3
],
"p": false
},
{
"n": "15-20",
"f": 15,
"t": 20,
"c": [],
"path": [
15,
20
],
"p": false
},
{
"n": "24x15",
"f": 24,
"t": 15,
"c": [
20
],
"path": [
24,
15
],
"p": false
}
],
"theme": "1 dame contre 2 pions",
"pub": "37-31 26x37 46x14x3 15-20 24x15",
"win": "white"
},
"int_finales_l3_pos5": {
"id": "int_finales_l3_pos5",
"ch": 3,
"title": "1 dame contre 2 pions",
"start": {
"wm": [
39,
45
],
"wk": [
9
],
"bm": [
6,
15,
17,
24,
32,
35
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "1 dame contre 2 pions"
}
}
}

export default DATA
