// Auto-generated by backend/curriculum/build_parcours_manuels.py — do not edit by hand.
import type { ManuelData } from '../ManuelInteractif'

const DATA: ManuelData = {
"book": "Pions et formations avancés",
"level": "Intermédiaire",
"chapters": [
{
"n": 0,
"title": "Présentation"
},
{
"n": 1,
"title": "Le pion blanc 45"
},
{
"n": 2,
"title": "Le pion blanc 35"
},
{
"n": 3,
"title": "La formation 45-40"
},
{
"n": 4,
"title": "La flèche 33-38-42"
},
{
"n": 5,
"title": "La formation 34-39-43"
}
],
"blocks": [
{
"type": "h1",
"ch": 0,
"runs": [
{
"t": "Pions et formations avancés"
}
]
},
{
"type": "p",
"ch": 0,
"runs": [
{
"t": "Pions 45/35 et formations types."
}
]
},
{
"type": "p",
"ch": 0,
"runs": [
{
"b": 1,
"t": "Objectif. "
},
{
"t": "Reconnaître et jouer les formations clés (45-40, flèche 33-38-42, 34-39-43) et les pions 45/35."
}
]
},
{
"type": "h2",
"ch": 1,
"runs": [
{
"t": "Le pion blanc 45"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "Chapitre 5 : le pion blanc 45 Le pion 45 est un pion d’angle placé sur la droite du damier. Il est dans une certaine mesure équivalent au pion d’angle 46, positionné sur l’autre aile du damier. Ce pion 45 est très important dans la mesure où il sert de support au couple 40-45, si utile dans le mécanisme du coup royal, et de support à la flèche 34-40-45, essentielle dans les actions sur l’aile droite. Ce pion 45 peut également devenir un pion arrière dans certains cas de figure. Les diagrammes suivants résument parfaitement l’ambivalence de ce pion :"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "Trait aux noirs"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "Trait aux blancs"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "Dans le premier diagramme, les noirs sont menacés du coup royal par 27-22 (18x27) 32x21 (23x34) 40x7. Les noirs sont forcés de jouer : 1…"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "14-20"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "2. 39-34 !"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "Les blancs forment la flèche 34-40-45 afin de déloger les noirs du centre. 2…"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "12-17"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "Après (20-25) 34-29 (23x34) 40x20 (25x14) 33-29, les blancs s’emparent du centre, mais c’est ici insuffisant pour gagner : (14-20) 28-23x23 (20-25) 38-33 (25-30) 45-40 (30-34) 40-35 (16-21) 27x16 (18-22) 29x40 (22-27) etc. 3. 34-29 6. 29x20"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "23x34 25x14"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "4. 40x29 7. 33-29"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "17-21 14-20"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "5. 45-40 8. 38-33"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "20-25 19-24!"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "Sur (20-25), les blancs on tune jolie manière de gagner par 29-24 (19x30) 40-35 (18-22) 27x9 (21-27) 35x24 ! (27x20) 9-3 (20-24) 3-12 etc. 9. 28-23"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "18-22 !"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "10. 27x9"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "20-25"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "11. 29x20"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "25x3 etc.="
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "Dans le second diagramme, on voit clairement que le pion 45 est un pion “arrière” et que les 3 pions blancs sont tenus en respect par seulement 2 pions noirs. Dans le troisième diagramme, la situation est assez subtile. Le pion 45 ne peut être mis en jeu en raison de (18-23) 28x30 (25x45)."
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "Le diagramme suivant illustre bien les problèmes que peuvent rencontrer les blancs lorsque leur pion 45 est injouable : Wim van der SLUIS – Viacheslav SHCHEGOLEV Championnat d’Europe 1971 47e temps – trait aux noirs 47…"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "7-11"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "48. 27-21"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "45-40 et 43-39 sont évidemment interdits par (19-23). Le coup du texte est perdant, mais après 38-32 (11-16) 43-38 forcé (17-21x21) ! 28-22 (8-13) ! 45-40 (18-23) 33-28, les noirs concluent par la combinaison (13-18) 22x13 (19x8) 28x30 (25x45). 48…"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "11-16 !"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "49. 43-39"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "16x27"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "Et les blancs peuvent abandonner car le coup de dame 28-22 (17x28) 33x2 perd après (19-23) 2x30 (25x32)."
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "A présent, 1 situation dans laquelle la mise en jeu du pion 45 s’intègre parfaitement avec le plan de jeu général des blancs : Trait aux blancs 1. 45-40 La sortie du pion 45 vers la case 34 vient renforcer la flèche 3338-42 et introduit la menace de coup philippe. Les noirs ont à présent 4 possibilités : A – (15-20) 40-34 (20-25) et les blancs exécutent le coup philippe par 27-22 (18x27) 32x21 (16x27) 33-29 (24x33) 38x9. B – (24-30) 40-34 (30-35) 33-29 etc. C – (24-29) 33x24 (19x30) 40-35 etc. D – (23-29) 39-34 et si : D1 – (19-23) 34-30 (24x35) 33x24 etc. D2 – (18-23) 44-39 etc."
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "COMPLEMENT Dans les années 90, j’avais publié dans le bulletin de ligue Rhône Alpes une chronique traitant de la faiblesse du pion 45. J’en restitue ici une partie : Trait aux blancs 1. 32-27!"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "22x31"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "2. 36x27!"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "Elimine le pion 22 et assure le contrôle du centre noir 23 et 24. 2..."
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "12-17"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "(23-29) n’améliore pas vraiment la situation car les noirs déportent leur jeu sur leur gauche et laissent aux blancs une importante mobilité sur l’autre aile: 33-28 (18-23) 38-32 (6-11) 41-36! (12-18) [sur (11-17) 27-22 etc] 28-22! (11-17) 22x11 (16x7) 43-38 etc. 3. 38-32 5. 41-36 7. 33-28!"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "23-29 22x31"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "4. 43-38 6. 36x27"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "17-22 6-11"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "Les noirs peuvent abandonner car sur (18-23) suit 38-33 etc. Baba SY - Hugo VERPOEST tournoi olympique 1960 37e temps – trait aux blancs 37. 32-27! 39. 36x27"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "12-18 14-19"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "38. 31-26! 40. 26-21!"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "22x31"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "les blancs exploitent la position car (6-11) livre le coup de dame 33-28 (23x32) 27x38 (16x27) 38-32 (27x38) 39-33 (38x29) 34x3 40… 9-13 42. 48-42 20-24 44. 42-38 B+"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "41. 21-17 43. 40-35"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "15-20 4-9"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "Trait aux blancs Les blancs forcent le gain par : 1. 48-43!"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "12-18"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "Forcé car (23-29) perd par 38-33 (29x49) 32-28 (49x21) 26x8 2. 38-33"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "7-11"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "4. 33-28! B+"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "3. 43-38!"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "11-17"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "Trait aux blancs"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "Les blancs gagnent par : 1. 31-26! 22x31 3. 21x12 18x7 5. 26-21 +"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "2. 36x27 4. 38-32!"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "11-17 7-11"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "Trait aux blancs Les blancs gagnent par : 1. 37-32! 13-19 3. 32-28 B+"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "2. 33-29!"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "11-17"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "Trait aux blancs Les blancs gagnent astucieusement par : 1. 49-44!!"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "12-17"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "(6-11) est interdit et le coup de dame (23-28) et (13-19) est évidemment perdant. 2. 33-29"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "24x33"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "3. 39x28 B+"
}
]
},
{
"type": "board",
"id": "int_sdj_formations_l1_dia0",
"ch": 1
},
{
"type": "board",
"id": "int_sdj_formations_l1_dia1",
"ch": 1
},
{
"type": "board",
"id": "int_sdj_formations_l1_dia2",
"ch": 1
},
{
"type": "board",
"id": "int_sdj_formations_l1_dia3",
"ch": 1
},
{
"type": "board",
"id": "int_sdj_formations_l1_dia4",
"ch": 1
},
{
"type": "board",
"id": "int_sdj_formations_l1_dia5",
"ch": 1
},
{
"type": "board",
"id": "int_sdj_formations_l1_dia6",
"ch": 1
},
{
"type": "board",
"id": "int_sdj_formations_l1_dia7",
"ch": 1
},
{
"type": "board",
"id": "int_sdj_formations_l1_ex0",
"ch": 1
},
{
"type": "board",
"id": "int_sdj_formations_l1_ex1",
"ch": 1
},
{
"type": "board",
"id": "int_sdj_formations_l1_ex2",
"ch": 1
},
{
"type": "board",
"id": "int_sdj_formations_l1_ex3",
"ch": 1
},
{
"type": "h2",
"ch": 2,
"runs": [
{
"t": "Le pion blanc 35"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "Chapitre 6 : le pion blanc 35 Le pion blanc 35 ne présente aucun intérêt stratégique. Sa seule fonction est de venir en appui du pion 30. Trait aux blancs Dans l’exemple suivant, le couple de pions 35 et 30 permet aux blancs d’investir l’importante case stratégique 24 par : 1. 30-24"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "19x30"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "2. 35x24"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "Trait aux noirs En classique, la formation 30-35 joue un rôle important pour le contrôle de l’aile gauche adverse. 1…"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "23-29"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "2. 28-23"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "19x39"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "3. 30x8"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "12x3"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "4. 27-21"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "16x27"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "14-19"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "3. 44-39"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "20-25"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "5. 32x43"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "En début de partie, après par exemple : 1. 33-29 4. 29x20"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "19-24 25x14"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "2. 39-33"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "Trait aux blancs Dans cette situation neutre positionnellement, la mise en jeu du pion inactif 35 est constructive. Le pion 35 sera toujours plus utile sur la case 25. 5. 35-30"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "Trait aux blancs Une situation qui se présente assez régulièrement en début de partie. Les blancs peuvent profiter de l’absence de pion en 8 pour jouer : 1. 35-30 Et si : A – (20-25) les blancs se regroupent favorablement par 30-24 (19x30) 28-23 (18x29) 33x35 B – (18-23) 30-25 (23x32) 38x27 et l’aile gauche des noirs est alors assez difficile à développer."
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "Trait aux blancs Une situation intéressante dans laquelle la sortie du pion 35 se révèle très utile. Les noirs se sont formés pour reprendre le centre par (19-23). Le coup suivant les en empêche astucieusement : 1. 35-30"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "18-23"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "En effet (19-23) échoue sur 28x19 (13x35) 37-31 ! (26x28) 33x4 Par ailleurs, (11-17) livre le coup de l’espagnol par 27-22 (18x27) 32x21 (16x27) 37-31 (26x37) 42x11 (6x17) 28-23 (19x28) 33x11. La réponse des noirs 1… (14-20) est ici bien meilleure. Le coup du texte introduit une variante qu’il est utile de connaître. 2. 40-35 Un coup qui a du sens car le pion 35 vient en support du pion 30 pour pionner à 24. 2… 5. 35x24"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "12-18 26-31"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "3. 30-24"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "19x30"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "4. 28x19"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "14x23"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "Les noirs n’ont pas vraiment de meilleure alternative. L’attaque directe 5…(23-29) est évidemment interdite par 24-19 (13x24) 37-31 (26x28) 33x4. La sortie 5… (11-17) perd le pion par 24-19 etc. 6. 37x26"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "23-29"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "7. 24-20"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "15x24"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "8. 32-28"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "La perte d’un pion pour les noirs est à présent inévitable : A – (18-22) 27x18 (13x22) 28x11 (11x22) 44-40 suivi de 39-34 B – Sur tout autre coup 28-23. Andris Andreiko – Sergej Mansjien Championnat URSS 1971 Trait aux noirs Une tournure combinatoire prise après la sortie 35-30 : 35… 14-20 Livre un coup de dame. Après (4-9) 44-40 les blancs ne peuvent toujours pas jouer (14-20) en raison de 37-31 (26x37) 32x41 (23x43) 30-24 (20x38) 39-33 (21x32) 48x39 (38x29) 34x5 (32-38) 5-28 etc. 36. 37-31 38. 33-29 40. 34x5"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "26x37 21x32 43x23"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "37. 32x41 39. 30-24"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "23x43 19x30"
}
]
},
{
"type": "board",
"id": "int_sdj_formations_l2_dia0",
"ch": 2
},
{
"type": "board",
"id": "int_sdj_formations_l2_dia1",
"ch": 2
},
{
"type": "board",
"id": "int_sdj_formations_l2_dia2",
"ch": 2
},
{
"type": "board",
"id": "int_sdj_formations_l2_dia3",
"ch": 2
},
{
"type": "board",
"id": "int_sdj_formations_l2_dia4",
"ch": 2
},
{
"type": "board",
"id": "int_sdj_formations_l2_dia5",
"ch": 2
},
{
"type": "board",
"id": "int_sdj_formations_l2_dia6",
"ch": 2
},
{
"type": "board",
"id": "int_sdj_formations_l2_ex0",
"ch": 2
},
{
"type": "board",
"id": "int_sdj_formations_l2_ex1",
"ch": 2
},
{
"type": "board",
"id": "int_sdj_formations_l2_ex2",
"ch": 2
},
{
"type": "board",
"id": "int_sdj_formations_l2_ex3",
"ch": 2
},
{
"type": "h2",
"ch": 3,
"runs": [
{
"t": "La formation 45-40"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "Chapitre 1 : la formation 45-40 Cette association de 2 pions 45 et 40 est appelée formation olympique par les Russes, et le coup royal qui lui est associé, est lui-même dénommé coup olympique. Cette formation est utile en partie classique pour menacer du coup royal, créer une flèche 34-40-45, ou encore assurer quelques coups de réserve sur l’aile droite."
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "Cette formation de 2 pions est particulièrement intéressante lorsqu’elle est associée à l’étoile centrale 27-28-32-37-38 comme l’illustre le diagramme ci-contre. Il est important de noter que cette formation est plus efficace et plus économique en l’absence de pion à 35. Cette formation est encore plus efficace en présence d’un pion blanc en 25."
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "Nous allons à présent détailler les situations qui se présentent en fin de milieu de partie classique."
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "1 – LA MENACE DE COUP ROYAL Nikolai Sretenski – Jurij Kolodiev 1971 Trait aux blancs 43. 27-22 Le coup royal immédiat par 37-31 conduit à la nulle. 43…"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "11-16"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "Livre le coup royal, mais après (15-20) 39-34, la position des noirs est sans espoir. 44. 32-27 46. 45-40"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "23x34 12x23"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "45. 40x18 47. 22-17 +"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "8-12"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "G. de Bruijn – Flip Jernberg Amsterdam-ch 2e klasse, 1939 Trait aux noirs Les coups des noirs sont limités 42…"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "3-9"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "Le seul coup jouable pour éviter le coup royal, mais les noirs se retrouvent avec un pion arrière à 9. 43. 40-35 11-17 28x17 23-29"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "44. 45-40 46. 40-34 etc."
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "17-22"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "45."
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "Trait aux blancs Le bon coup positionnel 39-34 est réfuté par (24-29). Les blancs peuvent malgré tout tirer avantage de leur formation 45-40 en utilisant le coup Royal : 1. 37-31"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "23-29"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "L’attaque (21-26) est évidemment interdite par 27-22 etc. Après (13-18) 28-22 (8-13), les blancs poursuivent par 31-26. Après (12-17) 31-26 (13-18), 39-34 est décisif 2. 28-22"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "15-20"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "3. 40-35 etc."
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "2 – POUR CONTENIR L’AILE GAUCHE ADVERSE Iser Kouperman – Miguel J Wallen Match Wallen - Koeperman, 1986 Trait aux blancs Les noirs ont 3 pions en 23-24-25 et pas de pion en 8. Les blancs peuvent rendre inopérante l’aile gauche adverse en jouant : 45. 40-34 47. 33-28"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "17-22 24-30"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "46. 28x17"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "21x12"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "49. 38-33 51. 47-42"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "35x44 17-22"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "Sur (12-17), suit simplement 27-22. 48. 45-40 50. 39x50 52. 28x17"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "30-35 12-17 19-24 etc."
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "Cor Westerveld – Raoul Alias NHO-ch Hoofdklassse, 1997 Trait aux blancs La situation sur l’aile droite des blancs est encore plus caractéristique dans cette position avec, en plus le pion arrière noir en 15. 57. 40-34"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "18-23"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "Après (20-25) 45-40, les noirs doivent jouer (18-23) pour éviter 2823. 58. 45-40"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "24-29"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "Après (20-25) 39-33 (13-18) 40-35 (15-20), l’attaque à contretemps 28-22 est décisive. 59. 28-22 62. 27-21"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "19-24 16x27"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "60. 22-17 63. 32x21"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "13-18 15-20"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "61. 39-33 20-25 64.21-16 etc.+"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "Trait aux blancs La position de chaque pion est importante. Le pion 39, par exemple, peut jouer un rôle vers les cases 33 ou 34. De même, le pion 40 peut aller en 34 ou 35. Cette flexibilité est importante. 1. 40-34 Le meilleur moyen de contrer l’avancée ultérieure en 29. Après 40-35 (8-12), l’avancée (23-29) équilibre le jeu, aussi bien après 45-40 qu’après 39-34. 1…"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "8-12"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "2. 45-40"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "21-26"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "Sur (23-29) 34x23 (18x29), suit 27-22 puis 39-34 au bon moment. On mesure l’importance du pion 39. 3. 40-35 L’intention 36-31 est contrée par (12-17) 38-33 (17-22) et (24-29) etc. = 3…"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "23-29"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "4. 27-22"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "Et les blancs conservent de bonnes perspectives Trait aux blancs Un autre exemple de l’intérêt de monter par 40-34 lorsque les noirs ont 3 pions en 23-24-25. 1. 40-34"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "24-29"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "Les noirs doivent choisir entre ce coup et la fin de partie (20-25) 45-40 (7-11) 38-33 (11-16) 40-35 (25-30) 34x25 (23-29) 28-23 (29x38) 23x12 (16-21) 27x16 (38x27) 12-7 etc. 2. 45-40 4. 35x44 etc."
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "7-11"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "Avec"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "énorme"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "un"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "3. 40-35 avantage"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "pour"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "29x40 les"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "blancs"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "Trait aux blancs Là encore, la montée 40-34 est plus efficace que la flèche 45-4034 obtenue après 39-34. 1. 40-34"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "11-17"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "L’avancée à 30 par (24-30) ne sert à rien après 45-40 (30-35) 3731 etc. 2. 37-31 4. 45-40 6. 33-28"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "17-21 17-22 12-17 ou ?"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "3. 31-26 12-17 5. 28x17 21x12 7. 27-22 etc."
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "3 – UNE RESERVE DE TEMPS INTERESSANTE Trait aux blancs Dans certains cas de figure, la formation 45-40 peut représenter un intéressant réservoir de temps. Par exemple : 1. 40-34"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "17-21"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "2. 45-40"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "6-11"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "(13-18) est en effet interdit par 27-22 (18x27) 28-22 (27x18) 37-31 (26x28) 33x4 3. 40-35 5. 27-22"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "11-17"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "4. 34-30"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "23-29"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "Une attaque à contretemps décisive car après (29-34) et les prises, suit toujours 28-23."
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "Trait aux blancs 1. 40-35"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "11-17"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "2. 45-40"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "17-21"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "3. 40-34 Et les noirs n’ont rien de mieux que : 3.."
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "24-29"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "4. 33x24"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "19x30"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "5. 28x10"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "18-23"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "6. 35x24"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "23-28"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "7. 32x23"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "21x41"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "8. 39-33"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "Et les noirs se retrouvent avec une finale perdante, en raison des crochets."
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "Trait aux noirs 1…"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "7-12"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "Après (23-29) 42-38 (18-23) 40-35, les noirs doivent sacrifier un pion pour éviter 35-30. 2. 42-38"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "15-20"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "Après (12-17) 27-22 etc. la fin de partie est sans espoir pour les noirs 3. 40-35"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "12-17"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "5. 40-34 etc."
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "4. 45-40"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "17-21"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "4 – L’OCCUPATION TERRITORIALE Trait aux blancs La formation 45-40 associée à un pion 25 offre beaucoup de perspectives contre le centre adverse. 1. 39-34 La colonne de choc 45-40-34, avec la menace 34-29, force les noirs à quitter la case stratégique 24. 1…"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "24-30"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "2. 34-29"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "23x34"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "3. 40x29"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "30-35"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "4. 42-38"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "17-22"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "5. 28x17"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "21x12"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "6. 32-28 +"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "Trait aux blancs"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "1. 39-34"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "14-20"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "2. 34-29"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "23x34"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "3. 40x29"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "20-25"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "4. 29x20"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "25x14"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "5. 33-29 etc."
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "Trait aux blancs 1. 39-34"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "14-20"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "2. 34-29"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "23x34"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "3. 40x29"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "8-12"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "4. 45-40"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "20-25"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "5. 29x20"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "25x14"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "6. 33-29"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "14-20"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "7. 28-23"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "19x28"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "8. 32x23 etc."
}
]
},
{
"type": "board",
"id": "int_sdj_formations_l3_dia0",
"ch": 3
},
{
"type": "board",
"id": "int_sdj_formations_l3_dia1",
"ch": 3
},
{
"type": "board",
"id": "int_sdj_formations_l3_dia2",
"ch": 3
},
{
"type": "board",
"id": "int_sdj_formations_l3_dia3",
"ch": 3
},
{
"type": "board",
"id": "int_sdj_formations_l3_dia4",
"ch": 3
},
{
"type": "board",
"id": "int_sdj_formations_l3_dia5",
"ch": 3
},
{
"type": "board",
"id": "int_sdj_formations_l3_dia6",
"ch": 3
},
{
"type": "board",
"id": "int_sdj_formations_l3_dia7",
"ch": 3
},
{
"type": "board",
"id": "int_sdj_formations_l3_dia8",
"ch": 3
},
{
"type": "board",
"id": "int_sdj_formations_l3_dia9",
"ch": 3
},
{
"type": "board",
"id": "int_sdj_formations_l3_dia10",
"ch": 3
},
{
"type": "board",
"id": "int_sdj_formations_l3_dia11",
"ch": 3
},
{
"type": "board",
"id": "int_sdj_formations_l3_dia12",
"ch": 3
},
{
"type": "board",
"id": "int_sdj_formations_l3_dia13",
"ch": 3
},
{
"type": "board",
"id": "int_sdj_formations_l3_dia14",
"ch": 3
},
{
"type": "board",
"id": "int_sdj_formations_l3_ex0",
"ch": 3
},
{
"type": "board",
"id": "int_sdj_formations_l3_ex1",
"ch": 3
},
{
"type": "board",
"id": "int_sdj_formations_l3_ex2",
"ch": 3
},
{
"type": "board",
"id": "int_sdj_formations_l3_ex3",
"ch": 3
},
{
"type": "h2",
"ch": 4,
"runs": [
{
"t": "La flèche 33-38-42"
}
]
},
{
"type": "p",
"ch": 4,
"runs": [
{
"t": "Chapitre 2 : la flèche 33-38-42"
}
]
},
{
"type": "p",
"ch": 4,
"runs": [
{
"t": "Cette formation constituée des 3 pions 33-38-42 est très importante pour exercer une pression contre le centre adverse Cette pression peut s’exercer de plusieurs manières."
}
]
},
{
"type": "p",
"ch": 4,
"runs": [
{
"t": "1 – Le contrôle du centre adverse Trait aux noirs La position suivante est un cas remarquable. Les noirs sont immobilisés au centre. Ils n’ont aucun coup jouable : Après (8-12) ou (8-13), les blancs gagnent par un coup Philippe 27-22 (18x27) 33-29 (24x33) 38x7 ou 38x9 selon le cas."
}
]
},
{
"type": "p",
"ch": 4,
"runs": [
{
"t": "Isidore Weiss – A. C. van Wageningen Championnat du monde 1912 Trait aux blancs Le bloc noir 13-18-19-23-24 est immobilisé. Il reste à profiter de cette situation pour paralyser totalement la position des noirs : 44. 36-31"
}
]
},
{
"type": "p",
"ch": 4,
"runs": [
{
"t": "15-20"
}
]
},
{
"type": "p",
"ch": 4,
"runs": [
{
"t": "Sur (11-17) suit 31-26 et sur (21-26) suit 31-27 45. 41-37"
}
]
},
{
"type": "p",
"ch": 4,
"runs": [
{
"t": "20-25"
}
]
},
{
"type": "p",
"ch": 4,
"runs": [
{
"t": "46. 46-41"
}
]
},
{
"type": "p",
"ch": 4,
"runs": [
{
"t": "24-29"
}
]
},
{
"type": "p",
"ch": 4,
"runs": [
{
"t": "Les noirs n’ont pas d’autre alternative que celle de sacrifier un pion."
}
]
},
{
"type": "p",
"ch": 4,
"runs": [
{
"t": "Trait aux blancs On retrouve à nouveau un centre alourdi et inactif. Les blancs vont aggraver les problèmes des noirs en créant une formation 33-3842. 1. 34-30"
}
]
},
{
"type": "p",
"ch": 4,
"runs": [
{
"t": "20-25"
}
]
},
{
"type": "p",
"ch": 4,
"runs": [
{
"t": "Après (8-12) 48-42 (12-17) 33-28, les noirs sont sans défense contre la menace 27-22. Après (23-29) 32-28 (29-34), les blancs gagnent un pion par 3025 (18-23) 39x30 (23x21) 25x23 (21-27) 30x19 (13x24) 2. 39-34 5. 32x12"
}
]
},
{
"type": "p",
"ch": 4,
"runs": [
{
"t": "8-12 18x7"
}
]
},
{
"type": "p",
"ch": 4,
"runs": [
{
"t": "3. 48-42 6. 33-29"
}
]
},
{
"type": "p",
"ch": 4,
"runs": [
{
"t": "12-17 24x33"
}
]
},
{
"type": "p",
"ch": 4,
"runs": [
{
"t": "4. 27-21 7. 38x9"
}
]
},
{
"type": "p",
"ch": 4,
"runs": [
{
"t": "16x27 3x14"
}
]
},
{
"type": "p",
"ch": 4,
"runs": [
{
"t": "2 – Le centre sans support Jurij Ogorodnikov – Alexander Verete Championnat URSS 1965 Trait aux blancs Le bloc central des noirs est sous contrôle. 1. 41-36"
}
]
},
{
"type": "p",
"ch": 4,
"runs": [
{
"t": "8-12"
}
]
},
{
"type": "p",
"ch": 4,
"runs": [
{
"t": "2. 33-29"
}
]
},
{
"type": "p",
"ch": 4,
"runs": [
{
"t": "La formation de pionnage 33-38-42 joue bien son rôle. Elle permet de supprimer le pion stratégique 24 et de transformer la position des noirs en centre sans support. 2… 4. 42-38 6. 36x27 8. 25-20"
}
]
},
{
"type": "p",
"ch": 4,
"runs": [
{
"t": "24x33 17-22 7-11 9-14"
}
]
},
{
"type": "p",
"ch": 4,
"runs": [
{
"t": "3. 38x29 5. 30-25 7. 38-33 9. 20x9"
}
]
},
{
"type": "p",
"ch": 4,
"runs": [
{
"t": "11-17 22x31 12-17 13x4"
}
]
},
{
"type": "p",
"ch": 4,
"runs": [
{
"t": "11. 35-30 19-24 14. 32-28 etc +"
}
]
},
{
"type": "p",
"ch": 4,
"runs": [
{
"t": "12. 29x20"
}
]
},
{
"type": "p",
"ch": 4,
"runs": [
{
"t": "10-15"
}
]
},
{
"type": "p",
"ch": 4,
"runs": [
{
"t": "10. 33-28 Meilleur est 35-30 (4-10) 30-25 etc. 10… 13. 28x19"
}
]
},
{
"type": "p",
"ch": 4,
"runs": [
{
"t": "4-10 15x35"
}
]
},
{
"type": "p",
"ch": 4,
"runs": [
{
"t": "Altchoul,E. (Elena) - Michailovskaja,E. (Elena) WchW, 1980 Trait aux blancs Une autre position très instructive : 1. 33-29"
}
]
},
{
"type": "p",
"ch": 4,
"runs": [
{
"t": "24x33"
}
]
},
{
"type": "p",
"ch": 4,
"runs": [
{
"t": "2. 38x29"
}
]
},
{
"type": "p",
"ch": 4,
"runs": [
{
"t": "17-21"
}
]
},
{
"type": "p",
"ch": 4,
"runs": [
{
"t": "Sur (17-22) suit 26-21 (22x31) 32-27 (31x22) 29-24 etc. 3. 26x17 5. 42-38 7. 33-28 9. 30x39 11. 27x16 13. 41-37"
}
]
},
{
"type": "p",
"ch": 4,
"runs": [
{
"t": "12x21 7-12 21-26 19x30 18-22 31x42"
}
]
},
{
"type": "p",
"ch": 4,
"runs": [
{
"t": "4. 29-24 8-13 6. 38-33 12-17 8. 34-29 23x34 10. 35x24 16-21 12. 39-33 26-31 14. 33-29 etc."
}
]
},
{
"type": "p",
"ch": 4,
"runs": [
{
"t": "Mark Kemperman – Jo Weijman Huissen oc, 1996 Trait aux blancs La formation 33-38-42 va jouer un rôle essentiel pour forcer le gain : 1. 48-42 3..38x29"
}
]
},
{
"type": "p",
"ch": 4,
"runs": [
{
"t": "12-18 forcé"
}
]
},
{
"type": "p",
"ch": 4,
"runs": [
{
"t": "2. 33-29"
}
]
},
{
"type": "p",
"ch": 4,
"runs": [
{
"t": "24x33"
}
]
},
{
"type": "p",
"ch": 4,
"runs": [
{
"t": "Cet échange maintient l’immobilisation du bloc central adverse et libère des pions blancs. 3…"
}
]
},
{
"type": "p",
"ch": 4,
"runs": [
{
"t": "3-9"
}
]
},
{
"type": "p",
"ch": 4,
"runs": [
{
"t": "4. 29-24 +"
}
]
},
{
"type": "p",
"ch": 4,
"runs": [
{
"t": "3 – La pression contre le pion central adverse Geert Berends – Rik van Velzen NLD-Cup, 2001 Trait aux blancs La fleche 33-38-42 va permettre cette fois d’entamer une action contre le pion 23 : 1. 27-22 3. 33-29"
}
]
},
{
"type": "p",
"ch": 4,
"runs": [
{
"t": "18x27 24x33"
}
]
},
{
"type": "p",
"ch": 4,
"runs": [
{
"t": "2. 31x22 4. 38x18"
}
]
},
{
"type": "p",
"ch": 4,
"runs": [
{
"t": "4-9 9-14"
}
]
},
{
"type": "p",
"ch": 4,
"runs": [
{
"t": "Après (21-26) 43-39 (8-12) 30-24 (19x30) 35x24 (12x23) 39-33 les blancs gagnent le pion 23. 5. 43-39 14-20 6. 39-33 20-24 7. 42-37 3-9 8. 48-43 8-12 9. 22-17 les blancs conservent leur pion d’avance Frank Drost – Boris Sjkitkin NLD-URS, 27-06-1970 Trait aux noirs Dans cette position, les noirs ont forcé le gain de très jolie manière par : 1…"
}
]
},
{
"type": "p",
"ch": 4,
"runs": [
{
"t": "19-23"
}
]
},
{
"type": "p",
"ch": 4,
"runs": [
{
"t": "Menace (24-29) et (23-28) 2. 33-28"
}
]
},
{
"type": "p",
"ch": 4,
"runs": [
{
"t": "14-19"
}
]
},
{
"type": "p",
"ch": 4,
"runs": [
{
"t": "3. 45-40"
}
]
},
{
"type": "p",
"ch": 4,
"runs": [
{
"t": "24-29"
}
]
},
{
"type": "p",
"ch": 4,
"runs": [
{
"t": "(23-29) force le gain du pion, mais les noirs ont une autre idée en tête, plus expéditive. 4. 35-30 Après 40-34 (29x40) 35x44 (23-29) etc. +1p. 4… 7. 3x21"
}
]
},
{
"type": "p",
"ch": 4,
"runs": [
{
"t": "29-33 ! 16x27"
}
]
},
{
"type": "p",
"ch": 4,
"runs": [
{
"t": "5. 28x39 8. 25-20"
}
]
},
{
"type": "p",
"ch": 4,
"runs": [
{
"t": "23-28 ! 45-50 etc. +"
}
]
},
{
"type": "p",
"ch": 4,
"runs": [
{
"t": "6. 32x3"
}
]
},
{
"type": "p",
"ch": 4,
"runs": [
{
"t": "21x45"
}
]
},
{
"type": "p",
"ch": 4,
"runs": [
{
"t": "4 – En présence d’un pion à 23 R. C. Keller – I. J. de Jong NLD-ch, 1928 Trait aux blancs L’aile droite des noirs est encombrée. Le pion 23, connu sous le nom de piquet canadien, empêche les noirs de jouer au centre. Pour tirer pleinement profit de cette situation, les blancs ont intérêt à prendre le contrôle de l’aile droite en échangeant le pion 24 grâce à la formation 33-38-42."
}
]
},
{
"type": "p",
"ch": 4,
"runs": [
{
"t": "42. 49x38 45.38x27 48. 25x14 +"
}
]
},
{
"type": "p",
"ch": 4,
"runs": [
{
"t": "17-22 13-18"
}
]
},
{
"type": "p",
"ch": 4,
"runs": [
{
"t": "32. 33-29 34. 37-32 36. 34-30 38. 29-24 40. 30-25 43. 47-42 46. 21-17"
}
]
},
{
"type": "p",
"ch": 4,
"runs": [
{
"t": "24x33 27x38 10-15 25x34 27-32 22-27 18x47"
}
]
},
{
"type": "p",
"ch": 4,
"runs": [
{
"t": "33. 38x29 35. 42x33 37. 44-39 39. 39x30 41. 43-38 44. 26-21 47.17x8"
}
]
},
{
"type": "p",
"ch": 4,
"runs": [
{
"t": "22-27 21-27 20-25 8-13 32x43 27-32 47x20"
}
]
},
{
"type": "p",
"ch": 4,
"runs": [
{
"t": "Peter Bergsma – Wladimir Agafonow Yalta 1961 Trait aux blancs Dans une configuration analogue à la précédente, les blancs ont joué : 46. 33-29 48. 43-38 50. 42-37 52. 19x10"
}
]
},
{
"type": "p",
"ch": 4,
"runs": [
{
"t": "24x33 7-11 27-31 15x4"
}
]
},
{
"type": "p",
"ch": 4,
"runs": [
{
"t": "47. 38x29 22-27 49. 23-19 11-16 51. 37-32 9-14 53. 26x37 etc."
}
]
},
{
"type": "p",
"ch": 4,
"runs": [
{
"t": "Erik Brunsman – Freddy Wortel NLD-chA sf Groep B, 1980 Trait aux blancs Toujours sur le même thème : 41. 33-29 43. 43-38 45. 34-29 47. 24x15 49. 23-18"
}
]
},
{
"type": "p",
"ch": 4,
"runs": [
{
"t": "24x33 9-13 16-21 26-31 22x13"
}
]
},
{
"type": "p",
"ch": 4,
"runs": [
{
"t": "42. 38x29 11-17 44. 29-24 3-8 46. 38-33 15-20 48. 37x26 13-19 50. 42-37 etc."
}
]
},
{
"type": "p",
"ch": 4,
"runs": [
{
"t": "5 – Divers Avec la présence simultanée des pions 22 et 24 Trait aux blancs Dans cette situation, le pion noir 24 est indéfendable. 1. 34-29"
}
]
},
{
"type": "p",
"ch": 4,
"runs": [
{
"t": "17-21"
}
]
},
{
"type": "p",
"ch": 4,
"runs": [
{
"t": "La flèche 33-38-42 empêche les noirs de défendre leur pion directement par (10-15) 29x20 (15x24) car suit 33-28 etc. 2. 29x20 4. 36x27 6. 38x29"
}
]
},
{
"type": "p",
"ch": 4,
"runs": [
{
"t": "21-26 10-15"
}
]
},
{
"type": "p",
"ch": 4,
"runs": [
{
"t": "3. 31-27 5. 33-29 !"
}
]
},
{
"type": "p",
"ch": 4,
"runs": [
{
"t": "22x31 15x33"
}
]
},
{
"type": "p",
"ch": 4,
"runs": [
{
"t": "La position des noirs est indéfendable."
}
]
},
{
"type": "p",
"ch": 4,
"runs": [
{
"t": "Un thème peu connu Trait aux blancs Les blancs obtiennent un avantage décisif en jouant : 1. 33-29"
}
]
},
{
"type": "p",
"ch": 4,
"runs": [
{
"t": "24x33"
}
]
},
{
"type": "p",
"ch": 4,
"runs": [
{
"t": "2. 38x29"
}
]
},
{
"type": "p",
"ch": 4,
"runs": [
{
"t": "6-11"
}
]
},
{
"type": "p",
"ch": 4,
"runs": [
{
"t": "L’attaque (19-23) est effectivement interdite par 32-28 (23x21) 26x10. 3. 32-28 etc."
}
]
},
{
"type": "p",
"ch": 4,
"runs": [
{
"t": "Harm Wiersma – John van den Borst KSH GMA, 26-07-1977 Ce thème n’est pas sans rappeler le joli gain de Harm WIERSMA par : 45. 22-17 47. 35x44"
}
]
},
{
"type": "p",
"ch": 4,
"runs": [
{
"t": "23-29 24x35"
}
]
},
{
"type": "p",
"ch": 4,
"runs": [
{
"t": "46. 17x26 48. 33-29"
}
]
},
{
"type": "p",
"ch": 4,
"runs": [
{
"t": "29x40 18-22"
}
]
},
{
"type": "p",
"ch": 4,
"runs": [
{
"t": "Sur (19-23), suit 38-33 (23x34) 33-29 (34x23) 32-28 (23x21) 26x10 49. 27x7 51. 29x18"
}
]
},
{
"type": "p",
"ch": 4,
"runs": [
{
"t": "16-21 13x2"
}
]
},
{
"type": "p",
"ch": 4,
"runs": [
{
"t": "50. 26x17 52.38-33 +"
}
]
},
{
"type": "p",
"ch": 4,
"runs": [
{
"t": "19-23"
}
]
},
{
"type": "p",
"ch": 4,
"runs": [
{
"t": "Une jolie combinaison Les blancs dament par : 1. 27-21"
}
]
},
{
"type": "p",
"ch": 4,
"runs": [
{
"t": "16x27"
}
]
},
{
"type": "p",
"ch": 4,
"runs": [
{
"t": "2. 32x12"
}
]
},
{
"type": "p",
"ch": 4,
"runs": [
{
"t": "18x7"
}
]
},
{
"type": "p",
"ch": 4,
"runs": [
{
"t": "3. 33-29"
}
]
},
{
"type": "p",
"ch": 4,
"runs": [
{
"t": "24x33"
}
]
},
{
"type": "p",
"ch": 4,
"runs": [
{
"t": "4. 38x18"
}
]
},
{
"type": "p",
"ch": 4,
"runs": [
{
"t": "13x22"
}
]
},
{
"type": "p",
"ch": 4,
"runs": [
{
"t": "5. 37-31"
}
]
},
{
"type": "p",
"ch": 4,
"runs": [
{
"t": "26x48"
}
]
},
{
"type": "p",
"ch": 4,
"runs": [
{
"t": "6. 30-25"
}
]
},
{
"type": "p",
"ch": 4,
"runs": [
{
"t": "48x30"
}
]
},
{
"type": "p",
"ch": 4,
"runs": [
{
"t": "7. 35x4"
}
]
},
{
"type": "board",
"id": "int_sdj_formations_l4_dia0",
"ch": 4
},
{
"type": "board",
"id": "int_sdj_formations_l4_dia1",
"ch": 4
},
{
"type": "board",
"id": "int_sdj_formations_l4_dia2",
"ch": 4
},
{
"type": "board",
"id": "int_sdj_formations_l4_dia3",
"ch": 4
},
{
"type": "board",
"id": "int_sdj_formations_l4_dia4",
"ch": 4
},
{
"type": "board",
"id": "int_sdj_formations_l4_dia5",
"ch": 4
},
{
"type": "board",
"id": "int_sdj_formations_l4_dia6",
"ch": 4
},
{
"type": "board",
"id": "int_sdj_formations_l4_dia7",
"ch": 4
},
{
"type": "board",
"id": "int_sdj_formations_l4_dia8",
"ch": 4
},
{
"type": "board",
"id": "int_sdj_formations_l4_dia9",
"ch": 4
},
{
"type": "board",
"id": "int_sdj_formations_l4_dia10",
"ch": 4
},
{
"type": "board",
"id": "int_sdj_formations_l4_dia11",
"ch": 4
},
{
"type": "board",
"id": "int_sdj_formations_l4_dia12",
"ch": 4
},
{
"type": "board",
"id": "int_sdj_formations_l4_dia13",
"ch": 4
},
{
"type": "board",
"id": "int_sdj_formations_l4_dia14",
"ch": 4
},
{
"type": "board",
"id": "int_sdj_formations_l4_dia15",
"ch": 4
},
{
"type": "board",
"id": "int_sdj_formations_l4_ex0",
"ch": 4
},
{
"type": "board",
"id": "int_sdj_formations_l4_ex1",
"ch": 4
},
{
"type": "board",
"id": "int_sdj_formations_l4_ex2",
"ch": 4
},
{
"type": "board",
"id": "int_sdj_formations_l4_ex3",
"ch": 4
},
{
"type": "board",
"id": "int_sdj_formations_l4_ex4",
"ch": 4
},
{
"type": "board",
"id": "int_sdj_formations_l4_ex5",
"ch": 4
},
{
"type": "h2",
"ch": 5,
"runs": [
{
"t": "La formation 34-39-43"
}
]
},
{
"type": "p",
"ch": 5,
"runs": [
{
"t": "Chapitre 3 : la formation 34-39-43"
}
]
},
{
"type": "p",
"ch": 5,
"runs": [
{
"t": "Cette formation 34-39-43 est bien utile pour prendre le contrôle de l’aile droite par l’échange 34-30x30."
}
]
},
{
"type": "p",
"ch": 5,
"runs": [
{
"t": "Dans cette situation, le rôle de la formation 34-39-43 est d’interdire l’avancée (19-23)."
}
]
},
{
"type": "p",
"ch": 5,
"runs": [
{
"t": "Ben Springer – Alfred Molimard Championnat du monde 1928 Trait aux blancs Cette situation illustre bien les possibilités stratégiques offertes par la formation 34-39-43."
}
]
},
{
"type": "p",
"ch": 5,
"runs": [
{
"t": "tactiques"
}
]
},
{
"type": "p",
"ch": 5,
"runs": [
{
"t": "47. 32-27"
}
]
},
{
"type": "p",
"ch": 5,
"runs": [
{
"t": "14-20"
}
]
},
{
"type": "p",
"ch": 5,
"runs": [
{
"t": "3-8"
}
]
},
{
"type": "p",
"ch": 5,
"runs": [
{
"t": "48. 33-28"
}
]
},
{
"type": "p",
"ch": 5,
"runs": [
{
"t": "et"
}
]
},
{
"type": "p",
"ch": 5,
"runs": [
{
"t": "Pour éviter 28-23 (19x28) 34-30 (25x34) 39x10 49. 38-33"
}
]
},
{
"type": "p",
"ch": 5,
"runs": [
{
"t": "8-12"
}
]
},
{
"type": "p",
"ch": 5,
"runs": [
{
"t": "50. 47-42"
}
]
},
{
"type": "p",
"ch": 5,
"runs": [
{
"t": "11-16"
}
]
},
{
"type": "p",
"ch": 5,
"runs": [
{
"t": "Après (12-18), les blancs gagnent directement par 35-30 (24x35) 28-22 (17x28) 32x15 51. 28-23 53. 34-30"
}
]
},
{
"type": "p",
"ch": 5,
"runs": [
{
"t": "25x34"
}
]
},
{
"type": "p",
"ch": 5,
"runs": [
{
"t": "19x28"
}
]
},
{
"type": "p",
"ch": 5,
"runs": [
{
"t": "54. 39x19"
}
]
},
{
"type": "p",
"ch": 5,
"runs": [
{
"t": "Les blancs ont gagné le pion puis plus tard la partie."
}
]
},
{
"type": "p",
"ch": 5,
"runs": [
{
"t": "52. 33x11"
}
]
},
{
"type": "p",
"ch": 5,
"runs": [
{
"t": "6x17"
}
]
},
{
"type": "p",
"ch": 5,
"runs": [
{
"t": "Alex van Prinsenbeek – Raymond Vandecaetsbeek Brunssum 2000 46e temps – trait aux blancs On retrouve la faiblesse du pion 15. La formation 34-39-43 vient en appui. 46. 27-22 ! 48. 33x31 50. 38-33"
}
]
},
{
"type": "p",
"ch": 5,
"runs": [
{
"t": "18x27 13-19 forcé. 18-23"
}
]
},
{
"type": "p",
"ch": 5,
"runs": [
{
"t": "47. 28-23 49. 31-27"
}
]
},
{
"type": "p",
"ch": 5,
"runs": [
{
"t": "19x28 12-18"
}
]
},
{
"type": "p",
"ch": 5,
"runs": [
{
"t": "(15-20) ne sauve pas les noirs après 43-38 (19-23) 37-31 (26x37) 38-32 (37x28) 33x13 etc. 51. 43-38"
}
]
},
{
"type": "p",
"ch": 5,
"runs": [
{
"t": "15-20"
}
]
},
{
"type": "p",
"ch": 5,
"runs": [
{
"t": "52. 38-32 etc."
}
]
},
{
"type": "p",
"ch": 5,
"runs": [
{
"t": "."
}
]
},
{
"type": "p",
"ch": 5,
"runs": [
{
"t": "Trait aux noirs Le jeu des blancs est coupé en 2. Les noirs peuvent tirer profit de cette situation par : 1…"
}
]
},
{
"type": "p",
"ch": 5,
"runs": [
{
"t": "18-23"
}
]
},
{
"type": "p",
"ch": 5,
"runs": [
{
"t": "2. 38-32"
}
]
},
{
"type": "p",
"ch": 5,
"runs": [
{
"t": "Sur 39-33, suit (23-29) et la menace (17-21) est imparable 2… 4. 39-33"
}
]
},
{
"type": "p",
"ch": 5,
"runs": [
{
"t": "24-29 !"
}
]
},
{
"type": "p",
"ch": 5,
"runs": [
{
"t": "3. 43-38"
}
]
},
{
"type": "p",
"ch": 5,
"runs": [
{
"t": "13-18"
}
]
},
{
"type": "p",
"ch": 5,
"runs": [
{
"t": "Evite la perte du pion mais laisse un pion arrière en 36 et un trèfle inutile. 4… 6. 32x23"
}
]
},
{
"type": "p",
"ch": 5,
"runs": [
{
"t": "8-13 5. 33x24 23-28 18x20 l’avantage des noirs est probant"
}
]
},
{
"type": "p",
"ch": 5,
"runs": [
{
"t": "Nick Hoving – Roel Boomstra (2007) 34e temps – trait aux noirs La prise de contrôle de l’aile droite est primordiale en classique. Cela libère les pions arrière. Dans ce cas particulier, cela met en évidence le pion arrière 36. 34… 36. 48-42 38. 39-34 40. 34-30 42. 33-28"
}
]
},
{
"type": "p",
"ch": 5,
"runs": [
{
"t": "17-21 21-26 8-12 1-6 24-29"
}
]
},
{
"type": "p",
"ch": 5,
"runs": [
{
"t": "35. 26x17 37. 42-37 39. 30-25 41. 28-22 43. 36-31"
}
]
},
{
"type": "p",
"ch": 5,
"runs": [
{
"t": "12x21 5-10 10-14 6-11 12-17 +"
}
]
},
{
"type": "p",
"ch": 5,
"runs": [
{
"t": "Johan van der Borst – jannes van der Wal NLD-ch sf Groep 1, 1977 Les noirs forcent le gain du pion par : 35… 37. 35x44"
}
]
},
{
"type": "p",
"ch": 5,
"runs": [
{
"t": "24-29 23-28"
}
]
},
{
"type": "p",
"ch": 5,
"runs": [
{
"t": "36. 33x24"
}
]
},
{
"type": "p",
"ch": 5,
"runs": [
{
"t": "20x40"
}
]
},
{
"type": "p",
"ch": 5,
"runs": [
{
"t": "La menace (28-32) est inévitable 38. 26-21 40. 33x22 42. 27-22"
}
]
},
{
"type": "p",
"ch": 5,
"runs": [
{
"t": "17x26 12-17 18x27"
}
]
},
{
"type": "p",
"ch": 5,
"runs": [
{
"t": "39. 38-33 26-31 41. 22x11 16x7 43. 47-42 etc."
}
]
},
{
"type": "p",
"ch": 5,
"runs": [
{
"t": "Nicolai Mistchanski – Edvard Buzinskij Championnat URSS 1977 45e temps – trait aux blancs Les noirs n’ont que le pion 2 à jouer. Les blancs vont profiter de cette situation et utiliser leur formation 34-39-43 pour bloquer les noirs : 45. 48-42 !"
}
]
},
{
"type": "p",
"ch": 5,
"runs": [
{
"t": "2-8"
}
]
},
{
"type": "p",
"ch": 5,
"runs": [
{
"t": "Après (2-7) 34-30x30 l’attaque 28-22 est imparable. 46. 42-37"
}
]
},
{
"type": "p",
"ch": 5,
"runs": [
{
"t": "8-13"
}
]
},
{
"type": "p",
"ch": 5,
"runs": [
{
"t": "Sur (8-12), les blancs gagnent un pion par 37-31 (26x28) 33x13 (19x8) 34-30 (25x34) 39x28. 47. 33-28"
}
]
},
{
"type": "p",
"ch": 5,
"runs": [
{
"t": "24-29"
}
]
},
{
"type": "p",
"ch": 5,
"runs": [
{
"t": "48. 34-30"
}
]
},
{
"type": "p",
"ch": 5,
"runs": [
{
"t": "25x34"
}
]
},
{
"type": "p",
"ch": 5,
"runs": [
{
"t": "49. 39x30 etc."
}
]
},
{
"type": "p",
"ch": 5,
"runs": [
{
"t": "Evert Bronstring – Huib van der Vossen NLD-chT Hoofdklasse 2 1974 Dans cette position, les blancs ont forcé le jeu par : 48. 37-31 !"
}
]
},
{
"type": "p",
"ch": 5,
"runs": [
{
"t": "11-16"
}
]
},
{
"type": "p",
"ch": 5,
"runs": [
{
"t": "Livre une combinaison, mais sur : A – (12-18) 28-22 etc. B – (13-19) 28-23 (19x28) 33x22 (12-17) 22-18 (17-22) 18-12 (8x17) 27x18 etc. C – (12-17) 28-23 etc. 49. 34-30 51. 33-29"
}
]
},
{
"type": "p",
"ch": 5,
"runs": [
{
"t": "25x34 24x22"
}
]
},
{
"type": "p",
"ch": 5,
"runs": [
{
"t": "50. 39x19 52. 27x7+"
}
]
},
{
"type": "p",
"ch": 5,
"runs": [
{
"t": "13x24"
}
]
},
{
"type": "board",
"id": "int_sdj_formations_l5_dia0",
"ch": 5
},
{
"type": "board",
"id": "int_sdj_formations_l5_dia1",
"ch": 5
},
{
"type": "board",
"id": "int_sdj_formations_l5_dia2",
"ch": 5
},
{
"type": "board",
"id": "int_sdj_formations_l5_dia3",
"ch": 5
},
{
"type": "board",
"id": "int_sdj_formations_l5_dia4",
"ch": 5
},
{
"type": "board",
"id": "int_sdj_formations_l5_dia5",
"ch": 5
},
{
"type": "board",
"id": "int_sdj_formations_l5_dia6",
"ch": 5
},
{
"type": "board",
"id": "int_sdj_formations_l5_dia7",
"ch": 5
},
{
"type": "board",
"id": "int_sdj_formations_l5_dia8",
"ch": 5
},
{
"type": "board",
"id": "int_sdj_formations_l5_ex0",
"ch": 5
},
{
"type": "board",
"id": "int_sdj_formations_l5_ex1",
"ch": 5
},
{
"type": "board",
"id": "int_sdj_formations_l5_ex2",
"ch": 5
},
{
"type": "board",
"id": "int_sdj_formations_l5_ex3",
"ch": 5
},
{
"type": "board",
"id": "int_sdj_formations_l5_ex4",
"ch": 5
},
{
"type": "board",
"id": "int_sdj_formations_l5_ex5",
"ch": 5
}
],
"positions": {
"int_sdj_formations_l1_dia0": {
"id": "int_sdj_formations_l1_dia0",
"ch": 1,
"title": "Championnat d’Europe 1971",
"start": {
"wm": [
26,
27,
28,
33,
35,
38,
43,
45
],
"wk": [],
"bm": [
7,
8,
12,
17,
18,
19,
24,
25
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Championnat d’Europe 1971"
},
"int_sdj_formations_l1_dia1": {
"id": "int_sdj_formations_l1_dia1",
"ch": 1,
"title": "Trait aux blancs",
"start": {
"wm": [
27,
32,
33,
38,
39,
42,
44,
45
],
"wk": [],
"bm": [
13,
15,
16,
18,
19,
23,
24,
26
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Trait aux blancs"
},
"int_sdj_formations_l1_dia2": {
"id": "int_sdj_formations_l1_dia2",
"ch": 1,
"title": "COMPLEMENT",
"start": {
"wm": [
25,
26,
30,
32,
33,
35,
36,
38,
41,
43
],
"wk": [],
"bm": [
6,
12,
13,
14,
16,
18,
19,
22,
23,
24
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "COMPLEMENT"
},
"int_sdj_formations_l1_dia3": {
"id": "int_sdj_formations_l1_dia3",
"ch": 1,
"title": "Trait aux blancs",
"start": {
"wm": [
30,
31,
32,
33,
34,
36,
39,
40,
48
],
"wk": [],
"bm": [
4,
6,
9,
12,
14,
15,
16,
22,
23
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Trait aux blancs"
},
"int_sdj_formations_l1_dia4": {
"id": "int_sdj_formations_l1_dia4",
"ch": 1,
"title": "Baba SY - Hugo VERPOEST",
"start": {
"wm": [
26,
27,
32,
38,
48
],
"wk": [],
"bm": [
6,
7,
12,
16,
23
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Baba SY - Hugo VERPOEST"
},
"int_sdj_formations_l1_dia5": {
"id": "int_sdj_formations_l1_dia5",
"ch": 1,
"title": "Trait aux blancs",
"start": {
"wm": [
21,
27,
31,
33,
34,
35,
36,
38,
39
],
"wk": [],
"bm": [
6,
11,
16,
18,
19,
22,
23,
24,
25
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Trait aux blancs"
},
"int_sdj_formations_l1_dia6": {
"id": "int_sdj_formations_l1_dia6",
"ch": 1,
"title": "Trait aux blancs",
"start": {
"wm": [
26,
27,
33,
37,
38,
43
],
"wk": [],
"bm": [
6,
11,
12,
13,
16,
18
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Trait aux blancs"
},
"int_sdj_formations_l1_dia7": {
"id": "int_sdj_formations_l1_dia7",
"ch": 1,
"title": "3. 32-28 B+",
"start": {
"wm": [
26,
27,
32,
33,
34,
35,
39,
49
],
"wk": [],
"bm": [
6,
12,
13,
16,
18,
19,
23,
24
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "3. 32-28 B+"
},
"int_sdj_formations_l1_ex0": {
"id": "int_sdj_formations_l1_ex0",
"ch": 1,
"title": "LE PION BLANC 45 – D1",
"start": {
"wm": [
27,
28,
32,
35,
36,
37,
38,
42,
43,
44,
45,
48
],
"wk": [],
"bm": [
6,
7,
8,
9,
11,
13,
15,
16,
18,
19,
23,
29
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "27-22",
"f": 27,
"t": 22,
"c": [],
"path": [
27,
22
],
"p": false
}
],
"theme": "sdj_ch120",
"pub": "27-22 19x30 27-21 16x49 40-35 49x40 35x24 20x29 45x1",
"win": "white"
},
"int_sdj_formations_l1_ex1": {
"id": "int_sdj_formations_l1_ex1",
"ch": 1,
"title": "LE PION BLANC 45 – D2",
"start": {
"wm": [
29,
32,
39,
40,
43,
44,
45
],
"wk": [],
"bm": [
6,
7,
9,
13,
15,
16,
18,
19,
20,
25
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "39-33",
"f": 39,
"t": 33,
"c": [],
"path": [
39,
33
],
"p": false
}
],
"theme": "sdj_ch120",
"pub": "39-33 18x27 32x21 23x41 36x47 16x27 38-32 27x40 45x1",
"win": "white"
},
"int_sdj_formations_l1_ex2": {
"id": "int_sdj_formations_l1_ex2",
"ch": 1,
"title": "LE PION BLANC 45 – D3",
"start": {
"wm": [
24,
26,
27,
29,
34,
36,
38,
39,
40,
44,
45,
49
],
"wk": [],
"bm": [
4,
7,
8,
9,
12,
13,
15,
16,
18,
19,
20,
25
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "27-21",
"f": 27,
"t": 21,
"c": [],
"path": [
27,
21
],
"p": false
}
],
"theme": "sdj_ch120",
"pub": "27-21 16x47 32-28 23x32 38x27 47x40 45x1",
"win": "white"
},
"int_sdj_formations_l1_ex3": {
"id": "int_sdj_formations_l1_ex3",
"ch": 1,
"title": "LE PION BLANC 45 – D4",
"start": {
"wm": [
26,
27,
31,
32,
38,
39,
41,
42,
43
],
"wk": [],
"bm": [
2,
3,
6,
7,
8,
9,
13,
14,
15,
16,
17,
18,
23,
29
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "41-36",
"f": 41,
"t": 36,
"c": [],
"path": [
41,
36
],
"p": false
}
],
"theme": "sdj_ch120",
"pub": "41-36 25x21 26x17 19x30 44-39 12x21 29-23 18x29 40-34 29x40",
"win": "white"
},
"int_sdj_formations_l2_dia0": {
"id": "int_sdj_formations_l2_dia0",
"ch": 2,
"title": "Trait aux blancs",
"start": {
"wm": [
27,
28,
30,
32,
35,
37
],
"wk": [],
"bm": [
13,
15,
16,
18,
19,
21
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Trait aux blancs"
},
"int_sdj_formations_l2_dia1": {
"id": "int_sdj_formations_l2_dia1",
"ch": 2,
"title": "Trait aux noirs",
"start": {
"wm": [
26,
27,
28,
30,
32,
33,
35,
37,
38
],
"wk": [],
"bm": [
12,
13,
14,
16,
17,
18,
19,
23,
24
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Trait aux noirs"
},
"int_sdj_formations_l2_dia2": {
"id": "int_sdj_formations_l2_dia2",
"ch": 2,
"title": "Trait aux blancs",
"start": {
"wm": [
31,
32,
33,
34,
35,
36,
37,
38,
39,
40,
41,
42,
43,
45,
46,
47,
48,
49,
50
],
"wk": [],
"bm": [
1,
2,
3,
4,
5,
6,
7,
8,
9,
10,
11,
12,
13,
14,
15,
16,
17,
18,
19
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Trait aux blancs"
},
"int_sdj_formations_l2_dia3": {
"id": "int_sdj_formations_l2_dia3",
"ch": 2,
"title": "Trait aux blancs",
"start": {
"wm": [
28,
31,
33,
34,
35,
36,
38,
39,
40,
41,
42,
43,
44,
45,
47,
48,
49,
50
],
"wk": [],
"bm": [
1,
2,
3,
4,
6,
7,
9,
10,
11,
12,
13,
14,
15,
16,
17,
18,
19,
20
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Trait aux blancs"
},
"int_sdj_formations_l2_dia4": {
"id": "int_sdj_formations_l2_dia4",
"ch": 2,
"title": "Trait aux blancs",
"start": {
"wm": [
27,
28,
32,
33,
35,
36,
37,
38,
39,
40,
42,
43,
44,
48
],
"wk": [],
"bm": [
3,
6,
8,
9,
10,
11,
12,
13,
14,
15,
16,
18,
19,
26
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Trait aux blancs"
},
"int_sdj_formations_l2_dia5": {
"id": "int_sdj_formations_l2_dia5",
"ch": 2,
"title": "Andris Andreiko – Sergej Mansjien",
"start": {
"wm": [
1,
2,
3,
4,
5,
6,
7,
8,
9,
10,
11,
12,
14,
15,
16,
19,
20,
26,
27,
28,
29,
30,
31,
32,
33,
34,
35,
36,
37,
38,
39,
40,
41,
42,
43,
44,
45,
46,
47,
48,
49,
50
],
"wk": [],
"bm": [],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Andris Andreiko – Sergej Mansjien"
},
"int_sdj_formations_l2_dia6": {
"id": "int_sdj_formations_l2_dia6",
"ch": 2,
"title": "Championnat URSS 1971",
"start": {
"wm": [
27,
28,
30,
32,
33,
34,
36,
37,
38,
39,
44,
48
],
"wk": [],
"bm": [
3,
4,
8,
10,
13,
14,
16,
18,
19,
21,
23,
26
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Championnat URSS 1971"
},
"int_sdj_formations_l2_ex0": {
"id": "int_sdj_formations_l2_ex0",
"ch": 2,
"title": "LE PION BLANC 35 – D1",
"start": {
"wm": [
27,
30,
32,
33,
34,
35,
37,
38,
42
],
"wk": [],
"bm": [
9,
13,
16,
17,
18,
19,
23,
24,
26
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "34-29",
"f": 34,
"t": 29,
"c": [],
"path": [
34,
29
],
"p": false
}
],
"theme": "sdj_ch121",
"pub": "34-29 19x39 30x19 13x33 38x29 39x30 35x4",
"win": "white"
},
"int_sdj_formations_l2_ex1": {
"id": "int_sdj_formations_l2_ex1",
"ch": 2,
"title": "LE PION BLANC 35 – D2",
"start": {
"wm": [
25,
26,
28,
29,
30,
33,
34,
35,
38,
41,
42,
43,
47,
48
],
"wk": [],
"bm": [
5,
8,
10,
11,
12,
13,
14,
17,
18,
19,
20,
22,
24,
27
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "28-23",
"f": 28,
"t": 23,
"c": [],
"path": [
28,
23
],
"p": false
}
],
"theme": "sdj_ch121",
"pub": "28-23 16x27 32x12 18x7 33-29 24x33 38x18 13x22 37-31 26x48",
"win": "white"
},
"int_sdj_formations_l2_ex2": {
"id": "int_sdj_formations_l2_ex2",
"ch": 2,
"title": "LE PION BLANC 35 – D3",
"start": {
"wm": [
30,
32,
33,
34,
35,
37,
38,
40,
42,
45,
47
],
"wk": [],
"bm": [
3,
5,
9,
11,
16,
18,
19,
24,
25,
26,
31
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "32-27",
"f": 32,
"t": 27,
"c": [],
"path": [
32,
27
],
"p": false
},
{
"n": "31x22",
"f": 31,
"t": 22,
"c": [
27
],
"path": [
31,
22
],
"p": false
},
{
"n": "33-28",
"f": 33,
"t": 28,
"c": [],
"path": [
33,
28
],
"p": false
},
{
"n": "22x33",
"f": 22,
"t": 33,
"c": [
28
],
"path": [
22,
33
],
"p": false
},
{
"n": "38x20",
"f": 38,
"t": 20,
"c": [
24,
33
],
"path": [
38,
29,
20
],
"p": false
},
{
"n": "25x14",
"f": 25,
"t": 14,
"c": [
20
],
"path": [
25,
14
],
"p": false
},
{
"n": "37-31",
"f": 37,
"t": 31,
"c": [],
"path": [
37,
31
],
"p": false
},
{
"n": "26x48",
"f": 26,
"t": 48,
"c": [
42,
31
],
"path": [
26,
37,
48
],
"p": true
},
{
"n": "30-25",
"f": 30,
"t": 25,
"c": [],
"path": [
30,
25
],
"p": false
},
{
"n": "48x30",
"f": 48,
"t": 30,
"c": [
34
],
"path": [
48,
30
],
"p": false
}
],
"theme": "sdj_ch121",
"pub": "32-27 31x22 33-28 22x33 38x20 25x14 37-31 26x48 30-25 48x30",
"win": "white"
},
"int_sdj_formations_l2_ex3": {
"id": "int_sdj_formations_l2_ex3",
"ch": 2,
"title": "LE PION BLANC 35 – D4",
"start": {
"wm": [
30,
32,
33,
34,
35,
37,
38,
40,
42,
45,
47
],
"wk": [],
"bm": [
3,
5,
9,
11,
16,
18,
19,
24,
25,
26,
31
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "33-29",
"f": 33,
"t": 29,
"c": [],
"path": [
33,
29
],
"p": false
},
{
"n": "24x33",
"f": 24,
"t": 33,
"c": [
29
],
"path": [
24,
33
],
"p": false
}
],
"theme": "sdj_ch121",
"pub": "33-29 24x33 38x18 13x22 32-28 22x33 42-38 33x42 37x48 26x37",
"win": "white"
},
"int_sdj_formations_l3_dia0": {
"id": "int_sdj_formations_l3_dia0",
"ch": 3,
"title": "Nikolai Sretenski – Jurij Kolodiev",
"start": {
"wm": [
27,
28,
32,
37,
38,
39,
40,
45
],
"wk": [],
"bm": [],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Nikolai Sretenski – Jurij Kolodiev"
},
"int_sdj_formations_l3_dia1": {
"id": "int_sdj_formations_l3_dia1",
"ch": 3,
"title": "Trait aux blancs",
"start": {
"wm": [
25,
27,
28,
32,
33,
37,
38,
39,
40,
45
],
"wk": [],
"bm": [
7,
8,
11,
13,
14,
15,
19,
23,
24,
26
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Trait aux blancs"
},
"int_sdj_formations_l3_dia2": {
"id": "int_sdj_formations_l3_dia2",
"ch": 3,
"title": "Amsterdam-ch 2e klasse, 1939",
"start": {
"wm": [
25,
27,
28,
32,
33,
37,
38,
39,
40,
45
],
"wk": [],
"bm": [
3,
11,
13,
14,
16,
18,
19,
23,
24,
26
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Amsterdam-ch 2e klasse, 1939"
},
"int_sdj_formations_l3_dia3": {
"id": "int_sdj_formations_l3_dia3",
"ch": 3,
"title": "Trait aux blancs",
"start": {
"wm": [
25,
27,
28,
32,
33,
37,
38,
39,
40,
45
],
"wk": [],
"bm": [
8,
12,
13,
14,
15,
16,
19,
21,
23,
24
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Trait aux blancs"
},
"int_sdj_formations_l3_dia4": {
"id": "int_sdj_formations_l3_dia4",
"ch": 3,
"title": "Match Wallen - Koeperman, 1986",
"start": {
"wm": [
27,
28,
32,
33,
37,
38,
39,
40,
45,
47
],
"wk": [],
"bm": [
13,
16,
17,
18,
19,
21,
23,
24,
25,
26
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Match Wallen - Koeperman, 1986"
},
"int_sdj_formations_l3_dia5": {
"id": "int_sdj_formations_l3_dia5",
"ch": 3,
"title": "Trait aux blancs",
"start": {
"wm": [
27,
28,
32,
37,
38,
39,
40,
45
],
"wk": [],
"bm": [
13,
15,
16,
18,
19,
20,
24,
26
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Trait aux blancs"
},
"int_sdj_formations_l3_dia6": {
"id": "int_sdj_formations_l3_dia6",
"ch": 3,
"title": "Trait aux blancs",
"start": {
"wm": [
25,
27,
28,
32,
36,
37,
38,
39,
40,
45
],
"wk": [],
"bm": [
8,
9,
13,
14,
16,
18,
19,
21,
23,
24
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Trait aux blancs"
},
"int_sdj_formations_l3_dia7": {
"id": "int_sdj_formations_l3_dia7",
"ch": 3,
"title": "Trait aux blancs",
"start": {
"wm": [
27,
28,
32,
37,
38,
39,
40,
45
],
"wk": [],
"bm": [
7,
13,
18,
19,
20,
23,
24,
26
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Trait aux blancs"
},
"int_sdj_formations_l3_dia8": {
"id": "int_sdj_formations_l3_dia8",
"ch": 3,
"title": "Avec",
"start": {
"wm": [
27,
28,
32,
33,
37,
38,
39,
40,
45
],
"wk": [],
"bm": [
11,
12,
13,
16,
18,
19,
23,
24,
25
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Avec"
},
"int_sdj_formations_l3_dia9": {
"id": "int_sdj_formations_l3_dia9",
"ch": 3,
"title": "Trait aux blancs",
"start": {
"wm": [
25,
27,
28,
32,
33,
37,
38,
39,
40,
45
],
"wk": [],
"bm": [
6,
9,
13,
14,
16,
17,
19,
23,
24,
26
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Trait aux blancs"
},
"int_sdj_formations_l3_dia10": {
"id": "int_sdj_formations_l3_dia10",
"ch": 3,
"title": "Trait aux blancs",
"start": {
"wm": [
25,
27,
28,
32,
33,
37,
38,
39,
40,
45
],
"wk": [],
"bm": [
9,
11,
13,
14,
16,
18,
19,
23,
24,
26
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Trait aux blancs"
},
"int_sdj_formations_l3_dia11": {
"id": "int_sdj_formations_l3_dia11",
"ch": 3,
"title": "Trait aux noirs",
"start": {
"wm": [
25,
27,
28,
32,
33,
37,
39,
40,
42,
45
],
"wk": [],
"bm": [
7,
13,
14,
15,
16,
18,
19,
23,
24,
26
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Trait aux noirs"
},
"int_sdj_formations_l3_dia12": {
"id": "int_sdj_formations_l3_dia12",
"ch": 3,
"title": "4 – L’OCCUPATION TERRITORIALE",
"start": {
"wm": [
25,
27,
28,
32,
33,
37,
39,
40,
42,
45
],
"wk": [],
"bm": [
13,
14,
16,
17,
18,
19,
21,
23,
24,
26
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "4 – L’OCCUPATION TERRITORIALE"
},
"int_sdj_formations_l3_dia13": {
"id": "int_sdj_formations_l3_dia13",
"ch": 3,
"title": "Trait aux blancs",
"start": {
"wm": [
27,
28,
32,
33,
37,
38,
39,
40,
45
],
"wk": [],
"bm": [
11,
13,
14,
16,
18,
19,
23,
24,
26
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Trait aux blancs"
},
"int_sdj_formations_l3_dia14": {
"id": "int_sdj_formations_l3_dia14",
"ch": 3,
"title": "Trait aux blancs",
"start": {
"wm": [
27,
28,
32,
33,
37,
38,
39,
40,
45
],
"wk": [],
"bm": [
8,
13,
14,
16,
18,
19,
23,
24,
26
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Trait aux blancs"
},
"int_sdj_formations_l3_ex0": {
"id": "int_sdj_formations_l3_ex0",
"ch": 3,
"title": "LA FORMATION 45-40 – D1",
"start": {
"wm": [
25,
27,
32,
33,
37,
39,
40,
45,
47,
48
],
"wk": [],
"bm": [
12,
13,
14,
16,
18,
19,
21,
23,
24,
26
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "37-31",
"f": 37,
"t": 31,
"c": [],
"path": [
37,
31
],
"p": false
}
],
"theme": "sdj_ch130",
"pub": "37-31 18x29 38-33 29x38 32x43 21x32 43-38 32x34 40x7",
"win": "white"
},
"int_sdj_formations_l3_ex1": {
"id": "int_sdj_formations_l3_ex1",
"ch": 3,
"title": "LA FORMATION 45-40 – D2",
"start": {
"wm": [
27,
28,
32,
38,
39,
40,
41,
45
],
"wk": [],
"bm": [
12,
13,
14,
16,
17,
18,
21,
24
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "28-23",
"f": 28,
"t": 23,
"c": [],
"path": [
28,
23
],
"p": false
}
],
"theme": "sdj_ch130",
"pub": "28-23 26x28 33x22 21x32 48-43 18x27 43-38 32x34 40x7",
"win": "white"
},
"int_sdj_formations_l3_ex2": {
"id": "int_sdj_formations_l3_ex2",
"ch": 3,
"title": "LA FORMATION 45-40 – D3",
"start": {
"wm": [
25,
27,
32,
33,
37,
38,
39,
40,
45
],
"wk": [],
"bm": [
13,
14,
16,
17,
18,
19,
23,
24,
26
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "37-31",
"f": 37,
"t": 31,
"c": [],
"path": [
37,
31
],
"p": false
}
],
"theme": "sdj_ch130",
"pub": "37-31 26x37 32x41 21x34 28-22 29x38 40x7",
"win": "white"
},
"int_sdj_formations_l3_ex3": {
"id": "int_sdj_formations_l3_ex3",
"ch": 3,
"title": "LA FORMATION 45-40 – D4",
"start": {
"wm": [
27,
28,
32,
33,
37,
38,
39,
40,
45,
48
],
"wk": [],
"bm": [
8,
12,
13,
14,
16,
19,
21,
24,
26,
29
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "37-31",
"f": 37,
"t": 31,
"c": [],
"path": [
37,
31
],
"p": false
}
],
"theme": "sdj_ch130",
"pub": "37-31 16x27 32x12 18x7 33-28 23x34 40x18",
"win": "white"
},
"int_sdj_formations_l4_dia0": {
"id": "int_sdj_formations_l4_dia0",
"ch": 4,
"title": "Trait aux noirs",
"start": {
"wm": [
33,
38,
42
],
"wk": [],
"bm": [],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Trait aux noirs"
},
"int_sdj_formations_l4_dia1": {
"id": "int_sdj_formations_l4_dia1",
"ch": 4,
"title": "Championnat du monde 1912",
"start": {
"wm": [
27,
33,
34,
35,
38,
42
],
"wk": [],
"bm": [
8,
16,
18,
19,
23,
24
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Championnat du monde 1912"
},
"int_sdj_formations_l4_dia2": {
"id": "int_sdj_formations_l4_dia2",
"ch": 4,
"title": "Trait aux blancs",
"start": {
"wm": [
30,
32,
33,
34,
35,
36,
38,
41,
42,
46
],
"wk": [],
"bm": [
6,
11,
13,
15,
16,
18,
19,
21,
23,
24
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Trait aux blancs"
},
"int_sdj_formations_l4_dia3": {
"id": "int_sdj_formations_l4_dia3",
"ch": 4,
"title": "Trait aux blancs",
"start": {
"wm": [
26,
27,
32
],
"wk": [],
"bm": [
3,
6,
8,
13,
16,
18,
19,
23
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Trait aux blancs"
},
"int_sdj_formations_l4_dia4": {
"id": "int_sdj_formations_l4_dia4",
"ch": 4,
"title": "Jurij Ogorodnikov – Alexander Verete",
"start": {
"wm": [
26,
27,
32,
41,
42
],
"wk": [],
"bm": [
7,
8,
9,
11,
13,
16,
18,
19,
23
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Jurij Ogorodnikov – Alexander Verete"
},
"int_sdj_formations_l4_dia5": {
"id": "int_sdj_formations_l4_dia5",
"ch": 4,
"title": "Championnat URSS 1965",
"start": {
"wm": [
26,
27,
32,
41,
42
],
"wk": [],
"bm": [
7,
8,
12,
16,
17,
18,
19,
23
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Championnat URSS 1965"
},
"int_sdj_formations_l4_dia6": {
"id": "int_sdj_formations_l4_dia6",
"ch": 4,
"title": "Mark Kemperman – Jo Weijman",
"start": {
"wm": [
27,
30,
32,
33,
34,
35,
37,
38,
48
],
"wk": [],
"bm": [
3,
12,
13,
16,
19,
23,
24,
25,
26
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Mark Kemperman – Jo Weijman"
},
"int_sdj_formations_l4_dia7": {
"id": "int_sdj_formations_l4_dia7",
"ch": 4,
"title": "Huissen oc, 1996",
"start": {
"wm": [
27,
30,
31,
32,
33,
34,
35,
36,
38,
42,
43,
48
],
"wk": [],
"bm": [
3,
4,
6,
7,
8,
16,
18,
19,
21,
23,
24,
25
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Huissen oc, 1996"
},
"int_sdj_formations_l4_dia8": {
"id": "int_sdj_formations_l4_dia8",
"ch": 4,
"title": "Trait aux blancs",
"start": {
"wm": [
25,
26,
27,
32,
33,
35,
38,
42,
45
],
"wk": [],
"bm": [
9,
13,
14,
16,
17,
18,
19,
21,
24
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Trait aux blancs"
},
"int_sdj_formations_l4_dia9": {
"id": "int_sdj_formations_l4_dia9",
"ch": 4,
"title": "NLD-ch, 1928",
"start": {
"wm": [
23,
26,
33,
34,
36,
37,
38,
42,
43,
44,
47,
49
],
"wk": [],
"bm": [
4,
6,
8,
10,
11,
12,
16,
17,
20,
21,
22,
24
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "NLD-ch, 1928"
},
"int_sdj_formations_l4_dia10": {
"id": "int_sdj_formations_l4_dia10",
"ch": 4,
"title": "Trait aux blancs",
"start": {
"wm": [
23,
26,
33,
38,
40,
42,
43,
46
],
"wk": [],
"bm": [
6,
7,
9,
15,
17,
21,
22,
24
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Trait aux blancs"
},
"int_sdj_formations_l4_dia11": {
"id": "int_sdj_formations_l4_dia11",
"ch": 4,
"title": "48. 25x14 +",
"start": {
"wm": [
23,
25,
33,
34,
36,
37,
38,
42,
43,
48
],
"wk": [],
"bm": [
3,
9,
11,
14,
15,
16,
22,
24,
26,
27
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "48. 25x14 +"
},
"int_sdj_formations_l4_dia12": {
"id": "int_sdj_formations_l4_dia12",
"ch": 4,
"title": "5 – Divers",
"start": {
"wm": [
31,
32,
33,
34,
35,
36,
38,
42
],
"wk": [],
"bm": [
10,
13,
16,
17,
18,
19,
22,
24
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "5 – Divers"
},
"int_sdj_formations_l4_dia13": {
"id": "int_sdj_formations_l4_dia13",
"ch": 4,
"title": "Trait aux blancs",
"start": {
"wm": [
25,
26,
27,
32,
33,
38,
42,
45
],
"wk": [],
"bm": [
6,
12,
13,
14,
16,
18,
19,
24
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Trait aux blancs"
},
"int_sdj_formations_l4_dia14": {
"id": "int_sdj_formations_l4_dia14",
"ch": 4,
"title": "Un thème peu connu",
"start": {
"wm": [
22,
25,
27,
30,
32,
33,
34,
35,
38,
42
],
"wk": [],
"bm": [
9,
12,
13,
14,
16,
18,
19,
21,
23,
24
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Un thème peu connu"
},
"int_sdj_formations_l4_dia15": {
"id": "int_sdj_formations_l4_dia15",
"ch": 4,
"title": "Une jolie combinaison",
"start": {
"wm": [
27,
30,
32,
33,
34,
35,
36,
37,
38,
42
],
"wk": [],
"bm": [
9,
13,
14,
16,
17,
18,
19,
23,
24,
26
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Une jolie combinaison"
},
"int_sdj_formations_l4_ex0": {
"id": "int_sdj_formations_l4_ex0",
"ch": 4,
"title": "LA FLÈCHE 33-38-42 – D1",
"start": {
"wm": [
25,
27,
30,
32,
33,
35,
37,
38,
42,
49
],
"wk": [],
"bm": [
13,
14,
15,
16,
17,
18,
19,
23,
24,
26
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "27-22",
"f": 27,
"t": 22,
"c": [],
"path": [
27,
22
],
"p": false
}
],
"theme": "sdj_ch131",
"pub": "27-22 18x27 32x21 33-29 24x33 38x7",
"win": "white"
},
"int_sdj_formations_l4_ex1": {
"id": "int_sdj_formations_l4_ex1",
"ch": 4,
"title": "LA FLÈCHE 33-38-42 – D2",
"start": {
"wm": [
27,
32,
33,
34,
35,
37,
38,
39,
42,
43,
44
],
"wk": [],
"bm": [
3,
9,
12,
13,
14,
16,
18,
19,
23,
24,
26
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "27-21",
"f": 27,
"t": 21,
"c": [],
"path": [
27,
21
],
"p": false
},
{
"n": "16x27",
"f": 16,
"t": 27,
"c": [
21
],
"path": [
16,
27
],
"p": false
}
],
"theme": "sdj_ch131",
"pub": "27-21 16x27 32x12 18x7 25-20 14x34 33-29 24x33 38x9",
"win": "white"
},
"int_sdj_formations_l4_ex2": {
"id": "int_sdj_formations_l4_ex2",
"ch": 4,
"title": "LA FLÈCHE 33-38-42 – D3",
"start": {
"wm": [
22,
27,
32,
33,
34,
37,
38,
39,
42,
44
],
"wk": [],
"bm": [
12,
13,
14,
16,
18,
19,
23,
24,
26,
35
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "27-21",
"f": 27,
"t": 21,
"c": [],
"path": [
27,
21
],
"p": false
}
],
"theme": "sdj_ch131",
"pub": "27-21 18x27 32x21 33-29 24x44 43-39 44x33 38x20",
"win": "white"
},
"int_sdj_formations_l4_ex3": {
"id": "int_sdj_formations_l4_ex3",
"ch": 4,
"title": "LA FLÈCHE 33-38-42 – D4",
"start": {
"wm": [
25,
27,
32,
33,
35,
37,
38,
39,
42,
43,
45,
48
],
"wk": [],
"bm": [
3,
6,
8,
12,
13,
14,
16,
18,
19,
23,
24,
26
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "27-21",
"f": 27,
"t": 21,
"c": [],
"path": [
27,
21
],
"p": false
}
],
"theme": "sdj_ch131",
"pub": "27-21 26x28 33x22 18x27 32x21 16x27 44-40 35x33 38x7",
"win": "white"
},
"int_sdj_formations_l4_ex4": {
"id": "int_sdj_formations_l4_ex4",
"ch": 4,
"title": "LA FLÈCHE 33-38-42 – D5",
"start": {
"wm": [
27,
32,
33,
34,
35,
37,
38,
39,
42,
43,
48
],
"wk": [],
"bm": [
3,
9,
12,
13,
14,
16,
17,
18,
19,
23,
24
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "27-22",
"f": 27,
"t": 22,
"c": [],
"path": [
27,
22
],
"p": false
}
],
"theme": "sdj_ch131",
"pub": "27-22 21x12 27-22 18x27 32x21 16x27 33-29 24x33 38x7",
"win": "white"
},
"int_sdj_formations_l4_ex5": {
"id": "int_sdj_formations_l4_ex5",
"ch": 4,
"title": "LA FLÈCHE 33-38-42 – D6",
"start": {
"wm": [
22,
27,
30,
32,
33,
34,
35,
38,
42,
43
],
"wk": [],
"bm": [
3,
8,
13,
16,
18,
19,
21,
23,
24,
25
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "22-17",
"f": 22,
"t": 17,
"c": [],
"path": [
22,
17
],
"p": false
}
],
"theme": "sdj_ch131",
"pub": "22-17 17x28 33x22 18x27 32x21 16x27 34-29 24x44 43-39 44x33",
"win": "white"
},
"int_sdj_formations_l5_dia0": {
"id": "int_sdj_formations_l5_dia0",
"ch": 5,
"title": "Ben Springer – Alfred Molimard",
"start": {
"wm": [
34,
39,
43
],
"wk": [],
"bm": [
25
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Ben Springer – Alfred Molimard"
},
"int_sdj_formations_l5_dia1": {
"id": "int_sdj_formations_l5_dia1",
"ch": 5,
"title": "Championnat du monde 1928",
"start": {
"wm": [
34,
35,
39,
43
],
"wk": [],
"bm": [
15,
19,
24,
25
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Championnat du monde 1928"
},
"int_sdj_formations_l5_dia2": {
"id": "int_sdj_formations_l5_dia2",
"ch": 5,
"title": "Trait aux blancs",
"start": {
"wm": [
32,
33,
34,
35,
38,
39,
43,
47
],
"wk": [],
"bm": [
3,
6,
11,
14,
17,
19,
24,
25
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Trait aux blancs"
},
"int_sdj_formations_l5_dia3": {
"id": "int_sdj_formations_l5_dia3",
"ch": 5,
"title": "Brunssum 2000",
"start": {
"wm": [
27,
28,
33,
34,
35,
37,
38,
39,
43
],
"wk": [],
"bm": [
12,
13,
15,
16,
18,
19,
24,
25,
26
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Brunssum 2000"
},
"int_sdj_formations_l5_dia4": {
"id": "int_sdj_formations_l5_dia4",
"ch": 5,
"title": "Trait aux noirs",
"start": {
"wm": [
25,
26,
27,
30,
35,
36,
38,
39,
43
],
"wk": [],
"bm": [
8,
12,
13,
14,
16,
17,
18,
19,
24
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Trait aux noirs"
},
"int_sdj_formations_l5_dia5": {
"id": "int_sdj_formations_l5_dia5",
"ch": 5,
"title": "Diag. 6",
"start": {
"wm": [
26,
27,
28,
30,
32,
33,
35,
36,
38,
39,
48
],
"wk": [],
"bm": [
1,
5,
8,
12,
13,
16,
17,
18,
19,
23,
24
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Diag. 6"
},
"int_sdj_formations_l5_dia6": {
"id": "int_sdj_formations_l5_dia6",
"ch": 5,
"title": "NLD-ch sf Groep 1, 1977",
"start": {
"wm": [
26,
27,
33,
34,
35,
36,
38,
39,
43,
47,
50
],
"wk": [],
"bm": [
8,
12,
13,
15,
16,
17,
18,
19,
20,
23,
24
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "NLD-ch sf Groep 1, 1977"
},
"int_sdj_formations_l5_dia7": {
"id": "int_sdj_formations_l5_dia7",
"ch": 5,
"title": "La menace (28-32) est inévitable",
"start": {
"wm": [
27,
32,
33,
34,
35,
38,
39,
43,
48
],
"wk": [],
"bm": [
2,
15,
16,
18,
19,
23,
24,
25,
26
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "La menace (28-32) est inévitable"
},
"int_sdj_formations_l5_dia8": {
"id": "int_sdj_formations_l5_dia8",
"ch": 5,
"title": "Nicolai Mistchanski – Edvard Buzinskij",
"start": {
"wm": [
27,
28,
33,
34,
35,
37,
39,
43
],
"wk": [],
"bm": [
8,
9,
11,
12,
13,
15,
24,
25
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "Nicolai Mistchanski – Edvard Buzinskij"
},
"int_sdj_formations_l5_ex0": {
"id": "int_sdj_formations_l5_ex0",
"ch": 5,
"title": "LA FORMATION 34-39-43 – D1",
"start": {
"wm": [
27,
28,
32,
33,
34,
35,
37,
38,
39,
43
],
"wk": [],
"bm": [
15,
16,
17,
18,
19,
21,
23,
24,
25,
26
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "27-22",
"f": 27,
"t": 22,
"c": [],
"path": [
27,
22
],
"p": false
},
{
"n": "18x27",
"f": 18,
"t": 27,
"c": [
22
],
"path": [
18,
27
],
"p": false
}
],
"theme": "sdj_ch132",
"pub": "27-22 18x27 28-23 19x28 33x11 16x7 34-30 25x34 39x8",
"win": "white"
},
"int_sdj_formations_l5_ex1": {
"id": "int_sdj_formations_l5_ex1",
"ch": 5,
"title": "LA FORMATION 34-39-43 – D2",
"start": {
"wm": [
27,
28,
32,
33,
34,
35,
37,
38,
39,
43
],
"wk": [],
"bm": [
13,
15,
16,
17,
18,
19,
21,
24,
25,
26
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "28-22",
"f": 28,
"t": 22,
"c": [],
"path": [
28,
22
],
"p": false
},
{
"n": "17x28",
"f": 17,
"t": 28,
"c": [
22
],
"path": [
17,
28
],
"p": false
}
],
"theme": "sdj_ch132",
"pub": "28-22 17x28 33x13 19x8 34-30 25x34 39x28",
"win": "white"
},
"int_sdj_formations_l5_ex2": {
"id": "int_sdj_formations_l5_ex2",
"ch": 5,
"title": "LA FORMATION 34-39-43 – D3",
"start": {
"wm": [
22,
28,
33,
34,
35,
36,
37,
38,
39,
43
],
"wk": [],
"bm": [
3,
11,
12,
13,
15,
16,
19,
24,
25,
26
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "37-31",
"f": 37,
"t": 31,
"c": [],
"path": [
37,
31
],
"p": false
}
],
"theme": "sdj_ch132",
"pub": "37-31 26x28 38-33 21x32 33x13 19x8 34-30 25x34 39x37",
"win": "white"
},
"int_sdj_formations_l5_ex3": {
"id": "int_sdj_formations_l5_ex3",
"ch": 5,
"title": "LA FORMATION 34-39-43 – D4",
"start": {
"wm": [
27,
32,
34,
35,
37,
38,
39,
43
],
"wk": [],
"bm": [
16,
18,
19,
21,
23,
24,
25,
26
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "37-31",
"f": 37,
"t": 31,
"c": [],
"path": [
37,
31
],
"p": false
}
],
"theme": "sdj_ch132",
"pub": "37-31 19x17 37-31 26x37 38-32 37x28 33x22 17x28 34-30 25x34",
"win": "white"
},
"int_sdj_formations_l5_ex4": {
"id": "int_sdj_formations_l5_ex4",
"ch": 5,
"title": "LA FORMATION 34-39-43 – D5",
"start": {
"wm": [
27,
28,
32,
34,
35,
37,
38,
39,
43
],
"wk": [],
"bm": [
12,
16,
17,
18,
19,
23,
24,
25,
26
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "28-22",
"f": 28,
"t": 22,
"c": [],
"path": [
28,
22
],
"p": false
}
],
"theme": "sdj_ch132",
"pub": "28-22 14x23 38-32 27x47 26-21 47x24 34-30 25x34 39x6",
"win": "white"
},
"int_sdj_formations_l5_ex5": {
"id": "int_sdj_formations_l5_ex5",
"ch": 5,
"title": "LA FORMATION 34-39-43 – D6",
"start": {
"wm": [
23,
26,
29,
34,
35,
36,
38,
39,
42,
43,
44,
49
],
"wk": [],
"bm": [
8,
9,
10,
11,
12,
14,
15,
18,
20,
22,
25,
27
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "23-19",
"f": 23,
"t": 19,
"c": [],
"path": [
23,
19
],
"p": false
}
],
"theme": "sdj_ch132",
"pub": "23-19 17x28 38-33 26-31 33x13 31x42 27-22 19x8 32-28 23x32",
"win": "white"
}
}
}

export default DATA
