// Auto-generated by backend/curriculum/build_parcours_manuels.py — do not edit by hand.
import type { ManuelData } from '../ManuelInteractif'

const DATA: ManuelData = {
"book": "Les coups nommés",
"level": "Débutant",
"chapters": [
{
"n": 0,
"title": "Présentation"
},
{
"n": 1,
"title": "La transition vers les combinaisons en 4 temps"
},
{
"n": 2,
"title": "Le coup de l’express"
},
{
"n": 3,
"title": "Le coup de ricochet"
},
{
"n": 4,
"title": "Le coup de rappel"
},
{
"n": 5,
"title": "Le coup renversé"
},
{
"n": 6,
"title": "Le coup Napoléon"
},
{
"n": 7,
"title": "Le coup de la trappe"
},
{
"n": 8,
"title": "Le coup de talon"
},
{
"n": 9,
"title": "Le coup Philippe"
},
{
"n": 10,
"title": "Récapitulatif"
}
],
"blocks": [
{
"type": "h1",
"ch": 0,
"runs": [
{
"t": "Les coups nommés"
}
]
},
{
"type": "p",
"ch": 0,
"runs": [
{
"t": "Express, ricochet, rappel, renversé, Napoléon, trappe, talon, Philippe."
}
]
},
{
"type": "p",
"ch": 0,
"runs": [
{
"b": 1,
"t": "Objectif. "
},
{
"t": "Reconnaître et exécuter les coups nommés classiques."
}
]
},
{
"type": "h2",
"ch": 1,
"runs": [
{
"t": "La transition vers les combinaisons en 4 temps"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "Le passage des combinaisons en 3 temps à celles en 4, ne constitue pas vraiment une étape. La manière de chercher les solutions demeure inchangée et les mécanismes de base restent les mêmes. Pourtant, ces combinaisons peuvent apparaître pour certains difficiles à résoudre. Il n’y a normalement rien d’inquiétant à cette situation. Cela peut avoir pour origine l’une des trois raisons suivantes : 1 – Le nombre de possibilité s’étant accru, il est préférable de rechercher les solutions en commençant par identifier la rafle et le point de départ. Il convient de privilégier le raisonnement et d’adopter une méthode rationnelle afin de capitaliser l’expérience acquise. Si vous persistez à examiner toutes les solutions possibles, à partir de la position de départ, il est probable que vous vous épuiserez et finirez par abandonner. Je vous recommande vivement de commencer par chercher la rafle la plus plausible. Même si vous ne trouvez pas la solution, cette démarche vous sera à l’usage beaucoup plus profitable. 2 – Envisager une combinaison en 4 temps, revient à mémoriser sept demi-coups, soit le nombre d’unités d’information considéré comme une limite haute chez la majorité des gens. Il est possible que vous rencontriez des difficultés à l’approche de cette limite. Dans ce cas, ce n’est pas un problème, les exercices vous aideront à franchir le cap et cela vous sera bénéfique dans votre vie quotidienne. 3 – Pour diverses raisons, il est possible que vous n’ayez pas assimilé les différents mécanismes d’envoi à dame, prise majoritaire, collage, temps de repos et que vous éprouviez des difficultés à passer le cran supérieur. Dans ce cas, je vous invite à prendre votre temps et réviser les combinaisons en 2 et 3 temps, l’idéal étant de parvenir à une forme d’automatisme."
}
]
},
{
"type": "h2",
"ch": 2,
"runs": [
{
"t": "Le coup de l’express"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "Nous avons déjà rencontré les principaux mécanismes de base qui permettent d’effectuer les combinaisons. Pour rappel, il s’agit de la prise majoritaire, du collage, de l’envoi à dame et des temps de repos. Il existe d’autres mécanismes qui se rencontrent assez fréquemment. Il est utile de les répertorier et de les mémoriser. Le premier mécanisme que nous allons détailler est connu sous le nom de coup de l’express."
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "Position clé pour les blancs"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "La position de base est bien souvent celle du premier diagramme. La combinaison typique du coup de l’express est celle du second diagramme. Elle se termine par une rafle 33x4 ou 33x2 comme le montre le troisième diagramme. Solution : à partir du 2 e diag. 37-31 (26x37) 27-21 (16x27) 28-22 (27x18) 38-32 (37x28) 33x2 ou 33x4."
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "Cette combinaison se rencontre fréquemment sous la forme élégante d’un forcing. Dans l’exemple suivant, les Blancs attaquent le pion 22 par 32-28 et après l’esquive (22-27) les Blancs concluent par 24-19 (13x24) 28-22 (27x18) 36-31 (26x37) 38-32 (37x28) 33x2 B+"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "Les 3 pions noirs 24, 26 et 27 ne font pas bon ménage lorsque le camp adverse possède le centre. Les Blancs Forcent le jeu ici par une manœuvre bien connue : 1. 34-30 3. 37-31"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "11-17 26x37"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "2. 30x19 4. 28-22"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "Sur (17x28), gain de pion 5. 38-32"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "37x28"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "6. 33x2"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "13x24 27x18"
}
]
},
{
"type": "h2",
"ch": 3,
"runs": [
{
"t": "Le coup de ricochet"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "Nous allons à présent poursuivre notre investigation avec le mécanisme du coup de ricochet."
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "Le schéma de base est présenté dans les deux premiers diagrammes. Dans le 1er diag, les Blancs jouent 34-30 (25x34) 40x18 et la prise (13x22) permet au pion blanc 28 de ricocher sur la case 26 comme le montre le 3e diagramme. Dans le 2e diagramme, les Blancs sacrifient d’abord le pion 27 par 27-22 et se retrouvent ensuite dans la même situation que le premier diagramme."
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "Ce type de combinaison présente un intérêt pratique dans le genre de situation suivante : Les Blancs ont leur aile gauche encombrée. Ils peuvent tirer profit de la présence d’un pion noir en 25 en jouant : 1. 27-22"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "18x27"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "2. 31x22"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "Les Noirs sont menacés de 22-18 ou 34-30. L’attaque du pion 22 n’est pas possible en raison du coup de ricochet. 2… 4. 34-30 6. 28x26"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "12-18 25x34"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "3. 46-41 5. 40x18"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "18x27 13x22"
}
]
},
{
"type": "p",
"ch": 3,
"runs": [
{
"t": "A noter que dans la position du diagramme, après 31-26, les Noirs seraient forcés de fermer par (1217) pour éviter le coup de ricochet. Il existe d’autres formes de coup de ricochet que vous rencontrerez dans les combinaisons à rechercher."
}
]
},
{
"type": "h2",
"ch": 4,
"runs": [
{
"t": "Le coup de rappel"
}
]
},
{
"type": "p",
"ch": 4,
"runs": [
{
"t": "Le mécanisme suivant est connu sous le nom de coup de rappel. Il se présente fréquemment en partie et les formes les plus usuelles se retrouvent dans les trois diagrammes suivants :"
}
]
},
{
"type": "p",
"ch": 4,
"runs": [
{
"t": "1er diagramme : 28-23 (19x39) et rappel par 38-33 (39x28) 32x3 2e diagramme : 30-24 (19x39) et rappel par 40-34 (39x30) 35x4 3e diagramme : 28-22 (17x37 et rappel par 38-32 (37x28) 33x4"
}
]
},
{
"type": "p",
"ch": 4,
"runs": [
{
"t": "Une situation caractéristique en fin de milieu de partie classique. Le développement naturel (13-18) est interdit par un coup de rappel. 1… 3. 28-22 5. 33x4"
}
]
},
{
"type": "p",
"ch": 4,
"runs": [
{
"t": "13-18 27x18"
}
]
},
{
"type": "p",
"ch": 4,
"runs": [
{
"t": "2. 27-22 4. 37-31"
}
]
},
{
"type": "p",
"ch": 4,
"runs": [
{
"t": "18x27 26x28"
}
]
},
{
"type": "p",
"ch": 4,
"runs": [
{
"t": "Les blancs ont une combinaison très connue, mais que je trouve toujours très stupéfiante en raison de la prise finale de 4 pions par la dame : 1. 34-29 3. 38-33 5. 3x4"
}
]
},
{
"type": "p",
"ch": 4,
"runs": [
{
"t": "23x25 39x28"
}
]
},
{
"type": "p",
"ch": 4,
"runs": [
{
"t": "2. 28-23 4. 32x3"
}
]
},
{
"type": "p",
"ch": 4,
"runs": [
{
"t": "19x39 21x41"
}
]
},
{
"type": "h2",
"ch": 5,
"runs": [
{
"t": "Le coup renversé"
}
]
},
{
"type": "p",
"ch": 5,
"runs": [
{
"t": "A présent, un mécanisme moins courant, mais utile à connaître car il se marie facilement avec des coups de mazette, coups philippe, et même des coups de ricochet. Il s’agit du coup renversé."
}
]
},
{
"type": "p",
"ch": 5,
"runs": [
{
"t": "Sa forme la plus élémentaire figure dans le diagramme ci-contre."
}
]
},
{
"type": "p",
"ch": 5,
"runs": [
{
"t": "Les blancs dament par 27-21, forçant les Noirs à prendre 2 pions par (26x28), avec la rafle 32x3."
}
]
},
{
"type": "p",
"ch": 5,
"runs": [
{
"t": "Dans le premier diagramme, les blancs forcent le jeu en amenant un coup renversé par 25-20 (24x15) 28-22 (8-13) 34-29 (23x34) 27-21 (26x28) 32x5. A noter que si les blancs attaquent directement par 1. 28-22, les noirs ont une défense par (10-14) 2. 22x2 (16-21) 3. 27x16 (26-31) 4. 37x26 (23-29) 5. 34x23 (19x48) 6. 2x30 (14-20) 7. 25x14 (48x9) Dans le second diagramme, les blancs utilisent le mécanisme du coup renversé pour éliminer les pions 16 et 18, afin d’exécuter ensuite la rafle caractéristique du coup philippe, 40x16. Solution : 27-21 (26x28) 33x22 (18x27) 31x21 (16x27) 34-30 (25x34) 40x16 Le troisième diagramme associe le mécanisme du coup renversé avec un coup de ricochet par 2721 (26x28) 32x23 (18x29) 33x15."
}
]
},
{
"type": "p",
"ch": 5,
"runs": [
{
"t": "Le diagramme suivant présente une autre forme de coup renversé, assez inattendue, sur l’autre aile du damier : 1. 28-23 19x30 forcé 3. 33x2"
}
]
},
{
"type": "p",
"ch": 5,
"runs": [
{
"t": "2. 29-24"
}
]
},
{
"type": "p",
"ch": 5,
"runs": [
{
"t": "30x28"
}
]
},
{
"type": "h2",
"ch": 6,
"runs": [
{
"t": "Le coup Napoléon"
}
]
},
{
"type": "p",
"ch": 6,
"runs": [
{
"t": "Le type de combinaison que je vous propose à présent, est connu sous le nom de coup Napoléon. On le trouve sous différentes formes :"
}
]
},
{
"type": "p",
"ch": 6,
"runs": [
{
"t": "Les Blancs jouent 26-21"
}
]
},
{
"type": "p",
"ch": 6,
"runs": [
{
"t": "Les Blancs jouent 27-22"
}
]
},
{
"type": "p",
"ch": 6,
"runs": [
{
"t": "Les Blancs jouent 35-30"
}
]
},
{
"type": "p",
"ch": 6,
"runs": [
{
"t": "Le coup Napoléon est surtout caractérisé par la forme de sa rafle et par le dernier coup pour aboutir à cette rafle. Les coups qui précèdent sont très divers et souvent très spectaculaires. En voici quelques-uns :"
}
]
},
{
"type": "p",
"ch": 6,
"runs": [
{
"t": "La position à trouver est celle du second diagramme. On voit qu’il faut amener 3 pions noirs en 27-28 et 29. Solution : 27-22 (18x29) 28-22 (17x28) 26-21 (16x27) 31x4."
}
]
},
{
"type": "p",
"ch": 6,
"runs": [
{
"t": "La position à trouver est celle du second diagramme. On voit qu’il faut amener 3 pions noirs en 27-28 et 29, tout en éliminant les pions noirs 18 et 29. Le procédé suivant permet d’y parvenir élégamment par 3731 (26x28) 27-22 (18x27) 29x7 (2x11) 42-37 (20x29) 34x3."
}
]
},
{
"type": "h2",
"ch": 7,
"runs": [
{
"t": "Le coup de la trappe"
}
]
},
{
"type": "p",
"ch": 7,
"runs": [
{
"t": "Les combinaisons sont bien souvent inattendues. Même les mécanismes les plus usuels peuvent échapper à notre vigilance. Ainsi, le coup de la trappe figure parmi les mécanismes assez sophistiqués. Le mécanisme de base est le suivant :"
}
]
},
{
"type": "p",
"ch": 7,
"runs": [
{
"t": "Dans la position du 1er diag. Les Blancs ont un coup de dame en 2. Le problème, c’est qu’il n’y a pas de pion d’appui pour exécuter la rafle 33x2. Le mécanisme du coup de la trappe permet de créer un pion d’appui en emprisonnant un pion noir, comme le montre le second diagramme. La suite est alors évidente. Solution : 44-39 (35x44) 37-31 (26x28) 33x2 (44x33), le pion noir ricoche, 38x20. Comme on le voit, ce mécanisme permet éventuellement de cumuler 2 rafles."
}
]
},
{
"type": "p",
"ch": 7,
"runs": [
{
"t": "Les Blancs gagnent en associant le mécanisme de la trappe avec un coup renversé : 1. 38-32 29x38 3. 32x3"
}
]
},
{
"type": "p",
"ch": 7,
"runs": [
{
"t": "2. 27-21"
}
]
},
{
"type": "p",
"ch": 7,
"runs": [
{
"t": "26x28"
}
]
},
{
"type": "p",
"ch": 7,
"runs": [
{
"t": "Les Blancs gagnent ici par un double coup de la trappe : 1. 44-39 35x44 3. 36-31 26x37 5. 38x18 44x33"
}
]
},
{
"type": "p",
"ch": 7,
"runs": [
{
"t": "2. 32-27 4. 38-32 6. 47x9"
}
]
},
{
"type": "p",
"ch": 7,
"runs": [
{
"t": "22x42 37x28"
}
]
},
{
"type": "p",
"ch": 7,
"runs": [
{
"t": "Comme on le voit, les rafles finales concluant les coups de la trappe, sont assez difficiles à prévoir."
}
]
},
{
"type": "h2",
"ch": 8,
"runs": [
{
"t": "Le coup de talon"
}
]
},
{
"type": "p",
"ch": 8,
"runs": [
{
"t": "Le mécanisme que je vous propose de découvrir à présent est également surprenant. Il s’agit du coup de talon. En fait, ce mécanisme ne dévoile le point d’appui de la rafle qu’au dernier moment. Par exemple :"
}
]
},
{
"type": "p",
"ch": 8,
"runs": [
{
"t": "La rafle finale aboutit bien sur la case 7 (diag. 2). Le pion de départ de la rafle est le pion 40, masqué par le pion 34. Cela signifie qu’il va falloir déloger le pion 34 pour permettre la reprise (25x34) puis 40x7. Le coup de talon permet d’y parvenir (diag. 3) Solution : 37-31 (26x39) 34x43 (25x34) 40x7"
}
]
},
{
"type": "p",
"ch": 8,
"runs": [
{
"t": "Dans la position suivante, les blancs utilisent le même mécanisme, cette fois-ci sur l’autre aile : 1. 34-30"
}
]
},
{
"type": "p",
"ch": 8,
"runs": [
{
"t": "24x42"
}
]
},
{
"type": "p",
"ch": 8,
"runs": [
{
"t": "2. 37x48"
}
]
},
{
"type": "p",
"ch": 8,
"runs": [
{
"t": "26x37"
}
]
},
{
"type": "p",
"ch": 8,
"runs": [
{
"t": "3. 41x5"
}
]
},
{
"type": "p",
"ch": 8,
"runs": [
{
"t": "Le coup de talon présente un intérêt pratique en classique lors de l’avancée à 22. 1. 27-22 Les noirs sont menacés de 35-30 (24x35) 34-29 (23x34) 39x30 (35x24) 22-18 (13x22) 28x6. Ils ne peuvent jouer : 1…"
}
]
},
{
"type": "p",
"ch": 8,
"runs": [
{
"t": "11-17"
}
]
},
{
"type": "p",
"ch": 8,
"runs": [
{
"t": "2. 22x11"
}
]
},
{
"type": "p",
"ch": 8,
"runs": [
{
"t": "16x7"
}
]
},
{
"type": "p",
"ch": 8,
"runs": [
{
"t": "4. 32x41"
}
]
},
{
"type": "p",
"ch": 8,
"runs": [
{
"t": "23x32"
}
]
},
{
"type": "p",
"ch": 8,
"runs": [
{
"t": "A cause du coup de talon : 3. 37-31 5. 38x16"
}
]
},
{
"type": "p",
"ch": 8,
"runs": [
{
"t": "26x37"
}
]
},
{
"type": "h2",
"ch": 9,
"runs": [
{
"t": "Le coup Philippe"
}
]
},
{
"type": "p",
"ch": 9,
"runs": [
{
"t": "Nous avons vu précédemment les mécanismes les plus originaux et les plus compliqués. Le mécanisme que je vais vous présenter est beaucoup plus simple et bien mieux connu. Il s’agit du coup Philippe. Mais le coup Philippe n’est pas vraiment un mécanisme. C’est plutôt une forme de combinaison dont la rafle finale commence par 40x ou 38x comme le montre les deux diagrammes ci-après :"
}
]
},
{
"type": "p",
"ch": 9,
"runs": [
{
"t": "Le principe de cette combinaison est très simple. D’un côté, on élimine les pions qui empêchent la rafle. De l’autre côté on amène un pion noir sur la case 33 ou 34. L’élimination des pions :"
}
]
},
{
"type": "p",
"ch": 9,
"runs": [
{
"t": "Pour faire sauter le pion 18, les blancs jouent : 1. 27-22"
}
]
},
{
"type": "p",
"ch": 9,
"runs": [
{
"t": "18x27"
}
]
},
{
"type": "p",
"ch": 9,
"runs": [
{
"t": "2. 32x21"
}
]
},
{
"type": "p",
"ch": 9,
"runs": [
{
"t": "16x27"
}
]
},
{
"type": "p",
"ch": 9,
"runs": [
{
"t": "Il ne reste plus qu’à jouer 33-29 ou 34-30 pour effectuer la rafle du coup Philippe"
}
]
},
{
"type": "p",
"ch": 9,
"runs": [
{
"t": "Amener un pion noir en 33 :"
}
]
},
{
"type": "p",
"ch": 9,
"runs": [
{
"t": "Les blancs ont 2 manières d’amener un pion en 33 : A - Le coup de rappel par 34-29 (24x44) 43-39 (44x33) B - Le coup du tourniquet par 35-30 (24x35) 45-40 (35x33)"
}
]
},
{
"type": "h2",
"ch": 10,
"runs": [
{
"t": "Récapitulatif"
}
]
},
{
"type": "p",
"ch": 10,
"runs": [
{
"t": "Avant de passer aux combinaisons en 5 temps, je vous propose de faire à nouveau un bilan de ce que nous avons vu. Je commence par rappeler une évidence. Notre cerveau, même après quelques années de pratique, ne « voit » pas spontanément des combinaisons en 2 temps. Il est nécessaire de mettre en œuvre un raisonnement. Cela commence par examiner les points de contact, suivre mentalement le déplacement des pions, et finalement découvrir la solution. La vitesse avec laquelle on décèle les combinaisons dépend de l’entrainement. Pour les combinaisons en 3 ou 4 temps, il faut recourir à un raisonnement plus élaboré. Le cheminement de la pensée nous conduit à rechercher la case d’arrivée de la rafle, sa case de départ et de répertorier les mécanismes disponibles pour acheminer les pions. A la suite de ce raisonnement, on peut commencer à déplacer mentalement les pièces, jusqu’au dénouement. Le déplacement mental des pièces nécessite un effort cérébral assez intense car il sollicite la mémoire de travail dans ses limites. Avec l’entraînement, les exercices paraissent plus simples et moins fatigants. Identifier les cases de départ et d’arrivée d’une rafle est primordial. En pratique, en partie, cela peut permettre d’affirmer qu’il n’y a pas de combinaison, tout simplement parce qu’il n’y a pas de rafle possible. Les combinaisons font toujours appel aux mêmes mécanismes de base, à savoir la prise majoritaire, le collage, les temps de repos, l’envoi à dame, et quelques autres plus spécifiques, comme le coup de rappel, le coup de talon, le coup de ricochet, par exemple. Avant d’entamer les séries avec des combinaisons en 5 temps, je vous conseille de bien maîtriser à la fois la méthode de recherche et le déroulement mental."
}
]
},
{
"type": "p",
"ch": 10,
"runs": [
{
"t": "Dans cette position, on peut affirmer qu’il n’y a pas de combinaison sur la case 5. La seule case de départ vraisemblable est la case 32, mais aucun pion noir ne peut être amené sur la case 28."
}
]
},
{
"type": "p",
"ch": 10,
"runs": [
{
"t": "Dans cette position, un coup de dame à 5 est potentiellement possible en concevant la rafle 43x5. En effet, le pion 26 peut être acheminé sur la case 39. Solution : 29-23 (18x29) 27-21 (16x27) 32x21 (26x17) 28-22 (17x39) 43x5."
}
]
}
],
"positions": {}
}

export default DATA
