// Auto-generated by backend/curriculum/build_parcours_manuels.py — do not edit by hand.
import type { ManuelData } from '../ManuelInteractif'

const DATA: ManuelData = {
"book": "La dame et la grande diagonale",
"level": "Intermédiaire",
"chapters": [
{
"n": 0,
"title": "Présentation"
},
{
"n": 1,
"title": "Capturer la dame sur la grande diagonale"
},
{
"n": 2,
"title": "La lutte pour la grande diagonale"
}
],
"blocks": [
{
"type": "h1",
"ch": 0,
"runs": [
{
"t": "La dame et la grande diagonale"
}
]
},
{
"type": "p",
"ch": 0,
"runs": [
{
"t": "La diagonale a1-h8, axe du jeu de dames."
}
]
},
{
"type": "p",
"ch": 0,
"runs": [
{
"b": 1,
"t": "Objectif. "
},
{
"t": "Maîtriser la lutte sur la grande diagonale et capturer une dame qui s'y aventure."
}
]
},
{
"type": "h2",
"ch": 1,
"runs": [
{
"t": "Capturer la dame sur la grande diagonale"
}
]
},
{
"type": "p",
"ch": 1,
"runs": [
{
"t": "Une dame sur la grande diagonale est puissante… mais vulnérable. Voici comment la piéger."
}
]
},
{
"type": "board",
"id": "int_grande_diagonale_l1_ex0",
"ch": 1
},
{
"type": "board",
"id": "int_grande_diagonale_l1_ex1",
"ch": 1
},
{
"type": "board",
"id": "int_grande_diagonale_l1_ex2",
"ch": 1
},
{
"type": "board",
"id": "int_grande_diagonale_l1_ex3",
"ch": 1
},
{
"type": "board",
"id": "int_grande_diagonale_l1_ex4",
"ch": 1
},
{
"type": "board",
"id": "int_grande_diagonale_l1_ex5",
"ch": 1
},
{
"type": "board",
"id": "int_grande_diagonale_l1_ex6",
"ch": 1
},
{
"type": "board",
"id": "int_grande_diagonale_l1_ex7",
"ch": 1
},
{
"type": "board",
"id": "int_grande_diagonale_l1_ex8",
"ch": 1
},
{
"type": "board",
"id": "int_grande_diagonale_l1_ex9",
"ch": 1
},
{
"type": "board",
"id": "int_grande_diagonale_l1_ex10",
"ch": 1
},
{
"type": "board",
"id": "int_grande_diagonale_l1_ex11",
"ch": 1
},
{
"type": "board",
"id": "int_grande_diagonale_l1_ex12",
"ch": 1
},
{
"type": "board",
"id": "int_grande_diagonale_l1_ex13",
"ch": 1
},
{
"type": "h2",
"ch": 2,
"runs": [
{
"t": "La lutte pour la grande diagonale"
}
]
},
{
"type": "p",
"ch": 2,
"runs": [
{
"t": "Contrôler la grande diagonale, c'est contrôler la partie. Apprenez à la prendre et à la garder."
}
]
},
{
"type": "board",
"id": "int_grande_diagonale_l2_ex0",
"ch": 2
},
{
"type": "board",
"id": "int_grande_diagonale_l2_ex1",
"ch": 2
},
{
"type": "board",
"id": "int_grande_diagonale_l2_pos2",
"ch": 2
},
{
"type": "board",
"id": "int_grande_diagonale_l2_pos3",
"ch": 2
},
{
"type": "board",
"id": "int_grande_diagonale_l2_pos4",
"ch": 2
},
{
"type": "board",
"id": "int_grande_diagonale_l2_pos5",
"ch": 2
},
{
"type": "board",
"id": "int_grande_diagonale_l2_pos6",
"ch": 2
},
{
"type": "board",
"id": "int_grande_diagonale_l2_pos7",
"ch": 2
}
],
"positions": {
"int_grande_diagonale_l1_ex0": {
"id": "int_grande_diagonale_l1_ex0",
"ch": 1,
"title": "SIJBRANDS — combinaison (p.106 #17)",
"start": {
"wm": [
8,
15
],
"wk": [],
"bm": [
31
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "8-2",
"f": 8,
"t": 2,
"c": [],
"path": [
8,
2
],
"p": true
}
],
"theme": "Capturer la dame sur la grande diagonale.",
"pub": "8-2",
"win": "white",
"exp": "Capturer la dame sur la grande diagonale."
},
"int_grande_diagonale_l1_ex1": {
"id": "int_grande_diagonale_l1_ex1",
"ch": 1,
"title": "SIJBRANDS — combinaison (p.108 #10)",
"start": {
"wm": [
7,
50
],
"wk": [],
"bm": [
34,
35
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "7-1",
"f": 7,
"t": 1,
"c": [],
"path": [
7,
1
],
"p": true
}
],
"theme": "Capturer la dame sur la grande diagonale.",
"pub": "7-1",
"win": "white",
"exp": "Capturer la dame sur la grande diagonale."
},
"int_grande_diagonale_l1_ex2": {
"id": "int_grande_diagonale_l1_ex2",
"ch": 1,
"title": "SIJBRANDS — combinaison (p.108 #12)",
"start": {
"wm": [
39
],
"wk": [
50
],
"bm": [
12,
45
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "39-34",
"f": 39,
"t": 34,
"c": [],
"path": [
39,
34
],
"p": false
},
{
"n": "12-18",
"f": 12,
"t": 18,
"c": [],
"path": [
12,
18
],
"p": false
},
{
"n": "34-29",
"f": 34,
"t": 29,
"c": [],
"path": [
34,
29
],
"p": false
},
{
"n": "18-22",
"f": 18,
"t": 22,
"c": [],
"path": [
18,
22
],
"p": false
},
{
"n": "50x6",
"f": 50,
"t": 6,
"c": [
22
],
"path": [
50,
6
],
"p": false
},
{
"n": "45-50",
"f": 45,
"t": 50,
"c": [],
"path": [
45,
50
],
"p": true
},
{
"n": "29-23",
"f": 29,
"t": 23,
"c": [],
"path": [
29,
23
],
"p": false
},
{
"n": "50-45",
"f": 50,
"t": 45,
"c": [],
"path": [
50,
45
],
"p": false
},
{
"n": "6-1",
"f": 6,
"t": 1,
"c": [],
"path": [
6,
1
],
"p": false
},
{
"n": "45x18",
"f": 45,
"t": 18,
"c": [
23
],
"path": [
45,
18
],
"p": false
},
{
"n": "1x23",
"f": 1,
"t": 23,
"c": [
18
],
"path": [
1,
23
],
"p": false
}
],
"theme": "Capturer la dame sur la grande diagonale.",
"pub": "39-34 12-18 34-29 18-22 50x6 45-50 29-23 50-45 6-1 45x18 1x23",
"win": "white",
"exp": "Capturer la dame sur la grande diagonale."
},
"int_grande_diagonale_l1_ex3": {
"id": "int_grande_diagonale_l1_ex3",
"ch": 1,
"title": "SIJBRANDS — combinaison (p.108 #4)",
"start": {
"wm": [
7,
29
],
"wk": [],
"bm": [
45
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "7-1",
"f": 7,
"t": 1,
"c": [],
"path": [
7,
1
],
"p": true
}
],
"theme": "Capturer la dame sur la grande diagonale.",
"pub": "7-1",
"win": "white",
"exp": "Capturer la dame sur la grande diagonale."
},
"int_grande_diagonale_l1_ex4": {
"id": "int_grande_diagonale_l1_ex4",
"ch": 1,
"title": "SIJBRANDS — combinaison (p.109 #14)",
"start": {
"wm": [
15,
18,
32
],
"wk": [],
"bm": [
40
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "15-10",
"f": 15,
"t": 10,
"c": [],
"path": [
15,
10
],
"p": false
},
{
"n": "40-44",
"f": 40,
"t": 44,
"c": [],
"path": [
40,
44
],
"p": false
},
{
"n": "10-4",
"f": 10,
"t": 4,
"c": [],
"path": [
10,
4
],
"p": true
},
{
"n": "44-49",
"f": 44,
"t": 49,
"c": [],
"path": [
44,
49
],
"p": true
},
{
"n": "18-13",
"f": 18,
"t": 13,
"c": [],
"path": [
18,
13
],
"p": false
},
{
"n": "49x27x9",
"f": 49,
"t": 9,
"c": [
32,
13
],
"path": [
49,
27,
9
],
"p": false
},
{
"n": "4x13",
"f": 4,
"t": 13,
"c": [
9
],
"path": [
4,
13
],
"p": false
}
],
"theme": "Capturer la dame sur la grande diagonale.",
"pub": "15-10 40-44 10-4 44-49 18-13 49x27x9 4x13",
"win": "white",
"exp": "Capturer la dame sur la grande diagonale."
},
"int_grande_diagonale_l1_ex5": {
"id": "int_grande_diagonale_l1_ex5",
"ch": 1,
"title": "SIJBRANDS — combinaison (p.109 #17)",
"start": {
"wm": [
10,
26,
35
],
"wk": [],
"bm": [
38
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "10-5",
"f": 10,
"t": 5,
"c": [],
"path": [
10,
5
],
"p": true
}
],
"theme": "Capturer la dame sur la grande diagonale.",
"pub": "10-5",
"win": "white",
"exp": "Capturer la dame sur la grande diagonale."
},
"int_grande_diagonale_l1_ex6": {
"id": "int_grande_diagonale_l1_ex6",
"ch": 1,
"title": "SIJBRANDS — combinaison (p.110 #18)",
"start": {
"wm": [
9,
16,
25
],
"wk": [],
"bm": [
33
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "9-4",
"f": 9,
"t": 4,
"c": [],
"path": [
9,
4
],
"p": true
}
],
"theme": "Capturer la dame sur la grande diagonale.",
"pub": "9-4",
"win": "white",
"exp": "Capturer la dame sur la grande diagonale."
},
"int_grande_diagonale_l1_ex7": {
"id": "int_grande_diagonale_l1_ex7",
"ch": 1,
"title": "SIJBRANDS — combinaison (p.110 #19)",
"start": {
"wm": [
10,
26,
35
],
"wk": [],
"bm": [
33
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "10-4",
"f": 10,
"t": 4,
"c": [],
"path": [
10,
4
],
"p": true
}
],
"theme": "Capturer la dame sur la grande diagonale.",
"pub": "10-4",
"win": "white",
"exp": "Capturer la dame sur la grande diagonale."
},
"int_grande_diagonale_l1_ex8": {
"id": "int_grande_diagonale_l1_ex8",
"ch": 1,
"title": "SIJBRANDS — combinaison (p.113 #13)",
"start": {
"wm": [
9,
36,
48
],
"wk": [],
"bm": [],
"bk": [
15
],
"turn": "white"
},
"moves": [
{
"n": "9-4",
"f": 9,
"t": 4,
"c": [],
"path": [
9,
4
],
"p": true
}
],
"theme": "Capturer la dame sur la grande diagonale.",
"pub": "9-4",
"win": "white",
"exp": "Capturer la dame sur la grande diagonale."
},
"int_grande_diagonale_l1_ex9": {
"id": "int_grande_diagonale_l1_ex9",
"ch": 1,
"title": "SIJBRANDS — combinaison (p.114 #14)",
"start": {
"wm": [
10
],
"wk": [
19
],
"bm": [],
"bk": [
14
],
"turn": "white"
},
"moves": [
{
"n": "19-41",
"f": 19,
"t": 41,
"c": [],
"path": [
19,
41
],
"p": false
},
{
"n": "14x46",
"f": 14,
"t": 46,
"c": [
41
],
"path": [
14,
46
],
"p": false
},
{
"n": "10-5",
"f": 10,
"t": 5,
"c": [],
"path": [
10,
5
],
"p": true
},
{
"n": "46-41",
"f": 46,
"t": 41,
"c": [],
"path": [
46,
41
],
"p": false
},
{
"n": "5x46",
"f": 5,
"t": 46,
"c": [
41
],
"path": [
5,
46
],
"p": false
}
],
"theme": "Capturer la dame sur la grande diagonale.",
"pub": "19-41 14x46 10-5 46-41 5x46",
"win": "white",
"exp": "Capturer la dame sur la grande diagonale."
},
"int_grande_diagonale_l1_ex10": {
"id": "int_grande_diagonale_l1_ex10",
"ch": 1,
"title": "SIJBRANDS — combinaison (p.114 #16)",
"start": {
"wm": [
6,
49
],
"wk": [],
"bm": [],
"bk": [
40
],
"turn": "white"
},
"moves": [
{
"n": "6-1",
"f": 6,
"t": 1,
"c": [],
"path": [
6,
1
],
"p": true
}
],
"theme": "Capturer la dame sur la grande diagonale.",
"pub": "6-1",
"win": "white",
"exp": "Capturer la dame sur la grande diagonale."
},
"int_grande_diagonale_l1_ex11": {
"id": "int_grande_diagonale_l1_ex11",
"ch": 1,
"title": "SIJBRANDS — combinaison (p.114 #17)",
"start": {
"wm": [
42,
45,
50
],
"wk": [],
"bm": [
35
],
"bk": [
16
],
"turn": "white"
},
"moves": [
{
"n": "42-38",
"f": 42,
"t": 38,
"c": [],
"path": [
42,
38
],
"p": false
},
{
"n": "16x49",
"f": 16,
"t": 49,
"c": [
38
],
"path": [
16,
49
],
"p": false
},
{
"n": "50-44",
"f": 50,
"t": 44,
"c": [],
"path": [
50,
44
],
"p": false
},
{
"n": "49x40",
"f": 49,
"t": 40,
"c": [
44
],
"path": [
49,
40
],
"p": false
},
{
"n": "45x34",
"f": 45,
"t": 34,
"c": [
40
],
"path": [
45,
34
],
"p": false
},
{
"n": "35-40",
"f": 35,
"t": 40,
"c": [],
"path": [
35,
40
],
"p": false
},
{
"n": "34x45",
"f": 34,
"t": 45,
"c": [
40
],
"path": [
34,
45
],
"p": false
}
],
"theme": "Capturer la dame sur la grande diagonale.",
"pub": "42-38 16x49 50-44 49x40 45x34 35-40 34x45",
"win": "white",
"exp": "Capturer la dame sur la grande diagonale."
},
"int_grande_diagonale_l1_ex12": {
"id": "int_grande_diagonale_l1_ex12",
"ch": 1,
"title": "SIJBRANDS — combinaison (p.114 #18)",
"start": {
"wm": [
14,
31,
47
],
"wk": [],
"bm": [],
"bk": [
18
],
"turn": "white"
},
"moves": [
{
"n": "14-10",
"f": 14,
"t": 10,
"c": [],
"path": [
14,
10
],
"p": false
},
{
"n": "18x36",
"f": 18,
"t": 36,
"c": [
31
],
"path": [
18,
36
],
"p": false
},
{
"n": "10-4",
"f": 10,
"t": 4,
"c": [],
"path": [
10,
4
],
"p": true
},
{
"n": "36-31",
"f": 36,
"t": 31,
"c": [],
"path": [
36,
31
],
"p": false
},
{
"n": "4x36",
"f": 4,
"t": 36,
"c": [
31
],
"path": [
4,
36
],
"p": false
}
],
"theme": "Capturer la dame sur la grande diagonale.",
"pub": "14-10 18x36 10-4 36-31 4x36",
"win": "white",
"exp": "Capturer la dame sur la grande diagonale."
},
"int_grande_diagonale_l1_ex13": {
"id": "int_grande_diagonale_l1_ex13",
"ch": 1,
"title": "SIJBRANDS — combinaison (p.114 #19)",
"start": {
"wm": [
15,
46,
48
],
"wk": [],
"bm": [],
"bk": [
23
],
"turn": "white"
},
"moves": [
{
"n": "15-10",
"f": 15,
"t": 10,
"c": [],
"path": [
15,
10
],
"p": false
},
{
"n": "23x5",
"f": 23,
"t": 5,
"c": [
10
],
"path": [
23,
5
],
"p": false
},
{
"n": "48-42",
"f": 48,
"t": 42,
"c": [],
"path": [
48,
42
],
"p": false
},
{
"n": "5-23",
"f": 5,
"t": 23,
"c": [],
"path": [
5,
23
],
"p": false
},
{
"n": "42-37",
"f": 42,
"t": 37,
"c": [],
"path": [
42,
37
],
"p": false
},
{
"n": "23x41",
"f": 23,
"t": 41,
"c": [
37
],
"path": [
23,
41
],
"p": false
},
{
"n": "46x37",
"f": 46,
"t": 37,
"c": [
41
],
"path": [
46,
37
],
"p": false
}
],
"theme": "Capturer la dame sur la grande diagonale.",
"pub": "15-10 23x5 48-42 5-23 42-37 23x41 46x37",
"win": "white",
"exp": "Capturer la dame sur la grande diagonale."
},
"int_grande_diagonale_l2_ex0": {
"id": "int_grande_diagonale_l2_ex0",
"ch": 2,
"title": "SIJBRANDS — combinaison (p.99 #1)",
"start": {
"wm": [
7
],
"wk": [],
"bm": [
13,
26
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "7-1",
"f": 7,
"t": 1,
"c": [],
"path": [
7,
1
],
"p": true
}
],
"theme": "La lutte pour la grande diagonale",
"pub": "7-1",
"win": "white",
"exp": "La lutte pour la grande diagonale"
},
"int_grande_diagonale_l2_ex1": {
"id": "int_grande_diagonale_l2_ex1",
"ch": 2,
"title": "SIJBRANDS — combinaison (p.181 #18)",
"start": {
"wm": [],
"wk": [
32
],
"bm": [
26,
31,
36
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "32-46",
"f": 32,
"t": 46,
"c": [],
"path": [
32,
46
],
"p": false
},
{
"n": "31-37",
"f": 31,
"t": 37,
"c": [],
"path": [
31,
37
],
"p": false
},
{
"n": "46x28",
"f": 46,
"t": 28,
"c": [
37
],
"path": [
46,
28
],
"p": false
},
{
"n": "36-41",
"f": 36,
"t": 41,
"c": [],
"path": [
36,
41
],
"p": false
},
{
"n": "28x46",
"f": 28,
"t": 46,
"c": [
41
],
"path": [
28,
46
],
"p": false
},
{
"n": "26-31",
"f": 26,
"t": 31,
"c": [],
"path": [
26,
31
],
"p": false
},
{
"n": "46-28",
"f": 46,
"t": 28,
"c": [],
"path": [
46,
28
],
"p": false
},
{
"n": "31-36",
"f": 31,
"t": 36,
"c": [],
"path": [
31,
36
],
"p": false
},
{
"n": "28-23",
"f": 28,
"t": 23,
"c": [],
"path": [
28,
23
],
"p": false
},
{
"n": "36-41",
"f": 36,
"t": 41,
"c": [],
"path": [
36,
41
],
"p": false
},
{
"n": "23x46",
"f": 23,
"t": 46,
"c": [
41
],
"path": [
23,
46
],
"p": false
}
],
"theme": "La lutte pour la grande diagonale",
"pub": "32-46 31-37 46x28 36-41 28x46 26-31 46-28 31-36 28-23 36-41 23x46",
"win": "white",
"exp": "La lutte pour la grande diagonale"
},
"int_grande_diagonale_l2_pos2": {
"id": "int_grande_diagonale_l2_pos2",
"ch": 2,
"title": "La lutte pour la grande diagonale",
"start": {
"wm": [],
"wk": [
34
],
"bm": [
13,
31
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "La lutte pour la grande diagonale"
},
"int_grande_diagonale_l2_pos3": {
"id": "int_grande_diagonale_l2_pos3",
"ch": 2,
"title": "La lutte pour la grande diagonale",
"start": {
"wm": [
33
],
"wk": [
5
],
"bm": [
27,
31,
36
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "La lutte pour la grande diagonale"
},
"int_grande_diagonale_l2_pos4": {
"id": "int_grande_diagonale_l2_pos4",
"ch": 2,
"title": "La lutte pour la grande diagonale",
"start": {
"wm": [
43
],
"wk": [
5
],
"bm": [
21,
31,
36
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "La lutte pour la grande diagonale"
},
"int_grande_diagonale_l2_pos5": {
"id": "int_grande_diagonale_l2_pos5",
"ch": 2,
"title": "La lutte pour la grande diagonale",
"start": {
"wm": [
7,
22
],
"wk": [],
"bm": [
21,
34
],
"bk": [],
"turn": "white"
},
"moves": [
{
"n": "7-1",
"f": 7,
"t": 1,
"c": [],
"path": [
7,
1
],
"p": true
}
],
"theme": "La lutte pour la grande diagonale",
"pub": "7-1",
"win": "white"
},
"int_grande_diagonale_l2_pos6": {
"id": "int_grande_diagonale_l2_pos6",
"ch": 2,
"title": "La lutte pour la grande diagonale",
"start": {
"wm": [
17
],
"wk": [
4
],
"bm": [
2,
33
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "La lutte pour la grande diagonale"
},
"int_grande_diagonale_l2_pos7": {
"id": "int_grande_diagonale_l2_pos7",
"ch": 2,
"title": "La lutte pour la grande diagonale",
"start": {
"wm": [
30
],
"wk": [
23
],
"bm": [
15,
25,
36
],
"bk": [],
"turn": "white"
},
"moves": [],
"theme": "La lutte pour la grande diagonale"
}
}
}

export default DATA
