import React, { useState, useMemo, useEffect, useRef } from 'react'
import {
  getLegalMoves, applyEngineMove, type EngineMove, type Turn,
  WHITE_MAN, WHITE_KING, BLACK_MAN, BLACK_KING,
} from './draughtsEngine'

// ---------------------------------------------------------------------------
// Self-contained interactive manual viewer.
//
// Renders a `ManuelData` object — chapters of prose blocks plus interactive
// boards (step the solution, or solve it move by move). The data modules under
// ./data are generated by backend/strategy/build_manuel_interactif.py from the
// corpus prose + verified solution lines; this component is the shared reader
// (originally the hand-built "manuel Débutant", refactored to take `data` as a
// prop so every theoretical manual reuses it).
// ---------------------------------------------------------------------------

export interface Run { t: string; b?: number; c?: number; id?: number }

export interface StartState {
  wm: number[]; wk: number[]; bm: number[]; bk: number[]; turn: Side
}

export interface MoveStep {
  n: string; f: number; t: number; c: number[]; path: number[]; p?: boolean
}

export interface Motif { m: string; sev: number; sq: number[]; step?: number }

export interface Position {
  id: string
  ch?: number
  theme?: string
  title: string
  concept?: string
  exp?: string
  pub?: string
  prompt?: string
  start: StartState
  moves: MoveStep[]
  ev?: number
  win?: 'white' | 'black' | 'draw'
  dep?: number
  note?: string
  mot?: Motif[]
}

export type Block =
  | { type: 'board'; id: string; ch: number }
  | { type: 'hr'; ch: number }
  | { type: 'h1' | 'h2' | 'h3' | 'h4' | 'quote' | 'p'; ch: number; runs: Run[] }
  | { type: 'ul' | 'ol'; ch: number; items: Run[][] }
  | { type: 'table'; ch: number; rows: string[][] }

export interface Chapter { n: number; title: string }

export interface ManuelData {
  book: string
  level: string
  chapters: Chapter[]
  blocks: Block[]
  positions: Record<string, Position>
}

type Side = 'white' | 'black'

interface LiveState {
  wm: Set<number>; wk: Set<number>; bm: Set<number>; bk: Set<number>; turn: Side
}

const MOTIF_LABELS: Record<string, string> = {
  coup_de_talon: 'Coup de Talon', coup_philippe: 'Coup Philippe', coup_turc: 'Coup Turc',
  coup_enfilade: 'Enfilade', coup_du_bruleur: 'Brûleur', coup_raphael: 'Coup Raphaël',
  coup_royal: 'Coup Royal', coup_napoleon: 'Coup Napoléon', coup_manoury: 'Coup Manoury',
  coup_express: 'Coup Express', coup_bonnard: 'Coup Bonnard', envoi_a_dame: 'Envoi à dame',
  sacrifice: 'Sacrifice', prise_max_ratee: 'Prise max. ratée',
}

function coord(n: number): { r: number; c: number } {
  const i = n - 1, r = Math.floor(i / 5), c = 2 * (i % 5) + (r % 2 === 0 ? 1 : 0)
  return { r, c }
}
const SQ_AT: Record<number, number> = {}
for (let n = 1; n <= 50; n++) { const { r, c } = coord(n); SQ_AT[r * 10 + c] = n }

function startState(p: Position): LiveState {
  return {
    wm: new Set(p.start.wm), wk: new Set(p.start.wk),
    bm: new Set(p.start.bm), bk: new Set(p.start.bk), turn: p.start.turn,
  }
}
function applyMove(S: LiveState, m: MoveStep): void {
  const isKing = S.wk.has(m.f) || S.bk.has(m.f)
  const isWhite = S.wm.has(m.f) || S.wk.has(m.f)
  ;[S.wm, S.wk, S.bm, S.bk].forEach(s => s.delete(m.f))
  ;(m.c || []).forEach(c => [S.wm, S.wk, S.bm, S.bk].forEach(s => s.delete(c)))
  ;((isKing || m.p) ? (isWhite ? S.wk : S.bk) : (isWhite ? S.wm : S.bm)).add(m.t)
  S.turn = S.turn === 'white' ? 'black' : 'white'
}
function stateAt(p: Position, step: number): LiveState {
  const S = startState(p)
  for (let i = 0; i < step; i++) applyMove(S, p.moves[i])
  return S
}
const nMoves = (p: Position): number => p.moves.length
function moverSide(p: Position, i: number): Side {
  const S = stateAt(p, i), m = p.moves[i]
  return (S.wm.has(m.f) || S.wk.has(m.f)) ? 'white' : 'black'
}
function solverSide(p: Position): Side {
  const t = p.start.turn
  for (let i = 0; i < nMoves(p); i++) if (moverSide(p, i) === t) return t
  return t === 'white' ? 'black' : 'white'
}
function leadStep(p: Position): number {
  let s = 0
  while (s < nMoves(p) && moverSide(p, s) !== solverSide(p)) s++
  return s
}

// Engine board (length-51 piece array) for the free-play mode.
function liveToBoard(S: LiveState): number[] {
  const b = new Array<number>(51).fill(0)
  S.wm.forEach(s => { b[s] = WHITE_MAN })
  S.wk.forEach(s => { b[s] = WHITE_KING })
  S.bm.forEach(s => { b[s] = BLACK_MAN })
  S.bk.forEach(s => { b[s] = BLACK_KING })
  return b
}
function startBoard(p: Position): number[] { return liveToBoard(startState(p)) }

const CSS = `
.dm *{box-sizing:border-box}
.dm{--bg:#161419;--panel:#1f1d25;--panel2:#262430;--ivory:#ece3d2;--muted:#9b9485;--faint:#6b6577;
  --line:#322f3c;--brass:#c9a24a;--brass-dim:#8a7437;--sage:#445249;--sand:#c8bb9e;--ebony:#131218;
  --rim:#4a4755;--ok:#86ad8f;--warn:#c07b5e;--hi:#6fa8b8;
  --serif:"Hoefler Text","Iowan Old Style","Palatino Linotype",Palatino,Georgia,serif;
  --sans:ui-sans-serif,system-ui,-apple-system,"Segoe UI",Roboto,Helvetica,Arial,sans-serif;
  --mono:"SF Mono",ui-monospace,Menlo,Consolas,monospace;
  background:radial-gradient(1200px 700px at 80% -10%,#221f2b 0%,transparent 55%),var(--bg);
  color:var(--ivory);font-family:var(--sans);font-size:16px;line-height:1.65;min-height:100%;-webkit-font-smoothing:antialiased}
.dm .topbar{position:sticky;top:0;z-index:5;background:rgba(22,20,25,.92);backdrop-filter:blur(8px);
  border-bottom:1px solid var(--line)}
.dm .topin{max-width:760px;margin:0 auto;padding:10px 18px;display:flex;align-items:center;gap:12px}
.dm .mark{width:28px;height:28px;flex:0 0 28px;border-radius:50%;background:var(--ebony);position:relative;border:1px solid var(--rim)}
.dm .mark::after{content:"";position:absolute;inset:5px;border-radius:50%;background:var(--ivory);
  -webkit-mask:radial-gradient(circle at 70% 50%,transparent 52%,#000 53%);mask:radial-gradient(circle at 70% 50%,transparent 52%,#000 53%)}
.dm .bt{font-family:var(--serif);font-size:15px;flex:1;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
.dm .backbtn{background:var(--panel2);color:var(--ivory);border:1px solid var(--line);border-radius:8px;
  padding:7px 11px;font-family:var(--sans);font-size:13px;cursor:pointer}
.dm .backbtn:hover{border-color:var(--brass-dim)}
.dm select{background:var(--panel2);color:var(--ivory);border:1px solid var(--line);border-radius:8px;
  padding:7px 9px;font-family:var(--sans);font-size:13px;max-width:46vw}
.dm .doc{max-width:760px;margin:0 auto;padding:8px 18px 60px}
.dm .h1{font-family:var(--serif);font-weight:500;font-size:30px;line-height:1.15;margin:22px 0 6px}
.dm .h2{font-family:var(--serif);font-weight:500;font-size:25px;line-height:1.2;margin:34px 0 10px;
  padding-top:16px;border-top:1px solid var(--line)}
.dm .h3{font-size:13px;letter-spacing:.04em;text-transform:uppercase;color:var(--brass);font-weight:600;margin:26px 0 8px}
.dm .h4{font-size:16px;font-weight:600;color:var(--ivory);margin:20px 0 6px}
.dm p.par{margin:12px 0;color:#ddd6c9}
.dm .quote{margin:14px 0;padding:10px 16px;border-left:3px solid var(--brass-dim);background:var(--panel);
  border-radius:0 8px 8px 0;color:#cfc8bb;font-size:15px}
.dm ul.lst,.dm ol.lst{margin:12px 0;padding-left:22px;color:#ddd6c9}
.dm ul.lst li,.dm ol.lst li{margin:5px 0}
.dm code{font-family:var(--mono);font-size:.88em;background:var(--panel2);border:1px solid var(--line);
  border-radius:5px;padding:1px 5px}
.dm code.id{color:var(--brass);border-color:var(--brass-dim)}
.dm strong{color:var(--ivory);font-weight:600}
.dm hr{border:none;border-top:1px solid var(--line);margin:24px 0}
.dm .tbl{margin:14px 0;overflow:auto}
.dm table{border-collapse:collapse;font-size:13px;width:100%}
.dm th,.dm td{border:1px solid var(--line);padding:6px 9px;text-align:left}
.dm th{background:var(--panel2);color:var(--muted);font-weight:600}
.dm .card{background:var(--panel);border:1px solid var(--line);border-radius:14px;padding:16px;margin:20px 0}
.dm .cap{display:flex;align-items:baseline;gap:9px;flex-wrap:wrap;margin-bottom:12px}
.dm .cap .t{font-family:var(--serif);font-size:17px}
.dm .ptheme{font-size:10.5px;letter-spacing:.06em;text-transform:uppercase;color:var(--brass);
  border:1px solid var(--brass-dim);border-radius:999px;padding:2px 9px}
.dm .boardwrap{width:min(330px,100%);margin:0 auto}
.dm .board{position:relative;width:100%;aspect-ratio:1/1;border-radius:9px;overflow:hidden;
  display:grid;grid-template-columns:repeat(10,1fr);grid-template-rows:repeat(10,1fr);
  box-shadow:0 14px 36px -20px #000,0 0 0 1px var(--line),0 0 0 8px var(--panel2);border:1px solid #0c0b10}
.dm .sq{position:relative}
.dm .sq.light{background:var(--sand)}
.dm .sq.dark{background:var(--sage)}
.dm .board.clickable .sq.dark{cursor:pointer}
.dm .num{position:absolute;left:3px;top:1px;font-size:8px;opacity:.3;font-family:var(--mono);color:#cfe0d2;pointer-events:none}
.dm .sq.light .num{color:#1d231e;opacity:.34}
.dm .pc{position:absolute;inset:11%;border-radius:50%;pointer-events:none}
.dm .pc.w{background:radial-gradient(circle at 38% 32%,#fbf4e6,#d8caac 78%);box-shadow:inset 0 -3px 6px #b3a589,inset 0 2px 4px #fff,0 2px 5px -2px #000}
.dm .pc.b{background:radial-gradient(circle at 38% 32%,#3a3742,#131118 78%);box-shadow:inset 0 -3px 6px #000,inset 0 2px 4px #514d5d,0 2px 5px -2px #000;border:1px solid #524e5e}
.dm .pc.k::after{content:"";position:absolute;inset:24%;border-radius:50%;border:2px solid var(--brass);box-shadow:0 0 6px var(--brass-dim)}
.dm .pc.k::before{content:"";position:absolute;left:50%;top:50%;width:4px;height:4px;transform:translate(-50%,-50%);border-radius:50%;background:var(--brass);z-index:2}
.dm .ring{position:absolute;inset:6%;border-radius:50%;pointer-events:none}
.dm .ring.from{box-shadow:inset 0 0 0 2px var(--brass-dim);opacity:.8}
.dm .ring.to{box-shadow:inset 0 0 0 2px var(--brass)}
.dm .ring.sel{box-shadow:inset 0 0 0 3px var(--ok)}
.dm .ring.mhi{box-shadow:inset 0 0 0 3px var(--hi)}
.dm .ring.hint{box-shadow:inset 0 0 0 2px var(--hi);animation:dmpulse 1.1s ease-in-out infinite}
@keyframes dmpulse{0%,100%{opacity:.35}50%{opacity:1}}
.dm .trail{position:absolute;inset:34%;border-radius:50%;background:var(--brass);opacity:.22;pointer-events:none}
.dm .capx{position:absolute;inset:11%;border-radius:50%;pointer-events:none;border:2px solid var(--warn);animation:dmfade .55s ease-out forwards}
.dm .capx::after,.dm .capx::before{content:"";position:absolute;left:50%;top:14%;width:2px;height:72%;background:var(--warn)}
.dm .capx::after{transform:translateX(-1px) rotate(45deg)}
.dm .capx::before{transform:translateX(-1px) rotate(-45deg)}
@keyframes dmfade{from{opacity:1}to{opacity:.001}}
.dm .board.fok{animation:dmok .4s ease}
.dm .board.fno{animation:dmno .4s ease}
@keyframes dmok{50%{box-shadow:0 14px 36px -20px #000,0 0 0 1px var(--ok),0 0 0 8px var(--panel2),0 0 22px var(--ok)}}
@keyframes dmno{25%{transform:translateX(-4px)}75%{transform:translateX(4px)}}
.dm .ctrls{display:flex;align-items:center;gap:6px;flex-wrap:wrap;justify-content:center;margin-top:11px}
.dm .btn{display:inline-flex;align-items:center;gap:6px;background:var(--panel2);border:1px solid var(--line);
  color:var(--ivory);font-family:var(--sans);font-size:13px;padding:7px 11px;border-radius:7px;cursor:pointer}
.dm .btn:hover{border-color:var(--brass-dim)}
.dm .btn:disabled{opacity:.4;cursor:default}
.dm .btn.brass{background:var(--brass);color:#1c1813;border-color:var(--brass);font-weight:600}
.dm .btn.sm{padding:6px 9px;font-size:12.5px}
.dm .sc{font-family:var(--mono);font-size:12px;color:var(--muted);min-width:64px;text-align:center}
.dm .toplay{font-size:12px;color:var(--muted);display:flex;align-items:center;gap:6px}
.dm .dot{width:10px;height:10px;border-radius:50%;border:1px solid var(--rim)}
.dm .dot.w{background:linear-gradient(135deg,#fbf4e6,#d8caac)}.dm .dot.b{background:#15131a}
.dm .reveal{margin-top:13px;padding-top:12px;border-top:1px solid var(--line)}
.dm .lab{font-size:10px;letter-spacing:.14em;text-transform:uppercase;color:var(--faint);margin-bottom:6px}
.dm .notation{font-family:var(--mono);font-size:13px;background:var(--panel2);border:1px solid var(--line);border-radius:7px;padding:8px 10px}
.dm .expl{font-size:13.5px;color:#cfc8bb;margin-top:10px}
.dm .verdict{display:flex;align-items:center;gap:9px;margin-top:11px}
.dm .vbadge{font-family:var(--serif);font-size:14px;padding:5px 11px;border-radius:7px;border:1px solid var(--line);background:var(--panel2)}
.dm .vbadge .ev{font-family:var(--mono);color:var(--brass)}
.dm .vmeta{font-size:11px;color:var(--faint)}
.dm .chips{display:flex;flex-wrap:wrap;gap:6px;margin-top:11px}
.dm .chip{font-size:11.5px;padding:4px 9px;border-radius:999px;cursor:pointer;background:var(--panel2);border:1px solid var(--line);color:var(--ivory);display:inline-flex;align-items:center;gap:6px}
.dm .chip.on{border-color:var(--hi);box-shadow:0 0 0 1px var(--hi)}
.dm .chip .bar{width:20px;height:3px;border-radius:2px;background:var(--line);overflow:hidden}
.dm .chip .bar i{display:block;height:100%;background:var(--hi)}
.dm .solvemsg{font-size:12.5px;text-align:center;margin-top:8px;min-height:16px}
.dm .solvemsg.ok{color:var(--ok)}.dm .solvemsg.no{color:var(--warn)}
.dm .navrow{display:flex;justify-content:space-between;gap:10px;margin-top:34px;padding-top:18px;border-top:1px solid var(--line)}
`

function Runs({ runs }: { runs: Run[] }): React.ReactElement {
  return (
    <>
      {runs.map((r, i) => {
        if (r.b) return <strong key={i}>{r.t}</strong>
        if (r.c) return <code key={i} className={r.id ? 'id' : ''}>{r.t}</code>
        return <React.Fragment key={i}>{r.t}</React.Fragment>
      })}
    </>
  )
}

function BoardCard({ pos }: { pos: Position }): React.ReactElement {
  // Boards open directly in free-play mode: the reader can search the solution
  // on the board straight away. "Lire" switches to the step-through view.
  const [mode, setMode] = useState<'view' | 'solve' | 'play'>('play')
  const [step, setStep] = useState(0)
  const [revealed, setRevealed] = useState(false)
  const [solved, setSolved] = useState(false)
  const [solveSel, setSolveSel] = useState<number[]>([])
  const [hintLevel, setHintLevel] = useState(0)
  const [solveMsg, setSolveMsg] = useState<{ t: string; c: string }>({ t: '', c: '' })
  const [motifHi, setMotifHi] = useState<number[] | null>(null)
  const [activeChip, setActiveChip] = useState<number | null>(null)
  const [flash, setFlash] = useState<string | null>(null)
  // Free-play ("Jouer") mode: play any legal move on the board to search for
  // the solution yourself. Independent of the stored solution line.
  const [playBoard, setPlayBoard] = useState<number[]>(() => startBoard(pos))
  const [playTurn, setPlayTurn] = useState<Turn>(pos.start.turn)
  const [playHist, setPlayHist] = useState<{ board: number[]; turn: Turn }[]>([])
  const [playFrom, setPlayFrom] = useState<number | null>(null)
  const [playLast, setPlayLast] = useState<EngineMove | null>(null)
  const [playMsg, setPlayMsg] = useState('')

  const total = nMoves(pos)
  const inPlay = mode === 'play'
  const showSolution = (mode === 'view' && revealed) || (mode === 'solve' && solved)
  const S = useMemo(() => stateAt(pos, step), [pos, step])
  const lastMove = step > 0 ? pos.moves[step - 1] : null
  useEffect(() => {
    if (!flash) return
    const t = setTimeout(() => setFlash(null), 420)
    return () => clearTimeout(t)
  }, [flash])

  // Legal moves for the live free-play board (only computed while playing).
  const legal = useMemo(
    () => (inPlay ? getLegalMoves(playBoard, playTurn) : []),
    [inPlay, playBoard, playTurn],
  )

  function toView(): void {
    setMode('view'); setStep(0); setSolveSel([]); setHintLevel(0)
    setSolveMsg({ t: '', c: '' }); setMotifHi(null); setActiveChip(null)
  }
  function toSolve(): void {
    setMode('solve'); setSolved(false); setStep(leadStep(pos)); setSolveSel([]); setHintLevel(0)
    setSolveMsg({ t: '', c: '' }); setMotifHi(null); setRevealed(false); setActiveChip(null)
  }
  function resetPlay(): void {
    setPlayBoard(startBoard(pos)); setPlayTurn(pos.start.turn)
    setPlayHist([]); setPlayFrom(null); setPlayLast(null); setPlayMsg('')
  }
  function toPlay(): void {
    setMode('play'); setRevealed(false); setMotifHi(null); setActiveChip(null); resetPlay()
  }
  function undoPlay(): void {
    if (!playHist.length) return
    const prev = playHist[playHist.length - 1]
    setPlayBoard(prev.board); setPlayTurn(prev.turn)
    setPlayHist(playHist.slice(0, -1)); setPlayFrom(null); setPlayLast(null); setPlayMsg('')
  }
  function stepBy(d: number): void {
    setMotifHi(null); setActiveChip(null)
    setStep(s => Math.min(total, Math.max(0, s + d)))
  }
  function onSolveSquare(sq: number): void {
    if (solved || step >= total) return
    const exp = pos.moves[step]
    const path = exp.path || [exp.f, exp.t]
    const need = path[solveSel.length]
    if (sq === need) {
      const ns = [...solveSel, sq]
      if (ns.length === path.length) {
        let nstep = step + 1
        while (nstep < total && moverSide(pos, nstep) !== solverSide(pos)) nstep++
        const done = nstep >= total
        setSolveSel([]); setHintLevel(0); setStep(nstep)
        setSolveMsg({ t: done ? 'Résolu ✓' : 'Bien joué !', c: 'ok' })
        if (done) setSolved(true)
        setFlash('ok')
      } else { setSolveSel(ns); setSolveMsg({ t: '', c: '' }) }
    } else {
      const mid = solveSel.length > 0
      setSolveSel([])
      setSolveMsg({ t: mid ? 'Mauvaise case — on reprend.' : 'Pas le bon coup, réessaie.', c: 'no' })
      setFlash('no')
    }
  }
  function onPlaySquare(sq: number): void {
    const own = (p: number): boolean => playTurn === 'white'
      ? (p === WHITE_MAN || p === WHITE_KING) : (p === BLACK_MAN || p === BLACK_KING)
    if (playFrom == null) {
      if (legal.some(m => m.path[0] === sq)) { setPlayFrom(sq); setPlayMsg('') }
      else if (own(playBoard[sq])) setPlayMsg('Cette pièce ne peut pas jouer (prise majoritaire obligatoire ?).')
      return
    }
    if (sq === playFrom) { setPlayFrom(null); return }
    const cands = legal.filter(m => m.path[0] === playFrom && m.path[m.path.length - 1] === sq)
    if (cands.length) {
      const mv = cands.reduce((a, b) => (b.captures.length > a.captures.length ? b : a))
      setPlayHist(h => [...h, { board: playBoard, turn: playTurn }])
      setPlayBoard(applyEngineMove(playBoard, mv))
      setPlayTurn(playTurn === 'white' ? 'black' : 'white')
      setPlayLast(mv); setPlayFrom(null); setPlayMsg(''); setFlash('ok')
    } else if (legal.some(m => m.path[0] === sq)) {
      setPlayFrom(sq); setPlayMsg('')
    } else {
      setPlayFrom(null)
    }
  }
  function hint(): void {
    const h = Math.min(2, hintLevel + 1)
    setHintLevel(h)
    setSolveMsg({ t: h >= 2 ? 'Trajectoire indiquée.' : 'Pièce à jouer indiquée.', c: '' })
  }

  // Unified occupancy + last-move overlay for rendering (works for all modes).
  const board = inPlay ? playBoard : liveToBoard(S)
  const last = inPlay
    ? (playLast ? { path: playLast.path, c: playLast.captures } : null)
    : (lastMove ? { path: lastMove.path || [lastMove.f, lastMove.t], c: lastMove.c || [] } : null)
  const playDests = (inPlay && playFrom != null)
    ? legal.filter(m => m.path[0] === playFrom).map(m => m.path[m.path.length - 1])
    : []
  const turnNow: Turn = inPlay ? playTurn : S.turn

  const cells: React.ReactElement[] = []
  for (let r = 0; r < 10; r++) for (let c = 0; c < 10; c++) {
    const playing = (r + c) % 2 === 1
    const sq = playing ? SQ_AT[r * 10 + c] : null
    const inner: React.ReactElement[] = []
    if (playing && sq != null) {
      inner.push(<span className="num" key="n">{sq}</span>)
      const pc = board[sq]
      if (pc === WHITE_MAN) inner.push(<div className="pc w" key="p" />)
      else if (pc === WHITE_KING) inner.push(<div className="pc w k" key="p" />)
      else if (pc === BLACK_MAN) inner.push(<div className="pc b" key="p" />)
      else if (pc === BLACK_KING) inner.push(<div className="pc b k" key="p" />)
      if (last) {
        const pth = last.path
        const idx = pth.indexOf(sq)
        if (idx > 0 && idx < pth.length - 1) inner.push(<div className="trail" key="t" />)
        if (sq === pth[0]) inner.push(<div className="ring from" key="rf" />)
        if (sq === pth[pth.length - 1]) inner.push(<div className="ring to" key="rt" />)
        if (last.c.includes(sq)) inner.push(<div className="capx" key="cx" />)
      }
      if (mode === 'solve' && !solved) {
        if (solveSel.includes(sq)) inner.push(<div className="ring sel" key="sel" />)
        if (hintLevel >= 1 && step < total) {
          const exp = pos.moves[step]
          const hp = hintLevel >= 2 ? (exp.path || [exp.f, exp.t]) : [exp.f]
          if (hp.includes(sq)) inner.push(<div className="ring hint" key="hint" />)
        }
      }
      if (inPlay) {
        if (sq === playFrom) inner.push(<div className="ring sel" key="psel" />)
        else if (playDests.includes(sq)) inner.push(<div className="ring hint" key="pdst" />)
      }
      if (motifHi && motifHi.includes(sq)) inner.push(<div className="ring mhi" key="mhi" />)
    }
    const handler = inPlay ? onPlaySquare : (mode === 'solve' ? onSolveSquare : null)
    cells.push(
      <div key={r * 10 + c} className={'sq ' + (playing ? 'dark' : 'light')}
        onClick={playing && sq != null && handler ? () => handler(sq) : undefined}>{inner}</div>,
    )
  }
  const clickable = inPlay || (mode === 'solve' && !solved && total > 0)
  const boardCls = 'board' + (clickable ? ' clickable' : '')
    + (flash === 'ok' ? ' fok' : '') + (flash === 'no' ? ' fno' : '')
  const playOver = inPlay && legal.length === 0

  return (
    <div className="card">
      <div className="cap">
        <span className="t">{pos.title}</span>
        {pos.theme && <span className="ptheme">{pos.theme.replace(/_/g, ' ')}</span>}
      </div>
      <div className="boardwrap"><div className={boardCls}>{cells}</div></div>

      {mode === 'view' && (
        <div className="ctrls">
          <span className="toplay">
            <span className={'dot ' + (turnNow === 'white' ? 'w' : 'b')} />
            {turnNow === 'white' ? 'Blancs' : 'Noirs'}
          </span>
          <button className="btn sm" onClick={() => { setStep(0); setMotifHi(null) }} disabled={step === 0}>↺</button>
          <button className="btn sm" onClick={() => stepBy(-1)} disabled={step <= 0}>◀</button>
          <span className="sc">{step} / {total}</span>
          <button className="btn sm" onClick={() => stepBy(1)} disabled={step >= total}>▶</button>
          {total > 0 && <button className="btn sm" onClick={() => setRevealed(v => !v)}>{revealed ? 'Masquer' : 'Solution'}</button>}
          {total > 0 && <button className="btn sm" onClick={toSolve}>Résoudre</button>}
          <button className="btn sm brass" onClick={toPlay}>Jouer</button>
        </div>
      )}

      {mode === 'solve' && (
        <div>
          <div className="solvemsg" style={{ marginTop: 11 }}>
            {solved ? <span className="ok">Combinaison résolue ✓</span>
              : <>Joue le coup gagnant pour les <strong>{solverSide(pos) === 'white' ? 'Blancs' : 'Noirs'}</strong></>}
          </div>
          <div className={'solvemsg ' + solveMsg.c}>{solveMsg.t}</div>
          <div className="ctrls">
            <button className="btn sm" onClick={hint} disabled={solved}>Indice</button>
            <button className="btn sm" onClick={toSolve} disabled={!solved && step === leadStep(pos) && solveSel.length === 0}>↺</button>
            <button className="btn sm" onClick={toView}>Quitter</button>
          </div>
        </div>
      )}

      {mode === 'play' && (
        <div>
          <div className="solvemsg" style={{ marginTop: 11 }}>
            {playOver
              ? <span className="no">Plus de coup légal — trait aux {turnNow === 'white' ? 'Blancs' : 'Noirs'} : ils ont perdu.</span>
              : <>Exploration libre — trait aux <strong>{turnNow === 'white' ? 'Blancs' : 'Noirs'}</strong>. Clique une pièce, puis sa case d'arrivée.</>}
          </div>
          {playMsg && <div className="solvemsg no">{playMsg}</div>}
          <div className="ctrls">
            <button className="btn sm" onClick={undoPlay} disabled={!playHist.length}>↶ Annuler</button>
            <button className="btn sm" onClick={resetPlay} disabled={!playHist.length && playFrom == null}>↺ Position</button>
            {total > 0 && <button className="btn sm" onClick={toSolve}>Résoudre</button>}
            {total > 0 && <button className="btn sm" onClick={() => { setMode('view'); setStep(0); setRevealed(true) }}>Solution</button>}
            <button className="btn sm" onClick={toView}>Lire</button>
          </div>
        </div>
      )}

      {showSolution && (
        <div className="reveal">
          {pos.pub && <><div className="lab">Solution — notation</div><div className="notation">{pos.pub}</div></>}
          {pos.exp && <div className="expl">{pos.exp}</div>}
          {(pos.win != null || pos.ev != null) && (
            <div className="verdict">
              <span className="vbadge">
                {pos.win === 'white' ? 'Gain des Blancs' : pos.win === 'black' ? 'Gain des Noirs' : pos.win === 'draw' ? 'Nulle' : '—'}
                {typeof pos.ev === 'number' && <span className="ev">{' · ' + (pos.ev > 0 ? '+' : '') + pos.ev.toFixed(2)}</span>}
              </span>
              <span className="vmeta">combinaison vérifiée{pos.dep ? ' · prof. ' + pos.dep : ''}</span>
            </div>
          )}
          {pos.mot && pos.mot.length > 0 && (
            <div className="chips">
              {pos.mot.map((m, i) => (
                <button key={i} className={'chip' + (activeChip === i ? ' on' : '')}
                  onClick={() => { setMotifHi(m.sq); setActiveChip(i); setStep(Math.min(total, (m.step || 0) + 1)) }}>
                  {MOTIF_LABELS[m.m] || m.m}<span className="bar"><i style={{ width: Math.round(m.sev * 100) + '%' }} /></span>
                </button>
              ))}
            </div>
          )}
          {pos.note && <div className="expl" style={{ color: 'var(--warn)' }}>Note : {pos.note}</div>}
        </div>
      )}
    </div>
  )
}

function BlockView({ b, positions }: { b: Block; positions: Record<string, Position> }): React.ReactElement | null {
  if (b.type === 'board') { const p = positions[b.id]; return p ? <BoardCard pos={p} /> : null }
  if (b.type === 'hr') return <hr />
  if (b.type === 'h1') return <div className="h1"><Runs runs={b.runs} /></div>
  if (b.type === 'h2') return <div className="h2"><Runs runs={b.runs} /></div>
  if (b.type === 'h3') return <div className="h3"><Runs runs={b.runs} /></div>
  if (b.type === 'h4') return <div className="h4"><Runs runs={b.runs} /></div>
  if (b.type === 'quote') return <div className="quote"><Runs runs={b.runs} /></div>
  if (b.type === 'ul') return <ul className="lst">{b.items.map((it, i) => <li key={i}><Runs runs={it} /></li>)}</ul>
  if (b.type === 'ol') return <ol className="lst">{b.items.map((it, i) => <li key={i}><Runs runs={it} /></li>)}</ol>
  if (b.type === 'table') return (
    <div className="tbl"><table><tbody>
      {b.rows.map((row, ri) => (
        <tr key={ri}>{row.map((cell, ci) => ri === 0 ? <th key={ci}>{cell}</th> : <td key={ci}>{cell}</td>)}</tr>
      ))}
    </tbody></table></div>
  )
  if (b.type === 'p') return <p className="par"><Runs runs={b.runs} /></p>
  return null
}

export default function ManuelInteractif(
  { data, onClose, initialChapter }: { data: ManuelData; onClose?: () => void; initialChapter?: number },
): React.ReactElement {
  const chapters = data.chapters
  const firstWithBoards = useMemo(() => {
    const withB = new Set(data.blocks.filter(b => b.type === 'board').map(b => b.ch))
    const c = chapters.find(c => withB.has(c.n)) || chapters[0]
    return c ? c.n : 0
  }, [data])
  const [chap, setChap] = useState(
    initialChapter != null && chapters.some(c => c.n === initialChapter) ? initialChapter : firstWithBoards,
  )
  const scrollRef = useRef<HTMLDivElement>(null)
  const blocks = useMemo(() => data.blocks.filter(b => b.ch === chap), [data, chap])
  const idx = chapters.findIndex(c => c.n === chap)
  // Changing chapter (Précédent / Suivant or the selector) restarts the reader
  // at the top of the page rather than keeping the previous scroll position.
  useEffect(() => {
    // The reader scrolls inside its own `.dm` container; reset that, and also
    // walk up to whatever scrollable ancestor actually moved, as a fallback.
    scrollRef.current?.scrollTo({ top: 0, behavior: 'auto' })
    let el: HTMLElement | null = scrollRef.current?.parentElement ?? null
    while (el) { if (el.scrollTop > 0) el.scrollTop = 0; el = el.parentElement }
  }, [chap])
  function goChap(n: number): void { setChap(n) }

  return (
    <div ref={scrollRef} className="dm" style={{ width: '100%', height: '100%', overflowY: 'auto' }}>
      <style>{CSS}</style>
      <div className="topbar">
        <div className="topin">
          {onClose && <button className="backbtn" onClick={onClose}>← Manuels</button>}
          <div className="mark" />
          <div className="bt">{data.book}</div>
          <select value={chap} onChange={e => goChap(Number(e.target.value))}>
            {chapters.map(c => <option key={c.n} value={c.n}>{c.n === 0 ? 'Préface' : `Ch. ${c.n} — ${c.title}`}</option>)}
          </select>
        </div>
      </div>
      <div className="doc">
        {/* Key by chapter + position id so that switching chapters remounts each
            BoardCard with its own position. With a bare index key, a board at
            the same index in another chapter reused the previous card instance
            and kept its (free-play) board state — every chapter showed the same
            position. */}
        {blocks.map((b, i) => (
          <BlockView
            key={b.type === 'board' ? `${chap}-board-${b.id}` : `${chap}-${i}`}
            b={b}
            positions={data.positions}
          />
        ))}
        <div className="navrow">
          <button className="btn" disabled={idx <= 0} onClick={() => goChap(chapters[idx - 1].n)}>◀ Précédent</button>
          <button className="btn brass" disabled={idx >= chapters.length - 1} onClick={() => goChap(chapters[idx + 1].n)}>Suivant ▶</button>
        </div>
      </div>
    </div>
  )
}
